### ISSUE TITLE
Path and environment settings

### ISSUE THREAD

**Issue by rsuhada** [DaveDavenport/rofi#100]
I use rofi with i3wm and zsh is my shell. 
If I run rofi -rnow directly from my zsh on the command line everything works perfect.

However I'd like to have it bound in i3wm so my current setup is:

`bindsym Ctrl+space exec rofi -rnow`

In this case however rofi doesn't see my custom path or can't launch some applications (e.g. java based ones).

There was an open issue about the path with the solution to put it to .xinitrc or .xprofile, however neither helped.

What is the proper way to bind/call rofi in i3? How to execute custom command line scripts with it?

Thank you very much!
I'm really impressed by how nice it looks while being super responsive.

**Comment by jjehannet** [comment]
It is specific to i3wm which use /bin/sh as default value for shell
invocation.
Try to use this instead:

   bindsym Ctrl+space exec zsh -c "rofi -rnow"

2015-01-05 16:27 GMT+01:00 rsuhada <notifications@github.com>:

> I use rofi with i3wm and zsh is my shell.
> If I run rofi -rnow directly from my zsh on the command line everything
> works perfect.
>
> However I'd like to have it bound in i3wm so my current setup is:
>
> bindsym Ctrl+space exec rofi -rnow
>
> In this case however rofi doesn't see my custom path or can't launch some
> applications (e.g. java based ones).
>
> There was an open issue about the path with the solution to put it to
> .xinitrc or .xprofile, however neither helped.
>
> What is the proper way to bind/call rofi in i3? How to execute custom
> command line scripts with it?
>
> Thank you very much!
> I'm really impressed by how nice it looks while being super responsive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DaveDavenport/rofi/issues/100>.
>



-- 
J u l i e n    J e h a n n e t

**Comment by rsuhada** [comment]
Thank you but still no luck... I've tried both
`bindsym Ctrl+space exec zsh -c "rofi -rnow"`
`bindsym Ctrl+space exec bash -c "rofi -rnow"`

with the same results... it doesn't see my path although it is in my .zshrc (well in my oh-my-zsh config) or in .bashrc/.bash_profile...

**Comment by rsuhada** [comment]
Alright - I've logged out and again back in and it works!

So

bindsym Ctrl+space exec zsh -c "rofi -rnow"

did help - thank you very much!

Btw - unrelated - in order to install rofi I needed to install also
libXinerama-devel and pango-devel not mentioned in the requisites (and it
wasn't clear what to do from the error messages I got from configure). Not
sure how typical this is but, if it is relevant for others too it might be
worth to add this to the dependencies list.

**Comment by DaveDavenport** [comment]
Mentioned that the dev packages of the external libraries should be installed.

Thx.

**Comment by lwj0012** [comment]
same issue with the search path in rofi 1.0.0-RC1-3-gbf51983, under archlinux, which is installed from AUR.
Although I have change the bindsys to zsh -c "rofi -rnow", the search path does not change.
How ever if I execute the command from the bash or zsh directly, the search path is correct.

**Comment by DaveDavenport** [comment]
Is the environment is available in the program (i3?) that launches rofi?

also 1.0.0 does not support the `-rnow` flag anymore, it is `-show run`.

**Comment by lwj0012** [comment]
problem solved. It seems to be the issue of i3wm.

**Comment by DaveDavenport** [comment]
good.

**Comment by ephexeve** [comment]
Any idea why this doesn't work using `bash -c`? Using `zsh -c` works fine, it gets my custom paths, but not with bash.

**Comment by sardemff7** [comment]
Each shell reads its own files. Depending on which file you change your `$PATH` in, it will work or not. Read the relevant shells man pages.
