### ISSUE TITLE
Parse ssh config correctly

### ISSUE THREAD

**Issue by lasers** [DaveDavenport/rofi#101]
Dmenu does not play nicely with multi-monitors (especially when one is on potrait mode) so I looked into alternatives and installed rofi-git recently. I noticed something right away with ssh.

I have this in my ~/.ssh/config.

Host mps xps t60 apple
Hostname %h.local
User chris

Host *
ControlMaster auto
ControlPath ~/.ssh/socket-%r@%h:%p 

It'll show up as... 

mps
name
name
name
name

**Comment by DaveDavenport** [comment]
I agree, the parsing should be a bit more robust.

**Comment by kuminamoya** [comment]
It´s not a big problem, but now it chokes on lines with comments (which are valid ssh-config syntax):

host sshhost # some comment

now shows:
sshhost
some
comment

My simple workaround was to reformat my .ssh/config to move comments to a seperate line.

**Comment by DaveDavenport** [comment]
please make separate bug.  this should be fixed!
