### ISSUE TITLE
Add case sensitivity.

### ISSUE THREAD

**Issue by EdwinPujols** [DaveDavenport/rofi#102]
On my i3 configuration I tend to symlink common programs to Title-cased names in my personal bin folder. For example,

    Terminal  ->  gnome-terminal -e screen
    Chrome    ->  google-chrome

This way, given that with dmenu/dmenu_run the search is case sensitive, it's quite easy to filter out rarely used programs (since most have lower-case names).

It would be nice to have case sensitivity support in rofi.

**Comment by DaveDavenport** [comment]
Interesting.  Is it possible to add it to xrmoptions.c too? so you can set it from your Xresources.
Maybe we can add some indicator, showing what modi it is in.

**Comment by EdwinPujols** [comment]
Oh, yes. I will see what I can do.

About the indicator, I was thinking that if this feature was OK with you, I'd check for a way to add a visual indicator (but it slipped my mind until now that you mention it).

**Comment by DaveDavenport** [comment]
I moved the indicator to the end of the box. I did not like the weird 'gap' at the front and the odd misalignment.
