### ISSUE TITLE
settings from xresources not apply

### ISSUE THREAD

**Issue by SergShh** [DaveDavenport/rofi#110]
Hello. I build rofi for ubuntu on launchpad(https://launchpad.net/~sj-sr/+archive/ubuntu/extra-packages), everything works exclude user settings from xresources(colors, etc) Whats wrong with my build? Thanks.

**Comment by DaveDavenport** [comment]
You can use rofi -dump-xresources to see the settings that are currently active.
After updating your Xresources file, you need to 'load' them first using xrdb -load ~/.Xresources.

If it still does not work, please attach your resources file and the output of rofi -dump-xresources.

**Comment by SergShh** [comment]
xrdb -load solved the problem. Now it works. Not a bug, thanks)

**Comment by DaveDavenport** [comment]
Glad it works!.
