### ISSUE TITLE
"grave" not recognized to toggle case sensitivity (German keyboard)

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#112]
The code to toggle case sensitivity does not work for me (https://github.com/DaveDavenport/rofi/blob/master/source/rofi.c#L1758-1770).

I am using a German keyboard, where "`" (grave) is on the key left to backspace, and needs Shift to be pressed.
I am getting `ev.xkey.keycode == 21` when pressing it, both with `setxkbmap -layout de -variant nodeadkeys` and `setxkbmap -layout de`.

`xev` displays this (without `nodeadkeys`):

    KeyPress event, serial 36, synthetic NO, window 0x1400001,
        root 0x94, subw 0x0, time 7873990, (290,494), root:(291,495),
        state 0x10, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 36, synthetic NO, window 0x1400001,
        root 0x94, subw 0x0, time 7876109, (290,494), root:(291,495),
        state 0x11, keycode 21 (keysym 0xfe50, dead_grave), same_screen YES,
        XLookupString gives 1 bytes: (60) "`"
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: True

    KeyPress event, serial 36, synthetic NO, window 0x1400001,
        root 0x94, subw 0x0, time 7876109, (290,494), root:(291,495),
        state 0x11, keycode 0 (keysym 0x60, grave), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 1 bytes: (60) "`"
        XFilterEvent returns: False

    KeyRelease event, serial 36, synthetic NO, window 0x1400001,
        root 0x94, subw 0x0, time 7876220, (290,494), root:(291,495),
        state 0x11, keycode 21 (keysym 0xfe50, dead_grave), same_screen YES,
        XLookupString gives 1 bytes: (60) "`"
        XFilterEvent returns: False

    KeyRelease event, serial 36, synthetic NO, window 0x1400001,
        root 0x94, subw 0x0, time 7877022, (290,494), root:(291,495),
        state 0x11, keycode 62 (keysym 0xffe2, Shift_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

How would I print the value of `key` from:

    KeySym key = XkbKeycodeToKeysym ( display, ev.xkey.keycode, 0, 0 );

**Comment by DaveDavenport** [comment]
Curious, I did add the 'dead_grave' to the list (deee786c653e3b28fa965380e26b682e54502ba7).

I think you can just print key as an integer.  (printf("%d\n", key);) and see /usr/include/X11/keysymdef.h for the keysyms.

**Comment by blueyed** [comment]
> Curious, I did add the 'dead_grave' to the list (deee786).

I had this change already.

It prints 180, which is 0xb4 and XK_acute according to keysymdef.h:

> #define XK_acute                         0x00b4  /* U+00B4 ACUTE ACCENT */
