### ISSUE TITLE
Support for wildcards / regexp

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#113]
It would be great to match against simple glob patterns like `f*o` when filtering the list, which would match `foo`.

I am not sure, if regular expressions are useful to have enabled by default (requiring to use `.*` instead of just `*`). Maybe this could be switched similar to case sensitivity.

**Comment by DaveDavenport** [comment]
One of the things that kept me from supporting this is speed.
With Clerk we already notice that the utf8 case-insensitive matching can be slow for large lists (30k items).

Is there a ready to use fast glob matching library (glib has g_pattern_spec_* but no idea how fast this is.)

**Comment by f1xmAn** [comment]
Maybe it'll be cool to add possibility to enable glob patterns for different show modes? Patterns will be very useful for window or ssh mode and more often then not both of them have very small lists.

**Comment by DaveDavenport** [comment]
@f1xmAn glob matching has been added.

**Comment by f1xmAn** [comment]
@DaveDavenport thank you!

**Comment by blueyed** [comment]
@DaveDavenport 
Using `-glob` does not match the WM_CLASS column anymore, and should probably not be bound to the beginning of the string (i.e. "fox" should also match "Firefox").

**Comment by DaveDavenport** [comment]
yeah, I only append a * should probably prepend one too.

**Comment by blueyed** [comment]
> In fields it matches nothing has changed.

Does not match '*Fire' in the first col for "Firefox".

**Comment by DaveDavenport** [comment]
patch to fix is welcome

**Comment by DaveDavenport** [comment]
Added experimental `--regex- support.
