### ISSUE TITLE
(optionally) reuse last filter for window switcher

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#115]
Sometimes it would be convenient to re-use the last filter.

Maybe a new `-key-reuse` option could be added, e.g.:

    rofi -key mod1-F1 -key-reuse Shift-mod1-F1

**Comment by carnager** [comment]
i think the better aproach would be to add global -filter support, like the dmenu mode does.
I added a ticket here: https://github.com/DaveDavenport/rofi/issues/207
