### ISSUE TITLE
Display screen number in window switcher (with multiple screens)

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#120]
The window switcher displays the desktop number for the client, which maps to awesomeWM's tags.

With multiple screens it would be useful to have this information available as well in a similar way.

**Comment by blueyed** [comment]
I see now that clients on the 2nd screen get desktop numbers 10-18.
I will change my config to use 10 tags per screen, so that I get the screen number indirectly through the offset.
Would there be a way for rofi to get the screen number anyway?

**Comment by DaveDavenport** [comment]
(I assume you mean physical monitor with screen). 

I don't know if the actual monitor is a property (I doubt it) but it could be calculated based on the windows location.

**Comment by DaveDavenport** [comment]
with the fixing of desktop name, I guess we can close this.

**Comment by blueyed** [comment]
By default the tags are numeric, so both screen 1 and 2 would have a tag 1.
But given that names are used now, this can be addressed through the naming however, yes.

OTOH would it be nice if rofi would notice that tag/name "1" is used by different desktops, and then append/prepend the screen (physical screen) number to it.
