### ISSUE TITLE
"Invalid UTF-8 string." error with certain glyph in xterm title

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#121]
When I use the following in a xterm, its title gets displayed as "<Invalid text>" in awesomeWM's title bar, and shows up as "Invalid UTF-8 string." in rofi:

    print -Pn $'\e]2;test:✐'

Using "✐" works with urxvt and other terminals.

**Comment by DaveDavenport** [comment]
I am not sure how this is a Rofi issue (or how to work around it).
If I check what xterm sets for window title, it is not correct UTF-8: it returns (in hex) E23F3F instead of E29C90 (✐).

**Comment by blueyed** [comment]
Yes, it's a xterm issue, but rofi could handle it better.
Currently it does not display the class and desktop for the entry.

**Comment by DaveDavenport** [comment]
I changed it so it prints the string up to the last valid character. Other solutions seem to be more expensive.

**Comment by blueyed** [comment]
Thanks!
