### ISSUE TITLE
Find files

### ISSUE THREAD

**Issue by orschiro** [DaveDavenport/rofi#122]
Hi @DaveDavenport,

I just came across [Mutate](https://github.com/qdore/Mutate), another launcher with one very useful feature: finding and opening files. 

Could such a feature be added to rofi as well?

Thankfully,

Robert

**Comment by DaveDavenport** [comment]
Looks a lot like albert (https://github.com/ManuelSchneid3r/albert) they seem to be popping up a lot.
I have a file-browser script for rofi that allows you to quickly open file. This could easily be extended. Maybe with enough demand I will integrate it.
 
See Examples/rofi-file-browser:

https://github.com/DaveDavenport/rofi/blob/master/Examples/rofi-file-browser.sh

If rofi-file-browser.sh is in path:
```
rofi -switchers "file:rofi-file-browser.sh" -show file
```

**Comment by orschiro** [comment]
Thank you. 

I just tried your script. Am I correct that it only shows the files of the directory in which the `rofi-file-browser.sh` is located?

In other words, I cannot search for files located somewhere in a subfolder of `~/...`, correct?

**Comment by DaveDavenport** [comment]
It should store last location.   So once you enter the right directory, it should be there next time.

**Comment by orschiro** [comment]
Sorry for my late response. Indeed the right directory is there.
