### ISSUE TITLE
Mode switching impossible on german keyboard layout

### ISSUE THREAD

**Issue by rassie** [DaveDavenport/rofi#125]
The culprit is [here](https://github.com/DaveDavenport/rofi/blob/master/source/rofi.c#L1770): `XK_slash` is already `Shift+7` on German keyboard. More importantly, `Shift+/` only equals `?` on US layout. Using `XK_question` might be more straightforward -- or make it configurable.

**Comment by rassie** [comment]
Seems that `XK_question` won't work either, I've managed to make it work with `Shift-Right`.

**Comment by DaveDavenport** [comment]
What would be a good alternative?   ctrl-tab is often used to switch between windows/tabs inside a program?

**Comment by DaveDavenport** [comment]
@carnager You have any opinion about this?

**Comment by carnager** [comment]
actually i think shift+right/left is a good idea. Many tabbed terminals use this too

**Comment by DaveDavenport** [comment]
Shift left right does sound sane..  I will implement this.
