### ISSUE TITLE
Implement ctrl-w

### ISSUE THREAD

**Issue by vimeitor** [DaveDavenport/rofi#126]
Hello!

I saw the thread regarding the implementation of emacs keybindings. There is, however, one very useful keybinding (ctrl-w) that pretty much all programs implement which deletes one word backwards. It's a vim keybinding, but way more useful that the emacs counterpart, so I believe it would be extremely useful to implement. I would give it a shot if you are fine with it, but I have no idea how to start. What are the functions that control the text?

**Comment by DaveDavenport** [comment]
Finding boundaries in UTF-8 is not trivial:
http://www.unicode.org/reports/tr29/#Default_Word_Boundaries
Glib does not provide a function for this. 

Pango might have a function for this. (probably pango_break() can be used for this).

This is a WRONG!!! implementation, but shows how to add it:
http://random.sarine.nl/break_example_wrong.patch

**Comment by DaveDavenport** [comment]
pango break: https://developer.gnome.org/pango/stable/pango-Text-Processing.html#pango-break

**Comment by DaveDavenport** [comment]
Slightly better version: http://random.sarine.nl/implement_word_access.patch

This one implements some of the rules of the previous link.
alt-f forward one word.
alt-b backward one word.
ctrl-alt-h: delete one word back.
ctrl-alt-d: delete one word

This might be good enough.

**Comment by vimeitor** [comment]
Thank you!
