### ISSUE TITLE
Hotkey for custom modes

### ISSUE THREAD

**Issue by gbitzes** [DaveDavenport/rofi#128]
Hi, I was thinking about writing a patch for a new command line option called "-keys", which would be a comma separated list of keys for each mode in "-switchers". It would allow me to bind a key for a custom mode, which as far I can tell is not possible now.

As an example: ./rofi -switchers "run,ssh,CustomMode:custom_mode.sh" -keys "F10,F11,F12".

F10 would open run, F11 ssh and F12 CustomMode. It would deprecate "-rkey" and "-skey", and maybe "-key"

Would you be interested to merge it?

**Comment by DaveDavenport** [comment]
Yes, this is something I have been thinking over for a while.
I would like to have something like this:

```
-key-<switcher name>
```

**Comment by gbitzes** [comment]
Neat, thanks!
