### ISSUE TITLE
-show run only works

### ISSUE THREAD

**Issue by silasb** [DaveDavenport/rofi#130]
I'm having some trouble getting rofi working.  `rofi -rnow` doesn't work, just sits there doing nothing.  `rofi -show run` works.  All the other `snow, now, or rnow` all don't work.  Also when I start it up via `./rofi` no key bindings can activate it.

**Comment by DaveDavenport** [comment]
The -rnow, -snow and -now have been deprecated since 21 Juli. In yesterday commit they are removed.
For the new syntax please see the manpage.

Also the keybinding command has been updated to be more flexible.  see manpage.


```
-show run
-show window
-show ssh
-show <custom>
```
For keybinding:

```
-key-run alt-F2
-key-window alt-Tab
-key-ssh alt-F3
```
