### ISSUE TITLE
Implement fuzzy search (as an option)?

### ISSUE THREAD

**Issue by roomcays** [DaveDavenport/rofi#133]
[Dmenu2](https://bitbucket.org/melek/dmenu2/) provides so-called "fuzzy search", activated when providing `-z` option in command line:
```sh
$ dmenu -z
```
When using this mode, search is less conservative. For example, when having list like:

* foo
* bar
* foobar

typing `fb` will filter the list down to

* **f**oo**b**ar

in contrast to normal mode, when one would have to type `foob` to achieve the same result.
I wonder if rofi could implement this feature too?

**Comment by tempo** [comment]
I really'd like to see this :+1: :-)

**Comment by shioyama** [comment]
:+1: on this, would be great to have.

**Comment by gregf** [comment]
Would also love to see this. :+1:

**Comment by kornalius** [comment]
:+1:

**Comment by tempo** [comment]
I'm not sure how to test it, I run rofi as follows
`$ ./rofi -key-run F12 -z`

but I don't notice any differences to normal mode.

**Comment by DaveDavenport** [comment]
I implemented it in dmenu mode.  Not normal mode.

To be honest I think it is a bit silly and has way to many false positives.

**Comment by roomcays** [comment]
Just compiled rofi from github sources and "fuzzy search" works just fine (in dmenu mode)! Thanks, Dave!
I hope that this modification will not influence overall stability and will stay as an option for those rare scenarios where needed.

**Comment by DaveDavenport** [comment]
One thing I am very unsure about is how it handles utf8 input. Needs testing!

**Comment by tempo** [comment]
ah okay, now I see ;-)

I think there's a problem if a character appears twice in the search. Example list:
* test
* Makefile
* foo

I want to select `Makefile` and therefore type `ee`, but `test` remains in the result list

**Comment by DaveDavenport** [comment]
aah yes, indeed a bug. will ix.

**Comment by tempo** [comment]
issue with double chars fixed :+1:

unicode seems to work for me as well

**Comment by DaveDavenport** [comment]
```
-fuzzy
````
Now deprecates -z and should work globally in rofi (so also window switcher, run, etc.)

**Comment by roomcays** [comment]
Hmm... Something is possibly wrong, see the screenshot below:
![Rofi's find window, entered "RR"](http://oi61.tinypic.com/35d2o9j.jpg)

As you can see I entered `RR` and `Atom | untitiled - Atom` shows on the list.
`xprop` result can be found here: http://www.pastebin.ca/3042214
Probably `_OB_APP_ROLE(UTF8_STRING) = "browser-window"` is the reason of this "mismatch".

**Comment by DaveDavenport** [comment]
this is intended behavior.   The window part always matched title, class, role and name.
