### ISSUE TITLE
How to horizontal mode in v 0.15.2 

### ISSUE THREAD

**Issue by rfegq4** [DaveDavenport/rofi#134]
Hi guys,

In v 0.14.9 I had the ability to set rofi in horizontal mode. I've used the setting "rofi.hmode: true" in .Xresources. This doesn't seem to work for the version 0.15.2. Is this still possible in the version 0.15.2? If so, which command should I use?

Thanks in advance.

**Comment by roomcays** [comment]
As noted in [release note for 0.15.2](https://github.com/DaveDavenport/rofi/releases/tag/0.15.2), hmode is removed.

**Comment by DaveDavenport** [comment]
If somebody would implement this nicely I would accept a patch. but the current implementation was not very good.
