### ISSUE TITLE
/etc/hosts support for ssh mode

### ISSUE THREAD

**Issue by yermulnik** [DaveDavenport/rofi#137]
Please, add /etc/hosts scannig in addition to ~/.ssh/config in ssh mode.
Thanx in advance

**Comment by DaveDavenport** [comment]
Parse for the alias? and add those?

**Comment by yermulnik** [comment]
Hmm... guess, "official host name" (second field in a single line, as of `man 5 hosts') would be sufficient.
Thanx

**Comment by yermulnik** [comment]
By the way, I guess parsing of `known_hosts' rather than `config' and `hosts' could be much more usable (if records in `known_hosts' are not encrypted): `config' and `hosts' contain kind of "especial" hosts, but `known_hosts' contains all of the hosts known to this particular user and host. And I guess it's most often when one wants to connect to some already known host rather than "predefined" host from `config' or `hosts'.
Sorry for intricate ideas =)

**Comment by yermulnik** [comment]
Thank you. Will test it during the next week.
