### ISSUE TITLE
Close switcher window before activating the selected client (sloppy focus issue)

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#138]
I am seeing an issue when using rofi's window switcher and awesomeWM.

The problem seems to be that rofi activates the new selected client/window from the switcher window, but then unmaps/closes its window after that.

This causes awesomeWM to first raise the chosen window, but then it seems to get an event because of the unmapping and will focus the window where the mouse points at.
This is done internally in awesomeWM through the `mouse::enter` signal, which gets emitted / triggered via some X/xcb events, and then the default sloppy focus handler focusing the window.

TEST CASE:
1. open rofi's window switcher
2. put the mouse cursor into it
3. select a window from the same wm_desktop / awesome tag
4. awesomeWM will eventually give focus to the window that is under the mouse cursor

While it's probably an issue with awesome mainly, it appears to be sensible that rofi does not hide its window after activating another one, but should do so before.

**Comment by DaveDavenport** [comment]
hmmm would not have expected  that behavior, fixing it might not be fully trivial (to do cleanly) because internal structure.. Will look at it.

**Comment by blueyed** [comment]
Thanks!

It's a bit odd: there are also no mouse::enter/mouse::leave events for rofi's window, which is likely caused by some special property of it.

**Comment by blueyed** [comment]
Just for reference, the properties of the rofi window are just:
Just f    _NET_WM_WINDOW_OPACITY(CARDINAL) = 4294967295
    WM_NAME(STRING) = "rofi"
    _NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE

It also uses `override_redirect = True` ([source](https://github.com/DaveDavenport/rofi/blob/a083e21a6bf0d8f5e91b302a5033d1da5043145a/source/rofi.c#L259-261)), which prevents the mouse enter/leave in awesome.

**Comment by blueyed** [comment]
Just for reference (on the awesomeWM side): I've had fixed this in my awesomeWM config (by remembering and comparing it to the previous client), but then noticed it with the default config again.
I've created a PR, which looks at the mouse coords: https://github.com/awesomeWM/awesome/pull/183

**Comment by DaveDavenport** [comment]
Can you test this: http://random.sarine.nl/rofi_unmap_window_before_switch.patch patch to see if that fixes it. I now explicitly unmap the window before switching.

**Comment by DaveDavenport** [comment]
Can you test this: http://random.sarine.nl/rofi_unmap_window_before_switch.patch patch to see if that fixes it. I now explicitly unmap the window before switching.

**Comment by blueyed** [comment]
The patch itself does not appear to help: there's still a `mouse::enter` event when closing the rofi window (as expected), but it appears to be emitted after the selected window was focused.

While having this patch (maybe improved even) won't hurt, I think it's an issue with awesome's sloppy focus handler in the end.

Given the circumstances, do you think it's expected that a mouse::enter event is being emitted for the window below the rofi window, in case the mouse pointer is inside of it?
To prevent this, the window manager would have to ignore any events for regions of redirected windows altogether, or something similar?

**Comment by DaveDavenport** [comment]
Will this work? http://random.sarine.nl/rofi_unmap_release_window_before_switch.patch I also release keyboard before.

**Comment by blueyed** [comment]
It doesn't help either..

Is rofi also grabbing the mouse?
There's more information / a guessing in https://github.com/awesomeWM/awesome/issues/189#issuecomment-89427013.

**Comment by DaveDavenport** [comment]
just call XGrabKeyboard and then do XUngrabKeyboard

**Comment by DaveDavenport** [comment]
Current version does explicitly ungrab keyboard and unmap window before doing the switch.
