### ISSUE TITLE
Enter should not auto-complete commandline arguments

### ISSUE THREAD

**Issue by JasonWoof** [DaveDavenport/rofi#141]
This report is about -show run

Use-case:

I type: icew and press enter

result: it runs "iceweasel", as it should

I type: iceweasel jasonwoof.com

result: it opens my home page

I type: icew

result: it opens my home page

expected result: it opens iceweasel (not passing it any paramaters)

me: wtf? I didn't ask for jasonwoof.com, I just wanted iceweasel

Conclusions:

1.    auto-completing command names is awesome (since incomplete command names don't work).

2.    auto-completing command+parameters results in inconsistent (across time) results, thus forcing the user to break their concentration to pay attention to your program, instead of just typing what they want. It is important to me that I can always type the same sequence of keys to get a web browser. When this is the case, that sequence of keys becomes a habit, something I can do without breaking my concentration.

**Comment by DaveDavenport** [comment]
Disable history then. 
If you enter `iceweasel someurl.com`  this will be added to history
next time you search icew:  iceweasel and `iceweasel someurl.com` is in the list.
Depending if you have levensthein-sort enabled it will pick closes match (iceweasel) or iceweasel someurl (last used)

**Comment by JasonWoof** [comment]
Thanks. Disabling history is good enough for me.

**Comment by gergesh** [comment]
I know that this is old and closed - but I'd like to join the request. Disabling history isn't a good solution. I'd like to be able to type commands that require command line arguments without the compromise of typing 'ch' and being offered abcecho instead of chromium. Would it be hard to implement history only for the first word in the command?

**Comment by diparrtyate** [comment]
Another solution could be to introduce a key bind to run the command written by the user instead of the one suggested/auto-completed, so you don't have to delete an entry or disable history every time.

**Comment by sardemff7** [comment]
It already exists, and it gets added to the history. Please do not revive ancient bug reports for unrelated (or loosely related) comments.
