### ISSUE TITLE
window list: non-active selected entries not visible

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#148]
With/after c276090b183b2c78f97bd8fa329fd9347c774515 the non-current (but selected) entries in the window list are not visible, because they have the same bg/fg.

I've tried the patch/printf from https://github.com/DaveDavenport/rofi/issues/37, but it does not output anything.

I've also tried explicitly adding/using the output from `rofi -dump-xresources`.

**Comment by DaveDavenport** [comment]
yeah, that is indeed wrong.. thx.
