### ISSUE TITLE
Pasting and resulting cursor position

### ISSUE THREAD

**Issue by cipriancraciun** [DaveDavenport/rofi#150]
When pasting the cursor is placed just before the last character pasted.

This happens regardless if pasting when the input is empty, if pasting at the beginning, end or in the middle of existing input.

The `rofi` version used is `0.15.2`.

**Comment by DaveDavenport** [comment]
Hopefully this commit should fix that:
https://github.com/DaveDavenport/rofi/commit/21144aef177f80ba1936043710d6e82ca962b7fa
