### ISSUE TITLE
Tilda key is ignored (`~`)

### ISSUE THREAD

**Issue by cipriancraciun** [DaveDavenport/rofi#151]
When pressing the `~`, it is ignored (i.e. it does not show up in the input).

The used `rofi` version is `0.15.2`.

**Comment by DaveDavenport** [comment]
Tilde is used to switch between case-sensitive/insensitive mode.
Should come up with a better keybinding.

**Comment by cipriancraciun** [comment]
Only now I've seen that the tilda is used to change the casing.

Personally I would suggest leaving "normal" keys for input, and only allow keys in combination with either Control, Shift or Alt (plus the functional and usual navigation keys).

P.S.:  It would be lovely if one could customize all key bindings.

**Comment by DaveDavenport** [comment]
customizing key bindings is on the future to do.

**Comment by DaveDavenport** [comment]
should be ctrl+grave now. should also work with intl. keyboard.
