### ISSUE TITLE
delayed focus for rofi run dialog 

### ISSUE THREAD

**Issue by tempo** [DaveDavenport/rofi#153]
I'm running rofi 0.15.4-1 (from debian unstable) in daemon mode (within i3 window manager) as an replacement for dmenu as follows:

``` bash
$ rofi -key-run alt+r -key-window alt+w
```

When I'm hitting alt+r in order to open the run dialog and instantly starting to type the name of the program I want to start, then rofi doesn't get the first 1-3 characters typed. The missing characters are going to be typed within the window focused before hitting the run dialog shortcut. Same observation in case I'm hitting the shortcut and immediately ESC in order to close the window.

It feels like the dialog window itself shows up in time, but gets focus a couple of milliseconds later.

Tested with xfce as well, but the issue does hold true.

**Comment by DaveDavenport** [comment]
Yes, this is a known issue.  I am not sure how to solve this.
It seems it can easily take up to 300ms (in i3) to grab the keyboard, I am unsure why this takes so long.  To make things weirder, it seems to vary a lot between users.

As I said, I am unsure how to solve this, I use [XGrabKeyboard](http://tronche.com/gui/x/xlib/input/XGrabKeyboard.html) to get the keyboard and this calls just takes this long.

**Comment by fd0** [comment]
I'm suffering from this as well, makes me prefer to use dmenu instead of rofi at the moment. What things does dmenu different?

**Comment by DaveDavenport** [comment]
This copies dmenu behavior:
```patch
diff --git a/source/rofi.c b/source/rofi.c
index 8dd321c..e49d0af 100644
--- a/source/rofi.c
+++ b/source/rofi.c
@@ -935,6 +935,9 @@ MenuReturn menu ( char **lines, unsigned int num_lines, char **input, char *prom
     }
     workarea mon;
 
+    for(int i =0; i < 1000 && !take_keyboard ( display, DefaultRootWindow(display));i++){
+        usleep(1000);
+    }
     // main window isn't explicitly destroyed in case we switch modes. Reusing it prevents flicker
     XWindowAttributes attr;
     if ( main_window == None || XGetWindowAttributes ( display, main_window, &attr ) == 0 ) {
@@ -1071,7 +1074,7 @@ MenuReturn menu ( char **lines, unsigned int num_lines, char **input, char *prom
     menu_refilter ( &state, lines, mmc, mmc_data, sorting, config.case_sensitive );
 
     int x11_fd       = ConnectionNumber ( display );
-    int has_keyboard = take_keyboard ( display, main_window );
+    int has_keyboard = 1;//take_keyboard ( display, main_window );
     while ( !state.quit ) {
         // Update if requested.
         if ( state.update ) {

```

I can still reproduce the problem though. Does it improve?

**Comment by tempo** [comment]
Wow, that's what I call immediate response, thank you!

At first sight, your change fixed the issue for me! :-)
I will test it during the rest of the day and let you know if there are any problems coming up.

**Comment by DaveDavenport** [comment]
This change has one advantage, it grabs the keyboard on the main window.  This you can actually do before you start building up the GUI.  I used to grab the keyboard on the Rofi window.
The time to do the initial setup of the window and filter entries, etc. is therefor now after grabbing keyboard, not before. (To be honest I did not know I could do that, until I double checked dmenu's code).

So it does not solve the issue, but should reduce it. (I can still manage to get one or two keypresses reach the active program before rofi grabs it.)

**Comment by tempo** [comment]
It totally works out for me! I'm not able to reproduce the issue any more in my setting, no matter how fast I'm hammering on my keyboard.

Anyway, your fix reduces the chance of walking into the trap immensely.

**Comment by fd0** [comment]
Works for me, too. Thanks a lot!

**Comment by DaveDavenport** [comment]
Ok, I will commit this patch.
