### ISSUE TITLE
Allow any key binding to work with new feature introduce in commit 8d4e1ee

### ISSUE THREAD

**Issue by ejemba** [DaveDavenport/rofi#156]
In french keyboard there is no direct access to key 1 to 9. (I know ...)
In the great new feature introduced here https://github.com/DaveDavenport/rofi/commit/8d4e1ee8fa1b6cc2bdd97e8dc5bc47e0a4896b71

Can we propose a mapping keybinding/output at the command line ? this way even the alt+1-9 can be used and folks may avoid poorly designed keyboard side effects.

Very poor pseudo code sample:
          `"alt+1" => "1" / "n" => "n" / "ctrl+t" => "t"`

**Comment by carnager** [comment]
yes, might be good. Maybe arguments for keys and for modifier can be used.

rofi -modkey Mod1 -key10 1 -key11 2 -key12 3 -key13 4 -key14 5

**Comment by DaveDavenport** [comment]
Fixed in git:
```Xresources
rofi.kb-custom-1:                    Alt+1
rofi.kb-custom-2:                    Alt+2
rofi.kb-custom-3:                    Alt+3
rofi.kb-custom-4:                    Alt+4
rofi.kb-custom-5:                    Alt+5
rofi.kb-custom-6:                    Alt+6
rofi.kb-custom-7:                    Alt+7
rofi.kb-custom-8:                    Alt+8
rofi.kb-custom-9:                    Alt+9
```

**Comment by carnager** [comment]
Oh, it even works with single key events... nice
