### ISSUE TITLE
`dmenu`-like mode where the "displayed" data is mapped to different "output" data

### ISSUE THREAD

**Issue by cipriancraciun** [DaveDavenport/rofi#157]
In order to build more "user friendly menus", it would be lovely to have an option that makes `rofi` read from `stdin` two sets of data:  one to display the choices to the user, and one to actually output on `stdout`.

For example it could read a tab-separated input, where before the tab is what to be displayed, and after the tab what to be returned.  (This would imply adding a new separator option.)

A second choice would be to read one line for the displayed data, followed by one line of returned data.  (Using the same separator as before.)

Example (` \t ` is actually a tab character in this example):
> rofi <<'EOS'
> option one \t do something one
> option two \t do something two
> EOS

The user chooses `option one`, and `rofi` outputs to `stdout` `do something one`.

**Comment by carnager** [comment]
Though i don't think this will be implemented, just for reference:
https://the-lambda-church.github.io/dmlenu/

**Comment by DaveDavenport** [comment]
This can be solved in script wrapping rofi.
The `-i` mode (return index) can help here.

Extending the `dmenu` mode is fine, but it might be good to write a full specification first, then implement instead of having a wild grow. (like happen with the 312 dmenu patches)

**Comment by rightaway** [comment]
+1 Very useful, especially when the output data could be long and unreadable like URLs.

**Comment by DaveDavenport** [comment]
This can be easily solved outside rofi. (f.e. using the output formatting option (see manpage) where you can return the selected index). With this I don't see a reason to make rofi keep multiple lists.
