### ISSUE TITLE
Display window immediately on startup, then read `stdin` (in `dmenu` mode)

### ISSUE THREAD

**Issue by cipriancraciun** [DaveDavenport/rofi#159]
Currently, in `dmenu` mode, `rofi` waits to read the entire data from `stdin` and only then it displays the UI.

For example, in case the user starts `rofi` from the window manager as triggered by a key binding, and the user starts typing something (without waiting for the `rofi` window to appear), the key presses are missed by `rofi`.  Furthermore when the list of options is dynamically generated and it takes a while for it to finish, the user is left with no visual indication that something happened after his key press.

Therefore it would be nice for `rofi` to immediately show the UI and grab the keyboard, then continue reading from `stdin`.  (Bonus points if it allows the user to enter something while it reads from `stdin`, but even a UI saying something like `busy...` would be enough.)

**Comment by DaveDavenport** [comment]
It currently behaves as dmenu does, it would idd be nice if it could something like this.

**Comment by DaveDavenport** [comment]
First version of this in GIT.
