### ISSUE TITLE
Prefer last commands in search result list

### ISSUE THREAD

**Issue by tempo** [DaveDavenport/rofi#161]
I use have a small set of programs regularly started from the rofi launcher.

For example, if I start the rofi launcher, it looks like
```
firefox
nautilus
icedove
gdmflexiserver
arandr
[...]
```

I want to start `icedove` and therefore I start to type `ice`.
Rofi's result list now looks like:
```
nice
snice
ionice
renice
icedove
[...]
```

It would be very helpful if the most recent commands from the history were preferred among the result list. The list then could look like:
```
icedove
nice
snice
[...]
```
and I could just hit enter, my desired program would start and I could save dozens of keystrokes a day =)

**Comment by carnager** [comment]
just don't type. rofi lists most often started apps on top.

but I agree, history should be included in filtered results and it should be sorted the same way as in non-filtered state.

**Comment by DaveDavenport** [comment]
turn off levensthein sorting does this?

**Comment by tempo** [comment]
Oookay, I just didn't realised that levenstheun sorting was enabled by default. Turning it explicitly off with `-no-levenshtein-sort` shows the following result by typing `ic`

```
icedove
libreoffice
cachepic
cd-iccdump
[...]
```

thanks for the hint, I will test it today!

**Comment by tempo** [comment]
totally works for me with levenshtein sort turned off!
Thanks for the hint, this may be closed from my side.
