### ISSUE TITLE
Window switcher fails in i3: No such file or directory

### ISSUE THREAD

**Issue by vlow** [DaveDavenport/rofi#163]
Hello,

I just installed rofi and love it so far. Unfortunately, when I try to use the window switcher, it fails. On my terminal I get the output:

    Failed to connect to I3 (/run/user/1000/i3/ipc-socket.435): No such file or directory

This happens with an unconfigured stock rofi, freshly from git, compiled through AUR (with I3 support).

Am I doing something wrong?

Best regards

Florian

EDIT: Of course, also I checked. the above mentioned path is existing.

**Comment by DaveDavenport** [comment]
Never seen this one before.  Are you using i3?

**Comment by vlow** [comment]
Yes, and I only get this if I use the rofi-git package to which you refer in the installation guide (https://aur.archlinux.org/packages/rofi-git/). If I use the rofi package instead (https://aur.archlinux.org/packages/rofi) everything works out-of-the-box.

**Comment by DaveDavenport** [comment]
eeuh might be indeed silly issue:
Does this fix it?
```patch
diff --git a/source/i3-support.c b/source/i3-support.c
index 0d7a766..74dfeed 100644
--- a/source/i3-support.c
+++ b/source/i3-support.c
@@ -50,7 +50,7 @@ char *i3_socket_path = NULL;
 void i3_support_focus_window ( Window id )
 {
     i3_ipc_header_t    head;
-    char               command[128];
+    char               command[UNIX_PATH_MAX+1];
     int                s, len;
     ssize_t            t;
     struct sockaddr_un remote;
@@ -66,7 +66,7 @@ void i3_support_focus_window ( Window id )
     }
 
     remote.sun_family = AF_UNIX;
-    g_strlcpy ( remote.sun_path, i3_socket_path, strlen ( i3_socket_path ) );
+    g_strlcpy ( remote.sun_path, i3_socket_path, strlen ( i3_socket_path )+1 );
     len = strlen ( remote.sun_path ) + sizeof ( remote.sun_family );
 
     if ( connect ( s, ( struct sockaddr * ) &remote, len ) == -1 ) {
```

**Comment by vlow** [comment]
wow, yes! thank you for the quick fix!

**Comment by DaveDavenport** [comment]
thanks reporting. I made a typo yesterday. (still worked on my pc weirdly enough and on regression test server)

**Comment by DaveDavenport** [comment]
please test if latest commit did not break this again.

**Comment by vlow** [comment]
Sorry for the delay! I just checked with two machines and everything works smoothely.

**Comment by DaveDavenport** [comment]
Thanks.
