### ISSUE TITLE
Catch 'KeyRelease' event if the entry was selected by pressing 'Return'

### ISSUE THREAD

**Issue by foxxx0** [DaveDavenport/rofi#167]
If you select an entry with the 'Return' key rofi will start processing on the 'KeyPress' event an leave the 'KeyRelease' on the stdin buffer.

This produces some quite annoying side effects e.g. when rofi is used to fill out forms in a web browser. For example: The roundcube webinterface listens to KeyUp events and somehow jumps from the username field to the password field if it catches such an event.

After having a quick look through the source code I would suggest the following:
* handle 'Return' separatly from 'Control+j', 'Control+m' and 'KP_Enter'
* if the key from the 'KeyPress' event was 'Return' wait for the corresponding 'KeyRelease' event and THEN continue processing

This would be quite a nice fix that removes some definitely unwanted behaviour.

A fix would be greatly appreciated, thanks in advance.

**Comment by DaveDavenport** [comment]
Does this help? @carnager 

```patch
diff --git a/source/rofi.c b/source/rofi.c
index dd632f0..54d18ce 100644
--- a/source/rofi.c
+++ b/source/rofi.c
@@ -1302,7 +1302,14 @@ MenuReturn menu ( char **lines, unsigned int num_lines, char **input, char *prom
                     }
                 }
             } while ( XCheckTypedEvent ( display, KeyPress, &ev ) );
-        }
+        } 
+    }
+    // Wait for final release?
+    {
+        XEvent ev;
+        do{
+            XNextEvent(display,&ev);
+        }while(ev.type != KeyRelease);
     }
 
     // Update input string.
```

**Comment by foxxx0** [comment]
Works just fine, thank you very much for that fast fix.

**Comment by carnager** [comment]
just for completeness. works for me (tm)

**Comment by carnager** [comment]
Not sure, when this happened, but this bug is back.

**Comment by carnager** [comment]
for completeness:
`-kb-accept-entry \!Return` fixes this behavior

**Comment by DaveDavenport** [comment]
Going to close this for now.  Changing default behaviour feels weird, especially when using Control-j or so to accept entry. I guess for this particular tool, it can override the keybinding.
