### ISSUE TITLE
Compiling rofi in Ubuntu

### ISSUE THREAD

**Issue by mardukbp** [DaveDavenport/rofi#168]
I just compiled the latest release of rofi in Ubuntu 15.04. Following the installation guide was not sufficient. I had to also install `pkg-config` and the header files of all the libraries mentioned (package names ending with `-dev`).

**Comment by DaveDavenport** [comment]
`pkg-config` is indeed missing.  I can add a section targetting debian/ubuntu.  Shamefully package names are not 'unique' between distro's.

**Comment by jpleau** [comment]
I think RHEL/Fedora/CentOS use -devel for library headers.

@mardukbp rofi is now available in Ubuntu repos: https://launchpad.net/ubuntu/+source/rofi

Not sure if it can be used directly on 15.04, my guess is "yes"

**Comment by mardukbp** [comment]
@jpleau I could not install it with `apt-get` even with all the `*verse` repositories enabled.

**Comment by jpleau** [comment]
@mardukbp It's not available for 15.04, it was added recently for the next release 15.10
