### ISSUE TITLE
DPI honored for fonts?

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#171]
I've recently migrated away from gnome-settings-daemon and have changed my DPI settings via `xsettingsd` and `xrdb`.  I was using the default of 96 DPI before.

I've noticed that `rofi` displays the text bigger now, similar to other apps that were not aware of the adjusted DPI setting.

Should this be handled properly?
What resource is rofi using for this?

I can try if using gnome-settings-daemon again would fix it etc.

**Comment by DaveDavenport** [comment]
Good question, no idea how pango handles this.. cannot find anything about this in the docs.

**Comment by DaveDavenport** [comment]
Can you try setting `Xft.dpi` in Xresources and load that, that seems to adjust the rendering in rofi.

**Comment by blueyed** [comment]
I have that already:

    % xrdb -q|grep -i dpi
    Xft*dpi:	125

**Comment by blueyed** [comment]
I've also tried to kill and restart rofi - maybe it was started before.. but that did not help.

I am using `rofi -key-window mod1-F1 -key-run mod1-F2 -width 80`.

**Comment by DaveDavenport** [comment]
Ok, had time to play a bit with it:

For me it works correctly: If I increase Xft.dpi from `98` to `125` the font's gets bigger.
This is correct, because the font size is kept the same (in inches) so higher **D**ots **P**er **I**nch -> bigger fonts. This seems to be working ok if I compare my private laptop (216dpi) and work laptop (132 dpi).

**Comment by blueyed** [comment]
You are right.

I got confused, because I was using a wrong DPI (96) before, and often have configured fonts in pixels (e.g. pixelsize=16 for urxvt).
My thinking was that a font of 12pt should be the same size, but that's not the case if you change/fix the DPI for obvious reasons.

Just for clarification, and reference: `8pt` refers to `8/72` inches.
With 1366 pixels on 10,9 inches (277mm) the pt-to-px ratio is `1366 / (10.9 * 72) = 1.75` (125dpi).
With 1366 pixels on 14,21 inches (361mm) the pt-to-px ratio is `1366 / (14.21 * 72) = 1.36` (96dpi).

The default of `mono 12` used with rofi was OK with the wrong DPI, but appeared too big to me with a DPI of 125 then.

I am using `rofi -key-window mod1-F1 -key-run mod1-F2 -width 80 -font "Ubuntu Mono 9"` now.

Sorry for the noise.

**Comment by blueyed** [comment]
@DaveDavenport 
For some reason the DPI on a new machine does not get picked up properly currently anymore, but if I remember correctly it worked in the beginning.

```
$ xdpyinfo | grep resolution
  resolution:    176x177 dots per inch
$ xrdb -q|grep -P '(rofi|dpi)'
Xft*dpi:	176
rofi.bg-active:	#002b36
rofi.bg-urgent:	#002b36
rofi.key-run:	mod1-F2
rofi.key-window:	mod1-F1
```

I am using `xrandr -dpi 176` to configure this, and also have a xsettingsd instance, which serves `Xft/DPI 180224` (176*1024).

Any idea what I am missing?

**Comment by DaveDavenport** [comment]
please make a new bug report for this. Don'

**Comment by blueyed** [comment]
Sure: https://github.com/DaveDavenport/rofi/issues/254.
