### ISSUE TITLE
'rofi -show combi -combi-mode "window,run,ssh"' does not work

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#174]
I've tried the example from the man page, but it does not work.

    Combi settings
       -combi-modi mode1,mode2

              The modi to combine in the combi mode.
              For syntax to see `-modi`.
              To get one merge view, of window,run,ssh:
                      rofi -show combi -combi-mode "window,run,ssh"

    % rofi -show combi -combi-mode "window,run,ssh"
    The combi switcher has not been enabled

The following works:

    rofi -show combi -switchers combi -combi-modi window,run

1. There does not appear to be a "-combi-mode" setting, is there?
2. Unknown args should result in an error (e.g. `rofi -foo -show run`)
3. Using `-switchers` should not be necessary in this case?!

**Comment by DaveDavenport** [comment]
1. There is a combi-modi it tells the 'combi'  mode what switchers to combine.
2. this is debatable. I am not fully decided myself on this.
3. No, `-modi` still has a use here.. you might want to have combi combinding run and window, and have ssh as a separate one. e.g. I use this myself:
```
rofi.modi:                           combi,calc:qalc -t
rofi.combi-modi:                     window,run,ssh
```

**Comment by blueyed** [comment]
@DaveDavenport 
Regarding the `qalc -t` runner: it's very useful.

Is it possible to close rofi and copy the result (selected entry) to the clipboard? (with something like `Shift-Enter` / `Control-Enter`)

I am using `rofi -show calc -modi "calc:qalc -t"` currently.

**Comment by DaveDavenport** [comment]
make a script that wraps qalc and implements it, then call it from the modi.

Should not really be part of rofi..

**Comment by blueyed** [comment]
For this to work there would need to be a way for the script to distinguish between a selected entry (the result from qalc) and custom input (to be sent to qalc).
I've tried reading stdin to look for input (a selected entry) there without success.

This script I've tried:

```sh
while read -r line; do
  echo "INPUT:$line"
  exit
done

if [ -n "$1" ]; then
  out="$(echo "$@" | qalc -t | sed -E '/^(>.*)?$/d')"
  echo "$out"
fi
```

**Comment by blueyed** [comment]
Why don't you think that `rofi` should not have support for `copy selected entry to (primary) clipboard` key bindings?  (Ctrl-C seems to be available)

**Comment by DaveDavenport** [comment]
Because that is  something different.  On 'close'  ((shift/control)enter) I do not see a point, you can solve this externally (with a script.).

Copying a selected entry as generic keybinding I might consider, but not tagged on to an old bug report.

**Comment by blueyed** [comment]
> On 'close' ((shift/control)enter) I do not see a point, you can solve this externally (with a script.).

I might be missing something here then, because there is no "close" (apart with Escape) from there, i.e. I cannot distinguish input from a selection (of a result) in the script, can I?

**Comment by DaveDavenport** [comment]
Normally '(Shift) Enter'  is accept entry, how the script handles this is up to the script, not Rofi. Normally it is closing (window, ssh, run, drun, etc.).

**Comment by blueyed** [comment]
..but that's state information only available in rofi itself, isn't it?
(https://github.com/DaveDavenport/rofi/blob/bf51983150d5d193be702b496506090c0daf9fe1/include/mode.h#L27-L39)

**Comment by DaveDavenport** [comment]
Still for an Accept (enter) action,  ROFI should NOT decide to copy to clipboard.

If something in the interaction with the script is missing, we should fix that. Not move functionality into rofi.

Anyway this discussion does not belong here.  I do not want old bug reports being hi-jacked.
