### ISSUE TITLE
Segfault in dmenu mode with empty input

### ISSUE THREAD

**Issue by Schnouki** [DaveDavenport/rofi#175]
With a current master I can reliably crash rofi:

    $ echo -n '' | ./rofi -dmenu
    # Enter some text in the rofi window
    zsh: done                              echo -n '' | 
    zsh: segmentation fault (core dumped)  ./rofi -dmenu

`git bisect` show that this is a regression that was introduced in 4d3b9e414de15fc3ea3be0929da8b371372b0162.

**Comment by carnager** [comment]
can't reproduce...

```
carnager@caprica ~/cover > echo -n '' | rofi -dmenu
carnager@caprica ~/cover > 
```

**Comment by Schnouki** [comment]
@carnager Did you input some text in the window, or just press enter? What's the return code of rofi (`echo $?`)?

**Comment by DaveDavenport** [comment]
yeah, it is a valid bug. the moment I saw the title, I knew what was wrong :smile:

**Comment by carnager** [comment]
error happens here:

if ( ( mretv & ( MENU_OK | MENU_CUSTOM_INPUT ) ) && list[selected_line] != NULL ) {                 
    if ( ( mretv & MENU_CUSTOM_INPUT ) ) {                                                          
        dmenu_output_formatted_line ( format, *input, -1, *input );

**Comment by Schnouki** [comment]
@carnager Yep, forgot to include that :smiley: When running that line, `list` is `NULL`, which causes a segfault.

@DaveDavenport e5caaf9d1a737a64d22404fb067899918b095678 seems to fix the issue for me. Thanks a lot for the quick fix!
