### ISSUE TITLE
demnu: allow empty/escape with "-only-match"

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#176]
`-only-match` was added in #158 and is very useful.

But it prevents you from aborting the menu using `Escape`.  I'd like to either see an extra option to allow escaping / canceling the menu, or (probably better) a new option which would disable canceling instead (if you really want to allow only matches, and no escaping).

**Comment by carnager** [comment]
indeed. it even overrides rofi's exit codes.

**Comment by DaveDavenport** [comment]
`-only-match` is correctly implemented.
What you want is `-no-custom`. This is now implemented.

**Comment by cipriancraciun** [comment]
First thanks Dave for implementing my suggestion of allowing only matching lines to be selected.

However I've hit the same issue as Daniel in having escape not working, and indeed as you say it works with `-no-custom` instead of `-only-match`.

The only issue is that this option is not documented in the manual.

**Comment by DaveDavenport** [comment]
It is in the manpage. When it is in a stable release I plan to update the website.

**Comment by cipriancraciun** [comment]
OK (forgot to mention I was using on ArchLinux `rofi` version `0.15.5` which although supports `-no-custom`, it is not documented in the man page.)

**Comment by DaveDavenport** [comment]
manpage was updated in d11c61cef1c83fc1cd1692b5c8971f482e556628 when this was added. 
I think this was after the last release.. is ArchLinux shipping git version?

Might be packaging bug.

**Comment by cipriancraciun** [comment]
I use the AUR locally built package:

  https://aur.archlinux.org/packages/rofi/

Which seems to use the `tar.gz` releases from GitHub.  The one I have built is based on `0.15.5`.

I have re-built it and double checked and the manual doesn't have that option.

Anyway this is not a big issue.
