### ISSUE TITLE
parse .ssh/known_hosts

### ISSUE THREAD

**Issue by kuminamoya** [DaveDavenport/rofi#177]
While I can enable parsing /etc/hosts with "-parse-hosts", I miss parsing .ssh/known_hosts as well. This is what ssh commandline does, and this saves me from having a huge number of entries in .ssh/config.

Could you add "-parse-known-hosts" or something like that as well?

**Comment by DaveDavenport** [comment]
Agree.

**Comment by DaveDavenport** [comment]
Forgot, as stated in #137 (I think) the known_hosts file is hashed. I cannot get the names from there.

**Comment by kuminamoya** [comment]
Mine isn´t - this is configurable. From man ssh_config:

 HashKnownHosts
Indicates  that  ssh(1)  should  hash  host  names  and addresses when they are added to ~/.ssh/known_hosts.  These hashed names may be used normally by ssh(1) and sshd(8),  but they do not reveal identifying information should the file's contents be disclosed.  The default is ``no''. [...]

So it would still make sense as an option for those who don´t hash the host names in there, or don´t you agree?

Thanks
K.

**Comment by DaveDavenport** [comment]
I think currently the default is to HashKnownHosts. Currently I do not have a machine with hashing disabled.  If somebody has, a patch is appreciated.

**Comment by kuminamoya** [comment]
It´s not on my machine (arch, openssh 6.8). You could however set "HashKnownHosts no" in your .ssh/config - this will not alter the existing entries in known_hosts, so you´d have to add new ones (or remove and recreate some existing ones).

Sorry, I am not a programmer, so I can´t come up with a path by myself.

One word of caution: I am not sure how, but some entries in my known_hosts have multiple names or a name and an ip address in one line; e.g.

a.hostname.com,1.2.3.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhL[...]

Thanks again
K.

**Comment by landryb** [comment]
Fwiw, HashKnownHosts defaults to off in upstream openssh, and it is also the case on OpenBSD... so +1 for this feature :)

**Comment by jasperla** [comment]
+1 on parsing known_hosts. If the hashedness of it might be a concern, it could be moved behind a flag like the existing `-parse-hosts`?

**Comment by jasperla** [comment]
thanks!
