### ISSUE TITLE
Missing warning when encountering invalid color values

### ISSUE THREAD

**Issue by cipriancraciun** [DaveDavenport/rofi#181]
It would be nice to have `rofi` issue a warning when a color parsing error occurs.  (And possibly other cases.)

For example on `rofi` `0.15.5` one should not use spaces within the `rofi.color-*` Xresource attributes, else it will fail to correctly use the colors.  However `rofi` doesn't complain on error.

(And the manual doesn't clearly specify that no spaces are allowed.  Moreover the example given in the manual does contain spaces.)

**Comment by DaveDavenport** [comment]
I now check for errors and strip out white spaces.. Please test.

**Comment by cipriancraciun** [comment]
Seems to be working.  Thanks.

(Although you should add to the man page that `-dump-xresources` doesn't try to parse the values.)
