### ISSUE TITLE
Word based levenshtein sorting (instead of whole line)

### ISSUE THREAD

**Issue by cipriancraciun** [DaveDavenport/rofi#182]
Currently when using the levenshtein sorting, I guess `rofi` computes the distance from the current input (as a whole string) to each line (again as a whole string) and then sorts accordingly.

However given the fact that `rofi` uses word based searching it would be nice if "somehow" there would be an option to compute a levensthein-based distance but which takes into account the boundaries both in the input and the lines.

For example for the lines `abc` and `a b c`, if the user starts to enter `a b` the first match is still `abc` although one would expect `a b c` to be the first match.

I would guess the most simple algorithm would be:  for each word in the input, compute the distance from it (prefixed and suffixed with spaces) to each line (as a whole string), and then sum these distances to give the line ranking.  (This would have an `m*n` complexity (`m` being the number of words in the input and `n` being the number of lines), but given that the user enters a small number of words it wouldn't be an issue.)

P.S.:  I'm yet to find a good approach, but currently for one of my use-cases (web bookmarks) `rofi` is counter-intuitive with the current sorting.

**Comment by DaveDavenport** [comment]
hmm I agree, this could be better.
levensteihn is often good, sometimes horrible :smile:

**Comment by DaveDavenport** [comment]
This calculates the distance between each word of the input and the line:
```patch
diff --git a/source/rofi.c b/source/rofi.c
index 9c4df71..b8e69eb 100644
--- a/source/rofi.c
+++ b/source/rofi.c
@@ -727,7 +727,12 @@ static void menu_refilter ( MenuState *state, char **lines, menu_match_cb mmc, v
             if ( match ) {
                 state->line_map[j] = i;
                 if ( sorting ) {
-                    state->distance[i] = levenshtein ( state->text->text, lines[i] );
+                    state->distance[i] = 0;
+                    char *compk = token_collate_key ( lines[i], case_sensitive );
+                    for( int k = 0; tokens && tokens[k]; k++) {
+                        state->distance[i] += levenshtein ( tokens[k], compk );
+                    }
+                    g_free(compk);
                 }
                 j++;
             }

```

**Comment by DaveDavenport** [comment]
been thinking about this some more. The problem with levenshtein is that often the difference in string lengths.

So if you type in a keyword that is an exact match in a long string can get same score as a non exact match in a shorter string.   So we need to apply some weighting, deletions at the beginning and end should score lower then (deletion,substitution, insertion) in the middle of the string.

**Comment by DaveDavenport** [comment]
```patch
diff --git a/source/rofi.c b/source/rofi.c
index 9c4df71..96ab877 100644
--- a/source/rofi.c
+++ b/source/rofi.c
@@ -202,7 +202,7 @@ static int dist ( const char *s, const char *t, int *d, int ls, int lt, int i, i
 
     int x;
     if ( i == ls ) {
-        x = lt - j;
+        x = 0;//lt - j;
     }
     else if ( j == lt ) {
         x = ls - i;
@@ -220,7 +220,10 @@ static int dist ( const char *s, const char *t, int *d, int ls, int lt, int i, i
         if ( ( y = dist ( s, t, d, ls, lt, i + 1, j ) ) < x ) {
             x = y;
         }
-        x++;
+        // If the matching string (S) is at beginning, or end could less heavy.
+        if(i > 0){
+            x+=3;
+        }
     }
     return d[i * ( lt + 1 ) + j] = x;
 }
```

**Comment by cipriancraciun** [comment]
I'm working at an alternative approach, which so far gives the desired results (perhaps).  :)

Namely, I also tokenize the input line, and compare each word from the input with each word from the line, and compute the distance as:

    distance += levenshtein (word_from_line, word_from_input)
                     * len(word_from_line) * len(word_from_input)

However if the two words are the same I subtract their length product.

Thus I prioritize more close matches, and exact word matches.

    diff --git a/source/rofi.c b/source/rofi.c
    index 9c4df71..244c687 100644
    --- a/source/rofi.c
    +++ b/source/rofi.c
    @@ -727,7 +727,19 @@ static void menu_refilter ( MenuState *state, char **lines, menu_match_cb mmc, v
                 if ( match ) {
                     state->line_map[j] = i;
                     if ( sorting ) {
    -                    state->distance[i] = levenshtein ( state->text->text, lines[i] );
    +                    state->distance[i] = 0;
    +                    char **words = tokenize ( lines[i], case_sensitive );
    +                    for( int k = 0; tokens && tokens[k]; k++) {
    +                        for ( int j = 0; words && words[j]; j++) {
    +                            fprintf (stderr, "|%s| |%s| %d\n", tokens[k], words[j], levenshtein ( tokens[k], words[j] ));
    +                            if (strcmp ( tokens[k], words[j] ) != 0)
    +                                state->distance[i] += levenshtein ( tokens[k], words[j] ) * (strlen (tokens[k]) * strlen(words[j]));
    +                            else
    +                                state->distance[i] -= strlen (tokens[k]) << 2;
    +                        }
    +                    }
    +                    fprintf (stderr, "--|%s|-- %d\n", lines[i], state->distance[i]);
    +                    g_strfreev ( words );
                     }
                     j++;
                 }


I test it with

    ./rofi -dmenu -sep , <<<'abc,a b c,zbc,ab,a b,b c,b,aa,bb,aa bb cc,aaa,bbb,ccc'

**Comment by cipriancraciun** [comment]
Small correction:  in the patch the shift should be with one bit `<< 1`, and I think it's better to just multiply the distance with the word from the line (i.e. `tokens[k]`).

So far I think it's sufficient.

    diff --git a/source/rofi.c b/source/rofi.c
    index 9c4df71..4b71c33 100644
    --- a/source/rofi.c
    +++ b/source/rofi.c
    @@ -727,7 +727,17 @@ static void menu_refilter ( MenuState *state, char **lines, menu_match_cb mmc, v
                 if ( match ) {
                     state->line_map[j] = i;
                     if ( sorting ) {
    -                    state->distance[i] = levenshtein ( state->text->text, lines[i] );
    +                    state->distance[i] = 0;
    +                    char **words = tokenize ( lines[i], case_sensitive );
    +                    for( int k = 0; tokens && tokens[k]; k++) {
    +                        for ( int j = 0; words && words[j]; j++) {
    +                            if (strcmp ( tokens[k], words[j] ) != 0)
    +                                state->distance[i] += levenshtein ( tokens[k], words[j] ) * strlen (tokens[k]);
    +                            else
    +                                state->distance[i] -= strlen (tokens[k]) << 1;
    +                        }
    +                    }
    +                    g_strfreev ( words );
                     }
                     j++;
                 }

**Comment by DaveDavenport** [comment]
Interesting,  (shouldn't strcmp be strcasecmp based on the case_sensitive setting?)

**Comment by DaveDavenport** [comment]
Hmm still biased by long lines:
![fuzzy](http://images.sarine.nl/rofi-fuz.png)

**Comment by cipriancraciun** [comment]
Regarding the string comparison, my code was only a quick hack, thus using the case insensitive comparison would make sense.

Regarding the bias towards long lines, this was not my main problem, but instead the fact that although if I enter a full word from a line, the old algorithm used to show me higher in the list other lines which had words derived from the entered one.  (like with the example of `a b` and `ab`, if I enter `a` I would like to have them ordered like `a b` and then `ab` not the other way around.)

Ciprian.

**Comment by DaveDavenport** [comment]
Just showing we still have the same issue here.. maigret has a exact match, though they are not sorted on top.  I will think about this problem some more... its not trivial.

**Comment by cipriancraciun** [comment]
But, shouldn't the `make-...` line not even be shown because it doesn't actually contain the input which is `maigret`?  (Or is it perhaps that I use the `-dmenu` mode always and have not found this case...)

But indeed, this is a very tricky problem, which I'm afraid can't even be solved for all cases, thus a "good enough" solution might be preferred.

However one can prioritize short lines by adding to the overall distance also add the square of the difference between the whole line and the whole input.  This seems to solve somehow the line length bias, but with less bias for whole words...

    state->distance[i] += abs (strlen ( lines[i] ) - strlen ( state->text->text )) << 1

Perhaps using (in the `strcmp` condition) would fix the word bias issue:

    state->distance[i] -= strlen (tokens[k]) << 2


Anyway, "magic formulas".  :)

**Comment by DaveDavenport** [comment]
It is using the new fuzzy mode (needs to be tested too :wink:)

I will settle for a good enough solution, maybe if I have some time tomorrow I with look for some papers on the topic.

**Comment by Ivoz** [comment]
It appears to me that perhaps one good solution is that exact-prefix-matches should get a prioritised score in sorting match results. Then for instance `a b` is an exact prefix of `a b c` and should manage to be sorted higher than `abc` which is not. Advantage is we no longer need to care about tokenizing words. Figuring out what sort of prioritisation (multiply by `n`? add a static weight, add varied weight based on aboslute/relative length of prefix?) could be a tricky empirical trial to see what seems to work the best, however :( But something that seems to work pretty right might be a general improvement anyway.

I base suggestion on the fact that often we manage to get the start of our search right, it's all the fuzzy details at the end that tend to be forgotten.

**Comment by DaveDavenport** [comment]
#480 kinda hits on same topic, and implementing something like fzf does might be nice solution. Let continue there.
