### ISSUE TITLE
rofi -show ssh doesn't work with termite

### ISSUE THREAD

**Issue by smlb** [DaveDavenport/rofi#183]
As title say, when I try to launch ssh (with rofi.terminal: termite in ~/.Xresources), the terminal doesn't open. With urxvt it works like a charme. Any idea why this happens?

**Comment by DaveDavenport** [comment]
I do not know? maybe termite needs a different command line?
Check the relevant configuration options:

```
rofi.ssh-client:                     ssh
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
```

**Comment by smlb** [comment]
```
rofi.modi:                 run,window,ssh
!rofi.opacity:              75
rofi.width:                30
rofi.lines:                15
rofi.columns:              1
rofi.font:                 Terminus 9
rofi.fg:                   #839496
rofi.bg:                   #121212
rofi.bgalt:                #121212
rofi.hlfg:                 #5F87AF
rofi.hlbg:                 #242424
rofi.bc:                   #5B5B5B
rofi.terminal:             termite
rofi.ssh-client:           ssh
rofi.ssh-command:          {terminal} -e {ssh-client} {host}
rofi.run-command:          {cmd}
rofi.run-shell-command:    {terminal} -e {cmd}
rofi.disable-history:      false
rofi.levenshtein-sort:     false
rofi.case-sensitive:       false
rofi.auto-select:          false
rofi.parse-hosts:          false
```

This is how it looks like in my ~/.Xresources

**Comment by DaveDavenport** [comment]
**you** need to update the ssh-command to fit with termite.

**Comment by analogbyte** [comment]
For future visitors, quotes are needed with termite:

    rofi.ssh-command:          {terminal} -e "{ssh-client} {host}"

As this does not break rofi ssh for other terminal emulators, this might be a sane default option too.

**Comment by Marcel-Robitaille** [comment]
I think @analogbyte 's solution should be default.
