### ISSUE TITLE
Mark rows that contain a given string as urgent

### ISSUE THREAD

**Issue by mardukbp** [DaveDavenport/rofi#186]
I use rofi to find TeX macros in a plain text file in which I transcribed a LaTeX quick reference card. What I would like to do is to colorize the "heading rows" based on the occurrence of a string and not on their line number in the file. For example, I prepend an asterisk to these rows: * Font sizes.

**Comment by carnager** [comment]
heading rows?

**Comment by DaveDavenport** [comment]
You can do this without explicit support in Rofi:
Say you have test.txt:
````
ap
mies
* noot
aap
* mies
noot
````

And you want to highlight lines beginning with ```*```
```bash
cat test.txt | ./rofi -dmenu -u `egrep -n -s  "^\*" test.txt | awk -F: '{print ($1-1)}' | tr '\n' ','`
````

I am sure the grep, awk tr can be combined into one awk command.

**Comment by DaveDavenport** [comment]
```bash
cat test.txt | ./rofi -dmenu -u `egrep -n -s  "^\*" test.txt | awk -F: '{printf "%d,", ($1-1)}'`
````

**Comment by mardukbp** [comment]
Great! Thank you!
