### ISSUE TITLE
Pressing enter too quickly runs wrong command

### ISSUE THREAD

**Issue by marcvs** [DaveDavenport/rofi#187]
When typing well known commands quickly and adding enter to run them, before rofi actually found that command, rofi simply starts the default suggestions.

**Comment by DaveDavenport** [comment]
This should only happen in VERY large lists that are longer then ```lazy-filter-limit``` setting.
Try setting this to -1 and try again.

**Comment by DaveDavenport** [comment]
Also see #127

**Comment by marcvs** [comment]
Yep, fixes it for me.

On Tuesday 21 July 2015 00:22:23 Dave Davenport wrote:
> Also see #127
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DaveDavenport/rofi/issues/187#issuecomment-123197125
-- 
M.
