### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [DaveDavenport/rofi#191]
I would like to point out that identifiers like "[`__ROFI_I3_H__`](https://github.com/DaveDavenport/rofi/blob/6120b9ccb81fe9e954958131b24b015d31617440/include/i3-support.h#L1)" and "[`__SCRIPT_DIALOG_H__`](https://github.com/DaveDavenport/rofi/blob/6120b9ccb81fe9e954958131b24b015d31617440/include/dialogs/script.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by DaveDavenport** [comment]
Better?

**Comment by elfring** [comment]
Yes. - Thanks for [your improvement of affected include guards](https://github.com/DaveDavenport/rofi/commit/8104997e6f1c2d9de4c9757d6cfa79831aa20e9c "Deletion of a few underscores").

How do you think about to use the project name as a prefix there?

**Comment by DaveDavenport** [comment]
Is there a direct use? given that these header files are private to rofi?

**Comment by elfring** [comment]
Will it occasionally help when such identifiers are not only standard-compliant but also reasonably unique?

**Comment by DaveDavenport** [comment]
I guess.. mostly I was curious if there was another 'standard' on this :smile:

**Comment by elfring** [comment]
Are you interested in further software evolution from reusing "the standard" of "good development praxis"?

**Comment by DaveDavenport** [comment]
I am interested to get **rofi** as good as possible.  So I appreciate these bug reports a lot.

I do want to follow 'the standard',   if possible also ' good development practices' however the last one can be subjective or dependent on situation.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/DaveDavenport/rofi/blob/c6a9de8c4a1dd9fb5c179ff323f0508f72974b9e/include/widget.h#L4 "Update candidate: _Widget") left over?

**Comment by DaveDavenport** [comment]
What is wrong with ROFI_WIDGET_H?

**Comment by elfring** [comment]
Would you like to [reconsider any identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") for your data structures?

**Comment by DaveDavenport** [comment]
Aah (was looking at the include guards ) as they where mentioned in topic.

Answer is yes. Patch is welcome.

**Comment by DaveDavenport** [comment]
Removed all the pointless ```typedef struct _A {} A;``` to ```typedef struct {] A;```

**Comment by elfring** [comment]
Thanks for [another source code clean-up](https://github.com/DaveDavenport/rofi/commit/c4b65d975c08862dfbdce2552e681c62ea79da2f "Adjustments around data type identifiers").
