### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [DaveDavenport/rofi#192]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html "Close a stream.") ⇒ [history_set](https://github.com/DaveDavenport/rofi/blob/f88cfacfde7719cdaba2528b8d1f98c4674d2e94/source/history.c#L111)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [main](https://github.com/DaveDavenport/rofi/blob/c25396d50b2a9d94bddd41e9611265542f3b7673/source/rofi.c#L1761)

**Comment by DaveDavenport** [comment]
Fixed.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Are there [a few update candidates](https://github.com/DaveDavenport/rofi/blob/20c9abf0a2ef3072453b92db71ad259fd008e27a/source/dialogs/dmenu.c#L186 "Update candidate: dmenu_output_formatted_line()") left over?

**Comment by DaveDavenport** [comment]
Patch welcome.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by DaveDavenport** [comment]
No interest in switching to (aspect)C++.
