### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [DaveDavenport/rofi#193]
[The function "XOpenDisplay"](http://www.x.org/releases/X11R7.7/doc/libX11/libX11/libX11.html#XOpenDisplay "Opening the display.") does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[hup_action_handler](https://github.com/DaveDavenport/rofi/blob/c25396d50b2a9d94bddd41e9611265542f3b7673/source/rofi.c#L1719 "Check signal handling implementation.")".

**Comment by DaveDavenport** [comment]
thx. (Is there a tool that can automatically check these things..) I played with clang/cppcheck and more before. but most where somewhat limited in results.

**Comment by DaveDavenport** [comment]
(note for me) solution could be:
Get a FD for the signal: http://man7.org/linux/man-pages/man2/signalfd.2.html
In the 'main loop'  do a select on the signal fd and X11 fd

**Comment by elfring** [comment]
>Is there a tool that can automatically check these things

I am also curious on corresponding improvements for software around static source code analysis.
Would you like to help to make [data-flow analysis](https://en.wikipedia.org/wiki/Data-flow_analysis "Description for data-flow analysis") easier to use?


>solution could be

Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by DaveDavenport** [comment]
any particular reason for nothing going with signalfd? (the self-pipe looks interesting too)

**Comment by elfring** [comment]
If you would reuse the function "sigwaitinfo", you do not need to be concerned about asynchronous-signal-safety so much when corresponding callback functions will not be executed within the context of a signal handler then.
How do you think about to look a bit more at [the technical differences](https://unix.stackexchange.com/questions/40082/difference-between-signalfd-and-sigwaitinfo "Difference between signalfd and sigwaitinfo?")?

**Comment by DaveDavenport** [comment]
sigwaitinfo would not work I think, because I also need to listen for X11 events.  so I guess it is either signalfd or the self-pipe trick.

**Comment by elfring** [comment]
Software design details for further considerations:
* Are you willing to dedicate another thread for receiving of notifications by the function "[sigwaitinfo](http://stackoverflow.com/questions/6223191/dealing-with-asynchronous-signals-in-multi-threaded-program "Dealing with asynchronous signals in multi-threaded program")" or "[select](http://evbergen.home.xs4all.nl/unix-signals.html "Avoiding races with Unix signals and select() ")"?
* When do you want to receive events for any file or only specific signals?
* The function "[signalfd](http://linux.die.net/man/2/signalfd "Create a file descriptor for accepting signals.")" is Linux-specific, isn't it?
* How likely is it that a file descriptor will fit into the portable value range for [safe data exchange with a signal handler](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.")?

**Comment by DaveDavenport** [comment]
I don't have time to go 20 questions everytime.
Either say what is wrong, or not. 

1. don't care.
2. for the current use-case (reloading config) the point in main-loop is fine.
3. yes, should check (was on my todo) if bsd has an alternative.
4. is not a problem here.

**Comment by elfring** [comment]
* I suggest to work more with multi-threading.
* How long may the processing of a corresponding task last until your users might interpret the program as [not so responsive](https://en.wikipedia.org/wiki/Responsiveness "Description for responsiveness") as they expect?
* Safe data exchange with a signal handler is a general software development challenge if you care for program correctness.

**Comment by DaveDavenport** [comment]
1. can you ellaborate? are you talking in general? in this specific problem? if so you are referring to the self-pipe trick? if so how is this so much different then signalfd?
2. we are talking about a reloading (part) of the configuration when it is running in daemon mode. This is a very quick thing todo. I  don't think responsiveness is an issue (there are other places in rofi where this is a problem and I plan to fix it at some point.)
3. yes, but again for this specific problem either the self-pipe trick or the signalfd it would be fine.

Can you try to be more verbose in your answering, this only leads to more questions.
I do want to get  **rofi** right, but have limited time.

(btw. Patches are welcome.)

**Comment by elfring** [comment]
1. I would recommend the reuse of the sigwaitinfo() function together with dedicated threads.
2. I find that file processing is a task which should be performed in a separate thread so that the main event loop in a GUI application does not get blocked. Can it happen that a reconfiguration will take longer than you expect usually?
3. I prefer wider software portability.

Did you also look at the linked information sources?

**Comment by DaveDavenport** [comment]
1. Why.. you do not explain yourself.  (portability is a valid reason as it turns out signalfd is not available on bsd).
2. I would not allow the re-loading of config to happen when gui is running and visa versa (this is currently a known bug). only when backgrounded.
3. agree.


<sarcasm>No, I blindly ignored that</sarcasm>

Anyway I am going to file this for after my holiday.

Patches are welcome.

**Comment by elfring** [comment]
1. The sigwaitinfo() function has got special properties which I like in principle. Do you become also more aware of its useful functionality?
2. I find that you do not need to exclude such things. How do you think about to let more tasks run in parallel?

Concrete patches would need further clarification of acceptable libraries for better software reuse, wouldn't it?

**Comment by DaveDavenport** [comment]
yeah, I am going to stop with this discussion for now. It feels like you are being deliberately vague. e.g. 'has got special properties which I like in principle'  why not say what these properties are. Instead of turning it again in a question 'Do you become also more aware of its useful functionality?'. 

Thanks for the feedback, it is appreciated!!! I  will get back to this, but currently do not have time to have this question ping-pong.

**Comment by elfring** [comment]
I hope that you will understand the desired function properties from the available interface descriptions.
I assume that a better common understanding can be achieved for the involved implementation details so that corresponding software design decisions might become also a bit safer here.

**Comment by DaveDavenport** [comment]
NOTE to myself:

As I could not leave it, playing around with it a bit (not finished or clean at all!):
http://random.sarine.nl/signal_process_thread.patch

Creates a 2nd thread to do the signal handling, uses a pipe the inform the main thread to reload configuration  or quit.
The reloading is explicitly done at this point, so that the gui cannot popup when the config is reloaded (and therefor might be in an invalid state causing havoc).  

Big problem with this is we are now mixing threads and forks. This is not good!!!!!!!!!!!
One solution could be to not fork for popping up the GUI.  Given that if it is it handles the keypresses anyway this might be a valid solution.

**Comment by landryb** [comment]
sigwaitinfo() isnt available on OpenBSD either, but i think you can just use sigwait(), no ? Or it's not the same behaviour...
```
-        siginfo_t info;
-        int       sig = sigwaitinfo ( &set, &info );
-        if ( sig < 0 ) {
-            perror ( "sigwaitinfo failed, lets restart" );
+        int       sig = 0;
+        if ( sigwait( &set, &sig ) < 0 ) {
+            perror ( "sigwait failed, lets restart" );
         }

```

**Comment by DaveDavenport** [comment]
This is now handled with glib.
