### ISSUE TITLE
Sort filter results by 'frecency'?

### ISSUE THREAD

**Issue by TimoFreiberg** [DaveDavenport/rofi#194]
One thing that bugs me about rofi is that as soon as you type in a search term, the sorting switches from history to pure text matching.
When I want to start a program that is, say, the fourth most recent in the history, I'd like to type the first two letters of its name and filter my history.
Instead, when I type `em` for `emacs`, I get `gem` and `chem` first, even though I never run them.
I'd prefer if rofi filtered my history instead.

**Comment by DaveDavenport** [comment]
See #161. Does this solve it?

**Comment by TimoFreiberg** [comment]
How embarrassing! It does, thanks.

**Comment by DaveDavenport** [comment]
no problem. glad that it is solved.
