### ISSUE TITLE
rofi appears to be incredibly slow on my new funtoo install

### ISSUE THREAD

**Issue by michaelmrose** [DaveDavenport/rofi#198]
The window pops up 5-6 seconds after rofi is triggered in one shot mode or even in daemon mode.
Suggestions as to how this can be debugged would be welcome.

**Comment by DaveDavenport** [comment]
In what mode are you starting rofi?   (run? window?)

The only reason I could think of is run mode, you have a lot of files in your path and the disk access is slow.

Can you try the following?
```
echo "test" |  ./rofi -dmenu 
```
and see if that is slow?

**Comment by michaelmrose** [comment]
It turns out that it was a font issue. With 2 specific fonts installed rofi behaves as described I will post the font files when I get home if you like

**Comment by DaveDavenport** [comment]
Can you give the fonts name? I am curious about this.
