### ISSUE TITLE
rofi fails with "core dumped"

### ISSUE THREAD

**Issue by vanzef** [DaveDavenport/rofi#199]
Hello, today I have installed rofi-git from AUR. It fails with "core dumped" message after some time from boot. Here is a [systemd log](http://pastebin.com/aCr6CUT7) and [message](http://pastebin.com/YvKiFwHD).

Thaks!

**Comment by DaveDavenport** [comment]
What git version and can you get a core dump with debug symbols?

**Comment by DaveDavenport** [comment]
Can you test if this fixes it?  thanks.

**Comment by vanzef** [comment]
Thanks!I've just installed *-git version. Will report if there any problems after some days.

**Comment by DaveDavenport** [comment]
thanks.

**Comment by vanzef** [comment]
It hasn't crased for 2 days. Thanks for fixing!

**Comment by DaveDavenport** [comment]
thanks for reporting. it was an old bug that got more visible by recent changes.
