### ISSUE TITLE
Support for fractional element height or even custom value in pixels

### ISSUE THREAD

**Issue by Tisalgelijk** [DaveDavenport/rofi#202]
Up to and including rofi 0.15.4 the element height was just perfect on my systems. This changed in 0.15.5, now the lines are either too narrow for my taste, or too big (with -eh 2, which also does not affect the input line).

Would it be possible to add an override to the font metrics to set some vertical padding for each line of text?

**Comment by DaveDavenport** [comment]
The 0.15.4 was just broken beyond believe (tm). 
I will see if I can expose the line-margin as a user-setting.

**Comment by DaveDavenport** [comment]
Ok. added the -line-margin option, allowing you to manually set the space between the rows.
