### ISSUE TITLE
toggling dashed line below the input

### ISSUE THREAD

**Issue by r8b7xy** [DaveDavenport/rofi#206]
Toggling the visibility/changing width of this dashed line with an argument similar to ```rofi.bw: 0/1``` could be very useful. Now its' color is linked to rofi border color and that's all.

**Comment by DaveDavenport** [comment]
Making it an option is no problem, however we are getting an awfull lot of configuration options.

**Comment by DaveDavenport** [comment]
you can set color now  and separator-style (dash/solid)

**Comment by r8b7xy** [comment]
thanks a lot!
