### ISSUE TITLE
Config/switch to keep items from list

### ISSUE THREAD

**Issue by sanderboom** [DaveDavenport/rofi#213]
Thanks for the great tool!

Using MATE desktop environment, rofi always displays the following entries: 

- Mate-panel Bottom Expanded Edge Panel
- Mate-panel Top Expanded Edge Panel

It would be great to be able to keep those from appearing in the list as these are non-functional. E.g. by using a wildcard/RegEx from the CLI.

**Comment by DaveDavenport** [comment]
Why don't those panel set the _NET_WM_STATE_SKIP_PAGER and _NET_WM_STATE_SKIP_TASKBAR hint?

**Comment by sanderboom** [comment]
I have no idea TBH...
Does this issue belong here? https://github.com/mate-desktop/mate-panel

**Comment by DaveDavenport** [comment]
might be good to verify this with something like `xprop`.  Could still be a bug in rofi.
But this is normally the way to skip pagers. .(I3bar also does not do this correctly)

**Comment by sanderboom** [comment]
Didn't know `xprop`... quite some output, but 0 occurrences of "SKIP".

Maybe interesting:
```
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW

_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY

_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK

WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST

WM_CLASS(STRING) = "mate-panel", "Mate-panel"
```

**Comment by DaveDavenport** [comment]
_NET_WM_WINDOW_TYPE_DOCK might filter on this.

**Comment by DaveDavenport** [comment]
Can you test above commit.

**Comment by sanderboom** [comment]
Awesome, seems to work! 
No more panel items in the window list. Thanks for the quick fix.

**Comment by sanderboom** [comment]
It seems that the latest version reintroduces this behavior.

```
Version:    1.0.0-devel
Git:        5d7bf1c
```

Again the following entries are showing up:
- Mate-panel Bottom Expanded Edge Panel
- Mate-panel Top Expanded Edge Panel

Using `xprop` both panels have set:
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK
````

Thanks for looking into this!

**Comment by sardemff7** [comment]
Could you git bisect to know the change that broke it?

**Comment by DaveDavenport** [comment]
I cannot test this, but I found a possible cause in the code and fixed it, can you test this?

**Comment by sanderboom** [comment]
Fixed! 
Using:
```
Version:    1.0.0-devel
Git:        cdd9f97
```

Awesome. Thanks for the quick replies guys.
