### ISSUE TITLE
Browser tabs

### ISSUE THREAD

**Issue by sanderboom** [DaveDavenport/rofi#214]
Question: would it be possible to include browser tabs in the windowlisting?

**Comment by roomcays** [comment]
Personally, I think this would be way too far away from "simple".

**Comment by DaveDavenport** [comment]
It is possible without modifying rofi.. make a script that lists browser tabs and use the combi modi to combine the tabscript mode  with the window mode

**Comment by sanderboom** [comment]
I think it would be great to have all browser tabs listed and being able to switch to, but I don't have enough knowledge I guess to piece something like this together.

How to activate a tab anyway? Would [xdotool](http://www.semicomplete.com/projects/xdotool/) an viable tool?

How to gather a list of active tabs? ([source](http://www.commandlinefu.com/commands/view/4440/display-the-list-of-all-opened-tabs-from-firefox-via-a-python-one-liner-and-a-shell-hack-to-deal-with-python-indentation)): 

```
python2 <<< $'import json\nf = open("sessionstore.js", "r")\njdata = json.loads(f.read())\nf.close()\nfor win in jdata.get("windows"):\n\tfor tab in win.get("tabs"):\n\t\ti = tab.get("index") - 1\n\t\tprint tab.get("entries")[i].get("url")'
```

Or query the browser db's (although this is history, rather than active now): 
FF:
```
sqlite3 ~/.mozilla/firefox/*.default/places.sqlite "select url from moz_places order by last_visit_date desc limit 10;"
```

Chrome:
```
sqlite3 ~/.config/google-chrome/Default/History "select url from urls order by last_visit_time desc limit 10;"
```

**Comment by carnager** [comment]
there is no easy way to archive this. Yes it's possible to get a list of the tabs and most likely even possible to find out which one is the current one. but there is no way to tell the browser to activate a specific tab. you could use xdotool to send ctrl+n, where n is the tab number. But this aproach is limited to the first 9 tabs

**Comment by sanderboom** [comment]
Hmm sounds like a tedious process with flaky outcome. Thanks anyway!

**Comment by mokanfar** [comment]
[https://github.com/mokev/rofi-switch-browser-tabs](this repo) activates chromium tabs through node module and remote debugging enabled. Working for me.
