### ISSUE TITLE
option to dump visible input to file on exit

### ISSUE THREAD

**Issue by carnager** [DaveDavenport/rofi#216]
#### Update

Recent commits added a -dump option. This however does not show a dmenu prompt and simply prints the list to stdout. If the command producing the list is relatively slow this can be problematic, since the user still has to run it twice to a) get the dmenu prompt and b) save the dump.

A better aproach would be, if the -dump option simply calls dmenu just normal and after on exit simply dump the (filtered) list either to stdout or to a file (-dump "/path/to/file"). 

#### draft
* option `-dump` calls dmenu just like normal. when hitting enter (or any of the `-kb-custom` keys) rofi dumps the (possibly filtered) list to stdout.
* if `-dump` if followed by an optional filename, dump the list to that instead.
* parallelize the operation.
* Make sure rofi still has the correct exit code (0 or custom exit codes 10-29)
* add another option (ejemba called it -user-input) to simply dump the list, without showing a window, useful for debugging.

--------------

#### Original bug report
to re-use filtered list rofi offers the `-filtered` argument, which is nice.

But on very large lists this can be quite slow, esp in combination with pre-defined selection and can take several seconds before it actually shows the window.

An alternative aproach could to have an option to dump the visible list to a file, which could be used on next call.

so something like `rofi -dmenu -dump' would dump to the file, which is set in `rofi.dumpfile`

**Comment by ejemba** [comment]
:+1:

**Comment by ejemba** [comment]
Let me propose something: 
  `mylist.sh | rofi -dmenu -dump -user-input "zob" > mylist-filtered-by-zob.txt`

This would help bulk data treatment based on previous user input "zob".
Note that this won't open any window.

What do you think?

**Comment by DaveDavenport** [comment]
Having an option to do the filtering + sorting and dump that out might be a useful debug option.
I will put it on the todo.

**Comment by ejemba** [comment]
In fact, useful not only for debugging,  this is the only way to have batch operations on filtered list. 
This should support list of index as well, according to the right option

**Comment by DaveDavenport** [comment]
yep. it is. debugging is anice added bonus :smile:

**Comment by ejemba** [comment]
Hi @DaveDavenport is there a chance this can be included in the next release ? 
It will be very usefull for my workflow 
thank you

**Comment by DaveDavenport** [comment]
It is currently not planned.
Can you write a small `specification` of what functionality is needed, how the option should look, etc.
@carnager ^^ you have a wishlist?

**Comment by DaveDavenport** [comment]
Assigned it to next release.

**Comment by ejemba** [comment]
@DaveDavenport I'll write this today. I keep you informed.

**Comment by ejemba** [comment]
Given a list 

```
aa 11
bb 22
cc 11
dd 22
ee 11
ff 22
```

And a user input : 11

i) When issuing :

`echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | rofi -dmenu -dump -user-input 11`

the output is 
```
aa 11
cc 11
ee 11
```
ii) Should work with -format as well so

`echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | rofi -dmenu -dump -user-input 11 -format i`

should return
```
0
2
4
```

**Comment by carnager** [comment]
Hmm, I am not sure user input should be part of every line. Make it a special line (first with some special marker) 

On November 25, 2015 10:21:02 PM GMT+01:00, Epo Jemba <notifications@github.com> wrote:
>Given a list 
>
>```
>aa 11
>bb 22
>cc 11
>dd 22
>ee 11
>ff 22
>```
>
>And a user input : 11
>
>i) When issuing :
>
>`echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | rofi -dmenu -dump
>-user-input 11`
>
>the output is 
>```
>aa 11
>cc 11
>ee 11
>```
>ii) Should work with -format as well so
>
>`echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | rofi -dmenu -dump
>-user-input 11 -format i`
>
>should return
>```
>0
>2
>4
>```
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DaveDavenport/rofi/issues/216#issuecomment-159733981

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ejemba** [comment]
@carnager the fact that the user input is on every returned line was just for the example. '11' was on 3 lines. 
The goal here is to dump the filtered list to the output in function of 1) an input list and 2) a given user input . Or I did not understand what you meant.

**Comment by DaveDavenport** [comment]
Added to git, please test.. 
`-dump`

**Comment by ejemba** [comment]
I have the following error
```
 $  autoconf -i 
configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:17: error: possibly undefined macro: AM_PROG_CC_C_O
```

**Comment by DaveDavenport** [comment]
This is unrelated to this bug, for me this: `autoreconf -i` works

**Comment by ejemba** [comment]
```
 $ echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | ./rofi -dmenu -dump -user-input bb  
aa 11
bb 22
cc 11
dd 22
ee 11
ff 22
```
It looks like the output is not filtered by the user-input flag `bb` here

**Comment by DaveDavenport** [comment]
no it uses the existing `-filter` no point in duplicating

**Comment by ejemba** [comment]
```
$ echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | ./rofi -dmenu -dump -filter 11
aa 11
cc 11
ee 11
 ✘ $ echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | ./rofi -dmenu -dump -filter 11 -format i
0
2
4
 ✘ $ echo -e "aa 11\nbb 22\ncc 11\ndd 22\nee 11\nff 22" | ./rofi -dmenu -dump -filter 11 -format d
1
3
5
 ✘ /tmp/rofi/build $ echo $?
232
```
Looks good to me 
except the status code is not 0 but 232 should we matter ?

**Comment by DaveDavenport** [comment]
yeah that did go wrong, the internal return values are not very clear and mixed it up. 
I should clean that code up.

**Comment by carnager** [comment]
My original idea was, that when you call commands that are relatively slow, you can save the filtered lists to be able to re-use them. This way the command wont have to be run twice. 
This solution does however not show a regular dmenu prompt, so you still have to run it twice. one time to generate the dump and one time to give the user a prompt.

A better aproach would be, if the `-dump` option simply calls dmenu just normal and after on exit simply dump the (filtered) list either to stdout or to a file (`-dump "/path/to/file"`).

**Comment by DaveDavenport** [comment]
Fixed return value.
The output to file takes more effort, next release.

**Comment by ejemba** [comment]
looks good !
I added another test case I use a lot and it passes well  
```
echo -e "aa\n11|bb\n22|cc\n11|dd\n22|ee\n11|ff\n22" | ./rofi -dmenu  -eh 2 -sep '|' -dump -filter 11
aa
11
cc
11
ee
11
```
The status code looks ok.
So LGTM :+1:
