### ISSUE TITLE
Allow more than 9 "-kb-custom"

### ISSUE THREAD

**Issue by carnager** [DaveDavenport/rofi#218]
Could the limit be increased a bit? Is there a reason, why there is a limit at all?

**Comment by DaveDavenport** [comment]
I am not sure if this is a good thing, to me it sounds like a gateway to abuse. Do you really need more then 9 'extra' keybindings?

**Comment by carnager** [comment]
yes, i actually had a situation where i could need more. Would this really be an issue?
