### ISSUE TITLE
try to make selection centered

### ISSUE THREAD

**Issue by carnager** [DaveDavenport/rofi#219]
maybe an option to keep the selected line centered, if possible would be nice, so one can always see what comes after the current selection when scrolling down.

**Comment by DaveDavenport** [comment]
Can you test? `-scroll-method 1`

**Comment by bendem** [comment]
Works perfectly, only nit, when the number of lines displayed is odd, the index kept in the middle is the lower one, since my rofi is displayed on the top, I'd have expected it to use the upper middle
```
1
2                             <= would have expected this one to be
3 <= this line is the center
4
```
Maybe it can be configurable?

**Comment by DaveDavenport** [comment]
can you try? should round down.

**Comment by bendem** [comment]
Yep, works as advertised.

**Comment by DaveDavenport** [comment]
@carnager  reopen if not working right.(tm)
