### ISSUE TITLE
Command line option to force screen/workspace

### ISSUE THREAD

**Issue by fmos** [DaveDavenport/rofi#220]
For some cases (#84) and option to override the monitor determined by the `monitor_active` function would be useful, e.g. when rofi should be opened on a monitor having neither an active window nor the mouse.

**Comment by DaveDavenport** [comment]
There is an option `-m` in git version that allows you to set monitor.
The workspace is not a useful option as rofi shows on all and grabs keyboard.

**Comment by DaveDavenport** [comment]
```
       -m num -monitor num

           Select (Xinerama) monitor to display **rofi** on. The special number -1 denotes the currently focused monitor, the number -2 denotes the currently focused window (i.e. rofi will be displayed on top of the focused window).

           Default: *-1*
```

**Comment by fmos** [comment]
Cool, then I'll wait until that is released. Sorry for the duplication.
