### ISSUE TITLE
[Redundant] Fix -color-normal

### ISSUE THREAD

**Issue by kinclma1** [DaveDavenport/rofi#223]
Hello,

since the manual suggests that the `-bg`, `-fg`, etc. are deprecated, I tried the `-color-enabled -color-normal`.

`rofi -show run -color-enabled -color-normal "#0C0C0C,#FFFF00,#0C0C0C,#FFFF00,#0C0C0C"` gives me some white areas.

![2015-09-05-021137_1366x768_scrot](https://cloud.githubusercontent.com/assets/2377824/9696620/b436cdc6-5373-11e5-8bff-d12e774dc06e.png)

The normal color settings work fine.

Edit:
Sorry for this redundant issue, I just didn't understand the manual.

**Comment by DaveDavenport** [comment]
you also need to set the window color:
```
-color-window "#0C0C0C,#FFFF00
```

All these options are on 'user-request'. not happy with the complexity.

**Comment by DaveDavenport** [comment]
This is my current config:
```
! enable new color system
rofi.color-enabled:                  true
! normal row
rofi.color-normal:                   argb:dd170F0D,#e4dc8c,argb:dd392925, argb:dd544b2e,#e4dc8c
! urgent row
rofi.color-urgent:                   argb:dd170F0D,#af652f, argb:dd392925, #af652f, #e4dc8c
! active row
rofi.color-active:                   argb:dd170F0D,#70a16c, argb:dd392925, #70a16c, argb:dd170F0D
! window color (bg, border)
rofi.color-window:                   argb:dd170F0D,#746C48
```

**Comment by kinclma1** [comment]
Thanks for reply, I figured it out afterwards, but couldn't remove the issue. That's why I marked it redundant.

Would it be a bad idea to set the default window colors as they are when using the separate `-fg -bg -hlfg ...` arguments? Just for simplicity?

Are the `-fg -bg -hlfg` args really deprecated?
