### ISSUE TITLE
[question] run window mode for windows only on current desktop

### ISSUE THREAD

**Issue by vyp** [DaveDavenport/rofi#224]
I know it has the desktop numbers on the left, but is there a way to start it *only* for windows on the current desktop anyway? (assuming ewmh compliant wm that is)

**Comment by DaveDavenport** [comment]
No, that got removed at some point in time. But I will re-add it.

**Comment by vyp** [comment]
Was it buggy or just that no one used it? If you're wondering, my use case is the monocle window layout for bspwm, if you're familiar with bspwm.

It's actually a really big use case for me because I often have to work with multiple (a lot of) pdfs open at the same time. But my preferred pdf reader is zathura, which has little to no support for working with multiple pdfs simultaneously.

With this I can group a lot of instances of zathura that are opened with pdfs related to one another, on relevant desktops, and use rofi to quickly switch between them. But this is basically my only use case for it I think. Still worth it very much imo.

You can close this if you want, or perhaps you want to keep this open until this is re-added? I'll leave it to you. Any approximate timeline?

**Comment by DaveDavenport** [comment]
No, I will re-add it soon. Probably this week.

**Comment by vyp** [comment]
:sparkles: Thanks.

**Comment by DaveDavenport** [comment]
Can you test above commit?  I don't have a decent way to test.

**Comment by vyp** [comment]
Just did a rudimentary test on latest master (ae26c13), both `rofi -show windowcd -modi windowcd` and `rofi -show windowcd -modi windowcd,window` work as expected. i.e. ctrl-tab allows to switch between the modes for the latter command. Thanks!

**Comment by DaveDavenport** [comment]
If you know a better 'name'  then windowcd let me know (should be 1 word.)

**Comment by vyp** [comment]
At first I thought just "desktop", but that might be misleading because people will think it's for switching desktops. What about just "cwd", for 'current working desktop', or 'current windows on desktop'? Not that great at names..
