### ISSUE TITLE
Switch to stop cycling

### ISSUE THREAD

**Issue by sanderboom** [DaveDavenport/rofi#225]
I'd like to stop moving to the first item when I reach the end of the window-list and press `down`. Would you be interested in implementing a switch for this?

**Comment by valsoray17** [comment]
@sardemff7 any suggestions on the switch (what kind of config option should it be)? I will try to implement it

**Comment by sanderboom** [comment]
Thanks for your effort!

Setting an option should switch from the default behavior. The default is to have 'cycling' enabled. The right name for the switch might than be something like `-no-cycle`. 

P.S. I'd go for double-dash for the longer switches, but this is not used in Rofi as it seems, so better to keep consistency.

**Comment by valsoray17** [comment]
Should this issue be closed?

Thanks.

**Comment by sanderboom** [comment]
Works like a charm. Thanks!
