### ISSUE TITLE
Case Sensitive

### ISSUE THREAD

**Issue by ralpheeee88** [DaveDavenport/rofi#227]
Having an issue with rofi and case sensitivity:

when searching mousepad, gparted, zatthura for example nothing is found

however if i search Mousepad, GParted, Zatthura the programs are found

have checked my Xresources and made sure I had rofi.case-sensitive:                 false

my system: linux arch with i3wm

thxs (love rofi!)

**Comment by DaveDavenport** [comment]
can you paste the output of  `rofi -dump-xresources`?

**Comment by ralpheeee88** [comment]
thxs chief!

http://codepad.org/PhHFB0qG

**Comment by DaveDavenport** [comment]
p.s. are you using the build in Run of rofi or `dmenu_run`?  (given that gparted normally is spelled with small caps).

**Comment by ralpheeee88** [comment]
dmenu...very new to rofi so still trying to figure out how to implement...but for the moment using dmenu

**Comment by DaveDavenport** [comment]
dmenu case insensitive flag is `-i`, so rofi emulates this.

**Comment by ralpheeee88** [comment]
ok you lost me...lol...when using dmenu it finds the program regardless of caps or not...

anyway...if i figure how to change to "run" will that solve my issue....(should have given you heads up that i am complete noob)

**Comment by DaveDavenport** [comment]
`rofi -show run -modi run`  To get rofi's build in launcher.

**Comment by ralpheeee88** [comment]
CHAMPION!!! all working now....
