### ISSUE TITLE
Prefer items that start with the given string in -show run

### ISSUE THREAD

**Issue by kinclma1** [DaveDavenport/rofi#228]
Hello, I don't know whether it would be useful in other modes than `run`:

Would it be possible to sort the query results for a given string as follows?

1. Frequent entries that start with the string
2. Other entries that start with the string
3. Frequent entries that contain the string
4. Other entries that contain the string

In addition, I like the dmenu feature that you can enter starts of words of an entry separated by space when the entry consists of multiple words separated by `-` or `_` but not a letter or number.

Thank you.

**Comment by sasoiliev** [comment]
+1

When I want to run a program via a dmenu-like launcher, I know what the program's called. I want to type the first few letters and press enter to start it.

Please at least consider providing an option for such a mode.

**Comment by carnager** [comment]
... thats like the fifth issue for this in a few days. and the answer is always the same: `-no-levenshtein-sort`

**Comment by kinclma1** [comment]
`-no-levenshtein-sort` is default since two weeks ago. That commit made the situation better, but not really what I suggested.

**Comment by DaveDavenport** [comment]
http://random.sarine.nl/rofi-no-tokenize.patch will match from start on and accepts '*' and '?'
usage:
```rofi -glob -no-tokenize```

I don't feel like adding multi-layered sorting algorithms yet. (though I probly be worn down on this by all the users).

**Comment by kinclma1** [comment]
Thanks a lot Dave, that's the thing I was looking for, amazing. Is it possible to add this patch by default, as it is not that big?

**Comment by sasoiliev** [comment]
Looking at the last few commits, the `glob` and `tokenize` options are now in and `levenshtein-sort` seems out.

@DaveDavenport, will it stay this way?

**Comment by DaveDavenport** [comment]
No idea.

**Comment by kinclma1** [comment]
Sorry to bother again, but I've just noticed it's broken again. Unfortunately, I have no idea since when.

**Comment by DaveDavenport** [comment]
It caused confusion and inconsistency. This problem needs to be solved differently (giving scores to matching), but this needs to be done on a per-switcher basis, as it differs for run,drun or window.

I have some ideas here, but will be in next release.

**Comment by kinclma1** [comment]
Thanks for the reply.

From what I could imagine, for the `run` mode, the exact sequence matching was perfect. As of other modes, I don't know. Looking forward to the forthcoming development.

**Comment by vdrandom** [comment]
So, how is the progress? Is there still no way to match from the beginning of the command?

**Comment by DaveDavenport** [comment]
So, how it the progress on the patch?  Is there still no patch to match from the beginning of the command?

(Until then you can use the regex matcher with '^')
