### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by biscuitpants** [DaveDavenport/rofi#229]
Is it possible to build and use Rofi on OSX?

**Comment by jpleau** [comment]
Have you tried it?

**Comment by carnager** [comment]
It should work, except for the window runner, which must likely only works on X windows

**Comment by DaveDavenport** [comment]
I theory it should work (although most views will be useless), given you have an X11 server running.
But:
 * Window view not working.
 * Hotkeys not working
 * Rofi will get confuse as it might not be able to 'grab' the keyboard.

**Comment by biscuitpants** [comment]
@DaveDavenport I have been trying to make the switch to Arch but its been taking a while to get a perfect install of Arch up and running. I wanted to see if I could some of the productivity things I love from Arch to OSX (like i3, Rofi etc).

**Comment by DaveDavenport** [comment]
I have added a flag --disable-window-mode (see configure --help for the exact name).
This might help.

**Comment by DaveDavenport** [comment]
I do not think this is something I want to actively pursue.
Patches are welcome, but I have no OsX or any interrest in it.

**Comment by avindra** [comment]
Can we discuss alternatives in this thread? Is there something that can be used in place of `rofi` on Mac?

**Comment by DaveDavenport** [comment]
no.
