### ISSUE TITLE
Wait for the results before validating

### ISSUE THREAD

**Issue by Anthony25** [DaveDavenport/rofi#232]
Hello,
I use Rofi as my main launcher, but there is a behavior that (imo) is quite annoying when you know exactly the software you want to launch: for example, I'm used to type "ario" to launch the software Ario, and then quickly type "Enter" (because I'm sure about the result). But, as Rofi didn't have the time to get all the results, it's validating the 1st item in history, like if I just did an empty search and directly pressed Enter.

Would it be possible to wait that the results are computed before starting the command ?
Thanks !

PS: I'm sorry if my issue isn't clear, do no hesitate to ask me some details/explanations

**Comment by DaveDavenport** [comment]
See #187 and #127

**Comment by Anthony25** [comment]
Oh sorry, I searched related issues without finding them.

Thanks for your answer, I'm closing this one

**Comment by DaveDavenport** [comment]
no problem.I raised the default limit a bit.

**Comment by Anthony25** [comment]
Yep, that does the trick, thanks !
