### ISSUE TITLE
Error with switch to cairo

### ISSUE THREAD

**Issue by Narrat** [DaveDavenport/rofi#234]
With latest build from master (eba2170) rofi doesn't display any text. Although it still works (blindly typing a binary and pressing enter will start typed program)

Ending rofi via ESC produces additionally the following errors:
>$ rofi -show run   
error: request code=55, error code=9
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  55 (X_CreateGC)
  Resource id in failed request:  0x2800002
  Serial number of failed request:  91
  Current serial number in output stream:  93
error: request code=62, error code=9
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  62 (X_CopyArea)
  Resource id in failed request:  0x2800002
  Serial number of failed request:  92
  Current serial number in output stream:  95

**Comment by BOHverkill** [comment]
+1 same problem

**Comment by DaveDavenport** [comment]
Can you test if last commit fixes it?

**Comment by BOHverkill** [comment]
no the problem still exists :disappointed:

**Comment by DaveDavenport** [comment]
Can you give some information about your system? distro? X version? driver?

**Comment by DaveDavenport** [comment]
Seems cairo only does truecolor visuals.  That is annoying.

**Comment by DaveDavenport** [comment]
eeuh lets test the fix first.

**Comment by BOHverkill** [comment]
fixed for me :+1: :smile:

**Comment by Narrat** [comment]
Ditto.
So I'm closing it :)

**Comment by DaveDavenport** [comment]
thanks for reporting and testing!

**Comment by Tblue** [comment]
@DaveDavenport: Sadly, commit 838c838 did not fix this for me. rofi now looks like this on my system:

![rofi](https://cloud.githubusercontent.com/assets/842305/10144660/0561fa0a-661f-11e5-9283-d69e64482750.png)

Both the aforementioned commit 838c838 and the currently most recent commit ca8ff80a5c41b552694cf20deef85c29d29a4acf give the same, broken window.

rofi is still working, though. I can type something and press enter, which launches the selected application.

I'm running Arch Linux. X.Org 1.15.2, official Intel driver 2.99.917+381+g5772556, Cairo 1.14.2.

However, I just noticed that I'm using a patched version of Cairo. I will try using a regular Cairo build, maybe that will help. Will report back.

**Comment by Tblue** [comment]
Okay, using an official Cairo build did not help. I'm still seeing black bars.

However, it looks like it's not a library issue after all -- my rofi settings (i. e. X resources) seem to be at fault. Investigating.

**Comment by DaveDavenport** [comment]
@Tblue can you pastebin your config?  there is some breakage in parsing 'string' colors.

**Comment by Tblue** [comment]
@DaveDavenport Yep, I just figured that out, too. :-) My config used X11 color names -- I changed them to RGB hex values and now everything works again.

The fact that X11 color names are not supported anymore should be added to the Changelog, IMO.

**Comment by DaveDavenport** [comment]
@Tblue will see if I can re-add it again.

**Comment by DaveDavenport** [comment]
@Tblue  it is re-added. can you test?

**Comment by Tblue** [comment]
@DaveDavenport Seems to work. Thanks!
