### ISSUE TITLE
Is it possible to make rofi like a panel or pull up when you mouse over to the bottom?

### ISSUE THREAD

**Issue by varmanishant** [DaveDavenport/rofi#239]
1) Is it possible to make rofi like a panel or pull up when you mouse over to the bottom? So that it can work a bit like traditional panel as well.

2) Can we open a window with single click instaed of double click?

**Comment by DaveDavenport** [comment]
1.) This should be the task of the DE or another tool (hot corner tool should be able to call rofi when mouse goes  to bottom of screen. You don't want to leave rofi open as it does not 'react' to changes in the window list (this is why it grabs focus, all desktops and on top).

2.) hmmm I could make middle mouse button act as double  click?

**Comment by varmanishant** [comment]
Thanks. I tried `xdotool behave_screen_edge top exec rofi -fuzzy -show "window"` in my wm and that works. I just need to switch window instantly so I don't need it open ... I am not sure about making middle mouse act like double click but if single work doesn't have any other action then it would be good to make it behave like Enter.

**Comment by DaveDavenport** [comment]
single click is select.  This is consistent with most ui's out there, that is why I am hesitant.

**Comment by varmanishant** [comment]
Thats right, its better to be consitent. Btw the above xdotool approach leaves a lot of zombie? rofi process after you select a window. So might need to see a better way to trigger stuff at corner.

**Comment by DaveDavenport** [comment]
try passing --sync to xdotool. 

```exec --sync```

**Comment by varmanishant** [comment]
Ah yes that works fine! Nice

**Comment by calmarc** [comment]
In most menu's you right actually single-left-click not? (/me hates doubleclick as hell - a waste of energy for nothing - that's why it's the default on MS I guess.)

**Comment by DaveDavenport** [comment]
I never really imaged people using rofi 'mouse-driven'.

I don't consider rofi a context menu. So I tried to model the behaviour to most toolkits 'list views'

**Comment by calmarc** [comment]
ah ok. I use the 'run' thing all keyboard driven.. but I also want to clickable menus (initiated by some mouse-clickable icon in the bar) - when I happen to hold the mouse right there - so maybe I misused rofi :P 
But I'm happy with a slow double-click now anyway - not perfect so from a mouse-driven point of view :)

**Comment by DaveDavenport** [comment]
interresting.

**Comment by calmarc** [comment]
when you are interested in it: http://www.calmar.ws/tmp/output.mkv
and that https://github.com/calmarc/app_menu 
(I was used to  in 'awesome-wm'.. want it kinda-like in i3 too :)
