### ISSUE TITLE
Multi-line output

### ISSUE THREAD

**Issue by Pitometsu** [DaveDavenport/rofi#243]
Is there hard to add support for multiline output (make option to prvent folding lines and let search from all the content)? It will be really nice to use `rofi` instead of `dmenu` for clipboard management.

**Comment by DaveDavenport** [comment]
The search should go over the whole input . Currently the max element length is 1024 bytes.
It can even handle multi-line rows (set a custom separator)  but they need to be fixed height.
Can you explain me what the exact problem is?

**Comment by DaveDavenport** [comment]
For example:
````
echo -en "aap\nnoot|mies\ndoos"| rofi -dmenu -eh 2 -sep '|'
````

**Comment by Pitometsu** [comment]
Your example work well. Don't know, why, but [clipmenu](https://github.com/cdown/clipmenu)
show strange `(number_of lines)` labels at the end of each multi-line string, but with `dmenu` it work just fine.
![Screenshot](http://i.imgur.com/bFZCWBS.png)

**Comment by DaveDavenport** [comment]
the clipmenu script actively does this:
```
    first_line=$(sed -n '/./{p;q}' "$file" | cut -c1-"$line_length_limit")
    lines=$(wc -l < "$file")

    if (( lines > 1 )); then
        first_line+=" ($lines lines)"
    fi
```

**Comment by Pitometsu** [comment]
Oh, sorry, my mistake, so issue may be closed.

**Comment by DaveDavenport** [comment]
clipmenu could be improved I guess with 'rofi' specific features.

**Comment by Pitometsu** [comment]
But `rofi` support only constant cells height, right? It's not really convenient for different snippets. Or have you other features in mind?

**Comment by Xunius** [comment]
Hi all,
Could you give me a hint on the `-eh` flag you used in this example `echo -en "aap\nnoot|mies\ndoos"| rofi -dmenu -eh 2 -sep '|'`? I didn't find it in the man page.
I'm on rofi 1.5.1, which now supports multi-line rows with different cell heights, doesn't it?
