### ISSUE TITLE
Terminal not exiting

### ISSUE THREAD

**Issue by JonnyMako** [DaveDavenport/rofi#244]
When I open a terminator window from rofi, and type in exit in the window to close the window, it just echoes back exit and does not close the window. It also happens with other terminal emulators like terminology.

**Comment by DaveDavenport** [comment]
Can you tell me what version of rofi you are using? and how you are running rofi (one shot or daemon mode).

Thx.

**Comment by DaveDavenport** [comment]
I can reproduce this in git in daemon mode.

**Comment by DaveDavenport** [comment]
Can you test?

**Comment by JonnyMako** [comment]
works in daemon mode. thanks!
