### ISSUE TITLE
Extend -separator to use multiple-character delimiter

### ISSUE THREAD

**Issue by stereolink** [DaveDavenport/rofi#245]
For example, I'm storing a bookmarks file as:
```
<url>
<title>
<tags>

<url>
<title>
<tags>

...
```

In this case, I would like to be able to use `-sep "\n\n"`.

**Comment by t-wissmann** [comment]
As a workaround, you can use the null-byte as the item separator. The sed command
```
 sed -e ':a ; N ; $!{b a}' -e 's,\n\n[\n]*,\x0,g'
```
Replaces any sequence of two or more consecutive newlines by a null-byte. That is, the command
```
sed -e ':a ; N ; $!{b a}' -e 's,\n\n[\n]*,\x0,g' |rofi -dmenu -sep '\0'
```
is equivalent to `rofi -sep '\n\n'` (or even better because it also works for two empty lines as a paragraph spacer).

**Comment by DaveDavenport** [comment]
That is indeed a nice solution.

**Comment by stereolink** [comment]
Thank you @t-wissmann - this works perfectly.
