### ISSUE TITLE
How to show workspace numbers when using "-show window" + i3

### ISSUE THREAD

**Issue by mrgreen7** [DaveDavenport/rofi#248]
Hi,

in the documentation it says:

"The window switcher shows the following informations in columns:
Desktop number (optional, not shown in I3 mode)
..."

I'm using i3. Can I still enable the desktop numbering somehow? (Did not find an option myself)

**Comment by DaveDavenport** [comment]
There is no real desktop number in i3.  Desktop have a name (that can contain a number) but this information is not available to rofi.
