### ISSUE TITLE
rofi and Fedora

### ISSUE THREAD

**Issue by region51** [DaveDavenport/rofi#249]
*Hi, for Fedora users you could install rofi from [russianfedora repository](http://ru.fedoracommunity.org/repository)*
*and also*
*Copr (Cool Other Package Repo) https://copr.fedoraproject.org/coprs/region51/rofi/*

**Comment by DaveDavenport** [comment]
added to install.md

**Comment by region51** [comment]
@DaveDavenport 
INSTALL.md https://copr.fedoraproject.org/coprs/region51/rofi/* 
Error 404: Not Found ******

**Comment by DaveDavenport** [comment]
aah yeah, somebody though it a good idea to make whole post italic :D will fix.
