### ISSUE TITLE
rofi -e broken

### ISSUE THREAD

**Issue by koppa** [DaveDavenport/rofi#250]
"rofi -e message" only shows a black bar.
I'm not sure what the errror is, error_dialog (  ) is called with the correct parameters.

Here a screen shot:

![](http://i.imgur.com/ktF3EdM.png)

Versions tested: master and 0.15.10

**Comment by DaveDavenport** [comment]
auch. will take a look at it.
I don't use it myself (though the error_dialog on wrong config I did test before release)
I should see if I can automate testing this.

**Comment by DaveDavenport** [comment]
Possible fix in git, please test.

**Comment by koppa** [comment]
Thanks for the fast fix.
Now the dialog works as expected.
