### ISSUE TITLE
Segfaul when pressing "Shift Right"

### ISSUE THREAD

**Issue by esn89** [DaveDavenport/rofi#251]
To switch modes to window I press Shift Right, and from there rofi experiences a seg fault, am I alone in this?  Is there a fix available?

**Comment by DaveDavenport** [comment]
Please provide some more information (https://davedavenport.github.io/rofi//p09-Contact.html)

**Comment by esn89** [comment]
Sorry about the half-assed bug report.  I did it before bed-time, haha.

Rofi Version:  0.15.10-devel
Rofi Dump:  http://ix.io/lFR/#n-LINENO
Steps to reproduce: 1) Start rofi:  "rofi -key-run alt+r"   2) Press "alt+r"  3) When you see the dialogue, hit "shift + right arrow" 4) Receive the segfault.

The behavior I see is that, it crashes and the daemon dies in the background.
I expect to be in the workspaces mode.

I hope this is a more acceptable report.

**Comment by DaveDavenport** [comment]
this is fine, I wanted to take a look at the dump mostly and version :+1:

**Comment by DaveDavenport** [comment]
Hmmm I cannot seem to reproduce it.

Can you try to make a backtrace:
on a terminal:

enable backtrace
```bash
ulimit -c unlimited
```

```bash
rofi -key-run alt+r
````

make it crash, this should generate a core file:
get backtrace:
```bash
echo "thread apply all bt" | gdb rofi core
```

And paste the output of the last command here.

**Comment by keidax** [comment]
Affected by this issue as well. I'm having trouble generating the core dump, but the backtrace I get is

    Program received signal SIGSEGV, Segmentation fault.
    menu (sw=sw@entry=0x61a960 <ssh_mode>, input=input@entry=0x7fffffffdc20, prompt=prompt@entry=0x6463e0 "ssh:", selected_line=selected_line@entry=0x7fffffffdbe4, 
    next_pos=next_pos@entry=0x0, message=message@entry=0x0) at source/rofi.c:1037
    1037	    for ( unsigned int line = 0; state.lines[line]; line++ ) {

I'm pretty sure this is related to the ssh mode, because I get a segfault with `rofi -show ssh` as well.
I don't have a `~/.ssh` folder, so that might be a cause.

**Comment by esn89** [comment]
@DaveDavenport 

here is the backtrace: http://ix.io/lHL/#n-LINENO

**Comment by DaveDavenport** [comment]
Yep, the ascii speedup patch broke this. Fix in 1min.
