### ISSUE TITLE
DPI not handled for font setting

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#254]
For some reason the DPI on a new machine does not get picked up properly currently anymore, but if I remember correctly it worked in the beginning.

```
$ xdpyinfo | grep resolution
  resolution:    176x177 dots per inch
$ xrdb -q|grep -P '(rofi|dpi)'
Xft*dpi:	176
rofi.bg-active:	#002b36
rofi.bg-urgent:	#002b36
rofi.key-run:	mod1-F2
rofi.key-window:	mod1-F1
```

I am using `xrandr -dpi 176` to configure this, and also have a xsettingsd instance, which serves `Xft/DPI 180224` (176*1024).

Any idea what I am missing?

Ref: https://github.com/DaveDavenport/rofi/issues/171#issuecomment-105314810

**Comment by DaveDavenport** [comment]
You are not missing anything.  Broke with the move to pangocairo.
I am unsure how pango cairo determines dpi?

I added an override option to git, can you test?

```
rofi -dpi 177
```

or:
```
rofi.dpi: 177 
```

in Xresources

**Comment by DaveDavenport** [comment]
Please check if current git fixes it.

**Comment by blueyed** [comment]
`rofi -dpi` works, thanks!

For reference: https://github.com/DaveDavenport/rofi/commit/cb9dd606aa80387ccaf434f7bf575bf7018ef058

Could this default to `Xft.dpi`?

**Comment by DaveDavenport** [comment]
no. that would be incorrect.
It will obey a generic dpi setting (that also xft should then pick up):

```
*.dpi: 189
```
