### ISSUE TITLE
-show window produces segmentation fault on dwm

### ISSUE THREAD

**Issue by ubavic** [DaveDavenport/rofi#256]
Runing rofi -show window in shell produces  segmentation fault (core dumped)  rofi -show window .
Has anybody run into same problem? I use dwm on Arch. 
Maybe it is  dwm issue.

**Comment by DaveDavenport** [comment]
Can you get more information?  version? dump of configuration? (rofi -dump-xresources)
and if possible backtrace:


Can you try to make a backtrace:
on a terminal:

enable backtrace
```bash
ulimit -c unlimited
```

```bash
rofi -key-run alt+r
````

make it crash, this should generate a core file:
get backtrace:
```bash
echo "thread apply all bt" | gdb rofi core
```

And paste the output of the last command here.

**Comment by ubavic** [comment]
It is rofi 0.15.10 installed with pacman, and run from urxvt (zsh shell), on arch linux machine with dwm 

*Core dump:*
Type "apropos word" to search for commands related to "word"...
Reading symbols from rofi...(no debugging symbols found)...done.
[New LWP 1603]
[New LWP 1604]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `rofi -key-run alt+r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004076b0 in ?? ()
[Current thread is 1 (Thread 0x7f60ef6db8c0 (LWP 1603))]
(gdb) 
Thread 2 (Thread 0x7f60e7513700 (LWP 1604)):
#0  0x00007f60edd3c576 in sigwaitinfo () from /usr/lib/libc.so.6
#1  0x0000000000407360 in ?? ()
#2  0x00007f60ee44c715 in ?? () from /usr/lib/libglib-2.0.so.0
#3  0x00007f60ec0344a4 in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f60eddf113d in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f60ef6db8c0 (LWP 1603)):
#0  0x00000000004076b0 in ?? ()
#1  0x00000000004097de in ?? ()
#2  0x00000000004098eb in ?? ()
#3  0x00000000004057f4 in ?? ()
#4  0x00007f60edd28610 in __libc_start_main () from /usr/lib/libc.so.6
#5  0x0000000000406039 in ?? ()
(gdb) quit

*Xresources dump:*
rofi.modi:                           window,run
rofi.opacity:                        100
rofi.width:                          50
rofi.lines:                          15
rofi.columns:                        1
rofi.font:                           mono 12
rofi.fg:                             #FFFFFF
rofi.bg:                             #333333
rofi.fg-active:                      #1E90FF
rofi.fg-urgent:                      #FF6A6A
rofi.hlfg-active:                    #333333
rofi.hlfg-urgent:                    #333333
rofi.bg-active:                      #333333
rofi.bg-urgent:                      #333333
rofi.hlbg-active:                    #4682B4
rofi.hlbg-urgent:                    #CD5C5C
rofi.bgalt:                          #333333
rofi.hlfg:                           #EEE8D5
rofi.hlbg:                           #4D4D4D
rofi.bc:                             #FFFFFF
rofi.color-enabled:                  false
rofi.color-normal:                   #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
rofi.color-urgent:                   #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
rofi.color-active:                   #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
rofi.color-window:                   #fdf6e3,#002b36
rofi.bw:                             2
rofi.location:                       0
rofi.padding:                        5
rofi.yoffset:                        0
rofi.xoffset:                        0
rofi.fixed-num-lines:                false
rofi.terminal:                       urxvt
rofi.ssh-client:                     ssh
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
rofi.run-command:                    {cmd}
rofi.run-list-command:               
rofi.run-shell-command:              {terminal} -e {cmd}
rofi.disable-history:                false
rofi.levenshtein-sort:               false
rofi.case-sensitive:                 false
rofi.sidebar-mode:                   false
rofi.lazy-filter-limit:              150
rofi.eh:                             1
rofi.auto-select:                    false
rofi.parse-hosts:                    false
rofi.combi-modi:                     window,run
rofi.fuzzy:                          false
rofi.glob:                           false
rofi.tokenize:                       true
rofi.m:                              -1
rofi.line-margin:                    2
rofi.filter:                         
rofi.separator-style:                solid
rofi.hide-scrollbar:                 true
rofi.markup-rows:                    false
rofi.fullscreen:                     false
rofi.fake-transparency:              false
rofi.pid:                            /run/user/0/rofi.pid
rofi.kb-primary-paste:               Control+Shift+v,Shift+Insert
rofi.kb-secondary-paste:             Control+v,Insert
rofi.kb-clear-line:                  Control+u
rofi.kb-move-front:                  Control+a
rofi.kb-move-end:                    Control+e
rofi.kb-move-word-back:              Alt+b
rofi.kb-move-word-forward:           Alt+f
rofi.kb-move-char-back:              Left,Control+b
rofi.kb-move-char-forward:           Right,Control+f
rofi.kb-remove-word-back:            Control+Alt+h
rofi.kb-remove-word-forward:         Control+Alt+d
rofi.kb-remove-char-forward:         Delete,Control+d
rofi.kb-remove-char-back:            BackSpace,Control+h
rofi.kb-accept-entry:                Control+j,Control+m,Return,KP_Enter
rofi.kb-accept-custom:               Control+Return
rofi.kb-accept-entry-continue:       Shift+Return
rofi.kb-mode-next:                   Shift+Right,Control+Tab
rofi.kb-mode-previous:               Shift+Left,Control+Shift+Tab
rofi.kb-toggle-case-sensitivity:     grave,dead_grave
rofi.kb-delete-entry:                Shift+Delete
rofi.kb-row-left:                    Control+Page_Up
rofi.kb-row-right:                   Control+Page_Down
rofi.kb-row-up:                      Up,Control+p,Shift+Tab
rofi.kb-row-down:                    Down,Control+n
rofi.kb-row-tab:                     Tab
rofi.kb-page-prev:                   Page_Up
rofi.kb-page-next:                   Page_Down
rofi.kb-row-first:                   Home,KP_Home
rofi.kb-row-last:                    End,KP_End
rofi.kb-row-select:                  Control+space
rofi.kb-cancel:                      Escape
rofi.kb-custom-1:                    Alt+1
rofi.kb-custom-2:                    Alt+2
rofi.kb-custom-3:                    Alt+3
rofi.kb-custom-4:                    Alt+4
rofi.kb-custom-5:                    Alt+5
rofi.kb-custom-6:                    Alt+6
rofi.kb-custom-7:                    Alt+7
rofi.kb-custom-8:                    Alt+8
rofi.kb-custom-9:                    Alt+9
rofi.kb-custom-10:                   Alt+0
rofi.kb-custom-11:                   Alt+Shift+1
rofi.kb-custom-12:                   Alt+Shift+2
rofi.kb-custom-13:                   Alt+Shift+3
rofi.kb-custom-14:                   Alt+Shift+4
rofi.kb-custom-15:                   Alt+Shift+5
rofi.kb-custom-16:                   Alt+Shift+6
rofi.kb-custom-18:                   Alt+Shift+8
rofi.kb-custom-17:                   Alt+Shift+7
rofi.kb-custom-19:                   Alt+Shift+9
rofi.key-window:                     
rofi.key-run:

**Comment by DaveDavenport** [comment]
No debug symbols.

Can you try latest git? see if that fixes it?

**Comment by ubavic** [comment]
Nope. Same story.
But on arch it is painful to dump core. I can sent you lz4 core files.

**Comment by DaveDavenport** [comment]
sending core file does not help.

**Comment by DaveDavenport** [comment]
@carnager  can you test?

**Comment by carnager** [comment]
@ubavic can you build rofi with this PKGBUILD: https://fb.53280.de/6A8R/

then repeat the ulimit -c stuff...

**Comment by ubavic** [comment]
Problem is there is no dump file...

```
Reading symbols from rofi...done.
/root/desktop/rofi/core: No such file or directory.
```

**Comment by carnager** [comment]
`coredumpctl list` will show you a list of coredumps.

**Comment by ubavic** [comment]
I apologise for the inconvenience

From gdb
```
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./rofi -key-run alt+r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000410578 in window_mode_result (mretv=<optimized out>, input=0x7ffcd09d1d78, 
    selected_line=4294967295, sw=0x619400 <window_mode>) at source/dialogs/window.c:517
517	    else if ( ( mretv & ( MENU_OK | MENU_CUSTOM_INPUT ) ) && rmpd->cmd_list[selected_line] ) {
[Current thread is 1 (Thread 0x7f9a67f458c0 (LWP 6385))]
```

**Comment by DaveDavenport** [comment]
thanks, that is useful

**Comment by DaveDavenport** [comment]
Possible fix in git. trying to make a test case.

**Comment by ubavic** [comment]
Can I help somehow?

**Comment by DaveDavenport** [comment]
If you can test latest git, see if it is fixed.

**Comment by ubavic** [comment]
Rofi doesn't crush anymore, but window list is empty (still maybe it is dwm problem).

**Comment by DaveDavenport** [comment]
That is good to know.  I will see if I can setup dwm

**Comment by DaveDavenport** [comment]
Closing this one, will make new one for testing on DWM

**Comment by einalex** [comment]
arch linux, i3-gaps, urxvtc, zsh.  ran the PKGBUILD you posted (it lacks the git submodule init btw) -> same problem. dump:

           PID: 28688 (rofi)
           UID: 1000 (einalex)
           GID: 1000 (einalex)
        Signal: 11 (SEGV)
     Timestamp: Sa 2016-03-12 13:43:52 CET (1min 30s ago)
  Command Line: rofi -show run
    Executable: /usr/bin/rofi
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (einalex)
       Boot ID: b6be5f99e7274f098bbc9635cc03f0af
    Machine ID: a0afbd0256cf4d41a86bb73b027dd03f
      Hostname: imtrey.lan.mayanna.org
      Coredump: /var/lib/systemd/coredump/core.rofi.1000.b6be5f99e7274f098bbc9635cc03f0af.28688.1457786632000000000000.lz4
       Message: Process 28688 (rofi) of user 1000 dumped core.
                
                Stack trace of thread 28688:
                #0  0x00007fe56b3a6646 strlen (libc.so.6)
                #1  0x000000000041727b _window_mode_load_data (rofi)
                #2  0x0000000000417427 window_mode_init (rofi)
                #3  0x000000000040c747 mode_init (rofi)
                #4  0x0000000000408ec1 startup (rofi)
                #5  0x00007fe56d6dac3a g_main_context_dispatch (libglib-2.0.so.0)
                #6  0x00007fe56d6dafe0 n/a (libglib-2.0.so.0)
                #7  0x00007fe56d6db302 g_main_loop_run (libglib-2.0.so.0)
                #8  0x0000000000407f53 main (rofi)
                #9  0x00007fe56b348710 __libc_start_main (libc.so.6)
                #10 0x00000000004084f9 _start (rofi)
                
                Stack trace of thread 28689:
                #0  0x00007fe56b406c3d poll (libc.so.6)
                #1  0x00007fe56d6daf7c n/a (libglib-2.0.so.0)
                #2  0x00007fe56d6db08c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe56d6db0c9 n/a (libglib-2.0.so.0)
                #4  0x00007fe56d701795 n/a (libglib-2.0.so.0)
                #5  0x00007fe56aea2424 start_thread (libpthread.so.0)
                #6  0x00007fe56b40fcbd __clone (libc.so.6)

GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/rofi...(no debugging symbols found)...done.
[New LWP 28688]
[New LWP 28689]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `rofi -show run'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe56b3a6646 in strlen () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fe56dbac880 (LWP 28688))]

**Comment by DaveDavenport** [comment]
hmm no line numbers..  there was one strlen in that function without check.. added that.

**Comment by einalex** [comment]
sorry I hijacked this bug, I created a new one.
