### ISSUE TITLE
-padding causing segmentation faults.

### ISSUE THREAD

**Issue by yorickr** [DaveDavenport/rofi#258]
running rofi using a command containing -padding causes it to segfault. Using i3 on Gentoo.
Some things that might be helpful: 
Output of rofi -show run -padding 800:
```
The script command 'window' has 1 options, but needs 2: <name>:<script>.
Invalid script switcher: window
Failed to parse color: 'base00'
Failed to parse color: 'base05'

(process:20346): GLib-CRITICAL **: g_strchug: assertion 'string != NULL' failed

(process:20346): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed
[1]    20346 segmentation fault  rofi -show run -padding 800

```

If you need anything more please ask :p

**Comment by jpleau** [comment]
I can reproduce this as well.

@DaveDavenport, I ran a git bisect, and 93b6b83fb9fc1add7ebc781c7df20e005352acfb seems to be the offending commit.

**Comment by DaveDavenport** [comment]
Can you paste the relevant section of your Xresources files. It looks like more things are not right there. 
And you monitor(s) resolution?

I cannot reproduce this at all, the commit you point to is actually a commit checking if you are passing insane padding (I get a nice warning dialog when I pass a too large padding).

**Comment by Keats** [comment]
Got this one as well:

```sh
~ » rofi -show run -terminal termite -lines 3 -eh 2 -width 100 -padding 800 -opacity "95" -bw 0 -bc "#282828" -bg "#282828" -fg "#928374" -hlbg "#282828" -hlfg "#ebdbb2"

(process:3314): GLib-CRITICAL **: g_strchug: assertion 'string != NULL' failed

(process:3314): GLib-CRITICAL **: g_strchomp: assertion 'string != NULL' failed
[1]    3314 segmentation fault (core dumped)  rofi -show run -terminal termite -lines 3 -eh 2 -width 100 -padding 800  "95"
```

I don't use a .Xresources at all

**Comment by DaveDavenport** [comment]
fun.  let me try without xresources

**Comment by DaveDavenport** [comment]
Oop indeed, thanks. a failure on showing the error dialog.

**Comment by DaveDavenport** [comment]
Please test.

**Comment by Keats** [comment]
Yep I get the error now.
I guess i have to change the design now since it says that the padding is too big though, is there no way to have the window fullscreen? It was rendering something like http://i.imgur.com/L1y78yz.png

**Comment by DaveDavenport** [comment]
There is fullscreen mode.

**Comment by DaveDavenport** [comment]
Hmm that is missing from manpage, but is in `-h`.
