### ISSUE TITLE
Some Alt key bindings don't work

### ISSUE THREAD

**Issue by cruegge** [DaveDavenport/rofi#265]
Some `.Xdefaults` settings like `rofi.kb-page-prev: Alt+v` have no effect. Changing to `Control+v` or `Control+Alt+v` works, as does assigning the same key to e.g. `rofi.kb-remove-word-forward`.

**Comment by DaveDavenport** [comment]
Possible fix in Git. Can you test?

**Comment by cruegge** [comment]
Looks good. Thank you.

**Comment by DaveDavenport** [comment]
It works?

**Comment by cruegge** [comment]
Yes, that was what I wanted to say :)

**Comment by DaveDavenport** [comment]
thanks. Just making sure :smile:
