### ISSUE TITLE
combi modi

### ISSUE THREAD

**Issue by ralpheeee88** [DaveDavenport/rofi#266]
using i3wm and i simply cant get modi mode to work?

mod+z exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -combi-modi window,run,ssh'

does not work for me

**Comment by DaveDavenport** [comment]
You are using it wrong.
There is rofi that can run as window switcher, launcher, etc.
and there is rofi -dmenu emulation mode.

You are trying to use rofi in dmenu mode while putting it in combi mode.

**Comment by DaveDavenport** [comment]
Try:
```
mod+z exec rofi -combi-modi window,run,ssh -modi combi -show combi
```

**Comment by ralpheeee88** [comment]
that does not work...:(

but added these:

 bindsym $mod+x exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show window switcher'
bindsym $mod+z exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show run'
bindsym $mod+b exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -dmenu'
bindsym $mod+c exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show ssh'

and just use mod+z nd then ctrl tab to toggle in between them....

**Comment by DaveDavenport** [comment]
Again you are using it completely wrong. You seem to be missing the function of the different tools:

*dmenu*: a dynamic menu for X. It reads arbitrary text from stdin, and creates a menu. The user can then select an item and the line is printed to stdout.  This is used to make GUI's for simple tools.

*i3-dmenu-desktop*: A small tool that parses desktop files, and uses *dmenu* to present the user with a list.

*rofi*: A launcher and window switcher. 

*rofi -dmenu*: A dmenu replacement.


So in your above section:

> bindsym $mod+x exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show window switcher'
> bindsym $mod+z exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show run'
> bindsym $mod+b exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -dmenu'
> bindsym $mod+c exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -show ssh'

Only the 3rd line is using the tools correctly. The rest is trying to use rofi to show a list of options, but is starting rofi as a launcher/window switcher. This will be slower then needed and might cause some realy weird side effects.

This would be more sane:

> bindsym $mod+x exec --no-startup-id rofi -show window switcher
> bindsym $mod+z exec --no-startup-id rofi -show run
> bindsym $mod+b exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -dmenu'
> bindsym $mod+c exec --no-startup-id rofi -show ssh

To use combi mode, you can combine several build in launchers:

```
bindsym $mod+z exec rofi -combi-modi window,run,ssh -modi combi -show combi
```

It is hard to give the right help if the error is: 'that does not work...:(' Please try to explain what doesn't work and how it fails.

**Comment by ralpheeee88** [comment]
Thxs for all your help and explanation!! when using this:
bindsym $mod+z exec rofi -combi-modi window,run,ssh -modi combi -show combi

i get the following error:
http://codepad.org/IToYR9QF

i will amend my syntax to what you have suggested.

**Comment by DaveDavenport** [comment]
aah probably escaping, let me try.

**Comment by vyp** [comment]
@DaveDavenport I don't use i3 but at https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup, it says (emphasis mine):

> See [command_chaining] for details on the special meaning of ; (semicolon) and , (comma): they chain commands together in i3, **so you need to use quoted strings if they appear in your command**.

**Comment by DaveDavenport** [comment]
I tried adding quotes, but that still fails.

**Comment by vyp** [comment]
Did try both double and single quotes?

**Comment by DaveDavenport** [comment]
aah this does not work:
```
bindsym $mod+z exec rofi -combi-modi "window,run,ssh" -modi combi -show combi
```

but this does:
```
bindsym $mod+z exec "rofi -combi-modi window,run,ssh -modi combi -show combi"
```

weird, but solved. @ralpheeee88  ^^^^ that should work.

**Comment by ralpheeee88** [comment]
oh yeah!!!!!....thxs a million !!!

**Comment by jaksco** [comment]
Sorry to bring up this old issue but I have a similar problem. maybe it's just the way my brain is wired.

I have a script that runs `find ~ -not -path '*/\.*' -type f -print0 | xargs -0 stat -c "%y %n" | sort -r | cut -f 4 -d ' ' > /home/xk/.cache/filelist` every few minutes

my script was working perfectly when I was using the dmenu option `cat /home/xk/.cache/filelist | rofi -threads 0 -width 100 -dmenu -i -p "locate:" | xargs -r -0 xdg-open`

but I would much prefer all results to be together so I can filter them in one combi:
`bindsym $mod+space exec rofi -show combi -combi-modi drun#run#ssh#file:filelist.sh` 

And it shows up but I don't know where to put xdg-open... when I press enter nothing happens

right now my filelist.sh is just 
```#!/bin/bash
  cat /home/xk/.cache/filelist```

It seems like there should be a very simple solution but I can't find an example of it online
