### ISSUE TITLE
Opacity not working

### ISSUE THREAD

**Issue by BasedArno** [DaveDavenport/rofi#270]
I am currently running i3wm. All the options for rofi are working for me except opacity. I've tested it with many combinations, but I can't get it to display correctly.

-Tested with the following command:
% rofi -show window -fg "#505050" -bg "#000000" -hlfg "#ffb964" -hlbg "#000000" -opacity 50 -sidebar-mode

-Produces:
http://imgur.com/GyW0IhX

-X resources:
! Enabled modi
rofi.modi:                           window,run,ssh
! Window opacity
rofi.opacity:                        50
! Window width
rofi.width:                          50
! Number of lines
rofi.lines:                          15
! Number of columns
rofi.columns:                        1
! Font to use
rofi.font:                           mono 12
! Foreground color
rofi.fg:                             #505050
! Background color
rofi.bg:                             #000000
! Foreground color for active row
rofi.fg-active:                      #268BD2
! Foreground color for urgent row
rofi.fg-urgent:                      #DC322F
! Foreground color for highlighted active row
rofi.hlfg-active:                    #FDF6E3
! Foreground color for highlighted urgent row
rofi.hlfg-urgent:                    #FDF6E3
! Background color for active row
rofi.bg-active:                      #FDF6E3
! Background color for urgent row
rofi.bg-urgent:                      #FDF6E3
! Background color for highlighted active row
rofi.hlbg-active:                    #268BD2
! Background color for highlighted urgent row
rofi.hlbg-urgent:                    #DC322F
! Background color for alternating row
rofi.bgalt:                          #000000
! Foreground color for highlighted row
rofi.hlfg:                           #ffb964
! Background color for highlighted row
rofi.hlbg:                           #000000
! Border color
rofi.bc:                             #002B36
! Use extended color scheme
rofi.color-enabled:                  false
! Color scheme for normal row
rofi.color-normal:                   #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
! Color scheme for urgent row
rofi.color-urgent:                   #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
! Color scheme for active row
rofi.color-active:                   #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
! Color scheme window
rofi.color-window:                   #fdf6e3,#002b36
! Border width
rofi.bw:                             1
! Location on screen
rofi.location:                       0
! Padding
rofi.padding:                        5
! Y-offset relative to location
rofi.yoffset:                        0
! X-offset relative to location
rofi.xoffset:                        0
! Always show number of lines
rofi.fixed-num-lines:                false
! Terminal to use
rofi.terminal:                       rofi-sensible-terminal
! Ssh client to use
rofi.ssh-client:                     ssh
! Ssh command to execute
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
! Run command to execute
rofi.run-command:                    {cmd}
! Command to get extra run targets
rofi.run-list-command:               
! Run command to execute that runs in shell
rofi.run-shell-command:              {terminal} -e {cmd}
! Disable history in run/ssh
rofi.disable-history:                false
! Use levenshtein sorting
rofi.levenshtein-sort:               false
! Set case-sensitivity
rofi.case-sensitive:                 false
! Enable sidebar-mode
rofi.sidebar-mode:                   true
! Set lazy filter limit
rofi.lazy-filter-limit:              15000
! Row height (in chars)
rofi.eh:                             1
! Enable auto select mode
rofi.auto-select:                    false
! Parse hosts file for ssh mode
rofi.parse-hosts:                    false
! Parse known_hosts file for ssh mode
rofi.parse-known-hosts:              true
! Set the modi to combine in combi mode
rofi.combi-modi:                     window,run
! Do a more fuzzy matching
rofi.fuzzy:                          false
! Use glob matching
rofi.glob:                           false
! Tokenize input string
rofi.tokenize:                       true
! Monitor id to show on
rofi.m:                              -1
! Margin between rows
rofi.line-margin:                    2
! Pre-set filter
rofi.filter:                         
! Separator style (none, dash, solid)
rofi.separator-style:                dash
! Hide scroll-bar
rofi.hide-scrollbar:                 false
! Show markup
rofi.markup-rows:                    false
! Fullscreen
rofi.fullscreen:                     false
! Fake transparency
rofi.fake-transparency:              false
! DPI
rofi.dpi:                            -1
! Pidfile location
rofi.pid:                            /run/user/1000/rofi.pid
! Keybinding
rofi.kb-primary-paste:               Control+Shift+v,Shift+Insert
! Keybinding
rofi.kb-secondary-paste:             Control+v,Insert
! Keybinding
rofi.kb-clear-line:                  Control+u
! Keybinding
rofi.kb-move-front:                  Control+a
! Keybinding
rofi.kb-move-end:                    Control+e
! Keybinding
rofi.kb-move-word-back:              Alt+b
! Keybinding
rofi.kb-move-word-forward:           Alt+f
! Keybinding
rofi.kb-move-char-back:              Left,Control+b
! Keybinding
rofi.kb-move-char-forward:           Right,Control+f
! Keybinding
rofi.kb-remove-word-back:            Control+Alt+h
! Keybinding
rofi.kb-remove-word-forward:         Control+Alt+d
! Keybinding
rofi.kb-remove-char-forward:         Delete,Control+d
! Keybinding
rofi.kb-remove-char-back:            BackSpace,Control+h
! Keybinding
rofi.kb-accept-entry:                Control+j,Control+m,Return,KP_Enter
! Keybinding
rofi.kb-accept-custom:               Control+Return
! Keybinding
rofi.kb-accept-entry-continue:       Shift+Return
! Keybinding
rofi.kb-mode-next:                   Shift+Right,Control+Tab
! Keybinding
rofi.kb-mode-previous:               Shift+Left,Control+Shift+Tab
! Keybinding
rofi.kb-toggle-case-sensitivity:     grave,dead_grave
! Keybinding
rofi.kb-delete-entry:                Shift+Delete
! Keybinding
rofi.kb-row-left:                    Control+Page_Up
! Keybinding
rofi.kb-row-right:                   Control+Page_Down
! Keybinding
rofi.kb-row-up:                      Up,Control+p,Shift+Tab
! Keybinding
rofi.kb-row-down:                    Down,Control+n
! Keybinding
rofi.kb-row-tab:                     Tab
! Keybinding
rofi.kb-page-prev:                   Page_Up
! Keybinding
rofi.kb-page-next:                   Page_Down
! Keybinding
rofi.kb-row-first:                   Home,KP_Home
! Keybinding
rofi.kb-row-last:                    End,KP_End
! Keybinding
rofi.kb-row-select:                  Control+space
! Keybinding
rofi.kb-cancel:                      Escape
! Keybinding
rofi.kb-custom-1:                    Alt+1
! Keybinding
rofi.kb-custom-2:                    Alt+2
! Keybinding
rofi.kb-custom-3:                    Alt+3
! Keybinding
rofi.kb-custom-4:                    Alt+4
! Keybinding
rofi.kb-custom-5:                    Alt+5
! Keybinding
rofi.kb-custom-6:                    Alt+6
! Keybinding
rofi.kb-custom-7:                    Alt+7
! Keybinding
rofi.kb-custom-8:                    Alt+8
! Keybinding
rofi.kb-custom-9:                    Alt+9
! Keybinding
rofi.kb-custom-10:                   Alt+0
! Keybinding
rofi.kb-custom-11:                   Alt+Shift+1
! Keybinding
rofi.kb-custom-12:                   Alt+Shift+2
! Keybinding
rofi.kb-custom-13:                   Alt+Shift+3
! Keybinding
rofi.kb-custom-14:                   Alt+Shift+4
! Keybinding
rofi.kb-custom-15:                   Alt+Shift+5
! Keybinding
rofi.kb-custom-16:                   Alt+Shift+6
! Keybinding
rofi.kb-custom-18:                   Alt+Shift+8
! Keybinding
rofi.kb-custom-17:                   Alt+Shift+7
! Keybinding
rofi.kb-custom-19:                   Alt+Shift+9
! Keybinding
rofi.key-window:                     
! Keybinding
rofi.key-run:                        
! Keybinding
rofi.key-ssh:

**Comment by DaveDavenport** [comment]
Opacity gives a hint to the window manager. I3 does not support this hint, you need either a window manager that understands this, or an addon (like a composite manager) to handle this.

Personally I find 'opacity' a very ugly method of doing transparency, as it not only makes the window transparent, but also the content (e.g. text).

If you have a recent rofi you can create a transparent background, by passing an argb:EE000000 color to the theme, then if your window manager supports this, you get a nice transparent background.
(like this: http://images.sarine.nl/rofi-transbg-21-1-2015.png)

If you have an even more recent rofi (0.15.11) you can use fake-transparency (at some memory expense), here rofi takes a screenshots and then fakes it (-fake-transparency  option).
(http://images.sarine.nl/2015-10-20-175902_3840x1080_scrot.png)

**Comment by BasedArno** [comment]
I downloaded compton. That took care of it. Thanks!
