### ISSUE TITLE
Failing tests on OpenBSD

### ISSUE THREAD

**Issue by jasperla** [DaveDavenport/rofi#272]
`rofi_test` from 0.15.11 fails on OpenBSD:

```
Test 1 passed (retv == NULL)
Test 2 passed (length == 0)
Test 3 passed (retv != NULL)
Test 4 passed (length == 1)
Test 5 passed (strcmp ( retv[0], "aap" ) == 0)
assertion "retv == ((void *)0)" failed: file "test/history-test.c", line 47, function "history_test"
zsh: abort (core dumped)  ./rofi_test
```

Basic inspection shows that `retv` contains a single element: `aap`.

**Comment by jasperla** [comment]
Ok, if there's anything I could help out with, you can let me know by mail.

**Comment by DaveDavenport** [comment]
thanks, I will.

**Comment by DaveDavenport** [comment]
ok. this should be fixed.. except that I cannot compile rofi as sigwaitinfo is not available...

**Comment by jasperla** [comment]
All tests now pass on 0.15.11. As for sigwaitinfo() missing, I'll submit a PR for that in a few.

**Comment by DaveDavenport** [comment]
Good to hear.. sorry it took so long. (open a file for appending + reading "a+"  does not allow you to rewrite and truncate on openbsd (correctly)..)

**Comment by jasperla** [comment]
Not a problem, I'm glad this was resolved. I've also updated the OpenBSD port to 0.15.12.
