### ISSUE TITLE
Pango markup is matched when filtering

### ISSUE THREAD

**Issue by simonics** [DaveDavenport/rofi#273]
When Pango markup such as `<span weight='light' size='small'><i></i></span>` is used in list items, the tags are matched when filtering. The above markup is currently used in the new `drun` mode.

This causes problems for any short filters that clash with the markup (e.g. `sm`, `li`, `pan`), and increases edit distances between filters and results.

If it can be done in a reasonably efficient manner, it might be worth adding a plaintext copy of list item text to the data structure for filtering use, in case of any future markup usage...

**Comment by DaveDavenport** [comment]
Agree, this is on my todo. (part of the reason drus is experimental.)

**Comment by DaveDavenport** [comment]
Note to self: either fix for next release or probably remove druns markup.

**Comment by DaveDavenport** [comment]
Mostly fixed in git. Only thing left is the ctrl-space 'row complete' now still copies the markup into the textbox.

**Comment by simonics** [comment]
Looks fixed to me! :+1: 

ctrl-space copies the (mode) prefix when using `-modi combi` as well. That might be another problem.

**Comment by DaveDavenport** [comment]
I will make a fix for that, hopefully later today.
