### ISSUE TITLE
rofi theme examples in repo

### ISSUE THREAD

**Issue by acornejo** [DaveDavenport/rofi#274]
It would be great if rofi shipped with a few theme examples. For instance an Xresource file with vairous rofi configs, all of the commented out.

We could have solarized dark, solarized light (which i think would look very similar to the default), molokai, etc..

I've seen different rofi users fiddling with their own colors, but I think most folks would be satisfied if they could pick from a small collection of carefully crafted themes.

**Comment by carnager** [comment]
https://davedavenport.github.io/rofi//p06-Screenshots.html

If you wanna port some, feel free to do it, with a screenshot. I can add it then.

**Comment by DaveDavenport** [comment]
I would love to have a nice repository of example themes on the website. I hate doing websites, because of this I am not very good at it . So I am looking for volunteers.

**Comment by DaveDavenport** [comment]
https://github.com/DaveDavenport/rofi-themes/blob/master/README.md

Added some support to rofi to make this easier and make auto-updating 'repository'
If we get @gregf  themer, we will have a very nice setup for easy theming.
