### ISSUE TITLE
Can't change color of the active selected window

### ISSUE THREAD

**Issue by sirlnx** [DaveDavenport/rofi#276]
Hi guys,

I can't seem to find a way to change the color of the current active window.

How to reproduce?

Just run the following command, and you will see that when you navigate to the active window, the foreground will be blue, which I can't change with the provided options.

    rofi -show window -width 1366 -lines 3 -columns 4 -font "Terminus 9" -fg "#c2c2c2" -fg-urgent "#ff0000" -fg-active "#7a7a7a" -bg-urgent "#0a0a0a" -bg-active "#0a0a0a" -bg "#0a0a0a" -bgalt "#0a0a0a" -hlfg "#00ff00" -hlbg "#0a0a0a" -bc "#00ff00" -bw 0 -sep 1 -location 7 -separator-style none

PS
I'm running 0.15.10

**Comment by DaveDavenport** [comment]
You need to use the 'advanced' color setup for that, see manpage.


> `-color-enabled`
> Enable the exteneded coloring options.
> `-color-window` *background* *border color* *separator color */
> Set window background, border and separator color.
> `-color-normal` *background, foreground, background alt, highlight background, highlight foreground*
> `-color-urgent` *background, foreground, background alt, highlight background, highlight foreground*
> `-color-active` *background, foreground, background alt, highlight background, highlight foreground*
> Specify the colors used in a row per state (normal, active, urgent).
