### ISSUE TITLE
App st which is in $PATH can't be run nor appears suggested

### ISSUE THREAD

**Issue by fedemp** [DaveDavenport/rofi#277]
My current terminal is [`st`](http://st.suckless.org/) and is installed in `/usr/bin/st`. When I try to it to launch it from rofi, the first suggested app is launched (currently `steam` or `aatest`, depending of the machine). It won't appear in autocomplete either.

I can run it if I pass extra parameters, e.g. `st -f fixed`.

This also happened to me when testing interrobang. https://github.com/TrilbyWhite/interrobang/issues/28

**Comment by DaveDavenport** [comment]
did you select st?  or does it not show up in list? Rofi launch what is selected, or if nothing is selected it executes what you entered (or if you hit `ctrl-enter`)

**Comment by DaveDavenport** [comment]
(it works here btw. launching st from rofi)

**Comment by fedemp** [comment]
Found it. Very deep in the list. Shouldn't rofi show it first since it's an exact match?

**Comment by DaveDavenport** [comment]
Sorting algorithm is something still needing to be fixed.  Problem is that making the perfect one is not easy.

Currently we have levenshtein sorting that will move it to the top, but seems to be confusing for people.

If you have history enabled, running st a few time should move it to the top (based on usage)
