### ISSUE TITLE
No matches when LC_COLLATE != C

### ISSUE THREAD

**Issue by eigengrau** [DaveDavenport/rofi#282]
Actually, I just noticed that the changes made in #268 did break something: When `LC_COLLATE=C` isn’t forced from the enviroment, nothing will match any input, even in cases where it should (so, any character input just yields an empty list). Should rofi enforce `LC_COLLATE=C`? Though it seems unclear to me why `LC_COLLATE=en_US.UTF-8`, etc., should break all matching.

**Comment by DaveDavenport** [comment]
It seems when LC_COLLATE is set
```c
g_utf8_collate_key
``` 
Returns pretty much crap.

```
a results in: 'D	' 
```

**Comment by DaveDavenport** [comment]
hmm strstr on the collated string not work.

**Comment by DaveDavenport** [comment]
should be a fix in git (forgot to post last night). Can you test, no need to set LC_COLLATE=C anymore.

**Comment by eigengrau** [comment]
Nice! Yes, matching works now. Thank you kindly for the fix! Was the problem that collation keys were compared against the (untransformed) input?

As an added bonus, the normalization now allows us to have a binary named `è` (precomposed è) on the path and it will match against the input `è` (e + combining grave). Probably a niche usecase, but nice anyhow :)

**Comment by DaveDavenport** [comment]
collation keys where not suitable for substring matching, only for sorting.
The matching should be reasonably relaxed `test³` should be matched by 'test3' too.

Only regex mode now uses it internal matching on the 'raw' string and therefore is more strict.

**Comment by eigengrau** [comment]
I forgot to close. Thanks for the extra info!
