### ISSUE TITLE
drun: g_realloc() leaves junk data in DRunModeEntry structs

### ISSUE THREAD

**Issue by simonics** [DaveDavenport/rofi#285]
Yet another quick drun bug...
Some desktop files without a `Terminal` setting randomly open in a terminal, due to junk data that ends up in unallocated fields of the `DRunModeEntry` structs when it is [resized by `g_realloc()`](https://github.com/DaveDavenport/rofi/blob/master/source/dialogs/drun.c#L166)

I hotfixed the specific issue I was having by zeroing the `terminal` member [in this location](https://github.com/DaveDavenport/rofi/blob/master/source/dialogs/drun.c#L178). If I print the value of `pd->entry_list[pd->cmd_list_length].terminal` at this point, it's likely to be junk data, since `realloc()` [doesn't zero the newly added part](http://pubs.opengroup.org/onlinepubs/7908799/xsh/realloc.html) ("If the new size is larger, the contents of the newly allocated portion of the object are unspecified").

```diff
+                pd->entry_list[pd->cmd_list_length].terminal = 0;
                 if ( g_key_file_has_key ( kf, "Desktop Entry", "Terminal", NULL ) ) {
                     pd->entry_list[pd->cmd_list_length].terminal = g_key_file_get_boolean ( kf, "Desktop Entry", "Terminal", NULL );
                 }
```

**Comment by DaveDavenport** [comment]
Yep. completely right. thanks.

**Comment by DaveDavenport** [comment]
Should be fixed including another small issue.
