### ISSUE TITLE
Custom XKB mapping not detected by Rofi

### ISSUE THREAD

**Issue by jesusbriales** [DaveDavenport/rofi#286]
I'm using a customized keymap which I install in the boot with `xkbcomp`. Namely, my customization consists in mapping a *modifier* into the *Caps Lock* key and then assigning some special characters or functions to alphanumeric keys.
That said, the problem I'm experiencing is that inside *rofi* the custom layout is not detected (my *modified* Caps Lock is doing nothing). I do not understand if there should be some explanation why XKB is not correctly working inside the *rofi* environment, or this may be a particular issue.

**Comment by DaveDavenport** [comment]
Please tell me what version you are running.

Recently there been a big effort into improving this: See #268

**Comment by jesusbriales** [comment]
My current version is fa2bcd778c9840f660c28f007c1bd1456a8a7eb7, which I think is posterior to the fixes you introduced in that issue.
Maybe the issue continues for me because the shift level I'm using is a little bit more unusual, namely `ISO_Level5_Shift`. Do you think it would be possible to set *rofi* to recognize that shift level too?
Thanks!

PD: If you prefer it, I can include this in the other issue and close this one.

**Comment by DaveDavenport** [comment]
please dont close bug.

**Comment by DaveDavenport** [comment]
I need information on how to reproduce, or a patch fixing it.

**Comment by jesusbriales** [comment]
(I hope) you can reproduce the issue following the next steps:
- Get my custom mapping from the [xkb-extended-keys](https://github.com/jesusbriales/xkb-extended-keys) repository, cloning it into the path `~/.xkb`.
- Follow the *simple* installation steps described there, namely:
  `cd ~/.xkb && . install.sh`
- Now, if you write anywhere (the editor, for example) and keep the Caps_Lock key pressed,
  the keys `j`,`k`,`l` become the arrow keys `←`,`↓`,`→`, `m` maps to delete key, etc.
  Try any of these combinations to check it works in the editor.
- Then, try this same combination `Caps_Lock+...` inside the rofi popup line.

**Expected:** It works the same as for the rest of editor environments
**Actual:** While Caps_Lock is pressed the mapped keys do *nothing*

I hope that is enough to complete reproduce the issue!

**Comment by DaveDavenport** [comment]
It looks like I should no longer support the Mod1Mask,Mod2Mask,etc.. as I have a hard time detecting if they are valid modifier keys.

**Comment by jesusbriales** [comment]
I can confirm it now works seamlessly so... thanks!

**Comment by spul** [comment]
Hi, seems related, so I just want to drop that and ask if this sounds managable.
I use xmodmap to bind Caps to Hyper.

```
keycode 66 = Hyper_L
clear Lock
clear Mod4
add Mod4 = Super_L Hyper_L
```

With that I use xcape to double-bind Hyper to Escape with a short timeout:

```
xcape -t 300 -e Hyper_L Escape
```

Escape (pressing Caps) is functioning properly with rofi (1.0.0). afaik I cannot bind keys with Hyper? Tested 

```
rofi.kb-mode-next:                    Alt+Right,Hyper_L+w
rofi.kb-mode-previous:                Alt+Left,Hyper_L+b
```

and

```
rofi.kb-mode-next:                    Alt+Right,Hyper+w
rofi.kb-mode-previous:                Alt+Left,Hyper+b
```

so far with no success.

**Comment by sardemff7** [comment]
@spul Please do not resurrect an old bug for something only remotely related.
You tell xmodmap to use Hyper as Mod4, the same as Super. Why the hell do you expect it to be another modifier if you tell it to be Mod4? Make it the Hyper modifier, and it’ll work.
