### ISSUE TITLE
mark shift+entered lines by changing color of line

### ISSUE THREAD

**Issue by carnager** [DaveDavenport/rofi#287]
With rofi it's possible to select multiple lines in dmenu mode. It would be handy if rofi had a way to somehow mark those lines. 

The nicest solution is probably by coloring the lines differently.

**Comment by DaveDavenport** [comment]
This should work:
http://random.sarine.nl/selected_row.patch

Might not be the fasted though.  It can be optimized.
Currently the text color is set to 0.5 opacity when selected.
