### ISSUE TITLE
"Toggle case sensitivity" key inconsistency

### ISSUE THREAD

**Issue by Vifon** [DaveDavenport/rofi#289]
The manpage states that "Toggle case sensitivity" is bound to <kbd>Ctrl</kbd>+<kbd>\`</kbd> while in reality it's bound to just <kbd>\`</kbd>. I would submit a PR but I don't know which one is desirable.

**Comment by DaveDavenport** [comment]
yes, this should be fixed.

**Comment by DaveDavenport** [comment]
updated manpage.
