### ISSUE TITLE
Cleanup recent entries

### ISSUE THREAD

**Issue by rumpelsepp** [DaveDavenport/rofi#296]
Hi,
I am trying to figure out where rofi stores the recent items. I recently did some tests and now my rofi list of programs is full of garbage... How can I cleanup this?

**Comment by DaveDavenport** [comment]
It stores 25 items (I think) and you can remove items from this list with `shift-delete`

**Comment by rumpelsepp** [comment]
> and you can remove items from this list with shift-delete

Got it, thx!
