### ISSUE TITLE
File Search Modi

### ISSUE THREAD

**Issue by deviousgeek** [DaveDavenport/rofi#297]
This is a crazy / future sort of thing, but how hard would it be to implement a modi to look for files (in configured paths / home by default). This would bring rofi closer to being a 'Spotlight' (for OSX) kinda thing, and would be a nice thing to have. :)

Let me know your thoughts.

**Comment by DaveDavenport** [comment]
This can be added using scripts. This is currently not something I plan to integrate directly into Rofi.
See (here)[https://github.com/DaveDavenport/rofi/blob/master/Examples/rofi-file-browser.sh] for a simple file browser that can be ran like:

```bash
rofi -modi "file:./rofi-file-browser.sh,drun" -show file
```

If somebody makes a good patch that adds functionality (without adding obscure depencies) and is willing to maintain it, I will accept it.
