### ISSUE TITLE
changing matching and/or sorting options in runtime?

### ISSUE THREAD

**Issue by infokiller** [DaveDavenport/rofi#298]
Is it possible to define a keybinding to change options in runtime?
There are two typical scenarios when I'm launching a program:
* A frequently launched program. In this scenario, I find **no** levenshtein sort to be the best. The reason is that using levenshtein distance ignores the history entries (if I'm not missing anything).
* A program launched once in a while. In this scenario, the history doesn't help much and therefore levenshtein sort can be useful.

If it would be possible to change the match/sort option at runtime I could just start typing what I'm looking for a toggle the match/sort mode if needed. There is a similar existing feature in [fzf](https://github.com/junegunn/fzf).

**Comment by DaveDavenport** [comment]
Should be easy to implement, see no reason why not.

**Comment by DaveDavenport** [comment]
Fixed.

**Comment by infokiller** [comment]
Thanks a lot! you're awesome!
