### ISSUE TITLE
Add window icons to window switcher

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#30]
I would like to see the window icons in the window list, next to the class name maybe?

**Comment by ejemba** [comment]
:+1:  for this one. It could be usefull.

**Comment by roomcays** [comment]
As for me: -1. Keep fancy icons away from rofi please.

**Comment by blueyed** [comment]
It would/could be optional of course, and then disabled by default probably.

**Comment by ViktorNova** [comment]
As a compromise, would you be open to Rofi facilitating using an iconic font like [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/)?
Really this approach would only involve supporting using multiple fonts (does Rofi already do this?) and maybe a few helper functions

**Comment by DaveDavenport** [comment]
It uses pango for font rendering, so if pango can do multiple fonts (I  guess it can).

**Comment by blueyed** [comment]
> iconic font

I don't see how that helps with providing an icon of the application?!

**Comment by ViktorNova** [comment]
True, I apparently got excited about the idea of icons and missed the context of the original issue

I'll see what I can do with this

**Comment by DaveDavenport** [comment]
Curious to know if this font works correctly though. Might be useful for 'combi' mode.

**Comment by aviillouz** [comment]
At least some of the icons work
