### ISSUE TITLE
rofi and xbindkeys

### ISSUE THREAD

**Issue by infokiller** [DaveDavenport/rofi#301]
I have some xbindkeys bindings that I'm using, but they don't work in rofi. It seems that rofi is capturing the key events instead of xbindkeys. Any idea how I can fix that?

Thanks!

**Comment by DaveDavenport** [comment]
This is somewhat duplicate to #295. 
This is inherent to how rofi works, Rofi grabs the keyboard exclusively.
What keybinding do you want to call when **rofi** is active?

**Comment by infokiller** [comment]
I have a few keybindings defined that use combinations of the capslock key. Using `setxkbmap` I specified the option `lv3:caps_switch` so that now if I do `xev` and type capslock I get `ISO_Level3_Shift`. Then I have a set of keybindings such as the following:
* capslock+m: enter
* capslock+d: delete last word (like ctrl+backspace)
etc. Is it possible to define these mappings in rofi as well?

**Comment by carnager** [comment]
yes... all mappings can be re-mapped
see rofi -dump-xresources to see default bindings, including their config name

**Comment by DaveDavenport** [comment]
hmm this might require some modification to Rofi. (to use capslock as modifier).

**Comment by DaveDavenport** [comment]
This sucks.. I don't think I can fix this without either making things horrible confusing (use configurable modifier masks), or breaking keyboard layouts with multiple levels (.e.g that use ISO_l3 to enter characters.) 
I will need to think about this some more.

(p.s. I myself have caps set to be super key on laptop. And use that to bind keys).

**Comment by infokiller** [comment]
Thanks a lot @DaveDavenport for responding so quickly!
If I understand correctly #286, If I will use a true xkb keyboard layout (instead of xbindkeys hacks) then the keys will work well in rofi?
I can probably do this for most of the mappings I defined in xbindkeys, but not all of them. For example, I have Capslock+c mapped by default to Ctrl+c, but if the current focused window is an xterm it is mapped to Ctrl+Shift+c. This way i have a "global" copy key that works both in terminals and other programs.

**Comment by infokiller** [comment]
OK so I moved some of the mappings to xkb and indeed these work now in rofi. However, I still have some custom mappings in xbindkeys like Capslock+w is mapped to Ctrl+Left. I also mapped Capslock to `ISO_Level5_Shift` like in #286. Is it possible to use it as a modifier in the rofi config?

**Comment by yzhou61** [comment]
I'm having a similar problem. When the rofi window is active, none of the i3 keybindings work. Is there a way for rofi to pass the key press it doesn't know about to the rest of the system?

**Comment by DaveDavenport** [comment]
Please do not hijack a bug report.

**Comment by yzhou61** [comment]
Sorry, I was thinking it could be caused by the same underlying problem.

**Comment by infokiller** [comment]
Hey @DaveDavenport , just checking in on this issue.
Is there any workaround you're aware of that I can use to map Capslock+d to delete word (like Ctrl+Backspace)?
Currently I have Capslock mapped to `ISO_Level5_Shift`.
Back then you mentioned that `ISO_Level3_Shift` can't be mapped because, IIUC, some users use it to input characters. Is it the same with `Level5`?

Thanks!

**Comment by DaveDavenport** [comment]
@sardemff7  ideas?

**Comment by AlexDaniel** [comment]
> or breaking keyboard layouts with multiple levels (.e.g that use ISO_l3 to enter characters.) 

Actually, keyboard layouts are broken already. I have ``AltGr``+``i`` configured as backspace (in xkb, it is part of my layout), it does not work in rofi. Should I open a separate issue for this?

**Comment by DaveDavenport** [comment]
Don't highjack unrelated bug reports please.......

**Comment by AlexDaniel** [comment]
How the hell would I know if it is unrelated or not (that's why I asked the question). The fix for one will probably fix another as well. Eh.

**Comment by DaveDavenport** [comment]
Closed. To many random things are added to this bug report.
