### ISSUE TITLE
Broken rendering with properitary nvidia driver

### ISSUE THREAD

**Issue by kaueraal** [DaveDavenport/rofi#302]
When using the properitary nvidia driver rofi renders as an white rectangle for me. When using the nouveau driver everything works fine.

This occurred both with version 0.15.11 and the most recent git version. Running rofi from the command line doesn't yield any errors and I don't have this kind of issues anywhere else.

**Comment by DaveDavenport** [comment]
Weird, I am using it on properitary nvidia drivers. 
What distro are you running? on what DE? What nvidia driver version? running a composite manager?
Can you pastebin the --dump-xresources output?

**Comment by kaueraal** [comment]
I am running Arch Linux with i3 and compton. The nvidia package has version number 358.16-2.1 .

I found the issue, or at least the beginning of it: Killing compton lets return the rendering to normal.

The root seems to be compton when run like the following: 
```
alexander@vanilleeis ~ $ compton --backend glx
[     1.73 ] error 8 (BadMatch) request 154 minor 22 serial 1091 ("BadMatch (invalid parameter attributes)")
[     1.73 ] error 9 (BadDrawable) request 155 minor 4 serial 1092 ("BadDrawable (invalid Pixmap or Window parameter)")
[     1.73 ] error 172 (Unknown) request 154 minor 16 serial 0 ("GLXBadPixmap")
[     1.73 ] error 172 (Unknown) request 154 minor 16 serial 0 ("GLXBadPixmap")
[     1.73 ] error 9 (BadDrawable) request 155 minor 4 serial 1123 ("BadDrawable (invalid Pixmap or Window parameter)")
[     1.73 ] error 172 (Unknown) request 154 minor 16 serial 0 ("GLXBadPixmap")
[     1.74 ] error 172 (Unknown) request 154 minor 16 serial 0 ("GLXBadPixmap")
[     1.74 ] error 9 (BadDrawable) request 155 minor 4 serial 1154 ("BadDrawable (invalid Pixmap or Window parameter)")
[     1.74 ] error 172 (Unknown) request 154 minor 16 serial 0 ("GLXBadPixmap")
[     2.56 ] error 172 (Unknown) request 154 minor 16 serial 0 ("GLXBadPixmap")
[     2.56 ] error 172 (Unknown) request 154 minor 23 serial 1204 ("GLXBadPixmap")
```

Running compon without the glx backend works fine as well.

Pastebin for -dump-xresources: http://pastebin.com/Kg5JBkrG

**Comment by kaueraal** [comment]
Ok, using the git version of compton seems to fix it - it is probably an issue on their end.

**Comment by DaveDavenport** [comment]
Thanks for getting to the bottom of this. Was afraid that I had to postpone release.
