### ISSUE TITLE
Fonts do not look sharp enough

### ISSUE THREAD

**Issue by d125q** [DaveDavenport/rofi#303]
Is it just me or do fonts in Rofi simply not look sharp enough?  This is not very noticeable with large font sizes, but it is rather annoying with smaller fonts.  I can provide screenshots if you think it will be of any help.

**Comment by DaveDavenport** [comment]
This is a side effect of using pango with cairo.
If you have a fixed size font, but request a different size it will 'scale' making it fuzzy.

**Comment by d125q** [comment]
Thanks.  How can I not request a different size?

**Comment by DaveDavenport** [comment]
I am not sure if you can request 'no specific' size with pango..  But just set it to the right size.

What version of rofi are you running and can you pastebin the output of `rofi -dump-xresources`. This way it won't be a complete guessing game.

**Comment by d125q** [comment]
I am running the latest build from Git.  The X resources can be found on http://ix.io/n0J.  Note that the issue is present with other fonts, too.

**Comment by DaveDavenport** [comment]
Hmm pragmata should be fine? can y ou show screenshot?   

`alt-shift-s` should take a screenshot and store in the XDG picture directory (if set).

**Comment by d125q** [comment]
Here is a screenshot:
![rofi-2015-12-27-2249](https://cloud.githubusercontent.com/assets/7765538/12012235/2fcf7f74-acec-11e5-8575-154351fa32b8.png)

The fonts look very fuzzy compared to my regular terminal.  Perhaps fontconfig settings are not applied?

**Comment by DaveDavenport** [comment]
Can you show screenshot of terminal? so I can compare. (I see a lot of aliasing in screenshot, but it looks similar as here.)
I use pango directly, I assume that handles fontconfig correctly.

**Comment by d125q** [comment]
Here's an example:
![term](https://cloud.githubusercontent.com/assets/7765538/12012274/8fa08e10-aced-11e5-9758-145a8ae808ab.png)

**Comment by DaveDavenport** [comment]
![compare](https://cloud.githubusercontent.com/assets/406245/12012306/77a7a40a-acee-11e5-9b70-0f054fa86bd2.png)

The green 0 is from the terminal screenshot and the other 0 from the rofi one.

**Comment by DaveDavenport** [comment]
gimped:
![image2](https://cloud.githubusercontent.com/assets/406245/12012316/06343404-acef-11e5-9ea4-15b560d5966d.png)

**Comment by d125q** [comment]
OK, how about this?  Characters should be of same foreground/background so easier to compare.  The differences can easily be seen.
![term](https://cloud.githubusercontent.com/assets/7765538/12012321/47be56ac-acef-11e5-8625-3c9de4a00d4b.png)

**Comment by DaveDavenport** [comment]
Aah, rofi is not using subpixel hinting, but gray.

**Comment by d125q** [comment]
So, is that intended?

**Comment by DaveDavenport** [comment]
Not by me :smile:, I will have to look into this.
We should do subpixel hinting, if requested.

**Comment by d125q** [comment]
Thank you for looking into this and thank you for this wonderful little tool!

**Comment by DaveDavenport** [comment]
np. thanks for the report :smile: . If possible can I ask you test patches later?

**Comment by d125q** [comment]
Most definitely.  I'll have to go to sleep now, though :)

**Comment by DaveDavenport** [comment]
Well that was a fun ride (not).
subpixel hinting does not work with CAIRO_OPERATOR_SOURCE only with OVER. (this is not documented anywhere).

Also needed to refactor some stuff to get the right settings propagated from the xlib (base) surface.

This is a first draft of patch: http://random.sarine.nl/rofi-subpixel-hinting.patch
now it is many hours after bedtime.

**Comment by d125q** [comment]
The fonts look nicely, however, the cursor seems to be missing?
![rofi-patch1](https://cloud.githubusercontent.com/assets/7765538/12017064/79ddafee-ad52-11e5-829b-5098d699c657.png)

**Comment by DaveDavenport** [comment]
yeah, I know.. it was 3 at night.. will clean up patch and commit it

**Comment by DaveDavenport** [comment]
It is in git (with working cursor)

**Comment by d125q** [comment]
Thanks!  I believe it is a lot better this way, plus the code looks nicer.

**Comment by DaveDavenport** [comment]
Good to have it fixed.. Thanks.

**Comment by nick87720z** [comment]
Problem is still here. Version 1.5.4 from gentoo, but no patches, affecting program itself.
There is my config: [config.rasi.txt](https://github.com/davatorium/rofi/files/4557918/config.rasi.txt)

and screenshot:
![Снимок экрана_2020-04-30_16-30-18](https://user-images.githubusercontent.com/3896190/80705581-211c8700-8b00-11ea-8c74-12411e1b1ffb.png)

**Comment by DaveDavenport** [comment]
Looks like you are not getting subpixel hinting in rofi.

**Comment by DaveDavenport** [comment]
I am getting sub-pixel hinting  in rofi:
![image](https://user-images.githubusercontent.com/406245/80710909-c8dd8900-8aef-11ea-9d2b-ff5f9b9b9a72.png)

But not using the exo 2 font for some reason... 
![image](https://user-images.githubusercontent.com/406245/80710957-e0b50d00-8aef-11ea-9d02-16ef9c812b1d.png)

I am no fontconfig expert.. I just use pango and don't want to bother with that stuff :-P

**Comment by DaveDavenport** [comment]
I am confused, the font does do it in my own theme:
![image](https://user-images.githubusercontent.com/406245/80711823-4655c900-8af1-11ea-8fcd-ef54f439eb54.png)

**Comment by nick87720z** [comment]
I tried with "Sans 10" and "Drois Sans 10", still greyscale.

**Comment by DaveDavenport** [comment]
> 
> Upd2: For me subpixel works with default config/look (-no-config), but doesn't work e.g. with arthur and fancy themes.
> But with most other themes ot's ok.

Yeah it is weird. works fine for me with several themes.   I suspected transparency for a bit, but I have transparent themes,  doing it fine.

**Comment by DaveDavenport** [comment]
Interesting.

**Comment by DaveDavenport** [comment]
I wonder why that code somehow causes  cairo to stop doing subpixel hinting.
It just does some drawing, and that is it.

**Comment by nick87720z** [comment]
It is exactly caused by any of radius_{tl,te,bl,br} != 0. Further is somewhat hardcore or me, I was just happy with cairo_show_text :S.

**Comment by nick87720z** [comment]
It's caused by clipping in widget_draw() before more widget->draw() call. At least with my cairo version (1.16.0) there are two conditions, that break subpixel text rendering:
- clip shape has non orthogonal lines (tested only with quadrangle, but could be more complex shapes, consisting of orthogonal lines)
- if pango layout is cliped.

I wanted to check, how will it be using intermediate image surf, but by surprise can't even get this image painted (I have minimal working example if x11/cairo app without even event handling, which I use to learn using x11/cairo combo). Struggling for now. As another variant - could be to disable clip between another cairo_save/restore call pair.

**Comment by nick87720z** [comment]
fix in progress (looks too much to create/destroy img on each draw)
