### ISSUE TITLE
Sensitive Input

### ISSUE THREAD

**Issue by smasher816** [DaveDavenport/rofi#315]
Is it possible to input information without echoing the characters out (similar to how sudo behaves). I was developing a password manager like the many dmenu varieties out there and it would be nice to not worry about people looking over your shoulder as you type.

**Comment by smasher816** [comment]
Actually, with a little thought the ability to color the input differently than the prompt line and other "normal" input would suffice. One could then use a color with 0 alpha.

**Comment by carnager** [comment]
i would be interested in the script :)

**Comment by smasher816** [comment]
I'll probably throw it on my github page after I get it in a good state.

For now it actually seems like using pango might be a solution. Ex:

    rofi -dmenu -mesg '<span foreground="white">Enter Master Password</span>' -color-normal "argb:00000000,argb:00000000" <&-

It's a little ugly with the extra line, but I guess this will do. Rofi probably isn't the best tool for inputting custom information but I wanted to keep the theming with the rest of the script such as choosing the website.

**Comment by DaveDavenport** [comment]
This should not be too difficult to add

**Comment by DaveDavenport** [comment]
Added some experimental support (-password to dmenu).
No work has been done to 'keep the password safe'.

**Comment by smasher816** [comment]
Thanks for the quick work. I just tested it this morning and it works fine :+1: 

Honestly, I am not too worried about special "keep the password safe" features at the moment since I am still piping the output to other programs. Additionally it is always possible to find programs that will inspect running programs memory, or install a keylogger. Nothing is ever 100% secure.

**Comment by DaveDavenport** [comment]
I mostly wanted to make it very clear that I did not do anything to protect against it..  So people do not 'assume'.
