### ISSUE TITLE
Support killing windows from the window switcher

### ISSUE THREAD

**Issue by scottjad** [DaveDavenport/rofi#316]
It would be nice if the user could kill a window while in the window switcher. This would make it a bit more than a window switcher so maybe it's out of scope. 

If this feature were added, ideally the window list would remain open after the action (kill-window) and the windows listed below would shift up.

I think C-k would be a good binding.

Something more general than this could potentially be done (fzf has --bind). The user could bind key bindings to execute a script that receives the currently selected item as input and then it'd be up to them to make a kill window script that can figure out the window id/process from the window switcher description. Perhaps there'd need to be a way to designate whether the binding terminates rofi or not. Not sure how having an accurate listing after he script completes would work, since not all actions would remove items from the list.

**Comment by sardemff7** [comment]
Draft implementation in `wip/window-list` branch.

**Comment by sardemff7** [comment]
Branch merged to master.

**Comment by DaveDavenport** [comment]
thanks.

**Comment by iljapanic** [comment]
Apologies for bringing up an old issue. I have been struggling for the past hour to figure what parameters to pass to rofi to enable killing windows while keeping the list open. I suspect it has something to do with ``-windows-command``

Can you point to the right solution?

This is my windows switcher script:

```shell
rofi \
  -show window \
  -modi window,windowcd \
  -show-icons \
  -window-command  \
  -kb-accept-entry "space,Return" \
  -sidebar-mode&
```

cc: @sardemff7 @scottjad

**Comment by sardemff7** [comment]
Do not hijack an old issue for a question, and IRC or Reddit or the places to go for that.
