### ISSUE TITLE
Rofi as fast filemanager

### ISSUE THREAD

**Issue by rogorido** [DaveDavenport/rofi#318]
Is there any chance that rofi could be extended to work as a filemanager to quickly open files (for instance using the apps defined in .mailcap)? There is something similar with dmenu (https://github.com/hangtwenty/dmenfm), but rofi is of course much better!

**Comment by DaveDavenport** [comment]
Why don't you use that script with rofi?
Rofi is dmenu compatible.

**Comment by rogorido** [comment]
aha... good idea. I will give it a try. Thanks!

**Comment by DaveDavenport** [comment]
either change
```
menu=dmenu
```
in the script, or make a simlink from dmenu to rofi in your PATH. (if executable name is dmenu rofi will switch to dmenu mode).

**Comment by rogorido** [comment]
it works! thanks a lot!
