### ISSUE TITLE
Shift-Tab isn't working

### ISSUE THREAD

**Issue by flexo3001** [DaveDavenport/rofi#319]
The Shift-Tab keybind isn't working for rofi.kb-row-up. 
Version: 0.15.12, compiled with i3-support.

**Comment by d125q** [comment]
Same here; using latest build from Git.

**Comment by DaveDavenport** [comment]
aah fun, Tab key is Tab,  Shift tab is ISO_Left_Tab.
```
rofi -kb-row-up "Up,Control+p,Shift+ISO_Left_Tab"  -modi run -show run
```

Can you see if that fixes it.

**Comment by d125q** [comment]
It does indeed.

**Comment by flexo3001** [comment]
Yes, this works.

**Comment by milopiccolo** [comment]
On my machine (Thinkpad T410) I needed to add
`Shift_L+ISO_Left_Tab, Shift_R+ISO_Left_Tab`
to get the behavior I wanted. Yuck. Might be worth adding those too?

**Comment by DaveDavenport** [comment]
@milopiccolo  you are replying to a very old bug. please make a new one with all the required information added.

A lot has changed since 0.15.12 and now.
