### ISSUE TITLE
Expose parse_known_hosts option

### ISSUE THREAD

**Issue by mrabault** [DaveDavenport/rofi#320]
Hello,

First of all, I want to thank you for rofi, it's a great piece of software.

I've noticed that when using the SSH mode, rofi reads my `known_hosts` file. That's a bit annoying, because BitBucket , Github and so on end up there. I've read the code and noticed that in `config.def.c` you provide an option to avoid that behavior: [parse_known_hosts](https://github.com/DaveDavenport/rofi/blob/master/config/config.def.c#L130-L131).

I didn't see a CLI/Xresources option to set this. If there isn't one, could you expose that option, please ? And sorry if there is one that I didn't see. For now, I'll recompile rofi with that option set to `FALSE`.

Cheers,

**Comment by DaveDavenport** [comment]
from rofi --help:

```
        -[no-]parse-known-hosts                 Parse known_hosts file for ssh mode
                True
```

**Comment by mrabault** [comment]
Oh ... I didn't think of that, I checked the manpage on your website and it wasn't mentioned: [here](https://davedavenport.github.io/rofi/manpage.html). Might want to update it.

Sorry to have bothered you

**Comment by DaveDavenport** [comment]
No problem. I was just going over every item to see if it was mentioned. Yeah I need somebody to maintain website for me.

**Comment by mrabault** [comment]
Perhaps you could use a git hook or a Webhook so that the manpage gets regenerated from you server whenever you modify it.

**Comment by DaveDavenport** [comment]
I thould be done on a tag then (release), so only stable manpage is on website :+1:
