### ISSUE TITLE
Differentiate between kb-cancel and empty input

### ISSUE THREAD

**Issue by smasher816** [DaveDavenport/rofi#322]
For some "dmenu" like situations it would be useful to know if the user canceled (ex: by pressing escape) or if they simply entered an empty string. Right now both events will cause rofi to exit with the same exit code of 1.

**Comment by DaveDavenport** [comment]
why? you are presenting the user with no options and want to distinguish between escape and enter?

What is the point of an empty dialog anyway?

**Comment by DaveDavenport** [comment]
(If there is a good use-case I have no problems changing it.)

**Comment by smasher816** [comment]
I was building my own password manager similar to rofi-pass (https://github.com/carnager/rofi-pass). Using rofi as a frontend to select a site, then calling xdotool to type the password has been working great.

One thing I was hoping to implement was the ability to add a site from the list. My problem is that there are a few pieces of information the I need to ask for such as the password length, url, etc. Some of these (Ex: the URL) are allowed to be blank, or have a default if unspecified (ex: length=10). Sometimes I have realized I had mistyped something and would like to cancel the addition. Unfortunately when I tried to do this, I am unable to differentiate between the user leaving the input empty, and the user wanting to cancel, prompting me to open this issue.

Honestly, rofi probably is not the best tool for the job of inputting data. However, I was hoping to keep the UI consistent with the rest of the program (such as the main site choosing portion), and rofi-pass showed me it was possible. If you would like to see my code I would be happy to post it. I was trying to get this last feature ironed out before I published it though.

**Comment by carnager** [comment]
the process of entering usedata in rofi-pass is so cumbersome that i decided to add a little shellscript to do the same thing. I was actually thinking about removing the menu alltogether. 

what tool will your password manager be using? i guess it's not using pass? But if it is, may I ask you to keep the password files compatible? [autopass](https://github.com/jreinert/autopass) also uses the same format.

**Comment by DaveDavenport** [comment]
That seems to be a valid reason. I will fix it.

If there are ideas on how to improve text input? let me know.. (e.g. mode where entering text does not filter?)
