### ISSUE TITLE
rofi search through tabs too

### ISSUE THREAD

**Issue by xy124** [DaveDavenport/rofi#323]
It would be soo freaking awesome if one could search through open tabs in ffx, chromium, terminator ... with the rofi Alt+Tab - Menu ;)

**Comment by DaveDavenport** [comment]
You can write scripts to add this, then use the 'combi' browser to integrate it in window/run list.

**Comment by avindra** [comment]
@xy124  one way i got around this is by using extensions in Chromium and Firefox to disable tabbing (so that my window manager `i3` can handle it instead. Then, `rofi` can search through all tabs, because they're technically just more windows to `i3` :wink:
