### ISSUE TITLE
Launch on fixed monitor (multi-monitor setup) in fullscreen mode

### ISSUE THREAD

**Issue by Brillow** [DaveDavenport/rofi#324]
Tried using the -m option, but that doesn't seem to work with -fullscreen enabled.

Edit: To make it clearer: I want rofi to always open on the display specified instead of the one the current focus is on

**Comment by DaveDavenport** [comment]
Last time I tried, setting fullscreen made i3 completely ignore where I wanted to place it and always open it on active screen.
Should check if there is a way around it.

**Comment by Brillow** [comment]
I'm using XFCE, trying to set it to another monitor is just giving me an error saying to reset -m to -1

**Comment by sardemff7** [comment]
Can you test the `wip/fullscreen` branch?

**Comment by Brillow** [comment]
Uhm, I don't see that branch anywhere? Am I doing something wrong?

**Comment by DaveDavenport** [comment]
its been merged into master.

**Comment by Brillow** [comment]
Sorry, can't try that right now. I'm using Debian stable, most recent version for libxkb-common is 0.4.3 without a backport available. Any chance it will do without 0.5.0?

**Comment by DaveDavenport** [comment]
Did some more test son multi monitor. Seems to be fixed.
