### ISSUE TITLE
Where do I put custom modi scripts?

### ISSUE THREAD

**Issue by binaryplease** [DaveDavenport/rofi#325]
I found this explanation on how to create a custom mode:
https://blog.sarine.nl/blog/2014/08/03/rofi-updates/
It might be a dumb question but where do I have to put the script (in this case i3_switch_workspace_script.sh)?

I would like to create a mode that opens files matched by name in an editor.

**Comment by carnager** [comment]
whereever you want.

**Comment by DaveDavenport** [comment]
or in path. I normally put them in ~/.local/bin/ so I do not need to enter full path.

**Comment by indeedwatson** [comment]
This doesn't seem to be working for me. I have a script called rofi-bangs that works fine when called on it's own, but if I do `rofi -modi 's:rofi-bangs.sh' -show s`

I get:
```bash
(process:1050393): Helper-WARNING **: 17:33:53.298: Failed to set lock on pidfile: Rofi already running?

(process:1050393): Helper-WARNING **: 17:33:53.298: Got error: -1 Socket operation on non-socket
```

And rofi opens with the appropriate name (`s`) but with no content.

**Comment by DaveDavenport** [comment]
rofi-bangs.sh is not a custom modi. you cannot nest rofi's.

**Comment by DaveDavenport** [comment]
To explain (missed you in irc).

* Please don't ask questions in old issues.  This is not the place and it is clearly stated in the guidelines not to do this!
* rofi-bang is not a custom modi script.
  * It is a bash script that calls rofi to show options (via dmenu emulation).
  * Calling it as a modi script will cause rofi be called from within rofi. This is not supported.
