### ISSUE TITLE
Failed to create pid file.

### ISSUE THREAD

**Issue by marc3lsk** [DaveDavenport/rofi#328]
I have debian and i3wm. I launch "rofi -run-key F2" but when i press F2 i see message in console "Failed to create pid file." I dont have this issue when i launch rofi under root.

**Comment by DaveDavenport** [comment]
Version?
pastebin of `-dump-xresources`

**Comment by marc3lsk** [comment]
i launched rofi -dump-xresources http://pastebin.com/x0HFkJuz
Version 0.15.11 installed via apt-get

**Comment by DaveDavenport** [comment]
Does this file: `/run/user/1000/rofi.pid` and or directories exist?

**Comment by marc3lsk** [comment]
yes i can see `/run/user/1000/rofi.pid`

**Comment by vyp** [comment]
@marc3lsk https://i3wm.org/docs/userguide.html#keybindings

**Comment by DaveDavenport** [comment]
@vyp why are you posting that? yes there are other ways to launch rofi, but it is not directly the issue.

@marc3lsk is there a instance of rofi still running? if not, try removing that file.

**Comment by vyp** [comment]
@DaveDavenport

> how to use Windows Key to launch rofi?

**Comment by marc3lsk** [comment]
I could not figure how to make this work: `rofi -key-run WIN `
Workaround is `rofi -key-run mod4+d`

**Comment by DaveDavenport** [comment]
I am confused here...  the initial issue was with F2 and pid file, now we are talking about WIN? and it works?
