### ISSUE TITLE
Custom key exit code broken when options filtered

### ISSUE THREAD

**Issue by bcbnz** [DaveDavenport/rofi#333]
I'm using Rofi in dmenu mode with custom key mappings. When the list is filtered so there are no entries visible, the return code if the custom keys are pressed gives a weird value.

I've written the following test script to demonstrate it:

```bash
#!/usr/bin/env bash

opt=$(rofi -dmenu -format i -no-custom -p "Test" -kb-custom-1 F5 -kb-custom-2 Control+a -mesg "Press F5 to refresh, Control+A to add entry" <<ENDOPTS
Option 1
Option 2
Option 3
ENDOPTS
)
ret=$?

echo "Option selected (stdout): $opt"
echo "Return code: $ret"
```

The results on my computer for various filters with Rofi 0.15.12 are as follows:

Filter | Key pressed | Option selected (stdout) | Return code
-------|------------------|----------|-----------
         |  Enter  | 0 | 0
         |  Escape | | 1
         | F5     | 0 | 10
         | Ctrl+A | 0 | 11
2 | Enter | 1 | 0
2 | Escape | | 1
2 | F5 | 1 | 10
2 | Ctrl+A | 1 |11
q | Enter | Doesn't exit | Doesn't exit
q | Escape | | 1
q | F5 || 139
q | Ctrl+A || 139

If there is at least one entry visible after filtering, the return codes for pressing F5 or Ctrl+A are as expected. But if there are no entries, the return code is 139 (or -11 if you treat it as signed). Obviously this makes it impossible distinguish custom keys. It seems counter-intuitive to make the user clear the filter before using custom keys.

Is there something I am missing here, or is this a bug?

**Comment by DaveDavenport** [comment]
The bug is that it exists with custom keybinding. when `-no-custom` is set it should not exit at all.

**Comment by bcbnz** [comment]
Right. In that case I guess `-only-match` shouldn't exit either?

Would it be possible to add an option to allow custom keys to exit with `-no-custom` / `-only-match`? In my case I can get away with `-format i` as custom entries are printed as -1 so I can ignore them. An option may be useful for others though.

**Comment by DaveDavenport** [comment]
NOTE to self:

Several smaller things wrong here. selected_line is not ´updated' when no item is selected.
It can therefore have any value (UINT32_MAX or last selected value) and cannot be assumed to be used as index.

Needs fixing in menu function and dmenu.

**Comment by DaveDavenport** [comment]
This should be fixed. can you test?

**Comment by DaveDavenport** [comment]
Can you test?

**Comment by DaveDavenport** [comment]
No news, good news.
