### ISSUE TITLE
Input with < or > produce empty line

### ISSUE THREAD

**Issue by neg-serg** [DaveDavenport/rofi#334]
subj.

Try this snippet please to reproduce: $echo 'asdsdsd\n\<asdsd>\nsffd'|rofi -dmenu -yoffset -200

**Comment by DaveDavenport** [comment]
works fine here...

**Comment by DaveDavenport** [comment]
If `markup-rows`  is set, then this input fails. That options requires valid pango markup.

**Comment by neg-serg** [comment]
Thanks for reply!

Latest version from git. 
```
rofi -v
Version: 1.0.0-devel
```

Fixed, thanks
