### ISSUE TITLE
 Open in currently workspace focused output, disregarding mouse

### ISSUE THREAD

**Issue by GregorySchwartz** [DaveDavenport/rofi#335]
Similar to #81, but with multiple screens and workspaces, rofi opens in the workspace with the mouse (if the other workspace is empty) rather than the current workspace which, in my opinion, is should be the expected behavior.

**Comment by DaveDavenport** [comment]
What window manager? i3?

**Comment by GregorySchwartz** [comment]
Xmonad is where I experience this behavior.

**Comment by DaveDavenport** [comment]
I am not sure if X has a notion of 'active desktop'. Currently I search for active window, and if that does not exists I revert to pointer.

Maybe I can get it via CURRENT_DESKTOP and then via _NET_DESKTOP_VIEWPORT.. I would need to check.

**Comment by GregorySchwartz** [comment]
I'm not sure of the function, but for instance if desktop 1 is on my laptop and desktop 5 is on my external monitor, moving the mouse between the two would highlight desktop 1 then desktop 5 then desktop 1 etc. depending on where the mouse is. Opening rofi then goes to the desktop with the mouse, which makes sense as that is the highlighted one. However, when the mouse is stationary and I change workspaces with the keyboard, I can still go from desktop 1 to 5 to 1 etc., but no matter which one is highlighted (if there is an empty workspace), rofi always opens on the workspace with the mouse.

**Comment by DaveDavenport** [comment]
yes. that is the behaviour that I described above. Will try to fix.

**Comment by DaveDavenport** [comment]
Possible fix in git, that seems to work with a current i3. Can you test!

**Comment by DaveDavenport** [comment]
fixed. reopen if not worky on xnomad.

**Comment by GregorySchwartz** [comment]
Unfortunately, using rofi 1.0.1, this fix did not work. Rofi still opens in the workspace with the mouse (at least in xmonad). It also steals the focus from the monitor workspace and refocuses it on the workspace with the mouse.

**Comment by DaveDavenport** [comment]
mouse pointer is only used when all other fails (or explicitly selected).
Can you check if xnomad sets active desktop? desktop viewport? active window?
(these are all EWMH properties)

**Comment by DaveDavenport** [comment]
closing this bug, I have no xnomad.
If an xnomad is willing to get to the bottom of this bug, please make anew bugreport.
