### ISSUE TITLE
warning: implicit declaration of function

### ISSUE THREAD

**Issue by region51** [DaveDavenport/rofi#336]
latest git snapshot
```
source/textbox.c:68:9: warning: implicit declaration of function 'rofi_view_queue_redraw' [-Wimplicit-function-declaration]
         rofi_view_queue_redraw ( );
         ^
```
Any ideas?

**Comment by region51** [comment]
PS. Also

`source/x11-event-source.c:49:1: warning: missing initializer for field 'closure_callback' of 'GSourceFuncs {aka struct _GSourceFuncs}' [-Wmissing-field-initializers]
 };
 ^`

**Comment by DaveDavenport** [comment]
lol half an hour after merging in the branch.

1st: I know. was still on my todo.
2nd: hard to fix, given 'closure_callback' is an undocumented field (thanks Glib) [link](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#GSourceFuncs)
