### ISSUE TITLE
auto merge xdefaults

### ISSUE THREAD

**Issue by fx3O2** [DaveDavenport/rofi#337]
Using `urxvt` you can choose to write the config within `.Xdefaults` file in the home directory. With rofi I've to manually merge the `.Xresources` or `.Xdefaults` file first with `xrdb -merge .Xresources`. I would be much happier if rofi would just merge the defaults file whenever I change something. :kissing_cat:

**Comment by DaveDavenport** [comment]
You can set in `~/.config/rofi/config` (In Xresources format).

I am not sure 'autoloading' Xdefaults/Xresources is that common behavior.

**Comment by fx3O2** [comment]
Oh, I didn't know, docs don't mention that file. :+1:

**Comment by DaveDavenport** [comment]
Yeah, it is not  yet in a release. Will be in the next one.
