### ISSUE TITLE
transparency shows desktop

### ISSUE THREAD

**Issue by binaryplease** [DaveDavenport/rofi#338]
Hi,

I can't get the transparency to work right.
The background is transparent, as expected but the windows below rofi are not shown, only the wallpapaper. This is a screenshot of rofi opened over other opened windows:

![2016-02-12-001255_1915x1199_scrot](https://cloud.githubusercontent.com/assets/1719781/12995222/1068ab8e-d126-11e5-81c9-efbeb14ecece.png)

Expected behaviour would be that you can see the underlying windows.

I'm using i3 as wm and compton.
Linux arch, everything updated.

.Xressources
````
rofi.modi: run,ssh,window
rofi.fullscreen: true
rofi.lines: 3
rofi.terminal: urxvt
rofi.padding: 400
rofi.eh: 2
````

command to run rofi (.i3/config)
````
exec rofi -key-run SuperL-p -lines 7 -eh 3 -opacity 80 -bw 0 -bc "$base0D" -bg "$base00" -hlbg "$base00" -hlfg "$base0D" -fg "$base07" 

exec rofi -key-edit SuperL-Shift-p -modi "edit:/home/binaryplease/.local/bin/rofi-fmenu,run,ssh,window" -lines 7 -eh 3 -opacity 80 -bw 0 -bc "$base00" -bg "$base00" -hlbg "$base00" -hlfg "$base0D" -fg "$base07" 
````

**Comment by DaveDavenport** [comment]
This is how i3 handles full screen windows.  You can replicate this with a transparent terminal.

There is a dirty work-around, use fake-transparency. It will take a screenshot, then render rofi on top of that.

**Comment by psamim** [comment]
Actually I liked to see the desktop background instead if the windows and now after Rofi 1.0 it seems that Rofi correctly shoes the underlying windows instead of the desktop background. Is there a way to bring back the old way and make Rofi show the desktop when in fullscreen mode?

**Comment by DaveDavenport** [comment]
Nothing changed there.. If you do not use 'fake transparency'  the old behavior should be unchanged.

**Comment by DaveDavenport** [comment]
Please file a (new) bug report, might be option to add.

**Comment by psamim** [comment]
I created #390
