### ISSUE TITLE
pass arguments to -dmenu

### ISSUE THREAD

**Issue by fx3O2** [DaveDavenport/rofi#340]
on Arch x86_64
i3wm 4.11
```
rofi -v   
Version: 0.15.12
```

```
j4-dmenu-desktop --dmenu="rofi -dmenu -p 'run: '"
```

I would like to pass `-i` to dmenu mode of rofi, so dmenu is using case-insensitivity mode. Without I can't just type `atom` to open `Atom` (editor).

**Comment by DaveDavenport** [comment]
What is the question?

**Comment by carnager** [comment]
maybe he confused the issue tracker with his blog? :smile:

**Comment by fx3O2** [comment]
Seriously?

The question is, how do I pass the `i` argument to dmenu?

**Comment by fx3O2** [comment]
Just added the `fuzzy` option. Seems to work now, kinda stupid but... :see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by DaveDavenport** [comment]
In the line you paste:
```
j4-dmenu-desktop --dmenu="rofi -dmenu -p 'run: '"
```

You are already passing an argument to dmenu mode, namely: ```-p 'run'```.
Try to understand what you are doing (did you just copy paste this command from somewhere without understanding?), if you did this should have been clear to you. So to pass -i, you do:

```
j4-dmenu-desktop --dmenu="rofi -dmenu -p 'run: ' -i"
``

You somehow did manage to pass the `-fuzzy` option, so why couldn't you pass `-i`?
