### ISSUE TITLE
history in drun mode

### ISSUE THREAD

**Issue by m3l7** [DaveDavenport/rofi#343]
hello,
is history available in drun mode?
it seems that the list of entries is static and doesn't change with utilization.

**Comment by DaveDavenport** [comment]
Yes, this is missing.

Will add

**Comment by DaveDavenport** [comment]
Please test.

**Comment by m3l7** [comment]
yeah, it's working, thank you!

a quick off topic question: I'm using combi mode with window,drun.
the windows list is correctly placed first when I start rofi, but when I start typing, drun gets always the highest priority.
Is it the normal behaviour? if so, is there a way to always have the window list before the rest?

**Comment by DaveDavenport** [comment]
Question does not belong here (I need to setup a 'question' form (but look at levenshtein sort not being enabled)).

Thanks for testing.

**Comment by DaveDavenport** [comment]
at myself: update Changelog then  close issue.
