### ISSUE TITLE
.x_offset and .y_offset

### ISSUE THREAD

**Issue by 90d0fm15ch13f** [DaveDavenport/rofi#344]
So I've been playing around with rofi and I figured I'd like to move it around the screen, but the only method of doing so I can find is the -location flag. I feel like you should be able to do this with the .x_offset and .y_offset values in the config but those don't seem to do anything.

**Comment by DaveDavenport** [comment]
I am not sure what is not working?

Location defines the anchor point, then xoffset and yoffset the offset to that point.
For me this work.

```
$ ./rofi -h | grep off
	-yoffset [number]                       Y-offset relative to location
	-xoffset [number]                       X-offset relative to location
```

doing this:
```
rofi -location 1 -show run -no-fullscreen -padding 10 -lines 10 -yoffset 200 -xoffset 200
```

Puts it at 200x200.

**Comment by DaveDavenport** [comment]
https://github.com/DaveDavenport/rofi/wiki/WindowPosition

**Comment by 90d0fm15ch13f** [comment]
Yup, that works entirely. My bad.
