### ISSUE TITLE
Rofi hangs when ending command with underscore

### ISSUE THREAD

**Issue by ghost** [DaveDavenport/rofi#345]
Tried it with the latest version

Steps to recreate:
- run  ```rofi -show run```
- type any command/word directly followed by an underscore

I can still click stuff behind it so it may just be grabbing keyboard input and holding it

Apolagies for the (really) crappy gif,Just using it as a visual aid
![output](https://cloud.githubusercontent.com/assets/17088473/13147983/36916e90-d653-11e5-8d16-4b11a3933540.gif)

**Comment by bendem** [comment]
Can confirm, only solution is to <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>f\<x></kbd> to kill rofi from another session

**Comment by DaveDavenport** [comment]
Yep. broke in move to glib.

**Comment by DaveDavenport** [comment]
Can fix this after SardemFF7 is done with xcb move.

**Comment by DaveDavenport** [comment]
Please check if latest merge fixes this.
