### ISSUE TITLE
wrong resolution?

### ISSUE THREAD

**Issue by valdoonicanlives** [DaveDavenport/rofi#346]
When I start rofi  the font is tiny and unreadable
I am running rofi in i3 wm
the resolution of my screen is 96
I read the man page

**Comment by carnager** [comment]
but you did not provide your config

**Comment by DaveDavenport** [comment]
Can you provide a dump: ` rofi -dump-xresources` and the version of rofi `rofi -v`.
Possible include a screenshot?

**Comment by valdoonicanlives** [comment]
link to screenshot  http://i.imgur.com/YbMkC7u.jpg


! Rofi Version: 0.15.12
! Enabled modi
rofi.modi:                           window,run,ssh
! Window opacity
rofi.opacity:                        100
! Window width
rofi.width:                          50
! Number of lines
rofi.lines:                          15
! Number of columns
rofi.columns:                        1
! Font to use
rofi.font:                           xft:DejaVu Sans Mono:pixelsize=14
! Foreground color
rofi.fg:                             #BBDAE2
! Background color
rofi.bg:                             rgb:10/10/10
! Foreground color for active row
rofi.fg-active:                      #1C90E1
! Foreground color for urgent row
rofi.fg-urgent:                      #DC322F
! Foreground color for highlighted active row
rofi.hlfg-active:                    #FDF6E3
! Foreground color for highlighted urgent row
rofi.hlfg-urgent:                    #FDF6E3
! Background color for active row
rofi.bg-active:                      #FDF6E3
! Background color for urgent row
rofi.bg-urgent:                      #FDF6E3
! Background color for highlighted active row
rofi.hlbg-active:                    #268BD2
! Background color for highlighted urgent row
rofi.hlbg-urgent:                    #DC322F
! Background color for alternating row
rofi.bgalt:                          rgb:10/10/10
! Foreground color for highlighted row
rofi.hlfg:                           #EEE8D5
! Background color for highlighted row
rofi.hlbg:                           #586E75
! Border color
rofi.bc:                             #002B36
! Use extended color scheme
rofi.color-enabled:                  false
! Color scheme for normal row
rofi.color-normal:                   #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
! Color scheme for urgent row
rofi.color-urgent:                   #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
! Color scheme for active row
rofi.color-active:                   #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
! Color scheme window
rofi.color-window:                   #fdf6e3,#002b36
! Border width
rofi.bw:                             1
! Location on screen
rofi.location:                       0
! Padding
rofi.padding:                        5
! Y-offset relative to location
rofi.yoffset:                        0
! X-offset relative to location
rofi.xoffset:                        0
! Always show number of lines
rofi.fixed-num-lines:                false
! Terminal to use
rofi.terminal:                       rofi-sensible-terminal
! Ssh client to use
rofi.ssh-client:                     ssh
! Ssh command to execute
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
! Run command to execute
rofi.run-command:                    {cmd}
! Command to get extra run targets
rofi.run-list-command:               
! Run command to execute that runs in shell
rofi.run-shell-command:              {terminal} -e {cmd}
! Disable history in run/ssh
rofi.disable-history:                false
! Use levenshtein sorting
rofi.levenshtein-sort:               false
! Set case-sensitivity
rofi.case-sensitive:                 false
! Enable sidebar-mode
rofi.sidebar-mode:                   false
! Set lazy filter limit
rofi.lazy-filter-limit:              15000
! Row height (in chars)
rofi.eh:                             1
! Enable auto select mode
rofi.auto-select:                    false
! Parse hosts file for ssh mode
rofi.parse-hosts:                    false
! Parse known_hosts file for ssh mode
rofi.parse-known-hosts:              true
! Set the modi to combine in combi mode
rofi.combi-modi:                     window,run
! Do a more fuzzy matching
rofi.fuzzy:                          false
! Use glob matching
rofi.glob:                           false
! Use regex matching
rofi.regex:                          false
! Tokenize input string
rofi.tokenize:                       true
! Monitor id to show on
rofi.m:                              -1
! Margin between rows
rofi.line-margin:                    2
! Pre-set filter
rofi.filter:                         
! Separator style (none, dash, solid)
rofi.separator-style:                dash
! Hide scroll-bar
rofi.hide-scrollbar:                 false
! Show markup
rofi.markup-rows:                    false
! Fullscreen
rofi.fullscreen:                     false
! Fake transparency
rofi.fake-transparency:              false
! DPI (I changed this because I thought it might help but it didn't it was -1)
rofi.dpi:                            96
! Threads to use for string matching
rofi.threads:                        1
! Scrollbar width
rofi.scrollbar-width:                8
! Pidfile location
rofi.pid:                            /run/user/1000/rofi.pid
! Keybinding
rofi.kb-primary-paste:               Control+Shift+v,Shift+Insert
! Keybinding
rofi.kb-secondary-paste:             Control+v,Insert
! Keybinding
rofi.kb-clear-line:                  Control+u
! Keybinding
rofi.kb-move-front:                  Control+a
! Keybinding
rofi.kb-move-end:                    Control+e
! Keybinding
rofi.kb-move-word-back:              Alt+b
! Keybinding
rofi.kb-move-word-forward:           Alt+f
! Keybinding
rofi.kb-move-char-back:              Left,Control+b
! Keybinding
rofi.kb-move-char-forward:           Right,Control+f
! Keybinding
rofi.kb-remove-word-back:            Control+Alt+h
! Keybinding
rofi.kb-remove-word-forward:         Control+Alt+d
! Keybinding
rofi.kb-remove-char-forward:         Delete,Control+d
! Keybinding
rofi.kb-remove-char-back:            BackSpace,Control+h
! Keybinding
rofi.kb-accept-entry:                Control+j,Control+m,Return,KP_Enter
! Keybinding
rofi.kb-accept-custom:               Control+Return
! Keybinding
rofi.kb-accept-entry-continue:       Shift+Return
! Keybinding
rofi.kb-mode-next:                   Shift+Right,Control+Tab
! Keybinding
rofi.kb-mode-previous:               Shift+Left,Control+Shift+Tab
! Keybinding
rofi.kb-toggle-case-sensitivity:     grave,dead_grave
! Keybinding
rofi.kb-delete-entry:                Shift+Delete
! Keybinding
rofi.kb-row-left:                    Control+Page_Up
! Keybinding
rofi.kb-row-right:                   Control+Page_Down
! Keybinding
rofi.kb-row-up:                      Up,Control+p,Shift+Tab
! Keybinding
rofi.kb-row-down:                    Down,Control+n
! Keybinding
rofi.kb-row-tab:                     Tab
! Keybinding
rofi.kb-page-prev:                   Page_Up
! Keybinding
rofi.kb-page-next:                   Page_Down
! Keybinding
rofi.kb-row-first:                   Home,KP_Home
! Keybinding
rofi.kb-row-last:                    End,KP_End
! Keybinding
rofi.kb-row-select:                  Control+space
! Keybinding
rofi.kb-cancel:                      Escape,Control+bracketleft
! Keybinding
rofi.kb-custom-1:                    Alt+1
! Keybinding
rofi.kb-custom-2:                    Alt+2
! Keybinding
rofi.kb-custom-3:                    Alt+3
! Keybinding
rofi.kb-custom-4:                    Alt+4
! Keybinding
rofi.kb-custom-5:                    Alt+5
! Keybinding
rofi.kb-custom-6:                    Alt+6
! Keybinding
rofi.kb-custom-7:                    Alt+7
! Keybinding
rofi.kb-custom-8:                    Alt+8
! Keybinding
rofi.kb-custom-9:                    Alt+9
! Keybinding
rofi.kb-custom-10:                   Alt+0
! Keybinding
rofi.kb-custom-11:                   Alt+Shift+1
! Keybinding
rofi.kb-custom-12:                   Alt+Shift+2
! Keybinding
rofi.kb-custom-13:                   Alt+Shift+3
! Keybinding
rofi.kb-custom-14:                   Alt+Shift+4
! Keybinding
rofi.kb-custom-15:                   Alt+Shift+5
! Keybinding
rofi.kb-custom-16:                   Alt+Shift+6
! Keybinding
rofi.kb-custom-18:                   Alt+Shift+8
! Keybinding
rofi.kb-custom-17:                   Alt+Shift+7
! Keybinding
rofi.kb-custom-19:                   Alt+Shift+9
! Keybinding
rofi.kb-screenshot:                  Alt+Shift+S
! Keybinding
rofi.kb-toggle-sort:                 Alt+grave
! Keybinding
rofi.key-window:                     
! Keybinding
rofi.key-run:                        
! Keybinding
rofi.key-ssh:                        
-----------------------------
On Sat, Feb 20, 2016 at 02:42:35AM -0800, Dave Davenport wrote:
>Can you provide a dump: ` rofi -dump-xresources` and the version of rofi `rofi -v`.
>Possible include a screenshot?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DaveDavenport/rofi/issues/346#issuecomment-186566999

-- 
•*¨*•.¸¸❤ Elwoode ❤¸¸.•*¨*•

**Comment by DaveDavenport** [comment]
This syntax is deprecated, rofi uses pango now:

```
rofi.font: xft:DejaVu Sans Mono:pixelsize=14
```
try:
```
rofi.font:  DejaVus Sans Mono 14
```

**Comment by valdoonicanlives** [comment]
I didn't actually set any font for rofi specifically, it seems to have picked up a setting in .Xresources that I
had for all terminals to use:
! these settings are supposed to set font for all terminals
*fontName: DejaVu Sans Mono:pixelsize=14
*faceName: DejaVu Sans Mono:pixelsize=14
*font: xft:DejaVu Sans Mono:pixelsize=14
I will remover these then, thanks for the help
