### ISSUE TITLE
Compile issue with commit d99111c

### ISSUE THREAD

**Issue by Narrat** [DaveDavenport/rofi#351]
With commit https://github.com/DaveDavenport/rofi/commit/d99111c73b29ff3b047e911fb02c82e3e2dc8bea compiling fails with the following error message:

>make  all-am
make[1]: Entering directory '/home/omnius/Builds/AUR/rofi-git/src/rofi'
  CC       config/rofi-config.o
config/config.c:53:5: error: unknown field 'color_enabled' specified in initializer
     .color_enabled = FALSE,
     ^
config/config.c:54:22: warning: initialized field overwritten [-Woverride-init]
     .color_normal  = "#fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5",
                      ^
config/config.c:54:22: note: (near initialization for 'config.color_normal')
config/config.c:60:5: error: unknown field 'menu_bg' specified in initializer
     .menu_bg           = "#FDF6E3",
     ^
config/config.c:62:5: error: unknown field 'menu_bc' specified in initializer
     .menu_bc           = "#002B36",
     ^
config/config.c:64:5: error: unknown field 'menu_fg' specified in initializer
     .menu_fg           = "#002B36",
     ^
config/config.c:66:5: error: unknown field 'menu_fg_urgent' specified in initializer
     .menu_fg_urgent    = "#DC322F",
     ^
config/config.c:68:5: error: unknown field 'menu_fg_active' specified in initializer
     .menu_fg_active = "#268BD2",
     ^
config/config.c:69:5: error: unknown field 'menu_bg_urgent' specified in initializer
     .menu_bg_urgent = "#FDF6E3",
     ^
config/config.c:70:5: error: unknown field 'menu_bg_active' specified in initializer
     .menu_bg_active = "#FDF6E3",
     ^
config/config.c:70:23: error: incompatible types when initializing type 'enum _WindowLocation' using type 'char *'
     .menu_bg_active = "#FDF6E3",
                       ^
config/config.c:72:5: error: unknown field 'menu_bg_alt' specified in initializer
     .menu_bg_alt       = NULL,                                     //"#EEE8D5",
     ^
config/config.c:72:26: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_bg_alt       = NULL,                                     //"#EEE8D5",
                          ^
config/config.c:72:26: note: (near initialization for 'config.padding')
config/config.c:74:5: error: unknown field 'menu_hlfg' specified in initializer
     .menu_hlfg        = "#EEE8D5",
     ^
config/config.c:74:25: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_hlfg        = "#EEE8D5",
                         ^
config/config.c:74:25: note: (near initialization for 'config.y_offset')
config/config.c:75:5: error: unknown field 'menu_hlfg_urgent' specified in initializer
     .menu_hlfg_urgent = "#FDF6E3",
     ^
config/config.c:75:25: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_hlfg_urgent = "#FDF6E3",
                         ^
config/config.c:75:25: note: (near initialization for 'config.x_offset')
config/config.c:76:5: error: unknown field 'menu_hlfg_active' specified in initializer
     .menu_hlfg_active = "#FDF6E3",
     ^
config/config.c:76:25: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_hlfg_active = "#FDF6E3",
                         ^
config/config.c:76:25: note: (near initialization for 'config.fixed_num_lines')
config/config.c:78:5: error: unknown field 'menu_hlbg' specified in initializer
     .menu_hlbg        = "#586E75",
     ^
config/config.c:78:25: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_hlbg        = "#586E75",
                         ^
config/config.c:78:25: note: (near initialization for 'config.disable_history')
config/config.c:79:5: error: unknown field 'menu_hlbg_urgent' specified in initializer
     .menu_hlbg_urgent = "#DC322F",
     ^
config/config.c:79:25: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_hlbg_urgent = "#DC322F",
                         ^
config/config.c:79:25: note: (near initialization for 'config.levenshtein_sort')
config/config.c:80:5: error: unknown field 'menu_hlbg_active' specified in initializer
     .menu_hlbg_active = "#268BD2",
     ^
config/config.c:80:25: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     .menu_hlbg_active = "#268BD2",
                         ^
config/config.c:80:25: note: (near initialization for 'config.case_sensitive')
config/config.c:82:26: warning: initialized field overwritten [-Woverride-init]
     .terminal_emulator = "rofi-sensible-terminal",
                          ^
config/config.c:82:26: note: (near initialization for 'config.terminal_emulator')
config/config.c:83:26: warning: initialized field overwritten [-Woverride-init]
     .ssh_client        = "ssh",
                          ^
config/config.c:83:26: note: (near initialization for 'config.ssh_client')
config/config.c:85:26: warning: initialized field overwritten [-Woverride-init]
     .ssh_command       = "{terminal} -e {ssh-client} {host}",
                          ^
config/config.c:85:26: note: (near initialization for 'config.ssh_command')
config/config.c:87:26: warning: initialized field overwritten [-Woverride-init]
     .run_command       = "{cmd}",
                          ^
config/config.c:87:26: note: (near initialization for 'config.run_command')
config/config.c:89:26: warning: initialized field overwritten [-Woverride-init]
     .run_list_command  = "",
                          ^
config/config.c:89:26: note: (near initialization for 'config.run_list_command')
config/config.c:91:26: warning: initialized field overwritten [-Woverride-init]
     .run_shell_command = "{terminal} -e {cmd}",
                          ^
config/config.c:91:26: note: (near initialization for 'config.run_shell_command')
config/config.c:105:66: warning: initialized field overwritten [-Woverride-init]
     .padding           =                                         5,
                                                                  ^
config/config.c:105:66: note: (near initialization for 'config.padding')
config/config.c:107:66: warning: initialized field overwritten [-Woverride-init]
     .y_offset          =                                         0,
                                                                  ^
config/config.c:107:66: note: (near initialization for 'config.y_offset')
config/config.c:109:66: warning: initialized field overwritten [-Woverride-init]
     .x_offset          =                                         0,
                                                                  ^
config/config.c:109:66: note: (near initialization for 'config.x_offset')
In file included from /usr/lib/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from config/config.c:29:
/usr/include/glib-2.0/glib/gmacros.h:230:15: warning: initialized field overwritten [-Woverride-init]
 #define FALSE (0)
               ^
config/config.c:111:26: note: in expansion of macro 'FALSE'
     .fixed_num_lines   = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: note: (near initialization for 'config.fixed_num_lines')
 #define FALSE (0)
               ^
config/config.c:111:26: note: in expansion of macro 'FALSE'
     .fixed_num_lines   = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: warning: initialized field overwritten [-Woverride-init]
 #define FALSE (0)
               ^
config/config.c:113:26: note: in expansion of macro 'FALSE'
     .disable_history   = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: note: (near initialization for 'config.disable_history')
 #define FALSE (0)
               ^
config/config.c:113:26: note: in expansion of macro 'FALSE'
     .disable_history   = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: warning: initialized field overwritten [-Woverride-init]
 #define FALSE (0)
               ^
config/config.c:115:26: note: in expansion of macro 'FALSE'
     .levenshtein_sort  = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: note: (near initialization for 'config.levenshtein_sort')
 #define FALSE (0)
               ^
config/config.c:115:26: note: in expansion of macro 'FALSE'
     .levenshtein_sort  = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: warning: initialized field overwritten [-Woverride-init]
 #define FALSE (0)
               ^
config/config.c:117:26: note: in expansion of macro 'FALSE'
     .case_sensitive    = FALSE,
                          ^
/usr/include/glib-2.0/glib/gmacros.h:230:15: note: (near initialization for 'config.case_sensitive')
 #define FALSE (0)
               ^
config/config.c:117:26: note: in expansion of macro 'FALSE'
     .case_sensitive    = FALSE,
                          ^
make[1]: *** [config/rofi-config.o] Error 1
Makefile:1264: recipe for target 'config/rofi-config.o' failed
make[1]: Leaving directory '/home/omnius/Builds/AUR/rofi-git/src/rofi'
make: *** [all] Error 2
Makefile:799: recipe for target 'all' failed

**Comment by DaveDavenport** [comment]
There is a weird config file copy in the build system. Taking a clean checkout will fix it, or remove config/config.c in the build directory . (this should have been overwritten because it is older then original file.)

I will remove this from the build system.

**Comment by Narrat** [comment]
Wow, that was fast :D
Thanks for the intel and resolution
