### ISSUE TITLE
[request] Using dmenu with combi ?

### ISSUE THREAD

**Issue by Sigzegv** [DaveDavenport/rofi#356]
## Version
Version: 1.0.0-devel

Is it possible to combine a custom dmenu in combi view to use it side by side with "run", "ssh" and other base modes ? (the main goal is to use one keyboard shortcut and one search window with everything.

**Comment by DaveDavenport** [comment]
DMenu won't work. 

There is a 'script' mode where you can use custom scripts.
See: https://github.com/carnager/rofi-scripts/tree/master/mode-scripts

then you can do:
```
rofi -combi-modi "run,window,fb:~/file_browser.sh" -show combi
```

**Comment by DaveDavenport** [comment]
Is this sufficient for you?

**Comment by Sigzegv** [comment]
that works perfectly, I didn't add any idea that could be done that way, thnx for your help.
