### ISSUE TITLE
rofi -show run segfaults

### ISSUE THREAD

**Issue by einalex** [DaveDavenport/rofi#357]
## Version

Output of `rofi -v`
Version: 1.0.0-devel
used the PKGBUILD that was created for the other segfault bug involving DWM

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
https://gist.github.com/einalex/81fee0f171b2479909d9

## Steps to reproduce
environment: arch linux, i3-gaps, urxvtc, zsh

* Step 1
rofi -show run

## What behaviour you see

* - zsh: segmentation fault (core dumped)  rofi -show run

## What behaviour you expect to see

* - rofi running

dump:

           PID: 28688 (rofi)
           UID: 1000 (einalex)
           GID: 1000 (einalex)
        Signal: 11 (SEGV)
     Timestamp: Sa 2016-03-12 13:43:52 CET (1min 30s ago)
  Command Line: rofi -show run
    Executable: /usr/bin/rofi
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (einalex)
       Boot ID: b6be5f99e7274f098bbc9635cc03f0af
    Machine ID: a0afbd0256cf4d41a86bb73b027dd03f
      Hostname: imtrey.lan.mayanna.org
      Coredump: /var/lib/systemd/coredump/core.rofi.1000.b6be5f99e7274f098bbc9635cc03f0af.28688.1457786632000000000000.lz4
       Message: Process 28688 (rofi) of user 1000 dumped core.
                
                Stack trace of thread 28688:
                #0  0x00007fe56b3a6646 strlen (libc.so.6)
                #1  0x000000000041727b _window_mode_load_data (rofi)
                #2  0x0000000000417427 window_mode_init (rofi)
                #3  0x000000000040c747 mode_init (rofi)
                #4  0x0000000000408ec1 startup (rofi)
                #5  0x00007fe56d6dac3a g_main_context_dispatch (libglib-2.0.so.0)
                #6  0x00007fe56d6dafe0 n/a (libglib-2.0.so.0)
                #7  0x00007fe56d6db302 g_main_loop_run (libglib-2.0.so.0)
                #8  0x0000000000407f53 main (rofi)
                #9  0x00007fe56b348710 __libc_start_main (libc.so.6)
                #10 0x00000000004084f9 _start (rofi)
                
                Stack trace of thread 28689:
                #0  0x00007fe56b406c3d poll (libc.so.6)
                #1  0x00007fe56d6daf7c n/a (libglib-2.0.so.0)
                #2  0x00007fe56d6db08c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe56d6db0c9 n/a (libglib-2.0.so.0)
                #4  0x00007fe56d701795 n/a (libglib-2.0.so.0)
                #5  0x00007fe56aea2424 start_thread (libpthread.so.0)
                #6  0x00007fe56b40fcbd __clone (libc.so.6)

GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/rofi...(no debugging symbols found)...done.
[New LWP 28688]
[New LWP 28689]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `rofi -show run'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe56b3a6646 in strlen () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fe56dbac880 (LWP 28688))]

**Comment by einalex** [comment]
fixed now in HEAD. thanks for the quick reaction!

**Comment by DaveDavenport** [comment]
thx for testing.!
