### ISSUE TITLE
rofi.mouse=-3 does not display a window

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#358]
As stated in https://github.com/DaveDavenport/rofi/commit/f4f2e3d1294cfb470e9c8a51b72fc5aa3f47c8bd#commitcomment-16668313:

`rofi.mouse = -3` does not work for me:nothing gets displayed, but input is redirected.

This happens with a single monitor/display (via xrandr) or two.

It seems like the window gets displayed off-screen, but I cannot manage to get it displayed.

I am using awesomeWM.

rofi 545c423.

**Comment by DaveDavenport** [comment]
Can you pastebin your config?

**Comment by bendem** [comment]
You mean `s/mouse/monitor/` right?
I have the same problem, rofi works but it's not drawn (just a small black box on the top left of my screen.

Here is [`rofi -dump-xresources`](https://gist.github.com/bendem/f2a686d058559595a3d2), I'm running `rofi -monitor -3 -show drun -modi drun`.

**Comment by DaveDavenport** [comment]
Thanks, I can reproduce it now.

**Comment by DaveDavenport** [comment]
Does passing `-width -30` fix it for you?

**Comment by bendem** [comment]
Yes, it does

**Comment by DaveDavenport** [comment]
made a commit, can you test if this helps?

**Comment by bendem** [comment]
It helps, but the rofi windows is misplaced (like it's 480px on the right of my mouse).

**Comment by DaveDavenport** [comment]
Add `-location 1`. I should probably enforce this at -3.

**Comment by bendem** [comment]
Yep, I get the expected behavior now.

**Comment by blueyed** [comment]
Works for me now, too.  Thanks!

Closing this issue.

**Comment by DaveDavenport** [comment]
needs a config check.
