### ISSUE TITLE
changing -kb-accept-entry-continue hotkey does not work

### ISSUE THREAD

**Issue by carnager** [DaveDavenport/rofi#359]
## Version 

1.0.0-devel

## Configuration

https://gist.github.com/carnager/222b6b660e9689f8b708

## Steps to reproduce

`echo -e "1\n2\n3" | rofi -kb-accept-entry-continue "Control+o" -dmenu`
hit Control-o

## What behaviour you see

rofi selects line and exits

## What behaviour you expect to see

rofi should advance to next line, keeping last selection active

**Comment by sardemff7** [comment]
Merged `accept-entry-continue` as `accept-custom` for dmenu mode in 20c9abf0a2ef3072453b92db71ad259fd008e27a.
