### ISSUE TITLE
autocomplete not working (in i3)

### ISSUE THREAD

**Issue by tomster** [DaveDavenport/rofi#360]
## Version

Output of `rofi -v`

Version: 0.15.11

## Configuration

https://gist.github.com/tomster/b5b04a4808b0d663b3a5

additionally, i have configured i3 as follows:

``bindsym $mod+d exec --no-startup-id i3-dmenu-desktop --dmenu='rofi -dmenu'``

## Steps to reproduce

* Launch rofi (either using the above keybinding or simply via `rofi -show run`
* notice a list of installed application, i.e. the string `Chromium`
* start typing `c`, `h`, `r`...

## What behaviour you see

* the list of matches immediately reduces to an empty list

## What behaviour you expect to see

* i expected the list to narrow down as i type

rofi works fine as long as i select the entries by stepping through the list with the cursor keys but autocomplete is entirely broken.

any ideas? thanks for any hints!

p.s. i'm running PC-BSD with i3

**Comment by sardemff7** [comment]
Can you reproduce that with current master (cdd9f97072cc8023b47f71c7075dc1cf181c2f1e)?

Is that really i3-specific as your title suggest? Did you test in a bare X env with just xterm?

**Comment by DaveDavenport** [comment]
guess I should make a pc-bsd VM to test.

**Comment by tomster** [comment]
Let me know, if I can help, perhaps provide logging output etc.

**Comment by sardemff7** [comment]
It seems to have been fixed in the commit 611c2c4302f6fbe590bef639a4cfd2ed50cbeba7. I tried cherry-picking this commit on top of 0.15.11 and it worked.

There will be a release soon, and in the meantime you can backport the patch if needed.
