### ISSUE TITLE
Shortcut keys don't work with keyboard layouts other than `us`

### ISSUE THREAD

**Issue by d125q** [DaveDavenport/rofi#362]
## Version

Output of `rofi -v`
```
Version: 1.0.0-devel
Git:     86c8934
```

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))

https://gist.github.com/d125q/2fc72cd4fd0ec77a6eaa

```
   System Locale: LANG=en_US.utf8
       VC Keymap: us-acentos
      X11 Layout: us,mk
       X11 Model: pc105
     X11 Options: grp:win_space_toggle
```

## Steps to reproduce

* Change keyboard layout to `mk`;
* Open Rofi.

## What behaviour you see

* Shortcut keys don't work (e.g., can't use Escape to close Rofi).

## What behaviour you expect to see

* Shortcut keys should be working.

**Comment by d125q** [comment]
@sardemff7 Note that Ctrl-based modifiers still don't work, i.e., I can't use Ctrl+W to remove word, even though I have `rofi.kb-remove-word-back: Control+Alt+h,Control+w` in my `.Xresources`.

**Comment by sardemff7** [comment]
It works here. However, the `mk` layout has no `W` key, so it just cannot work.

What are you testing exactly?

**Comment by d125q** [comment]
Well, I assumed shortcuts would be independent of keyboard layout.  Apparently this is not the case.
