### ISSUE TITLE
rofi  fails with mem access error while qiv (picture viewer) is running

### ISSUE THREAD

**Issue by TheMuspilli** [DaveDavenport/rofi#363]
## Version

[folo] ~ $ rofi -version
Version: 1.0.0-devel

## Configuration

[ edit: the link did not show up, now it should]
https://gist.github.com/TheMuspilli/76248bf0a87a1620ae34

Hhm, the dump commands shows only the vanilla config, but that is ok, because I explicitly also used the parameter '--no-config' when investigating the issue. 

## Steps to reproduce

* use the picture viewer qiv
* try to start rofi
* close down qiv
* try again to start rofi

## What behaviour you see?

* while qiv is running, rofi upon startup causes a memory access error and memory dump
* as soon as qiv is terminated, the same rofi starts just fine

## What behaviour you expect to see

* I would expect that rofi starts also when qiv is running

## The whole story:

I encounter a strange phenomenon when using rofi. But first things first: I am a new to rofi, but I tried to make this report "waterproof". Therefore please excuse my verbosity possibly combined with lack of information ...

Everytime I use qiv (a picture viewer) to show a cheat sheet on the screen, rofi refuses to start and instead there is a memory access error. As soon as I close down qiv and the cheat sheet (a normal jpg or png), rofi is happy again and starts fine. Normally I use of course hotkeys, but to record what is happening I used the same commands in the console. Hope the markup works as advertised ;-)

The actors:

```
✓ [folo] ~ $ uname -mrv
4.4.5-1-MANJARO #1 SMP PREEMPT Thu Mar 10 20:58:34 UTC 2016 x86_64

✓ [folo] ~ $ rofi -version
Version: 1.0.0-devel

✓ [folo] ~ $ qiv --version
qiv (Quick Image Viewer) v2.3.1
```

The movie:

```
✓ [folo] ~ $ # first a normal start, just as my hotkey normally starts rofi

✓ [folo] ~ $ rofi -show combi -config /home/folo/.config/rofi/rofi.conf

✓ folo] ~ $ # the rofi window showed up and everything was fine

✓ [folo] ~ $ # now I start qiv

✓ [folo] ~ $ qiv -iR ~/Bilder/any.jpg &
[1] 10822

✓ [folo] ~ $ # qiv opened window and the picture is shown

✓ [folo] ~ $ rofi -show combi -config /home/folo/.config/rofi/rofi.conf
Speicherzugriffsfehler (Speicherabzug geschrieben)

✗ [folo] ~ $ # "memory access error (memory dump written)"

✗ [folo] ~ $ # I close the qiv window

✗ [folo] ~ $ rofi -show combi -config /home/folo/.config/rofi/rofi.conf
[1]+  Fertig                  qiv -iR ~/Bilder/any.jpg

✓ [folo] ~ $ # rofi worked just fine, I fire up qiv again

✓ [folo] ~ $ qiv -iR ~/Bilder/any.jpg &
[1] 12112

✓ [folo] ~ $ # picture is showing

✓ [folo] ~ $ rofi --no-config -show run
Speicherzugriffsfehler (Speicherabzug geschrieben)

✗ [folo] ~ $ # vanilla config rofi has problems, too. Quitting qiv ...

✗ [folo] ~ $ rofi --no-config -show run
[1]+  Fertig                  qiv -iR ~/Bilder/any.jpg

✓ [folo] ~ $ # rofi works like a charm
```

Some popcorn (sponsored by journalctl):

```
Mär 22 13:16:33 unkulunkulu kernel: rofi[11192]: segfault at 0 ip 00007f39a1bfa646 sp 00007ffdc54147b8 error 4 in libc-2.23.so[7f39a1b7c000+198000]
Mär 22 13:16:33 unkulunkulu systemd[1]: Started Process Core Dump (PID 11194/UID 0).
Mär 22 13:16:33 unkulunkulu systemd-coredump[11195]: Process 11192 (rofi) of user 1000 dumped core.
	Stack trace of thread 11192:
	#0  0x00007f39a1bfa646 strlen (libc.so.6)
	#1  0x0000000000416e3b n/a (rofi)
	#2  0x0000000000416fe7 n/a (rofi)
	#3  0x000000000040c617 n/a (rofi)
	#4  0x0000000000415e74 n/a (rofi)
	#5  0x000000000040c617 n/a (rofi)
	#6  0x0000000000408d21 n/a (rofi)
	#7  0x00007f39a3f2ec3a g_main_context_dispatch (libglib-2.0.so.0)
	#8  0x00007f39a3f2efe0 n/a (libglib-2.0.so.0)
	#9  0x00007f39a3f2f302 g_main_loop_run (libglib-2.0.so.0)
	#10 0x0000000000407df3 n/a (rofi)
	#11 0x00007f39a1b9c710 __libc_start_main (libc.so.6)
	#12 0x0000000000408359 n/a (rofi)

	Stack trace of thread 11193:
	#0  0x00007f39a1c5ac3d poll (libc.so.6)
	#1  0x00007f39a3f2ef7c n/a (libglib-2.0.so.0)
	#2  0x00007f39a3f2f08c g_main_context_iteration (libglib-2.0.so.0)
	#3  0x00007f39a3f2f0c9 n/a (libglib-2.0.so.0)
	#4  0x00007f39a3f55795 n/a (libglib-2.0.so.0)
	#5  0x00007f39a16f6424 start_thread (libpthread.so.0)
	#6  0x00007f39a1c63cbd __clone (libc.so.6)
```

The other dumps showed different thread IDs, but were apart from that identical.

This issue is in no way critical, only a bit annoying or me. When I forget to close one of my cheat sheets - or I want to keep it open - I cannot use rofi. Normally I notice when I am three of four desktops away from the qiv window that inhibits rofi ...

**Comment by DaveDavenport** [comment]
This is a weird problem. I would not expect rofi to fail on the run modi when an application is running (with window modi I this used to happen when the window title is malformed). 

Can you:

1.) Build rofi with debug symbols and get a backtrace
2.) report what git version you are running (the actual git hash). 
(rofi -v from latest git should report this? or did you build using a kind of AUR?)

**Comment by DaveDavenport** [comment]
I can reproduce.. fun!

**Comment by DaveDavenport** [comment]
and can you see if this crashes:

```
rofi -show run -modi run
```

**Comment by TheMuspilli** [comment]
My answers so far:

I thought to have installed from AUR, but rofi has actually made it into the Manjaro "community" packages. The version there was labeled with 0-15.12.1,  whereas the AUR-git version is at 0.15.12.r259.gb13bff6-1.

Now I have build from master (6693799) and the issue does no longer exist. Following your instructions from install.md I was a bit too fast and thus I discovered the debug symbol options only after the build was finished without and rofi installed.

With the new version also "rofi -show run -modi run" does not crash. But if it is of any value for you I can reinstall the old version and try there again. If not I am happy enough to bury this issue. 

Thanks alot for your help - and of course for rofi.

**Comment by DaveDavenport** [comment]
no, I had an idea what it was and I hoped that the latest git has fixed it.

So if latest git fixes it, I guess we can close it.
