### ISSUE TITLE
Rofi doesn't send SIG signals properly

### ISSUE THREAD

**Issue by kookerus** [DaveDavenport/rofi#366]
## Version

Version: Version: 0.15.12

## Configuration

[Gist](https://gist.github.com/kookerus/f6184fe7868835ad65d3)

## Steps to reproduce

* Run Rofi
* Run gnome-terminal or terminator from Rofi
*attempt to interrupt a process with SIGINT key (ctrl+c by default)

## What behaviour you see

* -Running terminator or gnome-terminal with Rofi will not send proper SIGINT signals when pressing the ctrl+c. When a process is running in the current terminal, ctrl+c prints `^C` and does nothing else. When a process ISN'T running, nothing happens.

## What behaviour you expect to see

* -When a process is running, the process is interrupted if it accepts SIGINT. When a process is not running, `^C` should be printed on the current prompt line, and a new prompt line should be started.

**Comment by DaveDavenport** [comment]
I don't follow. If I start gnome-terminal from rofi everything works fine in gnome-terminal.

Can you try to explain in more details? I might be missing something.

**Comment by kookerus** [comment]
Hm, when I start a terminal from rofi, I can't properly send SIGINT to a program. This might just be an issue with GNOME itself, so I'll try with another DE

**Comment by DaveDavenport** [comment]
What are you exactly doing (just to make sure?)

I start gnome-terminal from rofi, open f.e. htop then hit ctrl-c this works.
htop -> ctrl-z  also works.

if I start htop in gnome terminal from rofi, then hit ctrl-c it works too.

**Comment by kookerus** [comment]
I got a screenshot of what happened when I started terminator from rofi, running `sleep 5`, and trying to end it with ctrl+c doesn't work, even though SIGINT will make `sleep` stop.

In this screenshot, "^C" should've ended the process, instead it does nothing
![screenshot from 2016-03-29 23 43 57](https://cloud.githubusercontent.com/assets/8160403/14131368/79bdb8e8-f608-11e5-9d62-178f1f778240.png)

**Comment by DaveDavenport** [comment]
I have no idea what goes wrong... it a) works for me. b) I use g_spawn_async from glib to launch the application, 

Are you on linux or bsd?

**Comment by sardemff7** [comment]
Did you even try running a terminal without rofi? You should do that before anything else.

You should test other terminals too:

* Germinal (VTE-based)
* xterm (non-VTE)

That should tell us if VTE is the problem.

Also, please test a different shell.

**Comment by kookerus** [comment]
@DaveDavenport I'm using Ubuntu 14.04

@sardemff7 I did, and when launching the terminal normally, it works fine, and the issue doesn't exist. I've spent close to 40 minutes trying to get Germinal to compile, and it refuses to. However, xterm has the same problem, as does gnome-terminal. It isn't VTE. The same issue happens in bash, dash, and sh.

**Comment by DaveDavenport** [comment]
Found it, you are running rofi in daemon mode and this breaks things.

The quick fix for 0.15.12 is to use your WM to launch rofi (rofi -show run) 

In 1.0.0 daemon mode (and this bug) is gone.

**Comment by kookerus** [comment]
That definitely fixes it. Thanks for the help!

Is there any particular reason that daemon mode breaks things?

**Comment by DaveDavenport** [comment]
I made daemon mode grab sig-int to do a graceful shutdown. This grab seems to be inherited by the processed launched from g_spawn_async.
I never noticed because I never used daemon mode.

**Comment by DaveDavenport** [comment]
Thanks for reporting and helping to get to the bottom of it.

**Comment by egmontkob** [comment]
Coming here from http://askubuntu.com/questions/749870/control-c-doesnt-work-in-ubuntu-14-04.

I'm not happy with the analysis so far. First, VTE _does_ reset SIGINT's handler to its default before launching its child shell (src/pty.c `_vte_pty_reset_signal_handlers()`). Second, if it didn't then not only Ctrl+C wouldn't work but manually executing a `kill -INTR pid` wouldn't work either, which does work according to kookerus. So Rofi setting SIGINT to be ignored _cannot_ be the explanation for the buggy behavior.

I have no clue what's going on under the hood but I'd really like to get to the bottom of this. VTE should make sure that everything's okay inside its area, no matter in what environment it is started (well, within reasonabe limits, of course). It could easily be that xterm suffers from the same problem. I don't know what the problem could be, perhaps something around sessions (`setsid()`), process groups, process group leader etc., this has always been a mystery to me.

**Comment by DaveDavenport** [comment]
Interesting.  I confirmed that the problem is caused by rofi handling of the SIGINT signal..  disabling that code makes everything work as expected. 

What rofi does is set a sigprocmask blocking the signals and have a separate thread do sigwaitinfo.
It seems this mask is inherited by the launched process 
(man sigprocmask sais: A child created via fork(2) inherits a copy of its parent's signal mask;  the  signal  mask  is  preserved across execve(2).)

If xterm/gnome-terminal do not unblock sigint it might explain the behaviour? 

(confirmed this, I hacked my copy of termite to unblock the SIGINT at startup, this makes it behave as expected again.)

**Comment by egmontkob** [comment]
So, to clarify. Having a handler (default / ignore / custom function) is one thing, and blocking / unblocking is another. VTE resets the handler to their default, but does not unblock the signals. So probably they remain in blocked state. Yes, this can easily be the explanation.

**Comment by DaveDavenport** [comment]
Yes. mystery resolved.

**Comment by egmontkob** [comment]
I'd like to verify the theory. :) Could you please write a quick step-by-step guide how to reproduce the bug? I'm entirely new to Rofi. It's not even clear to me if I should run it within my regular WM, or replace it, or what... (I'm on Ubuntu Xenial beta, default Unity desktop, if that matters.)

**Comment by egmontkob** [comment]
Nevermind, I managed to reproduce it :) Note that vte-0.44 changed a few things around signal handling, and no longer suffers from this problem. Not sure if 0.42 and older branches deserve a backport of this fix.

**Comment by egmontkob** [comment]
VTE 0.44's fix: https://git.gnome.org/browse/vte/commit/?h=vte-0-44&id=171b8aa

**Comment by egmontkob** [comment]
Tried some other emulators: xterm, urxvt, konsole (kde), terminology (enlightenment), st (suckless), pterm (putty). None of them unblocks the signal. So I _think_ it's a reasonable expectation that Rofi should restore the signal states before exec'ing the emulator, rather than the emulator having to take care of it.

Thanks @kookerus and @DaveDavenport for the investigation!

**Comment by DaveDavenport** [comment]
It is no longer an issue for rofi anyway as daemon mode has been removed.

**Comment by kookerus** [comment]
Oh cool, I'm glad I could at least *kinda* help =P
