### ISSUE TITLE
Segfaulting with unicode

### ISSUE THREAD

**Issue by Phyks** [DaveDavenport/rofi#368]
## Version

% rofi -v
Version: 0.15.1

## Configuration

https://gist.github.com/Phyks/4046d801cd2b3c3fbacc6852567746cf

```
% locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=


% locale -a
C
en_US.utf8
fr_FR.utf8
POSIX
```

Using arch linux, and a system in French.

## Steps to reproduce

```
% echo -e '\xF0'|rofi -dmenu
```

## What behaviour you see

* Segfault when hitting any key after the menu opens.

```
% echo -e '\xF0'|rofi -dmenu
zsh: done                              echo -e '\xF0' | 
zsh: segmentation fault (core dumped)  rofi -dmenu
```

## What behaviour you expect to see

* working :)

Extra notes: I initially reported it to [fmenu-rofi](https://github.com/dbordak/fmenu-rofi/issues/2) as I had this issue with it, due to locale problems on my FS. Still, this is a more general issue which can affect users of rofi and not only fmenu-rofi. I remember we discussed this on IRC, but I am not sure what was the outcome, whether it was to be fixed in rofi or not. Still, I report it there so that anyone coming into this issue can find it easily, as it is not necessarily obvious that the segfault is due to locale problems.

Thanks

**Comment by DaveDavenport** [comment]
3 things:

1.) A version from a year ago?
2.) \xF0 is not valid utf-8
3.) Segfault on invalid utf-8 should be fixed in git.

**Comment by Phyks** [comment]
1. Bad copy/paste, I missed the trailing "2".

```
% rofi -v
Version: 0.15.12
```
which is the current version in Arch linux repos.

2. Ok, so I guess it is the plugin responsability to output proper UTF-8, and this could be safely closed.

Thanks!

**Comment by DaveDavenport** [comment]
I was surprised about the version :D.
