### ISSUE TITLE
Rofi crashes on key press in run mode. 

### ISSUE THREAD

**Issue by madisodr** [DaveDavenport/rofi#369]
## Version
Rofi  0.15.12

Ubuntu 14.04.4 Trusty x86_64

## Configuration

[My Rofi Configuration](https://gist.github.com/madisodr/3dd906fc650abda44cbd1bf156114e6d)

## Launch Command

I launch rofi through i3 by using "exec rofi -show run -font "pango:bitocra 8""

## Steps to reproduce

in a terminal (or using my i3 bind key) I run rofi -show run and when I try to search, rofi crashes. 

## What behavior you see

Rofi segfaults on an alphanumeric key press when I start it in run mode. I also can't switch modes while in run mode. Here is my GDB log from when I run rofi through it. Running a backtrace is a little difficult though since once rofi crashes I have to kill gdb in order to get my desktop back. 

[gdb output](http://pastebin.com/gHTbKyzs)

## What behavior you expect to see

I expected to be able to search in the run mode. If I have window mode start on default, then it works fine, I can search through open windows and it doesn't crash. But starting rofi in run mode causes a segfault. 

I am really at a loss here. It was working yesterday. The only change I had made was that I built vim from source using this guide. [Building Vim From Source](https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source )

I have rebuilt rofi from source, rebuilt vim, rebuilt i3. Nothing complains as far as dependencies go. Everything else seems to be working fine. The things I installed when I built vim doesn't raise any red flags. Looking at the gdb crash, I have a strong feeling that this isn't an error in rofi itself, granted this beautiful piece of software was working not but a day ago. Let me know if I can provide any further information.

**Comment by carnager** [comment]
that font syntax is wrong
`-font "bitocra 9"`

**Comment by DaveDavenport** [comment]
Sounds like a broken filename.

Can you test git version? there the run dialog actually convert to utf8 and back.

**Comment by DaveDavenport** [comment]
(p.s.. in the install file (https://github.com/DaveDavenport/rofi/blob/master/INSTALL.md) there is a small section on how to get a backtrace without 'blocking' the desktop.)

**Comment by sardemff7** [comment]
For our Travis build we use the future jessie-backports package, see 1e3294fa682a632cf72ff4c2f96c9c3216fc8e3e.

**Comment by madisodr** [comment]
Alright, so I did a github pull and running ./configure spit out exactly the errros that @sardemff7 's ppa addresses.  Managed to build successfully and get rofi running. Going to make sure everything else works nicely still and mess around with things. 

@DaveDavenport here is my core file if you still want it.

**Comment by DaveDavenport** [comment]
Thanks.

**Comment by madisodr** [comment]
Nah, thank you. This was bothering me so much. I love rofi, its just so useful so it not working was just bothering my work flow.
