### ISSUE TITLE
./configure errors

### ISSUE THREAD

**Issue by yermulnik** [DaveDavenport/rofi#371]
Cannot manage to `configure` newest `rofi` source code:
```
#> git clone https://github.com/DaveDavenport/rofi.git
Cloning into 'rofi'...
remote: Counting objects: 8872, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 8872 (delta 17), reused 0 (delta 0), pack-reused 8836
Receiving objects: 100% (8872/8872), 8.86 MiB | 1.83 MiB/s, done.
Resolving deltas: 100% (6451/6451), done.
Checking connectivity... готово.
#> cd ./rofi
#> autoreconf -i
#> ./configure
[...]
./configure: line 4890: syntax error near unexpected token `xcb-aux'
./configure: line 4890: `GW_CHECK_XCB(xcb-aux xcb-xkb xkbcommon >= 0.5.0 xkbcommon-x11 xcb-ewmh xcb-xinerama xcb-icccm)'
```
Appreciate your help.

**Comment by DaveDavenport** [comment]
Please read the [INSTALL.md](https://github.com/DaveDavenport/rofi/blob/master/INSTALL.md#install-a-checkout-from-git)

**Comment by yermulnik** [comment]
I see my mistake. Sorry for the noise.
But I still can't `./configure` on my Linux Mint 17.1 Rebecca:
```
Requested 'xkbcommon >= 0.5.0' but version of xkbcommon is 0.4.1
```
libxkbcommon-dev:
  Installed: 0.4.1-0ubuntu1
  Candidate: 0.4.1-0ubuntu1
  Version table:
 *** 0.4.1-0ubuntu1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```
Is this xkbcommon version requirement vital or can be lowered?

**Comment by DaveDavenport** [comment]
No, if it could be lowered, it would be lower.

Work around see: https://github.com/DaveDavenport/rofi/commit/1e3294fa682a632cf72ff4c2f96c9c3216fc8e3e

**Comment by yermulnik** [comment]
thanx

**Comment by yermulnik** [comment]
`rofi.fg` and `rofi.bg` are no longer supported?
how can I reproduce theirs behavior?

**Comment by DaveDavenport** [comment]
See [manpage](https://github.com/DaveDavenport/rofi/blob/master/doc/rofi-manpage.markdown#theming-1)
Or online [examples](https://github.com/DaveDavenport/rofi-themes)
Or the online [theme generator](https://davedavenport.github.io/rofi/)

**Comment by yermulnik** [comment]
thanx a lot. things became a little bit complicated.
just in case my terminal-like theme:
```
rofi.color-normal:      argb:00000000,#00CC00,argb:00000000,#000000,#00FF00
rofi.color-urgent:      argb:00000000,#F99157,argb:00000000,#F99157,#1B2B34
rofi.color-active:      argb:00000000,#6699CC,argb:00000000,#6699CC,#1B2B34
rofi.color-window:      argb:ee222222,#006600,argb:ef000000
rofi.separator-style:   solid
```

**Comment by DaveDavenport** [comment]
Yeah, people wanted these options and it was either 18 separate flags or this. 

That is why we have a theme generator now, to make it easier again.

**Comment by yermulnik** [comment]
Anyway thanx for the great and useful app!
