### ISSUE TITLE
Rofi crashes X11 when a unknown string is given

### ISSUE THREAD

**Issue by huffstler** [DaveDavenport/rofi#373]
## Version
Version: 1.0.0-devel

## Configuration
https://gist.github.com/huffstler/f431a33786bff7ef9b99a68b80fa585b

## Launch Command
rofi -key-run Alt+space

## Steps to reproduce
1. Open up rofi (In my case, press alt and space)
2. type in any string that rofi can't recognize as a program
    - testing, xfox, foo are all examples that work for me
3. Hit enter
4. a dialog box pops up with an error message (will put the text in here soon)
5. X server crashes (or something) after dialog is dismissed (I hit enter after error appears in dialog)
6. I don't use a display manager so I'm kicked back out to the xorg login
7. I can still login fine after

I can add more information if need be.

**Comment by sardemff7** [comment]
You are using the daemon mode, which is now removed.

Please try without the daemon mode, and then, with an up-to-date version.

**Comment by DaveDavenport** [comment]
closing because of no reply.
