### ISSUE TITLE
Custom -run-command fails to launch any program

### ISSUE THREAD

**Issue by noh4ck** [DaveDavenport/rofi#375]
## Version
Version: 0.15.12

## Configuration
[gist](https://gist.github.com/noh4ck/88a37ae50aeb3b1f2f747431b3a8aaff)

## Launch Command
`rofi -run-command "zsh -i -c '{cmd}'" -show run`

## Steps to reproduce

* Start something using the launch command
* make sure rofi is a background process
eg: run from [sxhkd](https://github.com/baskerville/sxhkd) or using this command from terminal:

`rofi -run-command "zsh -c -i '{cmd}'" -key-run F2 &`

## What behaviour you see

* Programs does not start
* Nothing happens if rofi is launched from sxhkd
* If running from the terminal, the launched application might crash or just use 100% cpu until it's manually killed

## What behaviour you expect to see

* To be able to launch programs that's in path or any zsh alias and function.
* I followed the steps from this issue https://github.com/DaveDavenport/rofi/issues/97 to find out how to use aliases and functions from rofi.

**Comment by DaveDavenport** [comment]
hmm I can only reproduce this with zsh.

Does it also happen when you do not pass the -i flag to zsh (this fixes it for me).  This looks to be not applicable here.

**Comment by noh4ck** [comment]
When using this command from terminal whithout -i: `rofi -run-command "zsh -c '{cmd}'" -key-run F2 &` I can successfully launch programs, but -i is required to access aliases etc. it seems. With -i, the program starts to consume 100% until I kill it.

From sxhkd, both with and without -i does nothing, this is the sxhkd config:

```
alt + {_,shift} + space
    rofi -run-command "zsh -c -i '{cmd}'" -show {run,window}
```

**Comment by sardemff7** [comment]
Are you sure your sxhkd configuration works as expected? It seems that `{}` have a special meaning in there, so maybe the `{cmd}` for rofi is conflicting?

I cannot reproduce from a terminal. Zsh 5.2 here.

**Comment by DaveDavenport** [comment]
I am unsure why -i is needed for aliases, given it is:

> -i
> Force shell to be interactive. 

According to manpage. 
Can try setting run-command Xresources? to see if it is conflicting syntax?

**Comment by sardemff7** [comment]
Zsh will read:
* `.zshenv`
* `.zprofile` if `-l` (login mode)
* `.zshrc` if `-i` (interactive mode)
Usually, you define aliases in `.zshrc` because it is where they make sense, but in this case, you could actually use `.zshenv`.

**Comment by DaveDavenport** [comment]
aah that explains, thx.

**Comment by noh4ck** [comment]
@sardemff7 You were right about the `{cmd}` in sxhkd, it strips out {} from the command, so it only tries to run `cmd`. I can't find a way to escape the curly brackets either, it must be a bug with sxhkd, or just something I've overlooked. 

But that still doesn't explain why something like `rofi -run-command "zsh -c -i 'vim'" -show run &` hangs and uses 100% cpu. htop shows `zsh -c -i vim` as the command that hangs and uses all the cpu. The same command works from the terminal.

**Comment by jazoom** [comment]
> I worked around the sxhkd issue by making a script, now everything seems to work.

I just used back slashes and it seems to have escaped them. This works fine for me:

`rofi -show drun -run-command 'gksudo \{cmd\}'`
