### ISSUE TITLE
Black box after update from 0.15.7 to 0.15.12

### ISSUE THREAD

**Issue by minzastro** [DaveDavenport/rofi#376]
## Version

Output of `rofi -v`
Version: 0.15.12

## Configuration

Output of `rofi -dump-xresources` 
[gist](https://gist.github.com/minzastro/fd40ff9ec625fc517ce7ad6d32647284)

## Launch Command

The commandline used to launch **rofi**
rofi -show run

## What behaviour you see

* - rofi dialog appears as a black box (black text on black background?), but still seems to work, i.e. i can type command and launch it. Passing color-specific options (-fg, -bg) does not help.
I use i3wm

**Comment by DaveDavenport** [comment]
Can you try the release candidate? 1.0.0-RC1?

**Comment by minzastro** [comment]
I can try, but I cannot see how to build it properly - there is no configure file in this version anymore...

**Comment by DaveDavenport** [comment]
rofi-1.0.0-RC1.tar.gz and rofi-1.0.0-RC1.tar.xz should have a configure file.
The other two are auto-attached by github and are just 'raw' snapshots from git.

**Comment by minzastro** [comment]
Yep. Works now. Thank You.

**Comment by DaveDavenport** [comment]
It  compiles? or black box is gone?

**Comment by minzastro** [comment]
It compiled, and works perfectly now.

**Comment by DaveDavenport** [comment]
great!
