### ISSUE TITLE
Select previous active window

### ISSUE THREAD

**Issue by KLIM8D** [DaveDavenport/rofi#377]
Hi,

When showing the window list, it currently selects the active window from the window list (-key-window feature), could it maybe select the previous active window? So you are able to quickly cycle between two open windows, just by pressing <KEYBIND> + Enter. Atleast this is a fairly common usecase for me and I think it is a bit more useful, since you are rarely looking for the active window. 

It could maybe be a flag, so it's possible to enable/disable.

Let me hear your thoughts.

**Comment by sardemff7** [comment]
Duplicates of #39.

**Comment by fullofcaffeine** [comment]
I'm also looking for this behavior. Did anyone find any scripts that do that? I use Mint 18.3 + Cinnamon.
