### ISSUE TITLE
Add support for (custom) accepting of entries from a script

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#379]
I am trying to use `qalc -t` via a script:

    #!/bin/sh
    out="$(rofi -show calc -modi "calc:qalc -t")"
    if [ -n "$out" ]; then
        echo "$out" | xsel
    fi

For this to work, the **accept-custom** binding used by `-dmenu` should do the same here, too - not sure about "moves to the next entry" in this context though:

> Pressing the accept-custom binding (control-enter  or  shift-enter)  sends the selected entry to STDOUT and moves to the next entry.

**Comment by blueyed** [comment]
The use case here is:

1. Start with empty input (`qalc -t`) should not be called initially even
2. As long as there is some custom input (text + Enter), it should be passed to the script.
3. If an entry is selected rofi should exit and print the result.

btw: different exit codes could be used (additionally?!): MENU_OK, MENU_CANCEL, MENU_CUSTOM_INPUT from via https://github.com/DaveDavenport/rofi/blob/bf51983150d5d193be702b496506090c0daf9fe1/include/mode.h#L32-L39 appear to make sense, e.g. as 0, 1, and 2.

**Comment by blueyed** [comment]
The main issue here appears to be that it's not possible to select an entry altogether after all, and the rofi can only be closed through `Escape`.

**Comment by DaveDavenport** [comment]
The script can close rofi by sending an empty list back. See the file-browser example.

Please take a look at how the script mode actually work. I am not going to tailor a solution just to fit `galc -t`.
