### ISSUE TITLE
command arguments not detected in combi

### ISSUE THREAD

**Issue by Sigzegv** [DaveDavenport/rofi#380]
Rofi version 1.0.0-devel
( well not sure about version because I installed it from AUR :aur/rofi-git 0.15.12.r259.gb13bff6-1 [installed: 0.15.12.r264.gabe4447-1)

When running with `rofi -show combi -modi "combi"` any command with arguments doesn't start. But using standard run mode `rofi -show run -modi "run"` arguments are transmited correctly to program. 

Note : running a command with arguments in `show -run` with history enabled, makes that record work in combi after that. Example :

* I execute `rofi -show run -modi "run"` and type a command with argument "google-chrome-stable google.com"
* Then I run `rofi -show combi -modi "combi"` and I select recorded command "google-chrome-stable google.com" command from history, it works.

**Comment by sardemff7** [comment]
[Side note: AUR versionning for `-git` packages is roughly `git describe --tags --always` with a sed. We now use that (without the sed) in master, so the AUR `rofi-git` version is as valuable as `rofi -v`.]

**Comment by sardemff7** [comment]
Could you test with current `master` and if it doesn’t work, with `wip/sn-launcher` branch?

**Comment by DaveDavenport** [comment]
This is no bug.

How should 'combi' mode know what mode can handle the request if nothing is selected?

**Comment by Sigzegv** [comment]
Hi Dave, what do you been by "nothing is selected ? I always select an entry before typing arguments (or I select an entry generated by history)

**Comment by DaveDavenport** [comment]
I mean that nothing is selected.

**Comment by Sigzegv** [comment]
hum ok I think I understand now, in run mode if a type a command and then a space and some argument, the last match disapears but rofi know to use the run mode on that command, but in combi mode, without history, it doesn't remember I selected a command from run mode before typing a space and an argument, is that the point ?

As well the tip with !r doesn't change anything in combi because as you said, as soon as a start the arguments, the completed command disapears.

Then couldn't this be a feature to remember the last completed command before typing an argument ?

**Comment by DaveDavenport** [comment]
The `!r`  tells combi to launch it with run.. This works for me with V1.0-RC1

**Comment by Sigzegv** [comment]
yes it works if we type command entirely, but when I autocomplete the command (what I do 99% of the time) the !r is removed.

**Comment by DaveDavenport** [comment]
hmm interresting.. could look at fixing that. Good idea.

**Comment by Sigzegv** [comment]
thnx
