### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by jubalh** [DaveDavenport/rofi#382]
On https://davedavenport.github.io/rofi/ it would be good to update
- Description: `A popup window switcher roughly based on superswitcher, requiring only xlib and pango`
- Info about colors/themes
- Remove mention of daemon mode

**Comment by DaveDavenport** [comment]
Current status of website is:
 

- I am not going to maintain it.
- I will accept merge requests
- If no updates will come, I will take it offline.

**Comment by jubalh** [comment]
Maybe it would be good to write that info quite visible on the website itself as many people regard the upstream website to be the most up to date one

**Comment by DaveDavenport** [comment]
well it is a recent decision, haven't gotten around doing that.

**Comment by jubalh** [comment]
Okay. I will submit the proposed changes later, when I find some time. Thanks
