### ISSUE TITLE
Rofi does not start

### ISSUE THREAD

**Issue by jubalh** [DaveDavenport/rofi#383]
## Version

Output of `rofi -v`
Version: 1.0.0

## Configuration
Failed to open display: (null)

## Launch Command

The commandline used to launch **rofi**
$ rofi

## Steps to reproduce

* I am just launching it

## What behaviour you see
Failed to open display: (null)

## What behaviour you expect to see

* - rofi starting

**Comment by DaveDavenport** [comment]
You are not running an X11 server or have not setup the DISPLAY environment correctly?

**Comment by jubalh** [comment]
I was running X and all other apps worked. Anyways I restarted the computer after an update and it helped.. strange..
