### ISSUE TITLE
Rofi 1.0.0 doesn't respect settings in i3

### ISSUE THREAD

**Issue by q00p-git** [DaveDavenport/rofi#385]
## Rofi 1.0.0 

Output of `rofi -v`

## Configuration

Ouput of rofi -dump-xresources can be seen here > https://bpaste.net/show/64dee22822b6

## Launch Command

For i3 I'm using $mod-p to use Rofi with old set :+1: 

bindsym $mod+p exec --no-startup-id rofi -show run -font "Terminus 9" -fg "#505050" -bg "#000000" -hlfg "#ffb964" -hlbg "#000000" -o 85

## What behaviour you see

I'm unable to make a screenshot while Rofi is activated. It doesn't give me the theme I set via config in i3 as it was working before. Looks like a standard theme is always loaded.

Thank you.

**Comment by DaveDavenport** [comment]
Please read the changelog for the new release.
