### ISSUE TITLE
rofi window mode no longer shows desktops

### ISSUE THREAD

**Issue by tummychow** [DaveDavenport/rofi#386]
## Version

`Version: 1.0.0` exhibits the bug
`Version: 0.15.2` does not have the bug

## Configuration

Default (https://gist.github.com/tummychow/930cd06d05be5b5ef48eb0c696a1da10)

## Launch Command

`rofi -show window`

## Steps to reproduce

Start rofi in window-switcher mode

## What behaviour you see

* window list is shown with no desktop numbers on the left

## What behaviour you expect to see

* window list has desktop numbers on the left

## More details

The WM is bspwm 0.9.1. With rofi 0.15.2, the window switcher mode displayed desktop numbers in the leftmost column. As of the 1.0.0 update, the desktop numbers are no longer present.

v0.15.2: ![v0152](http://i.imgur.com/6FYBB8o.png)

v1.0.0: ![v1](http://i.imgur.com/sNywfii.png)

**Comment by DaveDavenport** [comment]
Can you test the latest git, I think I fixed it. (never noticed it, as I use I3 and have no desktop numbers)

**Comment by tummychow** [comment]
:+1:, that commit fixed it. Thanks for the quick response! I can wait until the next release for this.

**Comment by DaveDavenport** [comment]
will try to do a bugfix release this weekend.
