### ISSUE TITLE
Color options are not working, history lost after update to 1.0

### ISSUE THREAD

**Issue by hosaka** [DaveDavenport/rofi#387]
## Version
Version: 1.0.0

## Configuration
In .Xresources. The colours are set above and used generically in the file for example with xterm as well, using lines similar to `#define sol_base02 #073642`
```
rofi.font:            Terminus 8
rofi.background:      sol_base02
rofi.foreground:      sol_base2
rofi.highlightbg:     sol_yellow
rofi.highlightfg:     sol_base2
rofi.bordercolor:     sol_base00
rofi.borderwidth:     1
rofi.padding:         1
rofi.lines:           5
rofi.fixed-num-lines: true
rofi.separator-style: solid
rofi.hide-scrollbar:  true
rofi.opacity:         100
rofi.location:        2
rofi.yoffset:         18
rofi.xoffset:         0
rofi.width:           100

! behavior
rofi.terminal:      urxvt
rofi.ssh-set-title: false
rofi.auto-select:   false

! keys
! enable if running in daemon mode, launched by i3 instead
!rofi.key-run:    mod4+r
!rofi.key-window: mod4+tab
rofi.kb-cancel:   Escape,Control+g
```

## Launch Command

Through i3 config, $mod+r is bound to:
`rofi -show run`

## Steps to reproduce

* Using Arch Linux, updated the package to the 1.0 version.
* Run rofi as normal using the i3 key binding

## What behaviour you see

* - Launched as expected, positioning, padding, fonts etc. working as expected. Changing for example rofi.lines in .Xresources works fine.
* - The colours are no longer corresponding to what they are set to. Changing .Xresources parameters doesn't affect the behaviour after reloading with xrdb. Even changing to "#ffffff" doesn't change the colour. Launching a single-shot example from the README `rofi -show run -font "snap 10" -fg "#505050" -bg "#000000" -hlfg "#ffb964" -hlbg "#000000" -o 85` doesn't change the colours either.
* - All previously learned history is gone. Not the biggest issue, I'm sure I can live with that.

## What behaviour you expect to see

* - The colours to stay the same (solarized theme) as they used to be and as defined by .Xresources.
* - The history preserved with the update.

**Comment by Alaanor** [comment]
Hi, I confirm this issue. Same here but all options are specified in command-line.

**Comment by sardemff7** [comment]
Read the release notes: old theming was removed, please change to the new theming. You can use the [theme generator](https://davedavenport.github.io/rofi/p11-Generator.html) to help you with the syntax.

As for the cache, the format changed, thus it cannot use the old one. Not sure what changed exactly, but you can always copy the file to the new name and see if that works for you.

**Comment by hosaka** [comment]
Apologies, I have missed that from the release info. Can you please tell me where the history file is so I can try to fix it manually?

**Comment by sardemff7** [comment]
In `~/.cache`, they are named `rofi-<number>.<modi>cache`.

**Comment by DaveDavenport** [comment]
duplicate of #385
