### ISSUE TITLE
Select previous focused Window in i3

### ISSUE THREAD

**Issue by pablospe** [DaveDavenport/rofi#39]
Could it be possible to easily select the previous focused Window (in i3)?

I would like to have something to back and forth between windows. There is a features request in i3, but... it seems they don't want to implement it (for now):
   http://bugs.i3wm.org/report/ticket/838

**Comment by varmanishant** [comment]
+1 is that possible?

**Comment by newsgrep** [comment]
+1
could you extend the Window Mode to be more "I switch Windows with Alt+Tab" like?
So when opened in Window Mode (Alt+Tab) then simply "make" rofi toggle one item and execute the highlighted item as soon as the Alt-Key is left up. And when Alt is still pressed down and the Tab-Key is pressed in addition while rofi is opened in Window Mode simply toggle one item farther and execute it as soon as the Alt-Key is released.

**Comment by uberspot** [comment]
Is this still considered? I'd like to see this feature as well. :+1:

**Comment by DaveDavenport** [comment]
A good patch is welcome.

**Comment by Airblader** [comment]
Is it just me or does this totally go against what rofi is for? This requires rofi to keep state of focused windows.

**Comment by DaveDavenport** [comment]
No, rofi keeping state would never be accepted.
A script that implements this would (or a simple way of getting this from stacking order or so.)

**Comment by DaveDavenport** [comment]
See previous comment. If we can get a clean WM agnostic solution, it will be accepted.

**Comment by fullofcaffeine** [comment]
+1
