### ISSUE TITLE
Show Desktop Background in Fullscreen Mode

### ISSUE THREAD

**Issue by psamim** [DaveDavenport/rofi#390]
## Version

1.0.0

## Configuration

https://gist.github.com/psamim/5959bc3c8ee2265dec7e9efadbbaa93a

## Launch Command

Using i3 key bindings, `rofi -modi run,window -show run`

## Steps to reproduce

* Open Rofi

## What behaviour you see

*  I see Rofi is transparent and the underlying windows are visible.

## What behaviour you expect to see

* I expected to see the desktop background instead if the windows and it was the default behaviour before 1.0. Ater Rofi 1.0 it seems that Rofi correctly shows the underlying windows instead of the desktop background. Is there a way to bring back the old way and make Rofi show the desktop when in fullscreen mode?

**Comment by DaveDavenport** [comment]
This btw has nothing todo with rofi showing anything, but more with how I3 treats the rofi window.

So possible solution would be to have rofi draw background image (like it currently draws screenshot inb fake-transparency mode)
