### ISSUE TITLE
Unable to set inactive font color?

### ISSUE THREAD

**Issue by N0ps32** [DaveDavenport/rofi#392]
## Version

Version: 1.0.0

## Launch Command

`rofi -show run -color-window "#222222,#0088CC" -color-normal "#222222,#000000,#222222,#0088CC,#FFFFFF" -color-urgent "#222222,#000000,#222222,#0088CC,#FFFFFF" -color-active "#222222,#000000,#222222,#0088CC,#FFFFFF"`

## My Question
So I updated rofi to the latest version and my color configuration stopped working (new format). I cannot figure out how to set the color of the "run: " text and text of non highlighted rows.

Here's a screenshot of my problem:
http://abload.de/img/screenshot_20160427_2pai2e.png

I'd like the text to be white but couldn't find a configuration option in the manual.
Thanks in advance for your help and this project.

EDIT:
Here is the old version that used to work:
`rofi -show run -bg "#222222" -fg "#ffffff" -bc "#0088cc" -hlbg "#0088cc" -font "System San Francisco Display 12"`

**Comment by DaveDavenport** [comment]
If you set foreground color to black, it will show black.. 
Scheme is in [manpage](https://github.com/DaveDavenport/rofi/blob/master/doc/rofi-manpage.markdown#theming-1), 

Or try https://davedavenport.github.io/rofi/p11-Generator.html to get preview

**Comment by N0ps32** [comment]
Awesome thanks that worked.
