### ISSUE TITLE
Does rofi work in awesome wm (window mode)?

### ISSUE THREAD

**Issue by rogorido** [DaveDavenport/rofi#394]
If I try to use rofi in window mode in awesome wm (3.5.9), rofi does not select the right window (I think, if the window is in other desktop). I see that rofi numbers the desktops with 0,1,etc. while the index of the first desktop ("tag" actually in awesome) is 1... 

## Version
Version: 1.0.0-9-g7861b73-dirty

**Comment by DaveDavenport** [comment]
Does pull request #393 fix this?

**Comment by rogorido** [comment]
thanks. This is not yet in master, isn't? If not, do I have to apply it as patch?

**Comment by rogorido** [comment]
I applied the patch and it seems to work. Thanks a lot.

**Comment by DaveDavenport** [comment]
thanks for testing.. I hope to do a bug fix release this weekend that will include this patch.
