### ISSUE TITLE
Rofi fails to identify focused monitor

### ISSUE THREAD

**Issue by pigmonkey** [DaveDavenport/rofi#395]
## Version

Version: 1.0.0

## Configuration

https://gist.github.com/pigmonkey/e5576fc55b5e8d273a43d5007ab6a67b

## Launch Command

    rofi -show run -m -1

## Steps to reproduce

Plug an external monitor (DP1) into a laptop (eDP1), and configure the external as the primary.

    xrandr --output eDP1 --auto --output DP1 --primary --auto --right-of eDP1

Launch rofi from a terminal on the external monitor.

## What behaviour you see

Rofi always appears on the laptop screen, not the external monitor where it was launched from.

## What behaviour you expect to see

Rofi correctly identifies the active monitor. This worked prior to v1.0. (I had never used the `-m` option in previous versions, as the default behaviour was what I expected.)

Using rofi with `-m -2` and `-m -3` does work as expected. It is just `-m -1` that does not work. My window manager is i3.

I have not seen the rofi window span screens, so I'm not sure if this is related to #364.

**Comment by DaveDavenport** [comment]
There are 2 problems here:

1. Rofi < 1.0 did not do what the documentation said.. It followed active window, not active monitor. (Causing issues in i3). Now it actually tries to find the right desktop.
2. Something (esp on laptops with hotplug) does not report this correctly, causing rofi to make mistakes about where to place itself.

(Current scheme is:
1. Find current Desktop,
2. Get viewports of said desktop.

On my fixed pc's this results in the right result. With hotplug, it goes wrong from time to time.
)

**Comment by pigmonkey** [comment]
Thanks for the response.

For now I can use `-m -2` to get the window roughly where I expect it, but I prefer it centered on the monitor rather than the window. Do you have any suggestions for how I can try to get the system to correctly report the active monitor, or is there something I can do to get the pre-v1.0 behavior?

**Comment by DaveDavenport** [comment]
I think I will change the current behaviour to now position rofi on top of the window, but the monitor the window is placed on.  (e.g. old behaviour)
I also still hope I can get to the bottom why on hotplug the viewport is not reported correctly.

**Comment by pigmonkey** [comment]
That would be perfect for me. Thanks!

If you need any additional output to help debug the viewport reporting issue, let me know.

**Comment by DaveDavenport** [comment]
Can you try `-m -4` if that behaves as intended?

**Comment by DaveDavenport** [comment]
Added two options, ones to put on active window monitor and one to put on monitor with mouse pointer. 
See manpage.

**Comment by pigmonkey** [comment]
I built latest git and `-4`does give me the old, pre-v1 behaviour. `-5` is useful too!

**Comment by antoyo** [comment]
Hello.
[The wiki page](https://github.com/DaveDavenport/rofi/wiki/WindowPosition#monitor) needs to be updated as well.
Thanks.

**Comment by antoyo** [comment]
By the way, using `-4` always use the focused monitor, except when there are no windows on this monitor.
In the case there are no windows on the focused monitor, it will use the primary monitor, but I believe it should still use the focused monitor.
Could you please fix this issue?
Thanks.

**Comment by DaveDavenport** [comment]
Please stop hijacking bug reports.
