### ISSUE TITLE
Can we have rofi auto close if focus is lost?

### ISSUE THREAD

**Issue by gavsiu** [DaveDavenport/rofi#396]
## Version

Version: 1.0.0-RC1-13-g0afc4cc (master)

## Configuration

https://gist.github.com/gavsiu/53622499bc188c3340ab82fa5df22ba6

## Launch Command

rofi -modi "Drun,window" -show Drun

## Steps to reproduce

* Step 1
Open rofi
* Step 2
Click outside of rofi (desktop / other apps)

## What behaviour you see

* - Nothing

## What behaviour you expect to see

* - rofi closing if focus is lost

**Comment by DaveDavenport** [comment]
rofi (in normal use)  does not loose focus when you click outside of it window.

**Comment by gavsiu** [comment]
Is it possible to request this as an option?

**Comment by ViktorNova** [comment]
+1

**Comment by DaveDavenport** [comment]
fixored.

**Comment by deviousgeek** [comment]
U da man.

**Comment by DaveDavenport** [comment]
@ianremmler  is da man.
