### ISSUE TITLE
rofi fails after complaint: xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.utf8"

### ISSUE THREAD

**Issue by bkerin** [DaveDavenport/rofi#400]
I build the latest version with all debian packages from the latest debian stable except xkbcommon,
which wasn't new enough.  Install went fine.  Scary warning at run time:

$ echo -e "foo\nbar\n" | rofi -dmenu
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.utf8"
Failed to get keyboard compose table. Trying to limp on.
bar
$ 

Requested version etc. follows:

## Version

$ rofi -v
Version: 1.0.1

## Configuration

$ rofi -dump-xresources
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.utf8"
Failed to get keyboard compose table. Trying to limp on.
! Enabled modi
rofi.modi:                           window,run,ssh
! Window opacity
rofi.opacity:                        100
! Window width
rofi.width:                          50
! Number of lines
rofi.lines:                          15
! Number of columns
rofi.columns:                        1
! Font to use
rofi.font:                           mono 12
! Color scheme for normal row
rofi.color-normal:                   #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
! Color scheme for urgent row
rofi.color-urgent:                   #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
! Color scheme for active row
rofi.color-active:                   #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
! Color scheme window
rofi.color-window:                   #fdf6e3,#002b36
! Border width
rofi.bw:                             1
! Location on screen
rofi.location:                       0
! Padding
rofi.padding:                        5
! Y-offset relative to location
rofi.yoffset:                        0
! X-offset relative to location
rofi.xoffset:                        0
! Always show number of lines
rofi.fixed-num-lines:                false
! Terminal to use
rofi.terminal:                       rofi-sensible-terminal
! Ssh client to use
rofi.ssh-client:                     ssh
! Ssh command to execute
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
! Run command to execute
rofi.run-command:                    {cmd}
! Command to get extra run targets
rofi.run-list-command:               
! Run command to execute that runs in shell
rofi.run-shell-command:              {terminal} -e {cmd}
! Disable history in run/ssh
rofi.disable-history:                false
! Use levenshtein sorting
rofi.levenshtein-sort:               false
! Set case-sensitivity
rofi.case-sensitive:                 false
! Enable sidebar-mode
rofi.sidebar-mode:                   false
! Row height (in chars)
rofi.eh:                             1
! Enable auto select mode
rofi.auto-select:                    false
! Parse hosts file for ssh mode
rofi.parse-hosts:                    false
! Parse known_hosts file for ssh mode
rofi.parse-known-hosts:              true
! Set the modi to combine in combi mode
rofi.combi-modi:                     window,run
! Do a more fuzzy matching
rofi.fuzzy:                          false
! Use glob matching
rofi.glob:                           false
! Use regex matching
rofi.regex:                          false
! Tokenize input string
rofi.tokenize:                       true
! Monitor id to show on
rofi.m:                              -1
! Margin between rows
rofi.line-margin:                    2
! Pre-set filter
rofi.filter:                         
! Separator style (none, dash, solid)
rofi.separator-style:                dash
! Hide scroll-bar
rofi.hide-scrollbar:                 false
! Fullscreen
rofi.fullscreen:                     false
! Fake transparency
rofi.fake-transparency:              false
! DPI
rofi.dpi:                            -1
! Threads to use for string matching
rofi.threads:                        1
! Scrollbar width
rofi.scrollbar-width:                8
! Scrolling method. (0: Page, 1: Centered)
rofi.scroll-method:                  0
! Pidfile location
rofi.pid:                            /run/user/1001/rofi.pid
! Keybinding
rofi.kb-primary-paste:               Control+Shift+v,Shift+Insert
! Keybinding
rofi.kb-secondary-paste:             Control+v,Insert
! Keybinding
rofi.kb-clear-line:                  Control+u
! Keybinding
rofi.kb-move-front:                  Control+a
! Keybinding
rofi.kb-move-end:                    Control+e
! Keybinding
rofi.kb-move-word-back:              Alt+b
! Keybinding
rofi.kb-move-word-forward:           Alt+f
! Keybinding
rofi.kb-move-char-back:              Left,Control+b
! Keybinding
rofi.kb-move-char-forward:           Right,Control+f
! Keybinding
rofi.kb-remove-word-back:            Control+Alt+h
! Keybinding
rofi.kb-remove-word-forward:         Control+Alt+d
! Keybinding
rofi.kb-remove-char-forward:         Delete,Control+d
! Keybinding
rofi.kb-remove-char-back:            BackSpace,Control+h
! Keybinding
rofi.kb-accept-entry:                Control+j,Control+m,Return,KP_Enter
! Keybinding
rofi.kb-accept-custom:               Control+Return,Shift+Return
! Keybinding
rofi.kb-mode-next:                   Shift+Right,Control+Tab
! Keybinding
rofi.kb-mode-previous:               Shift+Left,Control+Shift+Tab
! Keybinding
rofi.kb-toggle-case-sensitivity:     grave,dead_grave
! Keybinding
rofi.kb-delete-entry:                Shift+Delete
! Keybinding
rofi.kb-row-left:                    Control+Page_Up
! Keybinding
rofi.kb-row-right:                   Control+Page_Down
! Keybinding
rofi.kb-row-up:                      Up,Control+p,Shift+Tab,Shift+ISO_Left_Tab
! Keybinding
rofi.kb-row-down:                    Down,Control+n
! Keybinding
rofi.kb-row-tab:                     Tab
! Keybinding
rofi.kb-page-prev:                   Page_Up
! Keybinding
rofi.kb-page-next:                   Page_Down
! Keybinding
rofi.kb-row-first:                   Home,KP_Home
! Keybinding
rofi.kb-row-last:                    End,KP_End
! Keybinding
rofi.kb-row-select:                  Control+space
! Keybinding
rofi.kb-cancel:                      Escape,Control+bracketleft
! Keybinding
rofi.kb-custom-1:                    Alt+1
! Keybinding
rofi.kb-custom-2:                    Alt+2
! Keybinding
rofi.kb-custom-3:                    Alt+3
! Keybinding
rofi.kb-custom-4:                    Alt+4
! Keybinding
rofi.kb-custom-5:                    Alt+5
! Keybinding
rofi.kb-custom-6:                    Alt+6
! Keybinding
rofi.kb-custom-7:                    Alt+7
! Keybinding
rofi.kb-custom-8:                    Alt+8
! Keybinding
rofi.kb-custom-9:                    Alt+9
! Keybinding
rofi.kb-custom-10:                   Alt+0
! Keybinding
rofi.kb-custom-11:                   Alt+Shift+1
! Keybinding
rofi.kb-custom-12:                   Alt+Shift+2
! Keybinding
rofi.kb-custom-13:                   Alt+Shift+3
! Keybinding
rofi.kb-custom-14:                   Alt+Shift+4
! Keybinding
rofi.kb-custom-15:                   Alt+Shift+5
! Keybinding
rofi.kb-custom-16:                   Alt+Shift+6
! Keybinding
rofi.kb-custom-18:                   Alt+Shift+8
! Keybinding
rofi.kb-custom-17:                   Alt+Shift+7
! Keybinding
rofi.kb-custom-19:                   Alt+Shift+9
! Keybinding
rofi.kb-screenshot:                  Alt+Shift+S
! Keybinding
rofi.kb-toggle-sort:                 Alt+grave
! The display name of this browser
rofi.display-ssh:                    (ssh)
! The display name of this browser
rofi.display-run:                    (run)
! The display name of this browser
rofi.display-drun:                   (drun)
! The display name of this browser
rofi.display-window:                 (window)
! The display name of this browser
rofi.display-windowcd:               (windowcd)
! The display name of this browser
rofi.display-combi:                  (combi)
$ 

## Launch Command

See top

## Steps to reproduce

See top

## What behaviour you see

See top

## What behaviour you expect to see

Not the scary warning

**Comment by DaveDavenport** [comment]
Title says fails? in issue it looks like it is working just give warning.

What is it?

**Comment by bkerin** [comment]
On Tue, May 10, 2016 at 9:46 PM, Dave Davenport <notifications@github.com>
wrote:

> Title says fails? in issue it looks like it is working just give warning.
>
You are correct, it's just a warning.  I wrote the title before I realized
it was actually working, sorry.

I'm still curious about the warning and wouldn't mind getting rid of it.

Britton

**Comment by sardemff7** [comment]
Fix your locale to `en_US.UTF-8`. :-)
