### ISSUE TITLE
Make window switching customizable?

### ISSUE THREAD

**Issue by TheMuspilli** [DaveDavenport/rofi#401]
The problem is not located in rofi, but perhaps the solution could be in rofi. 

Some windowmanagers have built-in an option to shade a window. It is a nice feature and I use it a lot. Unfortunately there is almost no support for it. In graphical task switchers the preview is just the rolled up titlebar, and even when switching to a shaded window it does not automatically get unshaded, which to me makes as much sense as switching to a minimized (hidden) window and not restore (unhide) it. Rofi's "window" mode  seems to switch the same way, and that is why I would like to be able to customize the window switching action.

I call it customize, because I would like more than just unshading windows. I use a focus follows mouse policy (another unloved child of the wm makers) and moreover had to forbid my wm to switch to another desktop upon window activation. Thus I would like to be able to make rofi call a little script with some xdotool and wmctrl inside for window switching.

**Comment by sardemff7** [comment]
See the `wip/window-list` branch and the `-window-command` I added in it. Is that enough for you?

**Comment by TheMuspilli** [comment]
The description of the branch reads very promising and I would like to try it. However I do not manage to get it installed.  I crosschecked and have the same problems with the master branch, so my guess would be that I probably do it all wrong. I am really not experienced at this stuff. As I did not do that much at all, here my steps.

1. I downloaded the zip
2. unpacked it into a dir under home (maintaining dir structure)
3. cd into it
4. `autoreconf -i`
5. `mkdir build`
6. `cd build`
7. `../configure`

There everything looks fine until:

```
 checking for glib... yes
 ../configure: line 4933: syntax error near unexpected token `xcb-aux'
 ../configure: line 4933: `GW_CHECK_XCB(xcb-aux xcb-xkb xkbcommon >= 0.5.0 xkbcommon-x11 xcb-ewmh xcb-xinerama xcb-icccm)'
```

As I said, it is probably something I do wrong. But in the unlikely case that it's not me, I could provide the config.log from inside the folder build (30k), if that would help.

**Comment by region51** [comment]
@TheMuspilli 
git clone https://github.com/DaveDavenport/rofi.git
git submodule update --init

**Comment by sardemff7** [comment]
Or `git clone --recursive`

**Comment by TheMuspilli** [comment]
@region51 , @sardemff7 
Thanks for the instant help and babysitting me through this.  Now I got it installed and am testing. Out of the box the new version improves my workflow mentioned in the other issue I opened today. 


```
✓ [3101][folognorri] ~ $ rofi -version
Version: 1.0.1
```

My first attempt showed me clearly the master branch ("1.0.1-25-g09437e3 (master)"), so I

**Comment by TheMuspilli** [comment]
Everything runs fine now and exactly as I hoped it would. 

When I use the custom action on a window, the window gets activated, unshaded and the mouse gets parked. I had to use  wmctrl and xdotool, because one cannot move the mouse and the other cannot unshade, but that is the tiniest flaw. I like the solution so much that I even think about an additional  rofi dedicated to window switching only, while I normally use a one-rofi-rules-it-all approach where I first type and afterwards think what I want to do. 

Thanks again for the help! If github lets me do it I mark this issue now closed.

**Comment by sardemff7** [comment]
Thanks for testing.
That branch is now merged to master.
