### ISSUE TITLE
Use desktop names with window switcher

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#403]
I have `_NET_DESKTOP_NAMES(UTF8_STRING) = "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"` on the root X window, but rofi appears to display the desktop number only (starting at 0).

It would be nice if it would use the desktop names, which are mapped to tags in awesome WM.

**Comment by DaveDavenport** [comment]
Yep, is on my todo.

**Comment by DaveDavenport** [comment]
Can you test?

**Comment by blueyed** [comment]
Works!  Thanks!
