### ISSUE TITLE
Rofi hangs when running with dmenu option

### ISSUE THREAD

**Issue by craftyguy** [DaveDavenport/rofi#404]
## Version

Output of `rofi -v`
Version: 1.0.1

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
https://gist.github.com/craftyguy/c948a2137cdafd060447e501b0b41819

## Launch Command

The commandline used to launch **rofi**
rofi -dmenu

## Steps to reproduce

* Step 1
rofi -dmenu

* Step 2
rofi hangs

## What behaviour you see

* Nothing

## What behaviour you expect to see

* See menu

* gdb backtrace (after hitting ctrl-c) when hang occurs:
[New Thread 0x7fffef531700 (LWP 8339)]
^C
Thread 1 "rofi" received signal SIGINT, Interrupt.
0x00007ffff542fb1d in read () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff542fb1d in read () from /usr/lib/libc.so.6
#1  0x00007ffff53c64f8 in __GI__IO_file_underflow () from /usr/lib/libc.so.6
#2  0x00007ffff53bbb58 in getdelim () from /usr/lib/libc.so.6
#3  0x000000000041e16e in get_dmenu (pd=0x6933a0, fd=0x7ffff56f08c0 <_IO_2_1_stdin_>, length=0x6933f8) at ../source/dialogs/dmenu.c:86
#4  0x000000000041cf09 in dmenu_mode_init (sw=0x62a3d8 <dmenu_mode>) at ../source/dialogs/dmenu.c:328
#5  0x000000000040f985 in mode_init (mode=0x62a3d8 <dmenu_mode>) at ../source/mode.c:20
#6  0x000000000041d2fd in dmenu_switcher_dialog () at ../source/dialogs/dmenu.c:489
#7  0x00000000004097f1 in startup (data=0x0) at ../source/rofi.c:535
#8  0x00007ffff7b12dba in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7b13160 in ?? () from /usr/lib/libglib-2.0.so.0
#10 0x00007ffff7b13482 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#11 0x0000000000409233 in main (argc=9, argv=0x7fffffffdb48) at ../source/rofi.c:832

* strace running rofi

[rofi_strace.txt](https://github.com/DaveDavenport/rofi/files/262588/rofi_strace.txt)

**Comment by DaveDavenport** [comment]
This is intended behavior. Please check what dmenu is and how it works.
(original dmenu exhibits the same behavior).

**Comment by craftyguy** [comment]
Well, ok, this was working before and now it hangs:

```rofi -i -dmenu -font "SFNS Text 10" -m 0 -location 2```

**Comment by craftyguy** [comment]
Actually, I was piping output of i3-dmenu-desktop to rofi -dmenu and it was hanging in the exact same way. 

I figured out the issue though, here it is just for the sake of anyone else who might hit this: i3-dmenu-desktop was dying because there was a .desktop file that no longer pointed to a valid executable. This was feeding rofi with no data, causing rofi to hang.
