### ISSUE TITLE
Environment settings

### ISSUE THREAD

**Issue by ephexeve** [DaveDavenport/rofi#405]
## Version
Version: 1.0.1

## Configuration
https://gist.github.com/ephexeve/6bed3956184ce1b030ab14e5a480581e

## Launch Command
From i3:
`bindsym $mod+d exec --no-startup-id bash -c "rofi -show run"`

## Detail
When using `zsh -c` instead of `bash -c` I am able to use my custom paths, however not with bash. This question has already been asked [here](https://github.com/DaveDavenport/rofi/issues/100), but suddenly it was locked and I was not able to question this further. @sardemff7 told me it was because bash/zsh read different files (which I knew), and locked the issue without letting me explain it further. 

My bash config does have my custom paths so does my zsh configs. However, when doing a `zsh -c` it takes a long time because I am using Prezto (a Zsh framework), so it probably loads everything, in my bash config however, I only have my paths and custom aliases.
Any course of action?

**Comment by sardemff7** [comment]
This is not related to rofi in any way. rofi does not touch the environment it gets.
Please read your shell man page, specifically which files it reads (bash reads `.bashrc` for interactive shell, and first of `.bash_login`, `.bash_profile`, `.profile` for login shell).
If anything, your environment should be fixed *without running rofi with your shell*, in your case, i3 should already have the correct environment.

Here is a tip, hoping you will not open a new bug report for something not related to rofi:
Put *all* your environment setup (including `$PATH`) in your login shell (I will assume zsh) profile file (so `~/.zprofile`), and use `zsh -l -c i3` in your `~/.xinitrc`.

**Comment by natostanco** [comment]
this works for me:

`rofi -run-list-command "dmenu_path" -run-command "/bin/bash -c -i 'shopt -s expand_aliases; {cmd}'" -rnow -show run` 

I had to precede the run command with `expand_aliases` to make aliases work
