### ISSUE TITLE
Hyper modifier is not recognised?

### ISSUE THREAD

**Issue by krompus** [DaveDavenport/rofi#406]
## Version
Version: 1.0.0-9-g7861b73-dirty (makepkg)

## Configuration
https://gist.github.com/29333baf43af545a87092745151c8aac

## Launch Command
Three separate commands:
  
    rofi -run-list-command ". ~/sh/alias.sh" -run-command "/bin/bash -i -c '{cmd}'" -show run
    rofi
    j4-dmenu-desktop --dmenu='rofi -dmenu -i'

I also use [clerk](https://github.com/carnager/clerk), which is the primary reason I'd like to use the Hyper modifier in rofi in the first place; my system has global Hyper keybinds for media playback, and I'd like to be able to use these keybinds when clerk is open.

## Steps to reproduce
- Rebind a random command to use the Hyper modifier in `.Xresources`. For example, I have chosen `rofi.kb-move-end: Control+e`.

(I have tried rebinding this to a few different things: `Hyper+e`, `HyperL+e`, `Hyper_L+e`, and the HyperR variants)

- Launch rofi.

- Type a string of text.

- `Control+a` to place the cursor at the beginning of the string of text, and then try `Hyper+e` etc. to see if the cursor jumps to the end of the string. Also test this with the previous mapping, `Control+e`, to see if the remap has been recognised.

## What behaviour you see
`Control+e` is non-functional as expected, but `Hyper+e` and all of the variants I have tried will simply enter `e` as if the modifier were not being held.

## What behaviour you expect to see
The `Hyper` keybind should perform the assigned action.

**Comment by sardemff7** [comment]
Is that a real `Hyper` modifier in the keymap? Did you check with `xev`?

**Comment by krompus** [comment]
You betcha. `xev` reports `Hyper_L` (keysym `0xffed`).

I also tried with the key mapped as `Hyper_R`, same deal.

**Comment by sardemff7** [comment]
Pull the `wip/debug-modifiers` branch, build rofi, and run it with `export G_MESSAGES_DEBUG=all`.
It will print the list of modifiers of the keymap, let’s see which one you have.

**Comment by krompus** [comment]
> Pull the `wip/debug-modifiers` branch, build rofi, and run it with `export G_MESSAGES_DEBUG=all`.

I'm embarrassed to say I don't know how to do that. I'm new to using git. I installed rofi from the Arch User Repository.

Could you give me some instructions, or point me to a guide/tutorial?

**Comment by sardemff7** [comment]
AUR builds the package, right? So you have all the required dependencies. Here are the steps:

1. `git clone --recursive https://github.com/DaveDavenport/rofi`
2. `cd rofi`
3. `autoreconf -fi`
4. `./configure`
5. `make`
6. `export G_MESSAGES_DEBUG=all`
7. `./rofi`

**Comment by krompus** [comment]
Thank you!

I've done all this, and I get this:

    Rofi daemon mode is now removed.
    Please use your window manager binding functionality or xbindkeys to replace it.

I installed rofi into a testing directory as not to clobber my currently installed iteration.

I'm not exactly sure what it wants me to do here?

**Comment by krompus** [comment]
Ah, just saw your edit. I redid it with the branch. Now I get this:

    ** (process:26363): DEBUG: Mod 0: Shift
    ** (process:26363): DEBUG: Mod 1: Lock
    ** (process:26363): DEBUG: Mod 2: Control
    ** (process:26363): DEBUG: Mod 3: Mod1
    ** (process:26363): DEBUG: Mod 4: Mod2
    ** (process:26363): DEBUG: Mod 5: Mod3
    ** (process:26363): DEBUG: Mod 6: Mod4
    ** (process:26363): DEBUG: Mod 7: Mod5
    ** (process:26363): DEBUG: Mod 8: NumLock
    ** (process:26363): DEBUG: Mod 9: Alt
    ** (process:26363): DEBUG: Mod 10: LevelThree
    ** (process:26363): DEBUG: Mod 11: LAlt
    ** (process:26363): DEBUG: Mod 12: RAlt
    ** (process:26363): DEBUG: Mod 13: RControl
    ** (process:26363): DEBUG: Mod 14: LControl
    ** (process:26363): DEBUG: Mod 15: ScrollLock
    ** (process:26363): DEBUG: Mod 16: LevelFive
    ** (process:26363): DEBUG: Mod 17: AltGr
    ** (process:26363): DEBUG: Mod 18: Meta
    ** (process:26363): DEBUG: Mod 19: Super
    ** (process:26363): DEBUG: Mod 20: Hyper
    Rofi daemon mode is now removed.
    Please use your window manager binding functionality or xbindkeys to replace it.

**Comment by sardemff7** [comment]
So the keys are `Hyper_L` and `Hyper_R`, but maybe they are not mapped to the modifier itself.
Which keymap are you using?

**Comment by krompus** [comment]
I'm not sure what you mean by "which keymap". I've listed the output of xev above. I map the Hyper key with [xmodmap.](https://github.com/krompus/dotfiles/blob/master/Xmodmap/.Xmodmapc)

**Comment by sardemff7** [comment]
You are mapping the `Hyper_L` (and not `Hyper_R`, btw) to `Mod3`. Rofi does not use `Mod3`, you will have to map it to `Hype` somehow. I do not now xmodmap, so I cannot help on this.

**Comment by sardemff7** [comment]
Your keymap is `us colemak`

The more xkbcommon-friendly (and Wayland-friendly) way to modify a keymap is now to extend the keymap file, roughly:

1.  create a new keymap
2.  include your base keymap file
3. append any modification you want to

According to your `.Xmodmapc` it should look like that:
```
custom-us:
xkb_symbols "custom-us" {
    include "us(colemak)"
    name[Group1] = "English (US, custom keymap)";
    key <AD10> { [ colon, semicolon ] };
    modifier_map Hyper { <LCTL> };
} 
```
