### ISSUE TITLE
PATH and alias don't work in the I3 and bspwm config

### ISSUE THREAD

**Issue by Brainzman** [DaveDavenport/rofi#408]
Hi guys i have a problem . When enter that in my zsh shell 
`rofi -show run`

I have rofi whith all my alias and the program of my PATH

but when i add this in my i3 config (and its the same result in bspwm config) : 
`zsh -c "rofi -show run"`

I don't have my alias and my PATH

**Comment by DaveDavenport** [comment]
Duplicate of #405?
