### ISSUE TITLE
configurable prompt for -show modes

### ISSUE THREAD

**Issue by dylanmei** [DaveDavenport/rofi#409]
## Version
Version: 1.0.1

Using `rofi -dmenu` we can create a configurable prompt (#17) , but that was not carried over to the various `-show` modes. Supporting prompt everywhere:

- adds additional customization joy to *rofi* -- example below uses fontawesome to make a slick prompt
- resolves  confusion caused by `-p` not having an effect unless using `-dmenu`

`% rofi -show run -p " "`

**Comment by DaveDavenport** [comment]
The -p won't work if you have multiple 'modi'  open.. 
rofi -show run -modi 'run,ssh,window'

There is an option '-display-run' that I use in the combi browser .   (See http://images.sarine.nl/rofi-2016-05-20-1741.png) I could make that be picked up by the prompt.

**Comment by dylanmei** [comment]
Using the -display-x options in the prompt would be great! It's what I tried first before I found the `-p` option.

My use case is within i3, one binding for "run" and one binding for "window". I'm personally not combining modes together. Something like:

```
bindsym $mod+x exec rofi -show run -p " "
bindsym $mod+w exec rofi -show window -p " "
```

**Comment by dylanmei** [comment]
I understand now what *-modi 'run,ssh,window'* means, and why this problem is non-trivial. Have you considered incorporating -promt-run, -prompt-ssh, and -prompt-window flags?  Similar to the display-x flags but explicitly for the prompt, in non-dmenu mode?

**Comment by andyrichardson** [comment]
@DaveDavenport What reason was this issue closed for? I can see why it is desired; Is this a feature you are not interested in implementing?

**Comment by DaveDavenport** [comment]
Because it is fixed in the linked commit.

**Comment by andyrichardson** [comment]
Apologies, I've looked at the commit and I'm struggling to see how the prompt can be customized.

My understanding of this issue was that the prompt could be configured in a command line argument. 

For example `rofi -show run` would result in a prompt like so:
    
    run: <user enters text here>

`rofi -show run -prompt "$ :" would result in a prompt like so:

    $ : <user enters text here>

**Comment by DaveDavenport** [comment]
It implements what I suggested as solution in the 2nd comment.
```
rofi -show run -display-run 'blaat'
```

**Comment by andyrichardson** [comment]
Indeed it does; thanks for clarifying!
