### ISSUE TITLE
rofi hangs if invalid command entered.

### ISSUE THREAD

**Issue by claria** [DaveDavenport/rofi#410]
## Version

Output of `rofi -v`
Version: 1.0.0-devel
## Configuration
Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
http://pastebin.com/dr8wp2KW
## Launch Command

The commandline used to launch **rofi**
rofi -show run
## Steps to reproduce

start rofi
enter invalid command e.g. 'asdf'

Failed to execute: 'asdf'
Error: 'Failed to execute child process "asdf" (No such file or directory)'

So far so good. I would now expect that i can close the error window by pressing
ESC or similar. But nothing works. I have to kill the rofi process in order to use it again.

**Comment by carnager** [comment]
first of all: please don't use pastebin.com, it converts all linebreaks making your config unusable without converting it back manually. github has a nice pastebin itself: https://gist.github.com/

I just tried latest stable and latest git with your config and cannot reproduce it. Maybe a strace would help

**Comment by sardemff7** [comment]
I cannot reproduce it either, with 0.15.12, latest release and master. Either you are getting an issue specific to your environment (maybe GLib version) or you happen to have built the only broken commit.
Please test with current master and tell us if you can reproduce it.

**Comment by claria** [comment]
Hi,

you are right. The version i installed (arch linux aur) was
installed: rofi-git-0.15.12.r77.g784244a-1

After updating to
rofi-git-1.0.1.r29.g5b3239a-1

the problem is gone. Thanks for your help!!

**Comment by DaveDavenport** [comment]
This was indeed a bug in that version. duplicate of #345
