### ISSUE TITLE
Use rofi to quickly find rofi keybindings

### ISSUE THREAD

**Issue by mardukbp** [DaveDavenport/rofi#411]
One of the coolest uses of rofi is to write cheatsheets with keybindings for different programs. One day hopefully most developers will follow the lead of Vivaldi and realize that hiding commands in nested menus hinders productivity and using a rofi-like interface is much better. Until then we have rofi!

From that perspective, it is somewhat ironic that rofi does not rely on rofi for quickly finding its keybindings. I suggest adding the command line option `--keys` for this purpose.

**Comment by carnager** [comment]
`rofi -dump-xresources | grep -Ev '^! ' | grep 'rofi.kb-' | rofi -dmenu`

**Comment by mardukbp** [comment]
Yes, of course, But that is not the point. I am suggesting that this
should be a builtin feature.

**Comment by DaveDavenport** [comment]
`rofi -show keys`  should show you a list.  Now I need somebody to update all descriptions.

**Comment by mardukbp** [comment]
Awesome! Of course I will do it. I am on it.

**Comment by DaveDavenport** [comment]
The fields are here: https://github.com/DaveDavenport/rofi/blob/master/source/keyb.c#L37
