### ISSUE TITLE
Argument to disable input field

### ISSUE THREAD

**Issue by SL-RU** [DaveDavenport/rofi#422]
Can you also add arg which will disable input field and only arrows will be available.
I'm just using rofi as replacement for i3-nagbar.

```
echo -e "#Do not EXIT i3\ni3-msg exit #EXIT i3" | rofi -bg "#FF0000" -dmenu | sh
```

**Comment by DaveDavenport** [comment]
`-no-custom` and `-only-match`  will force the user to select an predefined entry.

**Comment by DaveDavenport** [comment]
from `rofi -h`:
```
        -only-match                            Force selection or custom entry
        -no-custom                             Don't accept custom entry
```

**Comment by SL-RU** [comment]
Awesome!
Thank you!
Sorry for stupid issues =P

**Comment by DaveDavenport** [comment]
No problem.
