### ISSUE TITLE
DPI not handled correctly anymore

### ISSUE THREAD

**Issue by blueyed** [DaveDavenport/rofi#423]
The DPI handling appears to have regressed when moving to xcb-xrm in a7922cc.

See https://github.com/DaveDavenport/rofi/issues/254#issuecomment-154360839 for the initial report, that could be made to work using `*.dpi:	176` in `xrdb`.

**Comment by DaveDavenport** [comment]
thx. will look at it.

**Comment by DaveDavenport** [comment]
```*.dpi``` might not be valid syntax (https://tronche.com/gui/x/xlib/resource-manager/file-syntax.html)

```*dpi: 133``` should work

**Comment by DaveDavenport** [comment]
Yep. Xlib was violating spec.

**Comment by Airblader** [comment]
On a separate note, it's currently a bad idea to use *only* `*dpi`, even if spec-compliant. Some tools and libraries such as xcb-util-cursor and cairo-xcb, which have not yet adopted xcb-util-xrm, do a hard-coded match on `Xft.dpi` and will not be able to properly read `*dpi`. So you should probably use

````
Xft.dpi: 133
*dpi: 133
```

Of course feel free to report bugs against those projects so they can adopt xcb-util-xrm. :-)
