### ISSUE TITLE
FreeBSD support?  Rehash of #328

### ISSUE THREAD

**Issue by vendion** [DaveDavenport/rofi#424]
## Version

Version: ~~0.15.12~~ 1.1.0

## Configuration

[See gist](https://gist.github.com/vendion/8f6cdc5743af1bc26334dc5c744794cb)

## Launch Command

    $ rofi -show run

## Steps to reproduce

* Install FreeBSD (or a FreeBSD variant like PC-BSD)
* Install `rofi` (pkg update && pkg install rofi)
* Try to run `rofi` from the terminal

## What behaviour you see

* [vendion@Freyja][~]% rofi -show run
Failed to create pid file.%  

## What behaviour you expect to see

* - A window for `rofi` to show

This is kind of a rehash of #328 that will hopefully go somewhere.  Reading through that issue, `rofi` wants to create a pid file in _/run/user/1000/_ but that directory doesn't exist under FreeBSD.

**Comment by DaveDavenport** [comment]
Rofi does not decide on this directory itself.

It uses `g_get_user_runtime_dir()` from glib, that internally uses XDG spec: XDG_RUNTIME_DIR and falls back to `g_get_user_cache_dir` if that fails.

I suspect you have an invalid XDG setup. 
What does 
```
xdg-user-dir RUNTIME
```
return?

**Comment by DaveDavenport** [comment]
closing because of no reply.

**Comment by DaveDavenport** [comment]
Install `xdg-user-dirs`

**Comment by vendion** [comment]
Sorry for the delayed reply, things got busy.   Here is the output of xdg-user-dirs:

```
$ xdg-user-dirs RUNTIME
/home/vendion
```

**Comment by DaveDavenport** [comment]
weird, I tried it out in a VM and after installing xdg stuff it worked.

**Comment by vendion** [comment]
Does this depend on any of the $XDG_* environment variables being set?  On my system `$XDG_SESSION_COOKIE` is set but `$XDG_RUNTIME_DIR` is not.  Could that be the issue?

**Comment by DaveDavenport** [comment]
This is what being [used](https://developer.gnome.org/glib/2.48/glib-Miscellaneous-Utility-Functions.html#g-get-user-runtime-dir)

**Comment by vendion** [comment]
Well both `XDG_RUNTIME_DIR` and `XDG_CACHE_HOME` are both set now:

XDG_RUNTIME_DIR is /var/run/user/runtime-dir-$UID
XDG_CACHE_HOME is /home/vendion/.cache

I'm still getting an error about not being able to create a pid file.
Since rofi no longer has a daemon mode what is the pid file for?

**Comment by DaveDavenport** [comment]
Did the error change? did it pick up the new directory.....   What is reported in ```rofi -dump-xresources```  you are giving me little to work with.

You can always override the pid via the configuration option.
But as I said, I installed freebsd, installed the xdg-* packages and it worked. (it placed the pid file for me in the cache directory) and others confirmed this.

**Comment by DaveDavenport** [comment]
pid file is there to still stop two rofi's at the same time.  This to avoid the instances fighting over grabbing keyboard and ending up in a situation where one rofi has grabbed the keyboard and the other not but still gets the events from X (had this before) and the only way out is killing rofi from the commandline.

I should check if with the xcb move this situation still occurs.

**Comment by vendion** [comment]
No the error message is still the same `Failed to create pid file.`

As far as the output of `rofi -dump-xresources` show that it is trying to set the PID file in _/run/user/1000/rofi.pid_ even though `XDG_RUNTIME_DIR` is set to be _/var/run/user/runtime-dir-$UID_ which resolves to being _/var/run/user/runtime-dir-1001_.  Looking into it deeper it turns out it was a problem caused by invalid settings on my part https://gitlab.com/vendion/dotfiles/blob/master/.xres/rofi#L88

My apologies for wasting your time in troubleshooting this, this is an old config file that I copied over and forget that line was there.  Closing this ticket.

**Comment by DaveDavenport** [comment]
no problem :smile:  Happy that it is solved. I will see if I can make dump-xresources report what set the option. Should help debugging in future.
