### ISSUE TITLE
Implement client-server mode?

### ISSUE THREAD

**Issue by eigengrau** [DaveDavenport/rofi#425]
Ever since the removal of daemon mode, I’ve been somewhat disenfranchised by occasionally rather high latencies between firing up rofi from my hotkey daemon and the rofi window actually being displayed. This might be a SucksToBeMe™ kind of problem, since my work machine is pretty clunky and doesn’t have an SSD. But anyway, I thought I’d ask how you’d feel about bringing back a “sort of” daemon mode, only without hotkey support. So the daemon would just linger around and map/unmap the window, keeping it around so that all the Xorg housekeeping and disk IO won’t apply and the rofi window can be shown instantly.

**Comment by DaveDavenport** [comment]
Can you provide more information (as requested):

* Rofi version
* Desktop/Window manager used
* How you launch rofi now (from DE/WM or separate daemon)

Also if you compile rofi with --enable-timings  it will generate a rofi-timings.log file that might be interesting.

**Comment by eigengrau** [comment]
Sorry, I didn’t include any further info because I don’t suspect the slowness concern rofi specifically. However:

- This is rofi 1.1.0-31-gbaee50e
- launched by sxhkd in a bspwm session

My guess, however, is that this is mostly about disk IO.  The worst latencies are got when the disk is busy. Normally, one would expect the disk scheduler to keep rofi cached, since I launch it all the time and I’m not starved for memory; however, it seems to occur that it’s frequently expired nonetheless. I don’t suspect this to be (too much) CPU-related, since rofi is stalling when the rest of the system (apart from anything that wants disk IO) is responsive. Then again rofi seems to come up a bit slower than when I used daemon mode, even when IO is idle.

From an economic perspective, with these kinds of commands, it might be reasonable to just keep the process around all the time. But maybe that’s a personal preference.

Thanks for the hint on timings. I’ll rebuild rofi and will see whether this tells me more. E.g., maybe the rofi binary is cached, after all, but some IO done by the run dialog causes it to stall (history file?).

**Comment by DaveDavenport** [comment]
As discussed in a previous bug report (https://github.com/DaveDavenport/rofi/issues/347), the extra "load" introduced should be fairly limited. VERY little was kept around in the daemon mode.

Until I get some numbers, I am not going to work on this. I want to know *why* it stalls first.
For example: I had it before with I3 (a git version) that it would take ages (0.5-0.6 seconds) for I3 to release the mouse/keyboard so Rofi could actually grab them. Maybe that is the case here?

**Comment by eigengrau** [comment]
> Until I get some numbers, I am not going to work on this. I want to know why it stalls first.
For example: I had it before with I3 (a git version) that it would take ages (0.5-0.6 seconds) for I3 to release the mouse/keyboard so Rofi could actually grab them. Maybe that is the case here?

Seems fair. I’ll investigate further!

**Comment by DaveDavenport** [comment]
Thanks for being understanding :+1:

**Comment by carnager** [comment]
with sxhkd you want to use @KEY instead of KEY, so it triggers the action on release event

**Comment by DaveDavenport** [comment]
Any more information on this?

**Comment by DaveDavenport** [comment]
timeout.
