### ISSUE TITLE
Every window title is ellipsized

### ISSUE THREAD

**Issue by d125q** [DaveDavenport/rofi#426]
## Version

Output of `rofi -v`

```text
Version: 1.1.0-44-gfc24fcc-dirty (makepkg)
```

## Configuration

Output of `rofi -dump-xresources`

[Gist](https://gist.github.com/d125q/34ffaec36530613870a2ad50075f8830)

## Launch Command

The commandline used to launch **rofi**

```sh
rofi -show combi
```

## Steps to reproduce

* Have a window title that needs to be ellipsized

## What behaviour you see

* Every window title is ellipsized (see screenshot)

![rofi-2016-07-16-2038](https://cloud.githubusercontent.com/assets/7765538/16896503/4b114658-4b95-11e6-8ce1-ef3d222eb59e.png)

## What behaviour you expect to see

* Only the window title that needs to be ellipsized should be ellipsized

**Comment by DaveDavenport** [comment]
Yep.  should fix that :D
