### ISSUE TITLE
BSPWM's hidden node flag

### ISSUE THREAD

**Issue by MrZammler** [DaveDavenport/rofi#428]
Hi and thanks for rofi!

A few commits ago, bspwm has added the hidden flag for windows (nodes). Basically it removes the window from the layout, and hides it. Doing so is easy through a key combination, but there's currently no intuitive way to restore this window back.

I've done some tests with rofi on my PC and added a way to set this flag to off when the window is selected through the rofi window selection list. I was wondering if you'd accept this as a feature to rofi?

If yes, what would be the best way to add it? Since rofi is mostly WM independent, would for example a command line switch do (e.g. --bspwm-unhide) so as not to steal cpu cycles from other WM users?

Also there are two ways bspwm can be told to unhide the window. Either by running the proper bspc command (but that would require a system call from rofi), or by directly talking to it's /tmp/ socket (basically emulating what bspc does). 

I could provide a PR for this if interested.

Thanks!

**Comment by carnager** [comment]
shouldnt such WM-specific things be done in a wrapper script? Seems simple enough

**Comment by MrZammler** [comment]
Sure, I guess it could. Is there a way to get the window id the user selected from rofi? Or you mean something outside of rofi all-together?

**Comment by carnager** [comment]
yes i mean outside. a simple bash script that you call

```
#!/usr/bin/env bash

bspwm command to unhide windows
rofi -show window
bspwm command to hid windows
```

**Comment by DaveDavenport** [comment]
you can try overriding the 
```
rofi.window-command:  
```
command.
Currently it calls 
```
 xkill -id {window}
```
(keybinding is kb-delete-entry  (shift+delete))

**Comment by MrZammler** [comment]
Hi Dave. Yes, I had tried that and it worked, but it required selecting with something other than just enter, which was what made me search for another way to do it.

I guess another solution is to maybe have a new window-command parameter that could be invoked when doing a normal select?

Thanks.

**Comment by DaveDavenport** [comment]
Rebind the keys?. 

I don't want to add 'wm' specific code to **rofi**. I am very happy to finally got rid of the i3 specific code.
I guess you can easily script this using `dmenu` mode.

**Comment by MrZammler** [comment]
Ok, fair enough, I can understand that.

Thanks a lot!

**Comment by DaveDavenport** [comment]
thanks for understanding.
