### ISSUE TITLE
No keyboard input on empty sway workspace

### ISSUE THREAD

**Issue by embik** [DaveDavenport/rofi#431]
## Version

```
[~] rofi -v
Version: 1.1.0
```
## Configuration

[Output of `rofi -dump-xresources`](https://gist.github.com/embik/56cadf12ff4f9574f2d85c12b9670098)
## Launch Command

`[~] rofi -show run`
## Steps to reproduce
- Install [sway](https://github.com/SirCmpwn/sway), a i3-compatible Wayland compositor
- Configure `rofi -show drun` as `$menu`
- Reload configuration (Super+Shift+C)
- Switch to empty workspace
- Start launcher (Super+D)
## What behaviour you see
- rofi does not receive any keyboard input until you switch to a workspace containing applications
- See   [sway#267](https://github.com/SirCmpwn/sway/issues/267)
## What behaviour you expect to see
- rofi should properly receive keyboard input on empty workspaces

**Comment by DaveDavenport** [comment]
Don't have sway, not (yet) interested.  Patches are always welcome.
@sardemff7  you got thoughts on this?

**Comment by embik** [comment]
That's certainly a bummer, but thank you for leaving this issue open. Wayland support (at least I guess that's the problem?) would be pretty rad.

**Comment by sardemff7** [comment]
XWayland support of wlc is not perfect, can you try using Weston? And ideally with a recent GNOME too (selecting Wayland session)?
Weston has basic but good support for XWayland, and Mutter should support it almost perfectly (as it is the same code managing for plain X anyway). That would target the issue cause more closely.

**Comment by embik** [comment]
I will conduct some tests with GNOME and Weston and report back on any relevant findings.

**Comment by DaveDavenport** [comment]
@sardemff7  mentioned that it worked for him on weston:

> SardemFF7 | afaict, rofi works correctly in Weston, so the issue really is wlc+XWayland to me                                      

We also had a quick discussion on making rofi work on wayland (adding support for backends and add wayland), conclusion is it should be possible with reasonable amount of effort, that **I** won't be doing it, but if somebody wants to do it I will support the effort.

**Comment by embik** [comment]
A Wayland backend does sound more reasonable as XWayland is supposed to be a "hack-y" way of supporting legacy XOrg, not a permanent solution (at least, that's how I understand it). Would it make sense to close this bug and track backend support and a Wayland backend separately? I'm not fit to write any of this, unfortunately.

**Comment by carnager** [comment]
This is a known bug btw: https://github.com/SirCmpwn/sway/issues/267

**Comment by carnager** [comment]
@embik: Long time goal would be proper wayland support in rofi, which now that we got rid of most, if not all xlib dependencies is easier than ever.

**Comment by carnager** [comment]
I wonder if `-normal-mode` works properly?

**Comment by NateBrune** [comment]
I would love Wayland support for rofi and can confirm issues with sway.

**Comment by sardemff7** [comment]
@NateBrune Thanks for the confirmation.

See #446 and [the wiki page](https://github.com/DaveDavenport/rofi/wiki/Wayland) for more information on “Wayland support”.

**Comment by sardemff7** [comment]
To everyone:
We know Wayland support would be great, but do not hijack this issue for it.

**Comment by DaveDavenport** [comment]
closing. 1.5 will (hopefully ) have native wayland support.

**Comment by fourtytwo** [comment]
Is the newest version of rofi supposed to fix that?

**Comment by DaveDavenport** [comment]
@fourtytwo *that* will be fixed once we have native wayland support. See linked wiki page.
