### ISSUE TITLE
"Failed to create pid file" - looks like a memory corruption

### ISSUE THREAD

**Issue by infokiller** [DaveDavenport/rofi#435]
## Version

Output of `rofi -v`

```
Version: 1.1.0
```

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))

https://gist.github.com/infokiller/5a0d238f1213b331be5e6454c7854c74

## Launch Command

The commandline used to launch **rofi**

```
rofi -show run
```

## Steps to reproduce

* Run the command above

## What behaviour you see

* I get an error of "Failed to create pid file"

## What behaviour you expect to see

* Rofi starting successfully

**Note**: this happens only on some of my linux machines.

I started debugging the code and it seems that there's a memory corruption. I printed the value of the variable `pidfile` and it changes from `/run/user/1000/rofi.pid` to `/run/user/190249/rofi.pid`. Seems like the problem happens in the function `config_parse_xresource_options_dynamic`.
When running rofi using `-no-config` it works well.
You can also verify the memory corruption by starting rofi with gdb and then adding a watchpoint on `pidfile`. In the gdb prompt: `watch *pidfile`.

Thanks.

**Comment by infokiller** [comment]
Here's what I'm running to jump immediately after the memory corruption:
```
make CFLAGS="-O0 -g3" rofi && gdb -ex "b load_configuration_dynamic" -ex "r" -ex "watch *pidfile" -ex "c" --args rofi -show run
```

**Comment by DaveDavenport** [comment]
This is weird.  esp because it changes to something 'sane' if it was memory corruption I would not expect the end of the string to nicely move ... (I'd expect "/run/user/190249ofi.pid``` or similar)

Can you pastebin/gist the output of:
```
xrdb -query | grep rofi.pid
```
and if you have it, ```~/.config/rofi/config```.

**Comment by infokiller** [comment]
You're correct, of course!
Had a weird setting of the pid file in my xresources. Probably a bad copy paste between my machines. Sorry for the noise and thanks for the quick response!

**Comment by DaveDavenport** [comment]
No problem, happy that it is nothing serious :SMILE:.
Gave me the idea to maybe list in dump-resources who set the option.
