### ISSUE TITLE
unrecognized Shift and Control keys?

### ISSUE THREAD

**Issue by frnsys** [DaveDavenport/rofi#436]
## Version

Version: 1.1.0 (tags/1.1.0)

## Configuration

default config:
https://gist.github.com/frnsys/e669832a002c1f838baeb3465418de30

## Launch Command

`rofi`

## Steps to reproduce

- build rofi from source (checked out tags/1.1.0)
- run `rofi`

## What behaviour you see

The rofi window outputs the following:

> X11 configured keyboard has no *Shift* key
> X11 configured keyboard has no *Control* key
> Sorry, rofi cannot understand the key combination: _Control+Shift+v_
>
> Rofi supports the following modifiers:
>    _Shift, Control, Alt, Super, Meta, Hyper_

## What behaviour you expect to see

The regular rofi window

**Comment by sardemff7** [comment]
Could you add the outputs of `setxkbmap -query` and `xmodmap`? Do you use one of them to do some nasty stuff?

**Comment by frnsys** [comment]
sure thing. I think the only keyboard configuration that I did is enabling the compose key.

output of `xmodmap`:

```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

output of `setxkbmap -query`:

```
rules:      evdev
model:      pc105
layout:     us
options:    compose:ralt
```

**Comment by sardemff7** [comment]
Please compile rofi with the `wip/debug-modifiers` branch, and run it with `G_MESSAGES_DEBUG=all ./rofi` (nothing more, not needed). Then paste me the output (the "DEBUG: Mod:" lines).

**Comment by frnsys** [comment]
Alright, I just did that, but I'm not seeing any output...

here's what I ran:

```
git clone --recursive -b wip/debug-modifiers https://github.com/DaveDavenport/rofi
cd rofi
autoreconf -if
./configure
make
G_MESSAGES_DEBUG=all ./rofi
```

**Comment by sardemff7** [comment]
It should at least yell about the daemon mode being removed… no previous step failed?

**Comment by frnsys** [comment]
No, it looked like everything went without an issue. Is there a particular commit or anything I should be on?

**Comment by frnsys** [comment]
I have no idea what changed - but I on a whim I tried running `rofi` again and it's fine now. Since I opened this issue I did an `apt-get update/upgrade` and restarted my computer, but unfortunately I didn't keep close track if that's what fixed it or not.
