### ISSUE TITLE
Feature suggestion: Raw text input

### ISSUE THREAD

**Issue by vktec** [DaveDavenport/rofi#437]
While making some rofi scripts for interfacing with my window manager, I needed to get arbitrary user input from the user (for renaming a desktop). I would've liked to use rofi for this, as it has a clean, simple interface, but it doesn't seem to support it at the moment (let me know if I missed an option somewhere).

I ended up using Zenity instead, but I prefer rofi's interface and this seems like it would be a fairly trivial thing to add (if it doesn't already exist).

**Comment by carnager** [comment]
As mentioned on IRC:

`bla=$(echo "" | rofi -dmenu -p "Enter Text > "); echo "${bla}"`

**Comment by stevenengler** [comment]
You can also add `-lines 0 -separator-style "none"` to rofi to remove the unused bottom section.

**Comment by DaveDavenport** [comment]
the previous solution is not preferred. With the new theme format  you can disable this listview easily:
```
rofi -show run -theme-str 'listview { enabled: false;}'
```
