### ISSUE TITLE
Broken colors on 30-bit backbuffer

### ISSUE THREAD

**Issue by haasn** [DaveDavenport/rofi#438]
## Version

```
Version: 1.1.0
```

Note: Also happens on git master

## Configuration

https://0x0.st/Bql.txt (completely stock)

## Launch Command

```
rofi -show run
```

## Steps to reproduce

* Set X backbuffer into `Depth 30` mode (in Xorg.conf)
* Launch rofi

## What behaviour you see

![broken](https://0x0.st/Bq6.png)

## What behaviour you expect to see

* Working colors

## Additional info

In case it helps:

xwininfo:
```
xwininfo: Window id: 0x1a00001 "rofi"

  Absolute upper-left X:  1024
  Absolute upper-left Y:  913
  Relative upper-left X:  1024
  Relative upper-left Y:  913
  Width: 2048
  Height: 334
  Depth: 32
  Visual: 0x98
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1a00000 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +1024+913  -1024+913  -1024-913  +1024-913
  -geometry 2048x334+1024+913
```

xdpyinfo:
```
  visual:
    visual id:    0x98
    class:    TrueColor
    depth:    32 planes
    available colormap entries:    1024 per subfield
    red, green, blue masks:    0x3ff, 0xffc00, 0x3ff00000
    significant bits in color specification:    10 bits
```

**Comment by carnager** [comment]
output of `rofi -dump-xresources`?

**Comment by haasn** [comment]
@carnager  It's linked:

> https://0x0.st/Bql.txt (completely stock)

**Comment by DaveDavenport** [comment]
Interresting. Wonder where it goes wrong, given all drawing is cairo.

**Comment by DaveDavenport** [comment]
Possible fix in the  [issue438](https://github.com/DaveDavenport/rofi/tree/issue438) branch.

Can you try?

**Comment by DaveDavenport** [comment]
@sardemff7 We need to see what the right solution is here.

**Comment by DaveDavenport** [comment]
weird, with xephyr  it finds the right visual id, yet xcb_aux_get_visualtype fails. curious.

**Comment by haasn** [comment]
@DaveDavenport That branch fixes it

**Comment by DaveDavenport** [comment]
as @sardemff7 correctly points out, this breaks transparency.

**Comment by DaveDavenport** [comment]
pushed a fix to master, can you try?

This seeks for a 32bit 8bits per channel visual. That seems to render correct in both setups.

**Comment by haasn** [comment]
@DaveDavenport That also seems tow ork.

**Comment by DaveDavenport** [comment]
great thanks.
