### ISSUE TITLE
Rofi working with i3

### ISSUE THREAD

**Issue by ErraticFox** [DaveDavenport/rofi#440]
I'm new to Linux, so I'm looking for a little more guidance. I have Rofi in my i3 cofig with the display with a bunch of setting for how it works. Though I want to config it with the .xresource file, but I don't have the .xresource file in `~/.local/rofi/config` so do I just create this? I only have `shared` in my .local folder. If I am suppose to create my file, do I just add in my theme that I have made in the theme generator?

EDIT: In my i3 config I put 

```bindsym $mod+d exec rofi -show run -color-window "argb:02f3341, argb:0ef6155, argb:0ef6155" -color-normal "argb:02f1e2e, #ffffff, argb:02f1e2e, argb:0815ba4, argb:8e877fab" -color-active "argb:02f1e2e, #815ba4, argb:02f1e2e, argb:0815ba4, #815ba4" -color-urgent "argb:02f1e2e, #ef6155, argb:02f1e2e, argb:0815ba4, #ef6155" -font "System San Francisco Display 18"``` and was greeted by an error saying the command could not be ran.

**Comment by DaveDavenport** [comment]
I try to keep issue tracker for rofi issues, so closing it.  Irc is normally a good place to get support.

Xresources see the archlinux wiki as it is often a good resource: https://wiki.archlinux.org/index.php/x_resources. Using this for configuration is good when you work with remote X connections.
The easier way is to create the `~/.config/rofi/` directory and add a `config` file there, this should be picked up on each run.

You command-line is valid, i3 has some weird escaping issues in its config file.
