### ISSUE TITLE
Option to use single click to select?

### ISSUE THREAD

**Issue by ViktorNova** [DaveDavenport/rofi#441]
I have see this come up somewhere in the past, so a apologize for bringing it up again, but it would be GREAT if Rofi had a configuration option to select items with a single click. I understand this is not the intended use case, which is why I am asking it to be an _option_, but this would make Rofi useful in a wider variety of use cases where the user expects to make their selection with a single click (or touch) and not necessarily with the keyboard

Some examples:
- Confirmation dialogs (yes/no/cancel)
- 'Dropdown' menus (such as choosing a WiFi hotspot with nmcli-dmenu)
- Anything on a touch screen (Rofi would be great for low resource touch devices)

**Comment by DaveDavenport** [comment]
Selection works with a single click. I assume you mean accept?

For me double tapping on my screen nicely accepts the entry.

I wonder if rofi is the right tool here,  given you kinda need a keyboard to use it to its potential.

**Comment by ViktorNova** [comment]
I meant to choose it, yes. It would be nice to at least have the option to accept with a single click.

I could use other tools, but Rofi's compatibility with dmenu makes it kind of irreplaceable!

**Comment by gandalf3** [comment]
Here's another usecase: I'm using rofi with clipster as a clipboard history picker. A lot of my copy/pasting seems to be when I'm doing something mouse-based, so I have rofi appear at the mouse location, making things very convenient for rapid clicking. Unfortunately, that convenience is pretty much canceled out when I have to spend extra time double clicking. 

While I'm about it, I'd also be nice if there was an option to highlight the option under the mouse. That would make visually confirming I'm positioned over the desired option easier (and therefore faster).

**Comment by DaveDavenport** [comment]
@gandalf3  Please keep one request/problem per [issue](https://github.com/DaveDavenport/rofi/blob/master/.github/CONTRIBUTING.md). Can you make a new one about the highlight.

**Comment by gandalf3** [comment]
@DaveDavenport [Sure thing](https://github.com/DaveDavenport/rofi/issues/600) :)

**Comment by sardemff7** [comment]
Please try the `wip/bindings` branch.
Run rofi using: `-me-select-entry '' -me-accept-entry 'Mouse1'`

**Comment by snippins** [comment]
The function seem to be working, but now the open at mouse location function (-m 3) seem to be broken. The menu is off a huge distance to the right of the mouse.

**Comment by DaveDavenport** [comment]
might be broken by the new theming still, will check.

**Comment by sardemff7** [comment]
`wip/bindings` was finalised and merged to `master`.

**Comment by DaveDavenport** [comment]
@snippins if you set anchor and location to north west, it still works.

Via cmdline:
```
rofi    -show run -m -3  -theme-str '#window {anchor: north west; location: north west; }'
```

**Comment by snippins** [comment]
@DaveDavenport Thanks. It works. But I found that my color scheme does not apply anymore. I tried to config with ".Xresources", "~/.config/rofi/config" and command lines. 1.3.1 version still work correctly.
Not sure if you introduce new theming scheme or it is a bug?

**Comment by sardemff7** [comment]
rofi has a brand new theme format in master. Let’s move the discussion to IRC if you have any questions about it.
