### ISSUE TITLE
Password mode cursor mismatch on multi-bytes characters

### ISSUE THREAD

**Issue by sardemff7** [DaveDavenport/rofi#443]
## Version

1.2.0-1-gf066290 (master)

## Configuration

[Configuration file](https://github.com/DaveDavenport/rofi/files/416478/rofi.txt)
Diff to defaults:
```
rofi.color-normal:                   argb:0000000, #bbbbbb, argb:0000000, #586e75, #eee8d5
rofi.color-urgent:                   argb:0000000, #dc322f, argb:0000000, argb:7edc322f, #fdf6e3
rofi.color-active:                   argb:0000000, #268bd2, argb:0000000, argb:7d268bd2, #fdf6e3
rofi.color-window:                   #333333, argb:0002b36, #000000
rofi.kb-row-select:                  Tab
```

## Launch Command

`./rofi -dmenu -input /dev/null -password`

## Steps to reproduce

1. Run rofi
2. Type a few ASCII characters (not mandatory, but making it more obvious)
3. Type a non-ASCII character

## What behaviour you see

The `password` feature is replacing a multiple-bytes character with a one-byte character (`*`). Thus the cursor either disappear or shifts.
And this warning: `Pango-CRITICAL **: pango_layout_get_cursor_pos: assertion 'index >= 0 && index <= layout->length' failed`

## What behaviour you expect to see

Correct cursor

## First analyse

`pango_layout_get_cursor_pos()` expects an index in bytes, relative to its text. In password mode, the input text is different from the layout text.
Code needs to correctly poke the right text, in the right places, and doing index translation where needed.
Not sure there is one place (or a few places) to change, probably spread all other the place.

**Comment by DaveDavenport** [comment]
```patch
diff --git a/source/textbox.c b/source/textbox.c
index 302be53..6b78b7a 100644
--- a/source/textbox.c
+++ b/source/textbox.c
@@ -299,6 +299,9 @@ static void texbox_update ( textbox *tb )
             PangoRectangle pos;
             int            cursor_offset = 0;
             cursor_offset = MIN ( tb->cursor, text_len );
+            if ( (tb->flags&TB_PASSWORD) == TB_PASSWORD ){
+                cursor_offset = g_utf8_pointer_to_offset ( tb->text, tb->text+cursor_offset );
+            }
             pango_layout_get_cursor_pos ( tb->layout, cursor_offset, &pos, NULL );
             // Add a small 4px offset between cursor and last glyph.
             cursor_x = pos.x / PANGO_SCALE;
```

Can you test?

**Comment by sardemff7** [comment]
It works. :-)
