### ISSUE TITLE
Compiz uses 1 desktop, multiple viewports. Rofi always indicates 'Workspace 1'

### ISSUE THREAD

**Issue by sanderboom** [DaveDavenport/rofi#444]
## Version

Output of `rofi -v`
`Version: 1.2.0-1-gf066290-dirty (makepkg)` by Arch linux AUR package: `rofi-git`

## Configuration

Relevant part (the default anyway): 
```
rofi.window-format: {w} {c} {t}
```

## Launch Command
`/usr/bin/rofi -show window`

## Steps to reproduce
* Press rofi shortcut key

## What behaviour you see
* When running compiz WM, the `rofi.window-format` `{w}`-placeholder will always show 'Workspace 1', regardless of the viewport the window is at. 

## What behaviour you expect to see
* Indication of the viewport for a window (while running compiz).

## Extra info:

I spoke to one of the maintainers of compiz-reloaded about this on IRC. He indicated:

> yea it (`rofi`) is probably expecting a wm that uses multiple desktops
> viewports are in EWMH spec but most wm's use desktops
> so that's what's supported primarily by pagers and other apps

Thanks for looking into this!

**Comment by DaveDavenport** [comment]
It uses _NET_WM_DESKTOP and _NET_DESKTOP_NAMES.

I don't have compiz, patch is welcome.

**Comment by DaveDavenport** [comment]
Can you pastebin output of `xprop -root`

**Comment by sanderboom** [comment]
Here it is: http://pastebin.com/07xqjvyT
Thanks for looking into this!

**Comment by DaveDavenport** [comment]
thanks, so it sets _NET_DESKTOP_NAMES correctly.. Can you do the same for 2 windows on different desktops??

(xprop, then click on window).. Thanks.

**Comment by sanderboom** [comment]
Sorry for the delay. Here they are:
- http://pastebin.com/BeQ1Vw3J
- http://pastebin.com/pFaXR4MD

And the diff:
```diff
λ diff viewport1.xprop viewport6.xprop 
1,2c1,2
< _NET_WM_USER_TIME(CARDINAL) = 33292717
< _NET_WM_ICON_GEOMETRY(CARDINAL) = 2376, 1416, 183, 24
---
> _NET_WM_USER_TIME(CARDINAL) = 33268528
> _NET_WM_ICON_GEOMETRY(CARDINAL) = 10, 1416, 184, 24
```

Not so useful, I'm afraid? :/

**Comment by DaveDavenport** [comment]
Problem is they both indicate they are on the first desktop:
```
_NET_WM_DESKTOP(CARDINAL) = 0
```

This is wrong.

**Comment by sanderboom** [comment]
Discussed this is a bit in the #compiz-reloaded IRC channel. Comments pointed to an other software (tint2) that deals with the same issue, and the solution.

> it recently was fixed in tint2 https://gitlab.com/o9000/tint2/commit/eb044da8bc865f3ed8fda91986a1cbf8982c9a2f

> there are plenty of reports about this, here's a simpler preliminary patch https://gitlab.com/o9000/tint2/issues/94#note_2685162

My knowledge on this topic is very limited, but I hope this can provide some inspiration :)

**Comment by DaveDavenport** [comment]
I guess I can make a dirty work-around for compiz. Not very happy about that. (All the code needed is I think already there.)

**Comment by sanderboom** [comment]
Understand. 
Too bad it has to be a 'wm specific hack' and not just 'support for a different standard (viewports instead of desktops)'. I got the impression Compiz is adhering to a standard, although a different one.

**Comment by DaveDavenport** [comment]
Could be. Will check it out.

**Comment by sanderboom** [comment]
Thanks!

**Comment by DaveDavenport** [comment]
I am confused:
GEOMETRY is :  3840, 5400
WORKAREA is : 0 24 1920 1032

(assume FHD)
So that results in 10 desktop (2 wide, 5 high.   (0-1080, 1080-2160, 2160-3240, 3240-4320, 4320-5400) and 0-1920, 1920-3840).
Though I see 8 desktop names.

Also to calculate this (this is what tint does) I also need to know the size of the 'reserved' (dock, panel) space,  that should be indicated by NET_WM_STRUT and NET_WM_STRUT_PARTIAL,  otherwise I am not assuming 1920x1080 but (following tint solution)  1920x1067.

I must be missing something, but this looks like compiz is missing info, and tint's implementation is wrong.

https://specifications.freedesktop.org/wm-spec/1.4/ar01s03.html

**Comment by sanderboom** [comment]
> (assume FHD)
> So that results in 10 desktop (2 wide, 5 high.)
Correct.

> Though I see 8 desktop names.
This could be due to the fact that there is a separate plugin for (re)naming viewports. I think I've used this in the past but switched this plugin off later. It could be 'left over config' (?). Although from your remarks I assume it's quite crucial?

I'll try to come up with some more info on this matter.

**Comment by sanderboom** [comment]
I've tried but did not manage to obtain more information regarding this. Also, In the meantime I've switched from Compiz to i3. 
AFAIC this can be closed. Thanks for the effort.

**Comment by DaveDavenport** [comment]
Ok. closing for now.. Please if anybody hits this again and has more info, re-open (or create new issue referring this this one)
