### ISSUE TITLE
Rofi fails to detect monitor with default value of "-1"

### ISSUE THREAD

**Issue by d125q** [DaveDavenport/rofi#448]
## Version

Output of `rofi -v`:

`Version: 1.2.0-6-ga5acff5-dirty (makepkg)`

## Configuration

Default configuration.

## Launch Command

The commandline used to launch **rofi**:

`rofi -show run`

## Steps to reproduce

* Simply run `rofi -show run` (the mode is irrelevant).

## What behaviour you see

* Error message stating that monitor could not be found.

## What behaviour you expect to see

* `rofi` is shown on the focused monitor.

---

This started happening after the recent update to XRandR.  Adding `rofi.monitor: primary` to `.Xresources` makes `rofi` run properly again, and of course it is always shown on my primary monitor.

**Comment by DaveDavenport** [comment]
What WM do you use, this would indicate that the WM does not set current desktop hint.

The checks have become more 'strict' in the xrandr move, I should probably relax them.
I might need to make the default `-5`, as that should always work, and does what most people expect.

**Comment by d125q** [comment]
I use [`bspwm`](https://github.com/baskerville/bspwm).  You are correct -- it does not seem to set `_NET_DESKTOP_VIEWPORT` which is required for the handling of `"-1"`.

**Comment by DaveDavenport** [comment]
I think we should put default on something that won't complain :smile:

**Comment by DaveDavenport** [comment]
I picked another default, also it should translate the -X number in something more readable.

Thanks.
