### ISSUE TITLE
Rofi 1.2 with `eh > 1` does not vertically center text

### ISSUE THREAD

**Issue by deuill** [DaveDavenport/rofi#449]
## Version

`Version: 1.2.0`

## Configuration

[`rofi -show-xresources`](https://gist.github.com/deuill/70a02e396096b958c3890c636ab31968)

## Launch Command

`rofi -show run -eh 2`

## Steps to reproduce

* Upgrade to 1.2.0
* Execute rofi with `-eh 2`
* Text is not vertically centered

## What behaviour you see

![rofi-1 2](https://cloud.githubusercontent.com/assets/1138950/17831042/ceefd62c-66d6-11e6-9e1e-a19328f7f666.png)

## What behaviour you expect to see

![rofi-1 1](https://cloud.githubusercontent.com/assets/1138950/17831043/ceefaaee-66d6-11e6-8c52-2e7d76b84102.png)

**Comment by deuill** [comment]
Not certain if this is intentional, a regression, or simply not an issue, but thought I might just open a ticket anyways. Thanks!

**Comment by DaveDavenport** [comment]
This was done intentional,  `-eh` mode was added for multi-line entries. Did not assume it would be used for layouting.

**Comment by deuill** [comment]
Understood -- I find it easier to scan through the listings with a taller line-height, but I suppose using `eh` is kind of a hack.

**Comment by DaveDavenport** [comment]
Internally there is a define indicating row margin. I can see if I can pull this out.
I agree there is a thing to say for extra visual separation.

Btw do you want a margin between rows or extra padding within rows?

**Comment by DaveDavenport** [comment]
Just remember, I already exposed the spacing between the lines before. Option:
`-line-margin' it is even in the docs. (yay for me!)

**Comment by deuill** [comment]
Thanks, `-line-margin` helps, not exactly the same visually but it'll do! You can close this if you want.

**Comment by notantonia** [comment]
Line margin is nice for separating out the entries, but is there a way to also highlight this margin when going through entries?

**Comment by deuill** [comment]
It would be more of a padding then (if we're going with CSS-style names), which is what `-eh` approximated previously.
