### ISSUE TITLE
Failed to get keyboard compose table.

### ISSUE THREAD

**Issue by krypttr** [DaveDavenport/rofi#450]
## Version

Version :  1.2.0
## Configuration

https://gist.github.com/krypttr/f1fed28253faac2788bc8ef87693d32d
## Launch Command

rofi
## Steps to reproduce

run rofi
## What behaviour you see

On Screen:
Sorry rofi cannot understand the key combination: Shift+Insert

On Console:
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:175:17: unrecognized keysym "i" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:177:17: unrecognized keysym "i" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:179:13: unrecognized keysym "I" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:180:13: unrecognized keysym "I" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:181:13: unrecognized keysym "i" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:235:13: unrecognized keysym "Cyrillic_IE" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:236:21: unrecognized keysym "Cyrillic_IE" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:629:14: unrecognized keysym "I" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:630:21: unrecognized keysym "I" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:631:13: unrecognized keysym "I" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:632:14: unrecognized keysym "I" on left-hand side
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:632:14: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/en_US.UTF-8/Compose:632:14: failed to parse file
Failed to get keyboard compose table. Trying to limp on.

locale
LANG=tr_TR.utf8
LC_CTYPE="tr_TR.utf8"
LC_NUMERIC="tr_TR.utf8"
LC_TIME="tr_TR.utf8"
LC_COLLATE="tr_TR.utf8"
LC_MONETARY="tr_TR.utf8"
LC_MESSAGES="tr_TR.utf8"
LC_PAPER="tr_TR.utf8"
LC_NAME="tr_TR.utf8"
LC_ADDRESS="tr_TR.utf8"
LC_TELEPHONE="tr_TR.utf8"
LC_MEASUREMENT="tr_TR.utf8"
LC_IDENTIFICATION="tr_TR.utf8"
LC_ALL=
## What behaviour you expect to see

Rofi to run properly

**Comment by DaveDavenport** [comment]
Have you looked at this? https://github.com/DaveDavenport/rofi/wiki/xkbcommon-FAQ

**Comment by krypttr** [comment]
I did actually. Changing my locale to tr_TR.UTF-8 also does not work.  

Here is the relevant line from compose.dir

en_US.UTF-8/Compose:		tr_TR.UTF-8

**Comment by sardemff7** [comment]
It seems to complain about missing keysyms, are they missing for real? Does your layout have them?

**Comment by krypttr** [comment]
From what I understand tr_TR.UTF-8 line in compose.dir file points to /usr/share/X11/locale/en_US.UTF-8/Compose file. 

Here is my keyboard layout.
http://www.datacal.com/store/images/turkish-q-deadkeys.gif

**Comment by sardemff7** [comment]
Ping @xkbcommon

**Comment by DaveDavenport** [comment]
closing for now. Will re-open if needed..
