### ISSUE TITLE
Make rofi lose focus

### ISSUE THREAD

**Issue by bharadwaj-raju** [DaveDavenport/rofi#458]
There should be an option to make it
- lose focus on clicking outside
- start unfocused

`-normal-mode` comes close, but has a titlebar, unfortunately.
## Version

Output of `rofi -v:

Version: 1.1.0-71-g6495d8e-dirty (makepkg)
## Configuration

Output of `rofi -dump-xresources`:

https://gist.github.com/bharadwaj-raju/bc92f4444d3436bdfcc45da53c9cb168.

I've not changed anything, though.
## Launch Command

The commandline used to launch **rofi**:

``` bash
$ echo "list|of|items" | rofi -dmenu -fuzzy -sep "|" -p "> "
```
## Steps to reproduce
- Launch above command line
- Try to click outside and hope it remains and loses focus.
## What behaviour you see
- Rofi maintains focus.
## What behaviour you expect to see
- Rofi should remain on screen, but lose focus.

Another thing that is nice-to-have: An option to make it start unfocused, unless it is explicitly focused.

**Comment by DaveDavenport** [comment]
No. I don't see a reason to change this behavior. (current behavior matches dmenu).
Can you give a good reason why this behavior should change?

Normal window mode sounds like what you want,  maybe tell  your window  manager not to draw a titlebar around it.

**Comment by bharadwaj-raju** [comment]
Yes, current behaviour is fine for most, should not change, I am asking for an *option*.

Also, yes, I'll look into preventing the window borders.

**Comment by DaveDavenport** [comment]
Ok, any good reason/use-case for the added option?

**Comment by bharadwaj-raju** [comment]
Rofi as auto-completion (see [TextSuggest](https://github.com/bharadwaj-raju/TextSuggest)).

**Comment by DaveDavenport** [comment]
I don't follow, why would you want to keep the window open when it has no focus?

**Comment by bharadwaj-raju** [comment]
We want to, say, provide *optional* completion, wherein the user continues to type like normal, but on focusing the Rofi window, they can the search, choose, etc.

**Comment by DaveDavenport** [comment]
Aah ok, I get that. Need to test, not sure if that is going to work.

**Comment by DaveDavenport** [comment]
On the latest git  with [this](https://filebin.pw/PXw/) patch. rofi -normal-window -dmenu should show no window border. (If the WM obeys the MOTIF_WM_HINTS, i3  does.)

**Comment by DaveDavenport** [comment]
Clearing milestone. Need more feedback on what is needed to make this possible.
Not sure if current dmenu mode provides enough options.

Current git what would be possible to add (not sure if desirable):
 - Reposition rofi  on signal/new input. (so it can be placed near mouse again)
 - Continuously stream in new entries (possible now with the async dmenu mode)
 - Clear the dmenu entries somehow (unsure how to implement cleanly?)

**Comment by DaveDavenport** [comment]
closing.  last list are separate issues some with larger impact .
