### ISSUE TITLE
Deleting characters or moving the cursor does not force the cursor to reappear

### ISSUE THREAD

**Issue by fice-t** [DaveDavenport/rofi#462]
## Version
`Version: 1.2.0-50-g71f5f1a (master)`

## Configuration
Default config.

## Launch Command
`rofi`

## Steps to reproduce

* Type some characters and wait until the cursor blinks off
* Press backspace or move the cursor (`Control-b`, `Control-f`, `Alt-b`, etc.)

## What behaviour you see

* - The cursor does not immediately reappear.

## What behaviour you expect to see

* - The cursor immediately reappears as would happen if you typed a character when the cursor wasn't shown.

**Comment by DaveDavenport** [comment]
Can you test commit?

**Comment by fice-t** [comment]
Looks like it's fixed, thanks.
