### ISSUE TITLE
Feature request: make the "run: " string customizable

### ISSUE THREAD

**Issue by adtac** [DaveDavenport/rofi#463]
Not really an issue - when I run rofi in run-mode, I get a `run: ` prompt. I'd like that string to be customizable.

Thanks :) Great utility :+1:

**Comment by sardemff7** [comment]
`rofi -show run -display-run 'not run'` :-)

**Comment by alex-chew** [comment]
Is there a way to remove the colon as well, so that the entire prompt line is customizable? It looks like the colon is hardcoded right now:

from https://github.com/DaveDavenport/rofi/blob/master/source/rofi.c#L163
```
static void __run_switcher_internal ( ModeMode mode, char *input )
{
    char          *prompt = g_strdup_printf ( "%s:", mode_get_display_name ( modi[mode] ) );
    curr_switcher = mode;
...
```

**Comment by sardemff7** [comment]
Using the `wip/combi-markup` (that I need way more testers for) you can do:
`rofi -show run -display-run '<span size="0">' -display-close-run '</span>'`

**Comment by bentinata** [comment]
What's the status of this issue?
If I make a PR for just the prompt, would it be accepted?

**Comment by DaveDavenport** [comment]
The issue is closed.

**Comment by bentinata** [comment]
I'm referring to https://github.com/DaveDavenport/rofi/issues/463#issuecomment-249392170.
That colon also bugged me.
Should I make new Issue?
@DaveDavenport

**Comment by alex-chew** [comment]
Have you tried the -p (prompt) option? I'm on version 1.3.1 and the following displays a fully customizable prompt: `echo -e "choice a\nchoice b\nchoice c" | rofi -dmenu -p "no colon prompt "`

**Comment by bentinata** [comment]
@alex-chew
That options is `-dmenu` specific.
I want to use `rofi` run mode because it seems cleaner than making custom scripts to pass to `dmenu`.
Thanks for your suggestion though.

**Comment by DaveDavenport** [comment]
Please create a new issue for this. Issue highjacking is very annoying for me.

In short this is a no way to please everybody issue  (had ':' removed for a while so it could be set in -display-name, but people complained (validly) that this messed up the sidebar/combi ). That can only be solved by adding X extra options again.

**Comment by bentinata** [comment]
@DaveDavenport
Sorry to annoy you.
I guess I get the reasoning behind, and I don't want to add more options; thanks.
_I got my own patch built._
Closing this.
