### ISSUE TITLE
Window switcher does not show/switch to i3 scratchpad window

### ISSUE THREAD

**Issue by viering** [DaveDavenport/rofi#464]
## Version

Output of `rofi -v`
Version: 1.2.0 and Version: 1.2.0-50-g71f5f1a (master)

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
https://gist.github.com/viering/65efa5f21c0a2f7b2ab846b5b6a60eb4

## Launch Command

The commandline used to launch **rofi**
rofi  -combi-mode run,window -show combi

## Steps to reproduce

* Step 1 Have an application open and have it on a i3 scratchpad
* Step 2 Use rofi window switcher to switch to this application 

## What behaviour you see

* rofi sometimes switches the workspace however the application from the i3 scratchpad is not shown. 

## What behaviour you expect to see

* Show the application which is on a i3 scratchpad

If I compile rofi 1.1.0 then I can switch to i3 scratchpad windows.

**Comment by DaveDavenport** [comment]
Seems that I3 EWMH implementation lacks this. I removed the 'work-around' for i3 in 1.2 as it was no longer needed for switching between apps.

@airblader opinion about this?

**Comment by Airblader** [comment]
Mh, this is indeed an interesting case. There seem to be two issues at hand:

1. The fact that i3 doesn't remove `_NET_WM_DESKTOP` for windows in the scratchpad. In fact I'm not sure removing is correct, but we'd have to read the specs and figure out a good way to handle this. This isn't too relevant for this issue, though.
2. i3 rejecting `_NET_ACTIVE_WINDOW` client messages if the window is on an internal workspace (= the scratchpad). I actually think it would make sense to change i3 here to behave as if `scratchpad show` was called. This should also fix this issue. I'll raise a ticket on our side for this.

**Comment by Airblader** [comment]
I've opened https://github.com/i3/i3/issues/2456 and https://github.com/i3/i3/issues/2455.

**Comment by DaveDavenport** [comment]
absolutely brilliant, thanks.

**Comment by Airblader** [comment]
@viering I've posted a patch in https://github.com/i3/i3/issues/2455, could you perhaps try applying that and check if it works then?

**Comment by Airblader** [comment]
https://github.com/i3/i3/issues/2456 now also has a patch. @viering Try applying both and see if it fixes everything.

**Comment by viering** [comment]
Will try it on Monday and then report back.

**Comment by Airblader** [comment]
@viering Never mind, I've tested them myself now and they work (well, I modified the solution slightly). The PRs are pending now.

**Comment by viering** [comment]
ok thanks

**Comment by DaveDavenport** [comment]
Thanks!!!
