### ISSUE TITLE
rofi in run mode doesn't display unique candidate anymore

### ISSUE THREAD

**Issue by Coacher** [DaveDavenport/rofi#467]
## Version

Output of `rofi -v`
Version: 1.2.0-59-gacdb6bd-dirty (git-r3/HEAD)

## Configuration

Output of `rofi -dump-xresources` (preferable in a [gist](https://gist.github.com/))
https://bpaste.net/show/c60499508a2b

## Launch Command

The commandline used to launch **rofi**
`rofi -modi run -show run`

## Steps to reproduce

* Open rofi and start typing command's name until the command becomes the only one left.

## What behaviour you see

* - rofi doesn't display the command as a candidate anymore. No candidate is shown at all.

## What behaviour you expect to see

* - rofi still displays the command as a candidate.

**Comment by Coacher** [comment]
Not reproducible with rofi @ cf70fbf7

**Comment by DaveDavenport** [comment]
Can you take screenshot?  
Does `-fixed-num-lines` fixes the issue.

( I currently cannot reproduce, might be a rounding issue somewhere.)

**Comment by Coacher** [comment]
> Can you take screenshot? Alt-Shift-S

This is a cool feature I didn't know about. :)
Here's a step-by-step candidate elimination:
https://imgur.com/a/oES2L
https://imgur.com/a/OZfJV
https://imgur.com/a/hpGZ9
https://imgur.com/a/5Rjll

> Does -fixed-num-lines fixes the issue.

Yes.

**Comment by DaveDavenport** [comment]
thx.

**Comment by DaveDavenport** [comment]
Can you check last commit?

**Comment by Coacher** [comment]
I can confirm that `Version: 1.2.0-61-gca766b4-dirty (git-r3/HEAD)` fixes the problem.
Thank you very much!
