### ISSUE TITLE
[request] Add an option to make rofi window only resize and not move, when eliminating candidates

### ISSUE THREAD

**Issue by Coacher** [DaveDavenport/rofi#469]
Hello.

The recent feature that reduces the window size when there are few candidates is cool and in general I like it very much. The only downside is that when window shrinks, it gets repositioned too. It would be nice to have an option to make it not repositioned. Please add such option.

Current:
```
________
|      |        __________
|      |  -->   |________|
|______|
```
Requested:
```
________        __________
|      |        |________|
|      |  -->
|______|
```

Rationale: the typed command is always at the same level and I don't need to adjust my line of sight.

**Comment by DaveDavenport** [comment]
Yeah, wasn't sure about this one yet.

One thing you can do is change the 'anchor' of the window:
```
rofi -location 2 -yoffset 400 -show run
```

Will keep the top at fixed offset.

**Comment by DaveDavenport** [comment]
Changed in git. please test.

**Comment by Coacher** [comment]
Works perfectly with `Version: 1.2.0-65-g0da0587-dirty (git-r3/HEAD)`.
Thank you very much!
