### ISSUE TITLE
(not so) Configurable command completion

### ISSUE THREAD

**Issue by 4DA** [DaveDavenport/rofi#470]
## Version

Version: 1.2.0

## Configuration
https://gist.github.com/4DA/0a44d99d673fb1aea129e81b30e08fc4

## Launch Command
rofi -show run

## The problem
Rofi's command completion sometimes doesn't do what I mean.
Suppose i want to start emacs, but that's what I see as the default behaviour.
http://dump.bitcheese.net/images/rymykow/2016-09-21-203953_1920x1200_scrot.png

Thanks.

**Comment by DaveDavenport** [comment]
Enable levenshtein sort?

**Comment by 4DA** [comment]
thanks
