### ISSUE TITLE
Wrong command run

### ISSUE THREAD

**Issue by mmarquezs** [DaveDavenport/rofi#471]
## Version

Version: 1.2.0

## Configuration

https://gist.github.com/mmarquezs/f131e0edfd7343484aaefdae0b6e3480

## Launch Command

rofi -show run

## Steps to reproduce

* Execute a command on rofi  like this one: 

> program --test

* After that execute the command on rofi : 

> program -test

## What behaviour you see

* Instead of executing the last command, **program -test** , it executes the first one, **program --test** , again. When writing the last command the first one is suggested all the time even when it clearly different,it's like it ignores the difference between (--) and (-).

## What behaviour you expect to see

* I expect to run **program -test** when typing **program -test** instead of **program --test**.

**Comment by DaveDavenport** [comment]
It is actually behaving correctly, it finds and executes the best match. This is the default functionality of rofi.

This is not what you want, you want to ignore the match and execute what you want.
You need to tell rofi that you want to deviate from the default behavior (it cannot guess what you intend todo).

So for you I see three solutions:

1.) Tell rofi that you don't want to execute the best match, but the entered command:   Ctrl-Enter (kb-accept-custom)

Or fix the 'wrong' match:
2.) Remove the wrong entry from history, shift-delete (kb-delete-entry), so it does not match anymore.
3.) Make the matching more strict so it does not match. (disable tokenize)
