### ISSUE TITLE
Why was JSON support removed from rofi

### ISSUE THREAD

**Issue by IvanMalison** [DaveDavenport/rofi#472]
...? I would like to use this to more easily handle arbitrary text that could come from the command that I would like to pipe in to rofi. There is no separator that I can reliably use which makes my usecase nearly impossible without more structured input.

**Comment by DaveDavenport** [comment]
A few things:

1.) You are very unclear about what you mean.  I will assume you talk about dmenu mode? (because of piping in information)
2.) You don't give a/explain the use-case. Making it hard for me to a.) understand, b.) help.
3.) No indication of when it was removed.
4.) Did not follow the rules for reporting issue.
5.) It seems to be completely random and no research what-so-ever have been done. (see first part of answer)

I will try to answer.

There never was json support in **rofi** its dmenu mode Or in rofi at all. 

You can override the separator and use any, possibly non printable, ascii characters. For example \0 should allow you to get any displayable data into rofi.

Please if you file a report take the time to investigate, be clear and precise. You do expect me to take time to investigate and formulate an answer.

**Comment by IvanMalison** [comment]
> 1.) You are very unclear about what you mean. I will assume you talk about dmenu mode? (because of piping in information)

Yes, I was speaking about dmenu mode
 
> 2.) You don't give a/explain the use-case. Making it hard for me to a.) understand, b.) help.

The use case is the selection of something from my clipboard history which could contain any arbitrary character. Using \0 was an idea that occured to me as well, but that would likely be more difficult/less general IMO. Having JSON input seems much tidier to me.

> 3.) No indication of when it was removed.

See commit 8edac70 for when json was removed....

`git log -S json` is pretty freaking useful...

> 4.) Did not follow the rules for reporting issue.

This is because I'm not reporting an issue with rofi, I'm simply asking a question about why json support was removed

> 5.) It seems to be completely random and no research what-so-ever have been done. (see first part of answer)

REALLY? I don't understand your hostility at all. I DID actually go through the trouble of doing a git search for json support, and I noticed it was removed in a commit in the history. The fact that it was removed seemed strange to me, as no reasoning was given in the commit, but I assumed that there must have been a reason, so I figured I would ask here.

Have you noticed that I haven't supplied ANY additional information here that would help you answer the question, except maybe the exact commit where it WAS, in fact, removed? It seems reasonable to assume that the owner of a repository would know about the history of a project (and know how to use git) which is why it did not even occur to me to provide it.

**Comment by DaveDavenport** [comment]
I apologize for the json, that was a completely failed experiment i removed in 2 days and a few minutes (see git log) of adding it , forgot that ever hit master. This was a completely failed experiment.
Sorry that was a rash reply of me. (I get a lot of poorly researched bug reports that just cost me a lot of time)

>  Have you noticed that I haven't supplied ANY additional information here that would help you answer the question, except maybe the exact commit where it WAS, in fact, removed? It seems reasonable to assume that the owner of a repository would know about the history of a project (and know how to use git) which is why it did not even occur to me to provide it.

Yes, you did provide more information about the use-case, this does help  explain a lot to me what you are trying to do.

**Comment by DaveDavenport** [comment]
Feedback based on your usecase: 

For a clipboard what I would suggest todo make a script collect the different entries,  formulate a 'displayable' string for each and pass that to rofi, then make rofi (using the `-format` parameter) return the index of the choosen reply. Then you can use other commands to display it.

There is no point in passing rofi binary information, as it is most likely unable to display it and will reject/modify it anyway if it is invalid UTF-8.

**Comment by IvanMalison** [comment]
@DaveDavenport thanks for the reply. I'll take a look and post what I end up doing here for future reference in case anybody wants to do something similar.

**Comment by DaveDavenport** [comment]
There seems to be a nice list of dmenu based clipboard tools:

- https://github.com/cdown/clipmenu
- https://github.com/trapd00r/clipbored
- https://github.com/seven1m/dwm/blob/master/bin/dclip
- https://github.com/Excerion/cliphist

**Comment by DaveDavenport** [comment]
locked -> question.
