### ISSUE TITLE
The drun switcher has not been enabled

### ISSUE THREAD

**Issue by psamim** [DaveDavenport/rofi#474]
## Version

Version: 1.2.0-61-gca766b4-dirty (master)

From AUR rofi-git on Archlinux

## Configuration

https://gist.github.com/psamim/024ae6ec10f8947e17a1b222a8b6ece4

## Launch Command

 rofi -show drun

## Steps to reproduce

* Step 1
Run ` rofi -show drun`

## What behaviour you see

- Below error:

```
The script command 'drun' has 1 options, but needs 2: <name>:<script>.
Invalid script switcher: drun
The drun switcher has not been enabled
```

## What behaviour you expect to see

 - Rofi with desktop entries

**Comment by psamim** [comment]
I found out that drun mode is disabled by default and should be enabled at compile time by adding `--enable-drun` in the configure options.

**Comment by xaviervalarino** [comment]
For posterity, if anyone gets this error message when trying to run rofi in "single-shot" mode, enable drun with the `--modi` option:

```
rofi -modi drun -show -drun
```

**Comment by DaveDavenport** [comment]
Please do not hijack issues with unrelated stuff.

**Comment by DaveDavenport** [comment]
Added explanation to F.A.Q on wiki: https://github.com/DaveDavenport/rofi/wiki
