### ISSUE TITLE
Is there any way to align the text in the middle horizonally?

### ISSUE THREAD

**Issue by jamespanda** [DaveDavenport/rofi#475]
man rofi and find no solution...

**Comment by DaveDavenport** [comment]
No.

**Comment by jamespanda** [comment]
thanks...i think i need to study more to achieve this goal...

**Comment by DaveDavenport** [comment]
If you want to hack it in,  textbox.c and pango_set_alignment.

**Comment by jamespanda** [comment]
i want to make a script to detect the appropriate width to insert text...no plan to modify the source code and have to ability to do that
