### ISSUE TITLE
Setting a global hotkey (think I may be missing something)

### ISSUE THREAD

**Issue by CrashyBang** [DaveDavenport/rofi#476]
## Version

`0.15.11`

## Configuration

https://gist.github.com/CrashyBang/89c8bab0cd0633c7c03290c348b4bb3f

## Launch Command

`rofi -show run`

## Problem

I think I am missing something, how should one set up a **Global Hotkey** is that a config option for `rofi` or should it be set at a system level with the _launch command_?

**Comment by DaveDavenport** [comment]
**rofi** does not bind global hotkeys, use your DE/WM or separate hotkey tool to lauch it.

**Comment by DaveDavenport** [comment]
How do you expect me to do that?  a.) i don' t know what distro you run.  `apt-get` is not enough information. b.) I have no power over what version distributions ship.
