### ISSUE TITLE
Padding and switching monitors

### ISSUE THREAD

**Issue by sanderboom** [DaveDavenport/rofi#477]
## Version

```
λ rofi -v
Version: 1.2.0-1-gf066290-dirty (makepkg)
```
## Configuration

http://pastebin.com/VxP9yVfw
## Launch Command

`/usr/bin/rofi -show window`
## Steps to reproduce
- Launch rofi
## What behaviour you see
- On the integrated laptop display panel (1920x1080) rofi covers the whole screen, with the output listed centered vertically and horizontally. 
- After I plug-in a external monitor (2560x1440) and make this the primary display and launch rofi, the display is not fully covered by the rofi background. 
## What behaviour you expect to see
- Have combination of fullsceen + padding that works cross monitor/resolution.

I might be overlooking an combination of settings. As this is a common usage scenario (me thinks) I could be emphasized more clearly. I'd be glad to update docs.

Thanks!

**Comment by DaveDavenport** [comment]
I am confused. What is the exact problem. 

Your config also does not suggest you have fullscreen enabled, you are running stock.

**Comment by sanderboom** [comment]
My bad. I thought `rofi -dump-xresources` would dump the current config.

Here is the conf file: http://pastebin.com/LgLnYZxT

> What is the exact problem.

The goal is to have rofi 
- always fullscreen and 
- always have the output centered and
- always have the same amount of lines displaying.

'Always' refers to: when switching different monitors with different resolutions.

As centering the output can only be accomplished by using `padding: int` in pixels (AFAIK), he config should be: 
- smaller monitor, 1920x1080: `padding: 450`
- bigger monitor, 2560x1440: `padding: 600`

- What happens when I adjust the rofi config for the bigger monitor and I switch to the smaller monitor:
> The configration failed to validate:
> `config.padding + config.menu_bw=600` is too big for the minimum size of the monitor: 1080.
> Please update your configuration.

BTW. While playing around, I can find a setting for `padding` that gives a good-enough result on both monitors. An option to set `padding` as % (like `width`) would be nice though. Or another way to center the output, regardless of monitor resolution.

Thanks.

**Comment by DaveDavenport** [comment]
(-dump-xresources normally should dump current configuration)

When going to fullscreen mode the window size is no longer determined by the number of visible lines, it reverses to windows size determining the number of lines.

I could add an option to change this behavior, but it is *yet* another option. I think it is getting to the point where it might be discuss another method for configuring the looks of rofi, (CSS? ) we are getting **way** to many options.
Given I am currently overhauling the 'ui' part of rofi (see qtk_widgets branch) now might be the right time. @carnager, @sardemff7  ideas on this?

(padding as percentage does not sound bad.)

**Comment by DaveDavenport** [comment]
Current (on themer branch) theme format allows you to specify percentage in terms of current monitor size.
So you can do:
```
   padding: 10%;
```
To get a 10% padding around all the sides  (or per side, all is possible now).

**Comment by sanderboom** [comment]
Thanks for all the hard work! Rofi rocks!

**Comment by tmzhuang** [comment]
Could someone give me an example of what using this in the rofi config would look like?

**Comment by DaveDavenport** [comment]
See the included themes for examples.

**Comment by tmzhuang** [comment]
Okay great, I got the padding with % to work using the mainbox class as
shown in the Onedark theme. Is the theme schema for the rasi config
documented anywhere? I couldn't seem to find it. Thanks for your help!

**Comment by DaveDavenport** [comment]
See the rofi-theme manpages that is included.

**Comment by tmzhuang** [comment]
Fantastic! Thanks again for your help. Rofi is fantastic! Thanks for
sharing this great tool :)
