### ISSUE TITLE
[Request] Provide a way to disable vertical separators around the input field

### ISSUE THREAD

**Issue by Coacher** [DaveDavenport/rofi#479]
Hello.

I am using rofi `1.2.0-70-gf329880-dirty (git-r3/HEAD)`. Recently vertical separators around the input field were introduced. These separators can be seen at least in run and window modes.
Could you please add an option to disable/hide them, i.e. an option to return to the previous behaviour?
I didn't find relevant info in the man page.

Image where the problematic separators can be seen: https://i.imgur.com/Csz9V9u.png
Previous (desired) behaviour: https://i.imgur.com/ghy5DNj.png

**Comment by DaveDavenport** [comment]
That is not a separator, that is the window background color you see there. 
It looks like your theme has a different bg color for the text input field and the window background.

**Comment by Coacher** [comment]
Hmm. My rofi config is
```
rofi.threads:        2
rofi.font:           Dejavu Sans Mono 10
rofi.color-window:   #adadad,#4d4d4d,#4d4d4d
rofi.color-normal:   #dadada,#000000,#cdcdcd,#008cc8,#fcfcfc
rofi.color-urgent:   #dadada,#000000,#cdcdcd,#008cc8,#fcfcfc
rofi.color-active:   #dadada,#000000,#cdcdcd,#008cc8,#fcfcfc
rofi.hide-scrollbar: true
```
I haven't touched it for months, yet those 'separators' did appear suddenly.

**Comment by DaveDavenport** [comment]
I fixed the way widgets are placed in the gui, instead of hardcoded they now use horizontal/vertical boxes for packing.
This also fixed the issue that on the input bar the margins where not applied (those are the pieces of background  you see).

So, this is intended behaviour.

**Comment by DaveDavenport** [comment]
given discussion on theme format will take atleast another 20 months with the current progress I removed the padding.

**Comment by Coacher** [comment]
Works like a charm now. Thank you very much!

**Comment by DaveDavenport** [comment]
np. Hopefully we can converge on a nice theme format where more can be customized. (or not)

**Comment by Coacher** [comment]
Is that theme discussion public? Can I take a peek?

**Comment by DaveDavenport** [comment]
We mostly discuss things on IRC. It ain't that active.
