### ISSUE TITLE
fzf matching option

### ISSUE THREAD

**Issue by JelteF** [DaveDavenport/rofi#480]
I've been trying the `-matching fuzzy` option added in the git version of rofi and it works quite okay. But the sorting seems to be done quite eagerly and not done based on what match is better. 

`fzf` does this much better IMHO, so it might be good to see if something similar could be implemented in rofi: https://github.com/junegunn/fzf/blob/master/src/algo/algo.go
Or a second option is having an fzf matching option, although I'm not sure how easily it could be used intermediate program.

**Comment by DaveDavenport** [comment]
Patch is welcome.

**Comment by JelteF** [comment]
I just checked out what is possible with fzf and I think it should be relatively easy have it as a filter:
Because you can send it lines through STDIN and get its shown output in order on STDOUT:
```bash
$ printf 'aaab\nabbb\nccca' | fzf --filter ab
abbb
aaab
```

You can see the difference with rofi this way (and then typing "ab"):
```
printf 'aaab\nabbb\nccca' | rofi -dmenu
```
It will first show aaab, even though abbb starts with the search key and is thus more likely to be the desired match.

I wouldn't mind helping out with this, but I'm not sure where to integrate this as the other match options are all translated to a regex. If you could give me a pointer that would be great.

**Comment by DaveDavenport** [comment]
Matching, sorting is something different.
You want sorting to change, I think matching is fine.

**Comment by blueyed** [comment]
I am also interested in this.
@DaveDavenport 
Can you provide us some pointer?  /cc @junegunn

**Comment by DaveDavenport** [comment]
With rofi two things happen, it calculates if it is a match, and then a 'weight' for sorting.

This happens in `view.c:filter_elements`. Beware this runs in multiple threads and needs to be thread safe.

**Comment by DaveDavenport** [comment]
Also keep in mind that the matching and scoring should be utf8 aware.  I am not sure (when looking at the code) that the fzf matching is.
