### ISSUE TITLE
Rofi ignores Path entry in .desktop files

### ISSUE THREAD

**Issue by mgoral** [DaveDavenport/rofi#482]
Hello,

according to [XDG Desktop Entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html), desktop files accept `Path` entry, which modifies working directory of run program:

> Path: If entry is of type Application, the working directory to run the program in.

Rofi doesn't change working directory of run program and leaves it the same as Rofi's one. 

## Version

Version: 1.2.0

## Configuration

[gist](https://gist.github.com/mgoral/50b5b9a2bda3cc93e65524513620f1cf)

## Launch Command

rofi -show drun

## Steps to reproduce

* Create the following .desktop file wherever it can be accessed by Rofi (e.g. in "$HOME/.local/share/applications"):

    ```
    [Desktop Entry]
    Encoding=UTF-8
    Name=test pwd
    Type=Application
    Path="/etc"
    Exec="pwd"
```

* cd && rofi -show drun
* select "test pwd" from the list

## What behaviour you see

Application prints my home path.

## What behaviour you expect to see

Application should print "/etc".

**Comment by DaveDavenport** [comment]
Fix in Git.. 

Is that desktop file correct? I think Path and Exec should not have "'s around them?

**Comment by mgoral** [comment]
Thanks. :)

I think they both can (and sometimes must) be quoted [spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html):

> Arguments may be quoted in whole. If an argument contains a reserved character the argument must be quoted. The rules for quoting of arguments is also applicable to the executable name or path of the executable program as provided.

So the following is correct Exec entry for example:

```Exec="ls" "-hal" "/home/something something"```

**Comment by DaveDavenport** [comment]
Hmm `g_key_file_get_string`  includes the quote, for the Path that is an issue (Exec is fine).

**Comment by mgoral** [comment]
Hmm... After a second thought I think that only Exec can be quoted and by "path" they either mean full program path (/bin/ls instead of ls) or field code after program name (%u, %U, ...). Quick grep through some of Desktop files on my system shows that there is no file with quoted Path.

**Comment by DaveDavenport** [comment]
Kay. Thanks for the report.
