### ISSUE TITLE
When in drun mode, Desktop files in subdirs are not found, except when ending with ".desktop"

### ISSUE THREAD

**Issue by KuttKatrea** [DaveDavenport/rofi#484]
## Version

Version: 1.2.0-65-g0da0587-dirty (master)

## Configuration

[gist](https://gist.github.com/KuttKatrea/e12edfd616bc747d0f12d2b74e7b15c7)

## Launch Command

rofi -mode drun -show drun

## Steps to reproduce

* Create a subdir `chrome-profiles` in `~/.local/share/applications`
* Place a valid .desktop file there ([Desktop File](https://gist.github.com/KuttKatrea/7799fcd5a94210408a4df62e54056384))
* Run rofi in drun mode `rofi -mode drun -show drun`
* Type `chrome`

## What behaviour you see

* The default `Google Chrome` entry is shown

## What behaviour you expect to see

* The default `Google Chrome` and also the custom `Google Chrome (Developer)` entries should be shown

It seems to be a partial regression from #416

**Comment by DaveDavenport** [comment]
Fix in git, please test.

**Comment by KuttKatrea** [comment]
Tested, it's working, thanks
