### ISSUE TITLE
Rofi does not work well with custom layouts

### ISSUE THREAD

**Issue by AlexDaniel** [DaveDavenport/rofi#485]
## Version

Version: 1.2.0
## Configuration

Default
## Launch Command

Any
## Steps to reproduce

Configure your xkb layout to have some non-letter keys on the third level. For example:

```
key <AC05> { [ i, I, BackSpace, BackSpace ] };
```

Alternatively, try some layout that already has it (Neo?).

Then try using this key in rofi (AltGr+key).
## What behaviour you see

Rofi does not recognize Backspace, Delete, Left, Right or any other non-letter key.
## What behaviour you expect to see

I expect Backspace to work as Backspace, just like it does in any other program.

**Comment by DaveDavenport** [comment]
Rofi sees the key as 'Alt-Backspace'.  To see this, start rofi with: ' -kb-remove-char-back Alt+Backspace,Backspace'. Then it works.

@sardemff7 do you have any solution for this? It seems we are not seeing just the final key, but also the raw keymap..

**Comment by AlexDaniel** [comment]
Confirming, ``-kb-remove-char-back Alt+Backspace`` works here as well.

**Comment by DaveDavenport** [comment]
@sardemff7  Does this look like a sane fix?
```diff
diff --git a/source/view.c b/source/view.c
index 30a6da1..733c142 100644
--- a/source/view.c
+++ b/source/view.c
@@ -1189,8 +1189,10 @@ static void rofi_view_handle_keypress ( RofiViewState *state, xkb_stuff *xkb, xc
         len = xkb_state_key_get_utf8 ( xkb->state, xkpe->detail, pad, sizeof ( pad ) );
     }
 
-    unsigned int modstate = x11_canonalize_mask ( xkpe->state );
+    xkb_mod_mask_t mod = xkb_state_serialize_mods ( xkb->state, XKB_STATE_MODS_EFFECTIVE );
+    xkb_mod_mask_t rrstate = xkb_state_mod_mask_remove_consumed ( xkb->state, key,mod );
 
+    unsigned int modstate = x11_canonalize_mask ( rrstate );
     if ( key != XKB_KEY_NoSymbol ) {
         KeyBindingAction action;
         action = abe_find_action ( modstate, key );
```

**Comment by DaveDavenport** [comment]
This seems to remove shift/control from shift-enter/control-enter

**Comment by DaveDavenport** [comment]
@xkbcommon What is the normal way to handle a situation like this?
I want the Control-i to produce just a backspace (see discussion above) , as `xkb_state_mod_mask_remove_consumed` nicely does. But `Shift-Enter` also get the shift removed (and I want to be able to bind that).

I can make specific exceptions, but prefer a nice solution?

**Comment by fooishbar** [comment]
@DaveDavenport Does the discussion in https://github.com/xkbcommon/libxkbcommon/issues/17 help at all?

**Comment by DaveDavenport** [comment]
Thanks, I will give it a read.

**Comment by DaveDavenport** [comment]
@xkbcommon @fooishbar 

I took a look at the thread a few days back. It does not seem to help in my use-case. (I am probably doing something wrong)
I also got some inconsistent behavior from xkb:
If I use:
```c
xkb_state_mod_mask_remove_consumed ( xkb->state, key,mod );
```
I get `0` back, all mods consumed, when pressing the alt+i binding however if I call
```c
xkb_state_key_get_consumed_mods(struct xkb_state *state, xkb_keycode_t kc)
```
It also returns 0.  No mods consumed... What is it?

If I look at implementation, it looks like we hit:
```
    key = XkbKey(state->keymap, kc);
    if (!key)
        return 0;
```

This seems wrong behavior, in the first case it should return mask not 0.

**Comment by DaveDavenport** [comment]
Ok, fixed above patch.

**Comment by DaveDavenport** [comment]
For me the alt+i for backspace works, and shift/control-enter seems to work correctly.

**Comment by AlexDaniel** [comment]
Confirming, works fine now.

**Comment by fooishbar** [comment]
@DaveDavenport For what it's worth, `XkbKey()` will only return `NULL` when the keycode is out of bounds. At that point it doesn't really matter what we return for the mask since it's a nonsensical question. At a guess, your root error (which you seem to have fixed) was passing the keysym `key` rather than the keycode `xpke->detail`; you can use the remove API if you just pass the right values.

**Comment by DaveDavenport** [comment]
you must have an amazing backlog, replying after 2 1/2 years.
