### ISSUE TITLE
Color argument throws an error

### ISSUE THREAD

**Issue by Razorfin8** [DaveDavenport/rofi#489]
## Version

0.15.11

## Configuration

<script src="https://gist.github.com/Razorfin8/1344fccdf4cc7a97b14749e9cec9ef47.js"></script>

## Launch Command

bindsym $mod+d exec rofi -show run -lines 5 -eh 2 -width 100 -padding 100 -opacity 99% -color-window "#9d0000, #000000, #000000" -color-normal "#000000, #4c4c4c, #000000, #000000, #4c4c4c" #-color-active "#000000, #4c4c4c, #000000, #000000, #4c4c4c" -color-urgent "#000000, #ff0400, #000000, #000000, #ff0400"

## Steps to reproduce

* Step 1 - Put launch code in ~/.i3/config
* Step 2 - Reload i3
* Step 3 - Press Super+D

## What behaviour you see

* - Rofi running as it should with given arguments

## What behaviour you expect to see

* - Error code: <script src="https://gist.github.com/Razorfin8/15f92b717db416859b1e39f4a0d7a111.js"></script>

## Additional Notes: 

I commented out every part of the launch command until i received an error.  Everything ran fine until I uncommented `-color-window`, then spat out the error.  I copied that code straight from the theme generator.  Also a side note:  unless its been changed, -opacity doesn't work either.

**Comment by DaveDavenport** [comment]
What happened to this?
