### ISSUE TITLE
[Feature request] remember most used command for current workspace

### ISSUE THREAD

**Issue by smarek** [DaveDavenport/rofi#492]
## Version
Version: 1.2.0-161-g5228aa8-dirty (master)

Hi, thanks for the hard work, rofi is really excellent tool !
What I'd like to see in features, is remembering what commands (maybe just in dmenu mode) are usually launched on given workspace (used in combination with i3wm) and sort them, when running dmenu, in particular order for currently focused workspace.

So far the items are ordered by recent/most-used if I understand it correctly. 

Currently focused workspace (for i3wm) can be obtained by i3-msg, like this ([link for original Q&A](https://faq.i3wm.org/question/6200/obtain-info-on-current-workspace-etc.1.html))
```bash
#!/bin/sh
i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2
```

However, shoud this be used with different window-managers, there is simple way to integrate it, which is add a launch param to dmenu, which would identify statistical set, that should be retrieved or initialized in current run.

Thank you

**Comment by DaveDavenport** [comment]
dmenu (mode) is just a dynamic menu (and not a launcher). Current version does not order/sort the input or keep a history. What you describe sounds like the run/drun modi or an external script like dmenu_launch.

I am unsure if I would want to have native support for this in rofi, as it seems to be 'advanced'. You can however write a script around rofi's dmenu mode that implements just this.
