### ISSUE TITLE
Rofi doesn't create the .cache directory if it doesn't exist

### ISSUE THREAD

**Issue by mid-kid** [DaveDavenport/rofi#497]
## Version

Version: 1.2.0

## Configuration

Unrelated

## Launch Command

rofi -show run

## Steps to reproduce

* rm -rf ~/.cache
* rofi -show run

## What behaviour you see

* Failed to create pid file.
That error message lacks a newline by the way.

## What behaviour you expect to see

* Rofi creates .cache automatically and shows me the run menu.

**Comment by DaveDavenport** [comment]
Thanks, it now tries to create it at startup.

**Comment by mid-kid** [comment]
Thanks!
