### ISSUE TITLE
[Feature request] Search in categories

### ISSUE THREAD

**Issue by JJK96** [DaveDavenport/rofi#499]
Desktop files generally list a number of categories they belong to. 
I think it would be nice if rofi can search in these categories.

Maybe this is already possible?
I have not been able to find anything on this topic.

**Comment by DaveDavenport** [comment]
Making it search this field would be easy to add.

**Comment by DaveDavenport** [comment]
It now searches categories.

**Comment by JJK96** [comment]
Very nice, thx
