### ISSUE TITLE
Error dialog lingers

### ISSUE THREAD

**Issue by moosotc** [DaveDavenport/rofi#504]
## Version

Output of `rofi -v`
Version: 1.0.0-devel

## Configuration
! Enabled modi
rofi.modi:                           window,run,ssh
! Window opacity
rofi.opacity:                        100
! Window width
rofi.width:                          50
! Number of lines
rofi.lines:                          15
! Number of columns
rofi.columns:                        1
! Font to use
rofi.font:                           mono 12
! Foreground color
rofi.fg:                             #002B36
! Background color
rofi.bg:                             #FDF6E3
! Foreground color for active row
rofi.fg-active:                      #268BD2
! Foreground color for urgent row
rofi.fg-urgent:                      #DC322F
! Foreground color for highlighted active row
rofi.hlfg-active:                    #FDF6E3
! Foreground color for highlighted urgent row
rofi.hlfg-urgent:                    #FDF6E3
! Background color for active row
rofi.bg-active:                      #FDF6E3
! Background color for urgent row
rofi.bg-urgent:                      #FDF6E3
! Background color for highlighted active row
rofi.hlbg-active:                    #268BD2
! Background color for highlighted urgent row
rofi.hlbg-urgent:                    #DC322F
! Background color for alternating row
rofi.bgalt:                          #FDF6E3
! Foreground color for highlighted row
rofi.hlfg:                           #EEE8D5
! Background color for highlighted row
rofi.hlbg:                           #586E75
! Border color
rofi.bc:                             #002B36
! Use extended color scheme
rofi.color-enabled:                  false
! Color scheme for normal row
rofi.color-normal:                   #fdf6e3,#002b36,#eee8d5,#586e75,#eee8d5
! Color scheme for urgent row
rofi.color-urgent:                   #fdf6e3,#dc322f,#eee8d5,#dc322f,#fdf6e3
! Color scheme for active row
rofi.color-active:                   #fdf6e3,#268bd2,#eee8d5,#268bd2,#fdf6e3
! Color scheme window
rofi.color-window:                   #fdf6e3,#002b36
! Border width
rofi.bw:                             1
! Location on screen
rofi.location:                       0
! Padding
rofi.padding:                        5
! Y-offset relative to location
rofi.yoffset:                        0
! X-offset relative to location
rofi.xoffset:                        0
! Always show number of lines
rofi.fixed-num-lines:                false
! Terminal to use
rofi.terminal:                       rofi-sensible-terminal
! Ssh client to use
rofi.ssh-client:                     ssh
! Ssh command to execute
rofi.ssh-command:                    {terminal} -e {ssh-client} {host}
! Run command to execute
rofi.run-command:                    {cmd}
! Command to get extra run targets
rofi.run-list-command:               
! Run command to execute that runs in shell
rofi.run-shell-command:              {terminal} -e {cmd}
! Disable history in run/ssh
rofi.disable-history:                false
! Use levenshtein sorting
rofi.levenshtein-sort:               false
! Set case-sensitivity
rofi.case-sensitive:                 false
! Enable sidebar-mode
rofi.sidebar-mode:                   false
! Row height (in chars)
rofi.eh:                             1
! Enable auto select mode
rofi.auto-select:                    false
! Parse hosts file for ssh mode
rofi.parse-hosts:                    false
! Parse known_hosts file for ssh mode
rofi.parse-known-hosts:              true
! Set the modi to combine in combi mode
rofi.combi-modi:                     window,run
! Do a more fuzzy matching
rofi.fuzzy:                          false
! Use glob matching
rofi.glob:                           false
! Use regex matching
rofi.regex:                          false
! Tokenize input string
rofi.tokenize:                       true
! Monitor id to show on
rofi.m:                              -1
! Margin between rows
rofi.line-margin:                    2
! Pre-set filter
rofi.filter:                         
! Separator style (none, dash, solid)
rofi.separator-style:                dash
! Hide scroll-bar
rofi.hide-scrollbar:                 false
! Show markup
rofi.markup-rows:                    false
! Fullscreen
rofi.fullscreen:                     false
! Fake transparency
rofi.fake-transparency:              false
! DPI
rofi.dpi:                            -1
! Threads to use for string matching
rofi.threads:                        1
! Scrollbar width
rofi.scrollbar-width:                8
! Pidfile location
rofi.pid:                            /run/user/1000/rofi.pid
! Keybinding
rofi.kb-primary-paste:               Control+Shift+v,Shift+Insert
! Keybinding
rofi.kb-secondary-paste:             Control+v,Insert
! Keybinding
rofi.kb-clear-line:                  Control+u
! Keybinding
rofi.kb-move-front:                  Control+a
! Keybinding
rofi.kb-move-end:                    Control+e
! Keybinding
rofi.kb-move-word-back:              Alt+b
! Keybinding
rofi.kb-move-word-forward:           Alt+f
! Keybinding
rofi.kb-move-char-back:              Left,Control+b
! Keybinding
rofi.kb-move-char-forward:           Right,Control+f
! Keybinding
rofi.kb-remove-word-back:            Control+Alt+h
! Keybinding
rofi.kb-remove-word-forward:         Control+Alt+d
! Keybinding
rofi.kb-remove-char-forward:         Delete,Control+d
! Keybinding
rofi.kb-remove-char-back:            BackSpace,Control+h
! Keybinding
rofi.kb-accept-entry:                Control+j,Control+m,Return,KP_Enter
! Keybinding
rofi.kb-accept-custom:               Control+Return
! Keybinding
rofi.kb-accept-entry-continue:       Shift+Return
! Keybinding
rofi.kb-mode-next:                   Shift+Right,Control+Tab
! Keybinding
rofi.kb-mode-previous:               Shift+Left,Control+Shift+Tab
! Keybinding
rofi.kb-toggle-case-sensitivity:     grave,dead_grave
! Keybinding
rofi.kb-delete-entry:                Shift+Delete
! Keybinding
rofi.kb-row-left:                    Control+Page_Up
! Keybinding
rofi.kb-row-right:                   Control+Page_Down
! Keybinding
rofi.kb-row-up:                      Up,Control+p,Shift+Tab,Shift+ISO_Left_Tab
! Keybinding
rofi.kb-row-down:                    Down,Control+n
! Keybinding
rofi.kb-row-tab:                     Tab
! Keybinding
rofi.kb-page-prev:                   Page_Up
! Keybinding
rofi.kb-page-next:                   Page_Down
! Keybinding
rofi.kb-row-first:                   Home,KP_Home
! Keybinding
rofi.kb-row-last:                    End,KP_End
! Keybinding
rofi.kb-row-select:                  Control+space
! Keybinding
rofi.kb-cancel:                      Escape,Control+bracketleft
! Keybinding
rofi.kb-custom-1:                    Alt+1
! Keybinding
rofi.kb-custom-2:                    Alt+2
! Keybinding
rofi.kb-custom-3:                    Alt+3
! Keybinding
rofi.kb-custom-4:                    Alt+4
! Keybinding
rofi.kb-custom-5:                    Alt+5
! Keybinding
rofi.kb-custom-6:                    Alt+6
! Keybinding
rofi.kb-custom-7:                    Alt+7
! Keybinding
rofi.kb-custom-8:                    Alt+8
! Keybinding
rofi.kb-custom-9:                    Alt+9
! Keybinding
rofi.kb-custom-10:                   Alt+0
! Keybinding
rofi.kb-custom-11:                   Alt+Shift+1
! Keybinding
rofi.kb-custom-12:                   Alt+Shift+2
! Keybinding
rofi.kb-custom-13:                   Alt+Shift+3
! Keybinding
rofi.kb-custom-14:                   Alt+Shift+4
! Keybinding
rofi.kb-custom-15:                   Alt+Shift+5
! Keybinding
rofi.kb-custom-16:                   Alt+Shift+6
! Keybinding
rofi.kb-custom-18:                   Alt+Shift+8
! Keybinding
rofi.kb-custom-17:                   Alt+Shift+7
! Keybinding
rofi.kb-custom-19:                   Alt+Shift+9
! Keybinding
rofi.kb-screenshot:                  Alt+Shift+S
! Keybinding
rofi.kb-toggle-sort:                 Alt+grave
! Keybinding
rofi.key-window:                     
! Keybinding
rofi.key-run:                        
! Keybinding
rofi.key-ssh:                        
! The display name of this browser
rofi.display-ssh:                    (ssh)
! The display name of this browser
rofi.display-run:                    (run)
! The display name of this browser
rofi.display-drun:                   (drun)
! The display name of this browser
rofi.display-window:                 (window)
! The display name of this browser
rofi.display-windowcd:               (windowcd)
! The display name of this browser
rofi.display-combi:                  (combi)

## Launch Command
rofi -show run

## Steps to reproduce

* Step 1 enter  non existant command (f.e. "doesnotexist")
* Step 2 hit enter

## What behaviour you see

rofi shows error dialog and continues looping internall untill [x]killed
(this are uglier due to the fact that this dialog is really a menu, so impossible
to get rid of trivially in my wm of choice (icewm))

* -

## What behaviour you expect to see

Closable dialog with some indication on how to actually close it

* -

**Comment by DaveDavenport** [comment]
Development snapshot of  8-11 months ago.

**Comment by moosotc** [comment]
Dave Davenport <notifications@github.com> writes:

> Development snapshot of  8-11 months ago. 

Right you are 1.2.0-1 works fine, sorry. That said I have been trying to
build git version of rofi but couldn't get it to work:

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

$ autoreconf -i
configure.ac:37: installing './ar-lib'
configure.ac:16: installing './compile'
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'

$ ./configure   
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for clang... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of clang... gcc3
checking for clang option to accept ISO C99... none needed
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for getline... yes
checking for open... yes
checking for sysconf... yes
checking for getenv... yes
checking for strtok_r... yes
checking for flock... yes
checking for ftruncate... yes
checking for fcntl... yes
checking for setlocale... yes
checking for atexit... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib... yes
./configure: line 4932: syntax error near unexpected token `xcb-aux'
./configure: line 4932: `GW_CHECK_XCB(xcb-aux xcb-xkb xkbcommon >= 0.5.0 xkbcommon-x11 xcb-ewmh xcb-icccm xcb-xrm xcb-randr xcb-xinerama)'

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
moosotc@gmail.com writes:

> Dave Davenport <notifications@github.com> writes:
>
>> Development snapshot of  8-11 months ago. 
>
> Right you are 1.2.0-1 works fine, sorry. That said I have been trying to
> build git version of rofi but couldn't get it to work:
>
> $ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> nothing to commit, working tree clean

[..snip..]

My mistake was not reading installation instructions carefully, one has
to do git `submodule update --init' before attempting to build the
thing, sorry for the noise, it's all good now. And thank you for Rofi
which makes my life a lot more pleasant.

-- 
mailto:moosotc@gmail.com
