### ISSUE TITLE
The script command 'window' has 1 options, but needs 2: <name>:<script>. Invalid script switcher: window 

### ISSUE THREAD

**Issue by kahrkunne** [DaveDavenport/rofi#506]
## Version

Output of `rofi -v`
`Version: 1.2.0`

## Configuration

Output of `rofi -dump-xresources` (in a [gist](https://gist.github.com/))
https://gist.github.com/kahrkunne/c59cf9e94c8fb39ac687c1a6a892338c

## Launch Command

The commandline used to launch **rofi**
`rofi -show window`

## Steps to reproduce

* Step 1
Execute above command

## What behaviour you see
The following is outputted to stderr: 
```The script command 'window' has 1 options, but needs 2: <name>:<script>.
Invalid script switcher: window
The script command 'switcher' has 1 options, but needs 2: <name>:<script>.
Invalid script switcher: switcher
The switcher switcher has not been enabled
```
* -

## What behaviour you expect to see
Rofi's window switcher dialog should pop up
* -

**Comment by DaveDavenport** [comment]
Looks like your version is compiled with: '  --disable-windowmode    Disable window mode'.

**Comment by kahrkunne** [comment]
Is this the default? Because I just got the git version and compiled that. I do remember it saying something like "window switcher Enabled" too in the compiling output (there were 3 things, the first thing said Disabled, the other 2 said Enabled).

If disabling it is the default that should be mentioned somewhere, imho

**Comment by DaveDavenport** [comment]
No, is enabled by default. First time I heard about people having it disabled who did not explicitly want it.
