### ISSUE TITLE
i3 Workspace names can have pango markup

### ISSUE THREAD

**Issue by somini** [DaveDavenport/rofi#507]
## Version

1.2.0

## Launch Command

    rofi -show window

## Steps to reproduce

* Set a workspace name with pango markup: "1:<b>Main</b>"
* Run rofi with a mode that shows workspace names
    rofi -show window
or
    rofi -show ws

## What behaviour you see

* The markup is not interpreted

## What behaviour you expect to see

* The markup should be interpreted. Even when using `-markup-rows` the problem remains.

**Comment by DaveDavenport** [comment]
Did not know that was possible?
Is this in general or specific to i3.

(`-markup-rows` is a dmenu mode option)

**Comment by somini** [comment]
For i3 that's in the manual.
In other DM, most don't even let you change workspace names. Cinnamon does, at least, but I'm not sure about pango markup there.

**Comment by DaveDavenport** [comment]
This should become an option then regrettable (don't like wm specific options) because I cannot always assume valid markup.

**Comment by DaveDavenport** [comment]
Enabling markup would cause a  lot of side issues (truncating, column width, etc.) so for now markup is stripped when it detects I3.

A patch that nicely implements this while still keeping markup is welcome.
