### ISSUE TITLE
Icons - feature request

### ISSUE THREAD

**Issue by Tomas-M** [DaveDavenport/rofi#508]
It would be awesome if rofi could show icons of programs in run mode.
If you link to Imlib2 library, it could be very simple to implement.
I am even willing to spend some cash $$$ on it, if you wish to consider this as a paid task.
It could either parse existing desktop icons in /usr/share/application, or it could have its own config file for more simple parsing.
If user types a command to the "run" prompt, it would also serve as a filter for the displayed icons.
What do you think?
![applauncher](https://cloud.githubusercontent.com/assets/2259370/20793493/893a57be-b7c7-11e6-8b99-40b9ea5211f4.png)

**Comment by DaveDavenport** [comment]
I am not going to add any icon/image support to rofi.

If somebody wants to implement this, he/she is welcome to do this. If it is cleanly implemented and does not cause performance issues, I am willing to add it.

**Comment by DaveDavenport** [comment]
[image](https://filebin.pw/2WVNg/)

There is a patch that is getting there..

**Comment by sardemff7** [comment]
Icons support merged to master (still a bit buggy it seems, though not for me :-P).
