### ISSUE TITLE
Changed behaviour of custom modi

### ISSUE THREAD

**Issue by roomcays** [DaveDavenport/rofi#513]
## Version

Version: 1.2.0-233-gea28bcd (master)

## Configuration

https://gist.github.com/roomcays/c183907b6c09355d6d9b9f5620122936

## Launch Command

With xbindkeys:

    $ ~/.local/bin/rofi -show combi

## Steps to reproduce

* Take any **modi-compatibile** script and bind it with your rofi (for lazy ones: [script I used when I *detected* the issue](https://gist.github.com/roomcays/75640a1ecf50b56d3f9af9de9833e6b8))
* use it :)

## What behaviour you see

* with some previous (1.2.0 stable) version of rofi, after user input was submitted, rofi was filled with script results **and user input was cleared** so all items were displayed and could be matched again "from scratch" (example using the script I linked to: I enter **noga** and I have results: *log, hacker, footer, gam, footy* and all of them were displayed so I could )
* currently user input is not cleared which causes results to be filtered against it

## What behaviour you expect to see

* I'm not sure, because it might be desired to keep filtering on the results of modi-script. If I could vote, I would vote for clearing the input (just like in the stable 1.2.0 version)

**Comment by DaveDavenport** [comment]
Can confirm.
