### ISSUE TITLE
Missing Daemon mode

### ISSUE THREAD

**Issue by drasill** [DaveDavenport/rofi#514]
I understand why the daemon mode was removed from rofi.

But it had a huge benefit, IMHO : rofi was almost instantaneous when pressing the trigger key.

Now, as my computer is often slow, there can be many seconds before rofi starts (on a cold start).

Is there any hope to have the daemon mode reactivated ?
Or do you known any method to have the rofi binary kept in cache ?

**Comment by DaveDavenport** [comment]
This has been discussed many times before and there seems to be myths going around about it.
First: In my opinion launching programs on global keybindings does not belong in **rofi**. This is the task of the Window Manager, DE or a separate daemon.

Secondly, **rofi**  is *very* fast starting up and the difference between daemon mode and non daemon mode always been neglectable for me (milliseconds difference). ( in git the startup time and time to be interactive has been improved even further).

So the only thing is if you use **rofi** very infrequently on a very low memory machine its library like cairo, libxcb (That are shared with many others apps) might get discarded. But in situations like this even when running in background it is likely that its memory is swapped away in that case.

See also [here](https://github.com/DaveDavenport/rofi/issues/347) for a more detailed discussion on this.

**Comment by DaveDavenport** [comment]
For timing trace see [here](https://github.com/DaveDavenport/rofi/wiki/Debugging%20Rofi#timing-traces)

**Comment by DaveDavenport** [comment]
[This](https://github.com/DaveDavenport/rofi/issues/496) topic might also be interesting.

If you want to debug the slowness, please provide the information as requested in the [guidelines](https://github.com/DaveDavenport/rofi/blob/master/.github/CONTRIBUTING.md) as linked on the top of  the new issue page.

**Comment by DaveDavenport** [comment]
[this](https://github.com/hoytech/vmtouch) might be useful too.
Please let me know the results.

**Comment by bombela** [comment]
My computer is not slow, but for some reason when I start rofi via some i3 binding, it doesn't seem to run rofi until I **release** the shortcut keys. But this only happens with rofi, it doesn't happen when I start a terminal emulator or run some other program that I have direct shorcuts for.

**Comment by bombela** [comment]
Correction, after doing:
```
auditctl -a exit,always -S execve
tail -f tail -f /var/log/audit/audit.log 
```

i3 keeps starting rofi in a loop as long as I keep they shorcut keys pressed, but nothing appears until I give it enough time by releasing the keys.

**Comment by DaveDavenport** [comment]
Don't!!!!!!!!! highjack issue reports and check other issues, #524 .
