### ISSUE TITLE
I would like to disable the bold and underline highlighting for search matches. Is this possible?

### ISSUE THREAD

**Issue by krompus** [DaveDavenport/rofi#515]

**Comment by DaveDavenport** [comment]
> No description provided.

Impossible to answer given lack of information. Please *read* the [guidelines](https://github.com/DaveDavenport/rofi/blob/master/.github/CONTRIBUTING.md) linked at the top when reporting a new issue.

**Comment by leothelocust** [comment]
> Impossible to answer given lack of information.

That is a pretty snarky reply @DaveDavenport.  I too would like to know if this is possible.  The title is very complete and _reading_ the [guidelines](https://github.com/DaveDavenport/rofi/blob/master/.github/CONTRIBUTING.md) is irrelevant to this question.

If anything, this belongs in the forums.  See [forum post](https://www.reddit.com/r/qtools/comments/7rdygq/change_boldunderline_behavior_for_search_matches/) for my similar question.
