### ISSUE TITLE
Could not paste from clipboard.

### ISSUE THREAD

**Issue by snippins** [DaveDavenport/rofi#516]
## Version
I am using Ubuntu 16.04, i3 session. Two versions are tested. The stable version (1.2.0) download from the front page and clone from master. Both have the same problem.

Version: 1.2.0
Version: 1.2.0-250-gd25989e-dirty (master)

## Configuration
https://gist.github.com/snippins/4c150c1457e22ec7d63a8f467b7f68dd

## Launch Command
rofi -show run

## Steps to reproduce
1. Copy something to the clipboard
2. Run the said command in terminal or using hotkey
3. Press Ctrl+V

## What behaviour you see
Nothing pasted.
If running from a terminal, the message "Failed to convert selection" is shown.

## What behaviour you expect to see
The clipboard is pasted into rofi.

## Additional details.
Primary selection still works (Ctrl+Shift+V)

**Comment by DaveDavenport** [comment]
Indeed thanks for the report.

**Comment by DaveDavenport** [comment]
Can you test above commit to see if it fixes it?

**Comment by snippins** [comment]
Work as expected. Thanks for the quick fix.

**Comment by DaveDavenport** [comment]
np. Thanks for the report.
