### ISSUE TITLE
`rofi -dmenu` stops reading options from stdin upon empty line (1.3.0 regression)

### ISSUE THREAD

**Issue by grensjo** [DaveDavenport/rofi#518]
## Version
rofi 1.3.0 ([package from Arch Linux](https://www.archlinux.org/packages/community/x86_64/rofi/))

## Configuration

Output of `rofi -help`: [gist](https://gist.github.com/grensjo/f39348577515cc6b4b7a9135e7c17864)
## Launch Command

```
echo -e "Option #1\n\nOption #2" | rofi -dmenu
```

## Steps to reproduce

Run the command above.

## What behaviour you see

Only the `Option #1` menu entry is shown; it seems like rofi stops reading options when it encounters an empty line.

This breaks for example [nmcli-dmenu](https://github.com/firecat53/nmcli-dmenu), which uses empty lines to separate different sections of the menu.

## What behaviour you expect to see

Three menu entries: `Option #1`, an empty entry, and `Option #2`. This is the behavior obtained with rofi 1.2.0.

**Comment by DaveDavenport** [comment]
quick work-around is using `-sync` mode. will look into it.

**Comment by DaveDavenport** [comment]
Possible fix in git. Can you test?

**Comment by grensjo** [comment]
Works for me, both with my small example and with nmcli-dmenu. Thanks for fixing quickly!
