### ISSUE TITLE
"Cannot understand the key combination" Rofi error after upgrading to 1.3.0

### ISSUE THREAD

**Issue by jp1995** [DaveDavenport/rofi#519]
## Version

Version: 1.3.0

## Configuration

[gist](https://gist.github.com/jp1995/3636d627d2c98077ef789b2dacdd0357)

## Launch Command

rofi -show run

## Steps to reproduce

using rofi version 1.3.0 yields this problem. Downgrading to 1.2.0 fixes the issue.

## What behaviour you see

```
Cannot understand the key combination: Control+Backspace
- Key Backspace is not understood
Failed to set binding for: kb-remove-word-back
```

## What behaviour you expect to see

Rofi showing the run menu

**Comment by DaveDavenport** [comment]
It is `BackSpace` not `Backspace`.

**Comment by jp1995** [comment]
That indeed fixes it. However, my rofi window is now weirdly offset towards the bottom of the screen.

```
"Location on screen" Set from: Default
rofi.location:                       0
"Padding" Set from: Default
rofi.padding:                        1
"Y-offset relative to location" Set from: Default
rofi.yoffset:                        0
"X-offset relative to location" Set from: Default
rofi.xoffset:                        0
```

This should place it in the middle, right?

**Comment by DaveDavenport** [comment]
It has todo with the auto-resizing of the window. (I think this is in release notes).
enabled fixed-num-lines to stop this.

**Comment by jp1995** [comment]
Problem solved, thank you! :)
Sorry about the stupid questions

**Comment by DaveDavenport** [comment]
Please use forum/irc for questions like these. Easier to find for others .
