### ISSUE TITLE
Option for synchronous input

### ISSUE THREAD

**Issue by vshatskyi** [DaveDavenport/rofi#520]
## Version

Output of `rofi -v`
1.3.0

With the new async input feature now every time I open rofi with a larger list, the "Loading..." text shows up for a moment and then disappears. I find it rather distracting because red text on dark background is very noticeable. 

Would it be possible to add an option to signify that the input is synchronous and that rofi should wait till the end of it?

**Comment by DaveDavenport** [comment]
yes, `-sync`
