### ISSUE TITLE
Add custom coloration for substring matching

### ISSUE THREAD

**Issue by kilbith** [DaveDavenport/rofi#522]
Title says it all. I need the ability to set a custom color to highlight the matching substrings.

**Comment by DaveDavenport** [comment]
Need to think how to implement this (efficiently).
Could possibly support, color, underline, italic, stripe-through and more. (See pango attributes)

**Comment by DaveDavenport** [comment]
You can now set (per state)
```
highlight: {style} {color}
```

For example:
```
highlight: bold underline #ff0000;
```

**Comment by kilbith** [comment]
Thanks, you rock :+1:
