### ISSUE TITLE
Location of prompt

### ISSUE THREAD

**Issue by nioncode** [DaveDavenport/rofi#523]
## Version
1.3.0
## Configuration
https://gist.github.com/nioncode/6e6faac974eb335b0070c8ed71530999
## Launch Command
rofi -show run

## Steps to reproduce
Run rofi with location set to 6 or 7, once with v1.1 and once with v1.3.

## What behaviour you see
v1.1: https://postimg.org/image/r39z7lp0t/
v1.3: https://postimg.org/image/nv5huk2r1/

Notice how the location of the 'run:' prompt changed from being at the top of the ui to the bottom.
This makes it more difficult to relate the user input to the most likely match (the first entry).
It would be great to have an option for toggling this behavior off or make rofi output the list of matches in reverse sorting order so that the first highlighted match appears next to the user input.

**Comment by DaveDavenport** [comment]
The reverse ordering of the listview is a good idea. 
I place the entry box at the bottom to make sure that it does not move. (and it does look pretty good).

**Comment by DaveDavenport** [comment]
In new theme format the order of the listview can be reversed.

**Comment by DaveDavenport** [comment]
Changed my mind, it is default now.
