### ISSUE TITLE
rofi started on keyup from i3

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [DaveDavenport/rofi#524]
When rofi is run from i3 using `bindsym $mod+d`, it becomes visible after `d` has been released, instead of when `d` is pressed.

## Version
`Version: 1.3.0`

i3: `4.13`

## Configuration
default configuration:
https://gist.github.com/RagnarGrootKoerkamp/15ac4cc7bcd6002505f653cbb72c066a)

## Launch Command
`rofi -show run`

## Steps to reproduce
i3 config:
`bindsym $mod+d exec rofi -show run`

## What behaviour you see
rofi becomes visible after `d` has been released

## What behaviour you expect to see
It should show when `d` is pressed.

I also tried 
`bindsym $mod+d exec notify-send started && rofi -show run`
and the notification is immediately visible when the `d` is pressed.
(Moving these commands to a separate script and calling that from the keybind gives the same behaviour.]

This might be an i3 issue instead, but since the script is called as soon as the keys are pressed, I think rofi is the problem.

**Comment by milouse** [comment]
I can confirm this issue, but it's super weird. In fact, rofi is started as soon as you press the `d` key, but stay hidden until you release it. Moreover, if you deliberately keep pressing the `d` key for 3 or 4 seconds and then release it, nothing will show up, but you'll find a rofi process in the back (which prevent next rofi command to appear). 

The difference with notify-send must be that the later forks at startup and thus is not blocked by i3. Similarly, this bug does not happen with my branch of [quickswitch-i3](https://github.com/milouse/quickswitch-for-i3/), which start rofi in a subprocess: when I call it through another keystroke, it appears immediately, even if I keep pushing the keys.

Thus I really think it's related to i3, but I'm not an expert in X and have no idea how to investigate further on this. Maybe you should cross post this issue on the i3 bug tracker.

**Comment by DaveDavenport** [comment]
This is actually to be expected. One of the first things rofi tries to do is grab the keyboard. It can only do this when i3 releases it. Not grabbing the keyboard early on in the process is not desirable, on slow hardware the first keypress can be missed (because creating window+loading modi can take 100ms).

(you can verify this by running rofi with -normal-window, then it won't try to grab keyboard),

The fact that rofi stays running in the background is a bug.

**Comment by DaveDavenport** [comment]
Fix in git for the hanging in background.

**Comment by DaveDavenport** [comment]
From the i3 manual:

>  Some tools (such as import or xdotool) might be unable to run upon a KeyPress event, because the 
>  keyboard/pointer is still grabbed. For these situations, the --release flag can be used, which will 
>  execute the command after the keys have been released.

You probably want to trigger rofi on release. I3 also has the nasty habit off repeatedly launch the application if you keep the key pressed.

**Comment by DaveDavenport** [comment]
I added a commit to git that tries to work around this i3 behaviour.
It tries to grab they keyboard/mouse and if fails, continues to try in background while showing gui.
