### ISSUE TITLE
allow modi specific colors with new theme css engine

### ISSUE THREAD

**Issue by zeltak** [DaveDavenport/rofi#527]
Hi

I would like to request if possible now with the new theme css engine to configure separate colors per modi so that we have a nice visual que to differ the modi is multi modi mode

Z

**Comment by sardemff7** [comment]
One way to implement that is a CSS class-like feature.

**Comment by vahnrr** [comment]
I'm interested in using such a selector but can't find a documented way to do this, how would I go about selecting a specific modi or selecting all modis exept a specific one? I tried:

```
testmodi entry { background-color: #ff0000; }
entry[modi="testmodi"] { background-color: #ff0000; }
entry:not[modi="testmodi"] { background-color: #ff0000; }
```

But it did not work, how did you guys implement it?

**Comment by DaveDavenport** [comment]
This did not get implemented.  My apologies, I should have added a note to this issue.
