### ISSUE TITLE
[Feature Request] Non-blocking input

### ISSUE THREAD

**Issue by lbonn** [DaveDavenport/rofi#529]
It would be nice if the gui could respond before the full input entries are generated and allow search in the partial list. In the spirit of [this dmenu patch](http://tools.suckless.org/dmenu/patches/non_blocking_stdin) which does not seem to work too well for me.

The use case is a menu to select a directory with fuzzy search on the full path to open a tmux session.
It would give rofi the list of `$HOME` sub-directories sorted by ascending depth. Generating the full list is pretty slow but shallow dirs can be found early if a breadth-first search is used.

Right now, rofi seems to grab the keyboard until the end of the search and blocks the whole wm.

A work-around would be to limit the depth of the search but it could still take some time and block the gui.

I could also use `rofi-file-browser.sh` from the examples but it would not be usable with a fuzzy search on the full path.

This is probably a big task and a potential source of new bugs :), but it could have other use cases.
I can try to have a look if you think it has a chance to succeed.

**Comment by DaveDavenport** [comment]
https://github.com/DaveDavenport/rofi/releases/tag/1.3.0

**Comment by lbonn** [comment]
Sorry about that, I left `-auto-select` the first time and then tried with a modi script.
