### ISSUE TITLE
KP_Next and KP_Prior besides Page_Down and Page_Up

### ISSUE THREAD

**Issue by michalrus** [DaveDavenport/rofi#531]
## Version

1.2.0

## Configuration

https://gist.github.com/michalrus/d3db60e286f37d086fb0d16242dcc167

The interesting part is:

```
rofi.kb-page-prev:                   Page_Up,KP_Prior
rofi.kb-page-next:                   Page_Down,KP_Next
```

## Launch Command

`rofi -show run`

## Steps to reproduce

* Run the «Launch Command» above and press `KP_Next` (‘PgDn’ on the keypad).

## What behavior you see

* Nothing happens.

## What behavior you expect to see

* I’d expect the list to scroll one page down, as with `Page_Down`.

If you’re not sure about the naming, run `xev` and press ‘PgDn’ / ‘PgUp’ on the keypad. You should see `KP_Next`/`KP_Prior` in `xev`’s output.

**Comment by DaveDavenport** [comment]
Works for me (tm).
Can you update to latest release and try?

**Comment by DaveDavenport** [comment]
Did you load the Xresources file, your gist report you haven't.
```
xrdb -load ~/.Xresources
```

**Comment by michalrus** [comment]
@DaveDavenport, I’m using `~/.config/rofi/config`, and it’s picked up, because other options work. :smiley: 

I’ll try with the latest release.

**Comment by DaveDavenport** [comment]
```
        -kb-page-prev [string]                  Go to the previous page
        Page_Up (Default)
        -kb-page-next [string]                  Go to the next page
Page_Down (Default)
```

from your pastebin of ` rofi -h ` show that the setting is not set.

**Comment by michalrus** [comment]
Yeah, this surprised me, too. Other are changed. Example:

```
        -[no-]cycle                             Cycle through the results list
                False (File)
```

**Comment by DaveDavenport** [comment]
Yes. Can you pastebin (not copy paste, but upload) your config file?
Or mail it to me (if you don't want to put public?)

**Comment by michalrus** [comment]
@DaveDavenport, sure! It’s really short, though. http://pastebin.com/raw/n6SMX0b3

**Comment by DaveDavenport** [comment]
That file works for me, try to upgrade see if that fixes the issue.

**Comment by michalrus** [comment]
Noes, 1.3.1 exhibits the same behavior… :disappointed_relieved:

**Comment by DaveDavenport** [comment]
have you tried the commandline I pasted before, as I said, it works here both commandline as in config.

**Comment by michalrus** [comment]
Oh, I missed it, you must’ve edited that post.

Yeah! Now it works. :astonished: Why doesn’t it work with the config file, though?

**Comment by DaveDavenport** [comment]
I have no idea. I tried loading your file using `rofi -config config n6SMX0b3` and it worked.

Not sure why it does not pick it up for you, if other settings are loaded it parses the file. The entries seems to be correct.  What [xcb-utils-xrm](https://github.com/Airblader/xcb-util-xrm) version ?

**Comment by michalrus** [comment]
It doesn’t work for me, manually specifying the config file. :crying_cat_face: 

`xcb-utils-xrm` 1.0 here.

**Comment by michalrus** [comment]
@DaveDavenport, huh. I copied the file and removed comments before publishing it. Now, that I finished configuring Rofi and removed all the comments generated by `-dump-Xresources`, it has started working. Shouldn’t comments be ignored?

**Comment by DaveDavenport** [comment]
Should be.  Let me try it.

**Comment by DaveDavenport** [comment]
Do you still have the failing file in original form?

**Comment by michalrus** [comment]
Noes, but I can generate it, I think so!

Yep.

http://pastebin.com/raw/yVcwe4kw

Just `-dump-Xresources` with `KP_Prior` and `KP_Next` added. Doesn’t work.

**Comment by DaveDavenport** [comment]
You did not remove the `!` comment in front of the setting.....

**Comment by michalrus** [comment]
Oh, dear God. You’re right. Checked it now. :disappointed_relieved:

I should sleep more, probably. Sorry for taking your time. :man_facepalming:

**Comment by DaveDavenport** [comment]
No problem.

**Comment by michalrus** [comment]
And thanks for this wonderful piece of software! :bowing_man:
