### ISSUE TITLE
Rofi as file browser does not launch from Polybar clickable module

### ISSUE THREAD

**Issue by azaroma** [DaveDavenport/rofi#532]
## Version
1.3.0

## Configuration
[help output](https://gist.github.com/azaroma/58b7b14a872d376572b3b6f14a63e403)

## Launch Command
`rofi -switchers "file:~/bin/rofi-file-browser.sh" -show file`
`rofi -modi file:~/bin/rofi-file-browser.sh -show file`

## Steps to reproduce

Set up a Polybar module like this:

    [module/search]
    type = custom/text
    content = " "
    click-left = rofi -switchers "file:~/bin/rofi-file-browser.sh" -show file
    click-right = rofi -modi file:~/bin/rofi-file-browser.sh -show file

This will invoke `/usr/bin/env sh -c $COMMAND` according to Polybar's wiki.

## What behaviour you see
Nothing shows up. Polybar reports this:

    warn: Uncaught input event, forwarding to shell... (input: rofi -switchers "file\\:~/bin/rofi-file-browser.sh" -show file)
    warn: Uncaught input event, forwarding to shell... (input: rofi -modi file\\:~/bin/rofi-file-browser.sh -show file)

Which is normal behavior. Notice that things like `rofi -show run` do work from clickable module. Also, the command works fine with i3 keybindings. It works fine if I type `sh -c "rofi -modi file:~/bin/rofi-file-browser.sh -show file"` from terminal.

## What behaviour you expect to see

I expect rofi to show up with `file` modi as it does when the command is ran from terminal or from i3 keybinding.

**Comment by DaveDavenport** [comment]
The command issued by polybar is clearly wrong.
```
rofi -modi file\\:~/bin/rofi-file-browser.sh -show file
```
