### ISSUE TITLE
Dmenu window height

### ISSUE THREAD

**Issue by somini** [DaveDavenport/rofi#534]
## Version

v1.3.0

## Configuration

Nothing

## Launch Command

echo 'two\nlines' | rofi -dmenu

## Steps to reproduce

* Run the command

## What behaviour you see

* On v1.3.0, even thought the input has only two lines, rofi creates a larger window
![1 3](https://cloud.githubusercontent.com/assets/1750665/21765998/ddac1ebc-d663-11e6-92bb-b08a593d4135.png)

## What behaviour you expect to see

* On v1.2.0, rofi correctly creates a two-line height for two lines of input
![1 2](https://cloud.githubusercontent.com/assets/1750665/21766012/ef723cee-d663-11e6-954c-e0569ab0e13a.png)

**Comment by DaveDavenport** [comment]
Please read the release notes and check other bug reports:
#528
