### ISSUE TITLE
Tabbing causes an execution if a single element is found in the list

### ISSUE THREAD

**Issue by kilbith** [DaveDavenport/rofi#536]
I have some questioning about this behavior...

The <kbd>Tab</kbd> key is normally used for switching of selection, but when there's a single element in the list, it closes `rofi` and provokes an attempt of execution of the selected application.

I don't think it's consistent and is likely to cause some "accidents".

IMO, <kbd>Tab</kbd> should be dedicated to the selection, and <kbd>Enter</kbd> or double-click reserved for the execution.

**Comment by DaveDavenport** [comment]
This is a (several times) requested feature.

* Single tab: 1 entry left. -> accept it.
* Double tab no entry left -> next modi.

I'd be hesitant to remove it.

**Comment by kilbith** [comment]
By the way, <kbd>Tab</kbd> on the last entry could be used for autocompletion instead. There are annoying situations where I accidently pressed <kbd>Tab</kbd> on `shutdown` whereas I just wanted to autocomplete and add `now` next to it.

**Comment by DaveDavenport** [comment]
remap the key in rofi to autocomplete?

**Comment by kilbith** [comment]
I'm asking this to be the default behavior.
