### ISSUE TITLE
Window mode: switch to desktop needed?

### ISSUE THREAD

**Issue by lbonn** [DaveDavenport/rofi#537]
This is a follow-up to the changes introduced by #393 and a request to consider reverting them if issues with some WMs are no longer a problem.

I use i3 with a [focus-to-last helper](https://github.com/acrisci/i3ipc-python/blob/master/examples/focus-last.py) and the switch to desktop is reported through the i3 ipc.

As a result, the script changes the focus to the previously active window on the target desktop if used after a cross-desktop switch with rofi.

## Version

1.3.1-175-g547bac0 (master)

## Launch Command

`rofi -show window`

## Steps to reproduce

* record the window focus changes of your wm
* switch to an unfocused window in another desktop with `rofi -show window`
* try to go back to the previous window by using the recorded history

**Comment by DaveDavenport** [comment]
This will break awsomewm?

**Comment by lbonn** [comment]
When I read the other issues about that (also #394), it seems probable...
I'll do a quick test if I have some spare time at the end of the week.

In that case, the desktop switch logic could be guarded by a `if (awesome_wm)`.

**Comment by DaveDavenport** [comment]
Is there an easy way to detect awesome_wm? like property on root window?

**Comment by zestyr** [comment]
FWIW, [here's how neofetch detects the current window manager](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L615-L619).
