### ISSUE TITLE
feature request : toggle mode

### ISSUE THREAD

**Issue by eoli3n** [DaveDavenport/rofi#538]
Is there anyway to add a toggle mode ? 
When i start rofi, i need to press escape key to quit it.

I assigned rofi to $mod+w in i3 (escape is faaaaar), and it would be great to be able to 

```
rofi -show -toggle
#rofi shows
rofi -show -toggle
# rofi hides
```

**Comment by DaveDavenport** [comment]
bind kb-cancel to contain also `$mod+w` in rofi.

**Comment by eoli3n** [comment]
not a fix, i use many shortcuts to launch different rofi

``.i3/config``
```
# start drofi dmenu
bindsym $mod+w exec --no-startup-id rofi -show window
bindsym $mod+Shift+w exec --no-startup-id rofi -show run
bindsym $mod+Shift+x exec --no-startup-id rofi -show drun
#rofi_power menu
bindsym $mod+Shift+q exec ~/.i3/rofi_powermenu.sh
#rofi_custom menu
bindsym $mod+x exec ~/.i3/rofi_custom.sh
```

**Comment by eoli3n** [comment]
And what's the name for "windows" key, between CTRL and ALT please ? in i3 it's Mod4, but rofi doesn't accept it

**Comment by DaveDavenport** [comment]
The toggle would not work either, because once rofi is running, it has the keyboard grabbed and i3 won't receive those events anymore.

It is 'Super' .

**Comment by eoli3n** [comment]
ok thx

**Comment by MagnusOxlund** [comment]
You can achieve the desired toggle mode by using a 3rd-party application like [xcape](https://github.com/alols/xcape) or [ksuperkey](https://aur.archlinux.org/packages/ksuperkey/).

As an example using ksuperkey, add this to your `~/.config/i3`:

```
exec ksuperkey
bindcode 133 rofi -show run -kb-cancel Alt+F1
```
On a side note, until Rofi version 1.4 is released, you may experience an issue with Rofi freezing as described in #576 if you choose to use either xcape or ksuperkey. In the meantime and if possible, I suggest you build and install Rofi from the latest git master branch to avoid that problem.

**Comment by MagnusOxlund** [comment]
Anyone attempting this may have more success with "Super_L" as mentioned in #592, which also may be relevant to others seeking a toggle feature.
