### ISSUE TITLE
Empty path in desktop file breaks application run

### ISSUE THREAD

**Issue by eNcacz** [DaveDavenport/rofi#539]
## Version

Version: 1.3.0

## Configuration

[configuration](https://gist.github.com/eNcacz/ddee8f88e8222c7f0863f7cdf3849b74#file-config)

## Launch Command

rofi -show combi -combi-modi window,drun -modi window,drun

## Steps to reproduce

* put file [test.desktop](https://gist.github.com/eNcacz/ddee8f88e8222c7f0863f7cdf3849b74#file-test-desktop) to the `~/.local/share/applications directory`
* put file [test.sh](https://gist.github.com/eNcacz/ddee8f88e8222c7f0863f7cdf3849b74#file-test-sh) to the `/tmp` directory
* run `rofi -show drun` command
* select application with name `Test` in the rofi window and press Enter key

## What behaviour you see

* Error message appears: 
Failed to execute: '/tmp/test.sh'
Error: 'Failed to change directory '' (No such file or directory)'

## What behaviour you expect to see

* Ignore empty Path property in destkop file (in the same way as the property is completely missing) and run desired application. Now the Test script can be run via xfce menu but not via rofi.

**Comment by sprnza** [comment]
@DaveDavenpor what version does have this fix?

**Comment by sprnza** [comment]
archlinux community repo contains 1.3.1 and it doesn't have the fix. Installed from git.

**Comment by DaveDavenport** [comment]
did you install 1.3.1 or git? you are not being very clear.

**Comment by sprnza** [comment]
Sorry. I've had 1.3.1 version installed which doesn't have the fix and asked the question. Then I've installed from git and now I'm all happy! :) Have a good day!

**Comment by DaveDavenport** [comment]
1.3.1 --> 22 days ago.
commit --> 13 days ago.

**Comment by sprnza** [comment]
Yeah, my bad. Sorry for disturbing.

**Comment by DaveDavenport** [comment]
Good to hear the fix worked.
