### ISSUE TITLE
Rasi Theme Fonts

### ISSUE THREAD

**Issue by crgnclsn** [DaveDavenport/rofi#544]
Absolutely love the new theme system. Works beautifully and the configurability is fantastic. It's not a major issue but it would be nice to extend the "font" property to allow us in #window.mainbox.inputbar and #window.mainbox.listview. This would allow people to use different font sizes or even different fonts between these elements. I thought I would bring it up now while you are still finalising the format.

**Comment by DaveDavenport** [comment]
I thought about allowing different fonts, but I am a bit weary about things:
1. If different elements in the listview have different font (sizes) it makes rendering harder,  this would break things, or require a lot of re-calculations for resizing all the time.  With multiple columns this would start to get complex.
2. It would undo some of the optimizations done (but I need to test if this is a problem).

(Maybe not a valid reason, but do we *realy* want to have different fonts for different parts.  I don't see how this would improve usability.)

**Comment by DaveDavenport** [comment]
happy to hear you like the new theme format. :tada:

**Comment by crgnclsn** [comment]
I did think padding might be an issue, but would allowing only a different font between the input bar and the list view not solve this issue? Or does the theme structure not allow for that?

I have made a few themes on the new system now but the new one I'm trying would work well with a bigger font in the search box. It's not particularly different fonts I'm interested in - more changing their size. But some users might be interested into being able to do both.

**Comment by DaveDavenport** [comment]
Ill think about it, @carnager  also suggested a different font for the message might be nice (although the pango markup allows this). 

Any of themes online somewhere?

**Comment by crgnclsn** [comment]
Thank you very much for considering it. I'll use the software regardless. It's very very good! I'm not sure if it's a placebo but the new theme system makes rofi feel faster as well!

The font thing was just a thought I had when I was trying out some theme ideas. Ehm nothing ready to release publicly. Currently using this which is interesting because there isn't actually any compositor blurring being used. It's simply using a transparent and blurred copy of the desktop wallpaper to achieve the effect.

![screenshot](https://cloud.githubusercontent.com/assets/23727785/22221791/581c2040-e1ac-11e6-87ac-fc7518260ebe.png)

**Comment by DaveDavenport** [comment]
I don't expect the new theme stuff to be faster (I rather think it is slightly slower), but a lot of speed improvement went into the last 1.3 release.

That looks very good. (I think you can do some blurring using composite mangers (I think compton can do this?))

**Comment by crgnclsn** [comment]
Ahh okay. Must be placebo then! Yeah it's possible with compton but it can't do very extensive blurring and the compositors that can are quite resource intensive. This keeps it lightweight as there is no real time blurring to be done!

**Comment by carnager** [comment]
Please share the themes!

**Comment by DaveDavenport** [comment]
https://filebin.pw/En0pG/

**Comment by DaveDavenport** [comment]
Added basic support for it in GIT. (for testing).

**Comment by crgnclsn** [comment]
Wow, 14 hours from tentative request to a commit. Thank you Dave - you're incredible. Will be  trying this out as soon as I get home.

**Comment by DaveDavenport** [comment]
Well it is for testing, no promise I am going to keep it.
Please test

**Comment by crgnclsn** [comment]
Working well here. Have tried a number of different fonts and different sizes. It all seems to be working as intended. A lot of my themes work well with having a large font on the input bar and a slightly smaller one for the list view results. Is there anything specific you'd like me to test?

**Comment by DaveDavenport** [comment]
No, I did my best to make sure the overhead was limited. (keeping a cache of font descriptions and metrics). 

Currently I do not allow different fonts per listview element state (e.g. different font for selected).
I assume this is fine?

**Comment by crgnclsn** [comment]
Yes, I don't really see any practical use for that. It would just make the scaling and padding of the listview complex and would probably not look good.

Since they are distinct elements I think allowing for different fonts and font sizes between the inputbar and listview as you have done is a good feature to have! Are there reasons you would consider not keeping it?

**Comment by DaveDavenport** [comment]
Currently, i don't see an issue.
I haven't noticed a performance impact. The solution was reasonably tidy and compact.
