### ISSUE TITLE
sudo authentication

### ISSUE THREAD

**Issue by LordTaifleh** [DaveDavenport/rofi#545]
Let's have a feature where we can use rofis output to authenticate for sudo actions.

I wrote a script that executes `wifi-menu` (from `netctl`) in rofi. 
The problem is, i either need to start it with a terminal or `gksu`
which is annoying..
How do i accomplish this?

**Comment by DaveDavenport** [comment]
Sorry, it is not clear to me what exactly you want.

**Comment by LordTaifleh** [comment]
i want to execute an executable which needs root, and i want to be able to give my sudo password through rofi so the process can elevate and run.
what i do not want is using gksu .

**Comment by DaveDavenport** [comment]
(FYI: I don't see rofi as a safe way to enter passwords.)

But it sounds like you want to make a askpass wrapper around rofi and have sudo call that from the script.

**Comment by LordTaifleh** [comment]
yes, i have seen it in the man page, it should not be considered secure. 

I am writing a connection manager for wifi based on netctls wifi-menu.
i guess i'll have to work around it with /etc/sudoers manipulation for netctl

**Comment by DaveDavenport** [comment]
I guess giving the user permission to modify the wifi is the way to go then to sudo.

Anyway a rofi-askpass.sh would look something like this (for 1.3.1 rofi):
```bash
#!/usr/bin/env bash

rofi -password -dmenu -input /dev/null -sync  && echo
```

**Comment by LordTaifleh** [comment]
thank you, i'll play around with it!
