### ISSUE TITLE
rofi -m -3 lets rofi 'disappear'

### ISSUE THREAD

**Issue by LordTaifleh** [DaveDavenport/rofi#546]
I am running the git-version.
running rofi with the `m -3` argument causes rofi not to display when the cursor is at the bottom edge of the screen.
Can you please either add an option to display rofi in upwards direction or implement something more smart that does it automatically on m -3 setting only (or other applicable scenarios)?
##Launching Command
`echo "1|2|3|4|5" | rofi -dmenu -sep '|' -m -3

**Comment by DaveDavenport** [comment]
You can move it around the cursor using the new theme format:
```
echo "1|2|3|4|5" | rofi -dmenu -sep '|' -m -3 -no-config -theme-str '#window { anchor: southeast;}'
```

I guess an automatic option could be implemented, patch is welcome.

**Comment by LordTaifleh** [comment]
Oh i didn't know about that! it works beautifully now.
I'm not gonna patch this because i'm still new to programming. At least I'm not gonna do it soon. :)
