### ISSUE TITLE
Rofi has no class

### ISSUE THREAD

**Issue by vlaze** [DaveDavenport/rofi#549]
## Version

Output of `rofi -v`
1.3.0

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/vlaze/076eed928e27d2fe6ebd5c6574ec67e2))
(click *gist*)
## Launch Command

The commandline used to launch **rofi**
rofi -show run

## Steps to reproduce

* Step 1 Open a terminal and call xprop
* Step 2 Open another one (using your keyboard. Do not touch your mouse) and use the launch command for Rofi. Click over the Rofi dialog box you have started.

## What behaviour you see

* - Xprop's output looks like:
WM_NAME(STRING) = "rofi"
_NET_WM_NAME(UTF8_STRING) = "rofi"
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE

## What behaviour you expect to see

* - I expected to find information about the class of this program (WM_CLASS parameter). Unfortunately, the lack of this value makes it impossible to me to implement it inside my window manager of choice.

**Comment by TRSx80** [comment]
https://www.youtube.com/watch?v=cI1ViNssPr0
