### ISSUE TITLE
Very slow with -dmenu argument

### ISSUE THREAD

**Issue by mskorzhinskiy** [DaveDavenport/rofi#550]
## Version

Version: 1.3.0

## Configuration

https://gist.github.com/mskorzhinskiy/84389c946628168f80e2a32ab8c44d73

## Launch Command

echo "test" |  rofi -dmenu 

## Steps to reproduce

Just run standard rofi with -dmenu with version that is above or equal 1.3.0

## What behaviour you see

* - Element(s) apprears very slowly from time to time. (from 1 to 5-6 seconds)
* - Sometimes "Loading..." message appears.
* - Only the -demenu argument is affected. Everything works as a charp with the -show argument.

## What behaviour you expect to see

* - That rofi will works the same as always: fast as a spark.

## Additional information

I've downgraded to 1.2.0 version and the problem have been disappear.

**Comment by DaveDavenport** [comment]
Can you try version 1.3.1. Latest stable *please*, there was a fix related to this, where it would only update on the first cursor blink..

2ndly try if `rofi -dmenu -sync` helps.

**Comment by mskorzhinskiy** [comment]
> Can you try version 1.3.1. Latest stable please, there was a fix
> related to this, where it would only update on the first cursor
> blink..

I've tested it on 1.3.1 and 1.3. As I said: 1.3 and above.

> 2ndly try if rofi -dmenu -sync helps.

It helps, thanks!

**Comment by DaveDavenport** [comment]
to git i have added another update that should make it feel faster. (label disapearing more quickly).

I also added a hybrid async mode..  if you pass `-async-pre-read 100` it will load 100 items blocking
then switch to async read the rest.
