### ISSUE TITLE
Unexpected behaviour when wildcard "font" resource set in Xresources to non-pango font

### ISSUE THREAD

**Issue by asfethan** [DaveDavenport/rofi#554]
## Version

Output of `rofi -v`
1.2.0

## Configuration

N/A (without configuration)

## Launch Command

rofi -show run

## Steps to reproduce

 - set wildcard `*font` resource in `.Xresources` to xfont format value, eg:
` *font:                    -*-terminus-medium-*-*-*-14-*-*-*-*-*-iso10646-1`

## What behaviour you see

* - thin one-line window with no text which will terminate as soon as any key is pressed

## What behaviour you expect to see

* - fallback to default (or first available) font or don't pick up non-pango definitions

## Additional informations

This behaviour can be easily fixed (workaround) by specifying `rofi*font` resouce in `.Xresources`. But for new users like me it's unclear why they are experiencing this, so it could be helpful to implement described expected behaviour along with some warning message.

**Comment by DaveDavenport** [comment]
Agree.

**Comment by DaveDavenport** [comment]
This is what you see when trying your problem:
![](https://filebin.pw/UQl7R/)

With fonts specified in the new theme format this sanity check is not there.

**Comment by DaveDavenport** [comment]
Old check is still there (for old config format).
Fonts specified in the new theme format  are only parsed when used, it will ignore invalid fonts and print an error to the debug stream.
