### ISSUE TITLE
Rofi launches a terminal window, which then launches the app (subset of applications)

### ISSUE THREAD

**Issue by wjdp** [DaveDavenport/rofi#555]
## Version

0.15.11

## Configuration

https://gist.github.com/wjdp/4a950c13fa8624249c7e6cec887193fa

## Launch Command

`rofi -combi-modi window,drun -show combi -modi combi`

## Steps to reproduce

Launch simplenote. Other applications that tend to use web technology (electron-y apps) seem to be most affected.

## What behaviour you see

Rofi launches both a terminal window, which then launches the app.

## What behaviour you expect to see

Just the app launches.

**Comment by DaveDavenport** [comment]
1.) your version of rofi is to old (15 months?) please try with a newer one.
2.) Check the .desktop file of the electron-y apps, rofi will launch it in a terminal if that is specified in the desktop file.

**Comment by wjdp** [comment]
Whoops, must have installed from the Ubuntu repos. Is there a PPA for the project?

**Comment by DaveDavenport** [comment]
no idea.  Can you paste one of the desktop files that opens in terminal in a gist?

**Comment by DaveDavenport** [comment]
any update on this?

**Comment by wjdp** [comment]
[GitKraken](https://www.gitkraken.com/) is one offender. Not updated yet, haven't found an easy way to upgrade: build required many dependencies, newer debian packages have the same issue.

```
[Desktop Entry]
Name=GitKraken
Comment=Unleash your repo
GenericName=Demo Application
Exec=/usr/share/gitkraken/gitkraken %U
Icon=app
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Development;Documentation;
MimeType=text/plain;
```

**Comment by DaveDavenport** [comment]
GitKraken works fine, without a terminal, for me.

**Comment by DaveDavenport** [comment]
Unable to reproduce. Double checked code, seems correct.

**Comment by wjdp** [comment]
Eventually gave in and compiled from source (despite this package being quite power-usery, really don't want to be doing), issue fixed in 1.3.1.

**Comment by DaveDavenport** [comment]
thanks.

**Comment by pedrols** [comment]
I experienced the same issue and editing the .desktop files to add Terminal=false solved the problem for me

**Comment by DaveDavenport** [comment]
@pedrols: What version of rofi?

**Comment by pedrols** [comment]
Sorry for the delayed response. Version 0.15.11, from the Xenial repository

**Comment by DaveDavenport** [comment]
0.15.11 is 1.5 years old and not supported.
