### ISSUE TITLE
Windows aren't switching sometimes

### ISSUE THREAD

**Issue by schvabodka-man** [DaveDavenport/rofi#557]
Hi there! I've just encountered an interesting problem. When i was working on arch(manjaro) rofi works ok, but now i switched to fedora, and sometimes when i try to switch window with rofi -show window it's just not switching. Just nothing is happening at all.
My WM is i3, OS is Fedora 25

## Version
1.3.1
## Launch Command
 rofi -show window -hide-scrollbar -fullscreen
## Steps to reproduce
Just try to switch window with rofi window and sometimes(30-40%) it will not switch
## What behaviour you see
Window aren't switching
## What behaviour you expect to see
Window are switching!

**Comment by DaveDavenport** [comment]
Can you give a bit more information? for example the version of i3?
With a very outdated I3 this behaviour is to be expected.

**Comment by noahl98** [comment]
I have also been having this problem on Arch Linux running BSPWM version 0.9.2-19-gada559d.
When I use window or windowcd to switch between windows, I sometimes need to do it  multiple time in order to actually switch. When it doesn't switch, the rofi  menu just exits and nothing happens.

## Version

Version: 1.3.1-240-g98c625f-dirty (makepkg)

## Configuration

[Configuration](https://gist.github.com/noahl98/ee1f28dfd345b84ef39916207c178eca)

## Launch Command

```rofi -show window -no-fixed-line-nums```
```rofi -show windowcd -no-fixed-line-nums```

## Steps to reproduce

* Launch rofi using one of the above commands
* select on of the window options
* 30-45% it will not work and the above steps need to be repeated in order to switch the window


## What behaviour you see

* Windows don't switch  consistently

## What behaviour you expect to see

* Windows switching consistently

**Comment by DaveDavenport** [comment]
weird. 
Rofi calls `xcb_ewmh_Request_change_active_window`, so if bspwm is ewmh it should work.

Is this a new/recent problem?

**Comment by DaveDavenport** [comment]
When does this problem occurs? when switching between windows on the same desktop, or when switching to another desktop? or is it independent of that?

**Comment by noahl98** [comment]
For me, it happens both when switching between windows in different desktops and when switching windows in the same desktop.

**Comment by DaveDavenport** [comment]
I have no idea how to debug this. I cannot reproduce this with both i3 or bspwm.
As far as I can tell the right API is called.

Can you give more information about Distribution, wm version and X drivers?

**Comment by noahl98** [comment]
## System Info
- Distro: Arch Linux
- `uname -r`: 4.9.8-1-ARCH
- `bspwm -v`: 0.9.2-19-gada559d
- `xdpyinfo | grep version`: X.Org version: 1.19.1

[Here](https://gfycat.com/ShamefulWhirlwindFlickertailsquirrel) is a video of windowcd not switching. As you can see, right in the beginning, I launch rofi, select the window, and hit enter multiple times for the window to switch.

[Here](https://gfycat.com/QuerulousImpressionableGemsbuck) is a video of the same thing occurring while switching to windows in different desktops

As far as I can tell this happens with any application.

Let me know if there's any other version numbers you want or if there's more info I can provide

**Comment by DaveDavenport** [comment]
Do you have follow mouse enabled (e.g.  you move your mouse over another window, this grabs focus)?
If you move the mouse to a corner (not over a window) does it also happen?

**Comment by noahl98** [comment]
I don't have follow mouse enabled. I still tried moving my mouse to a corner not over a window and it still occurs.

**Comment by DaveDavenport** [comment]
Thanks, I could imagine that if rofi removes it window and then switch, the mouse follow might 'block'/'undo' the switch.

This is very curious maybe somebody at @bspwm can help figure this one out.

**Comment by noahl98** [comment]
yeah that would make sense. 

I will submit an issue in the bspwm github page when I get a chance later today.

Thanks for your help.

**Comment by DaveDavenport** [comment]
I can reproduce this in I3 with spotify on a visible workspace. 
If this happens I cannot use rofi to switch away. unless I put spotify workspace not on a monitor then it works.

*fun*

**Comment by schvabodka-man** [comment]
My OS is Fedora 25, i3wm version 4.13(from fedora copr, it's i3 gaps), rofi version is 1.3.1. Sorry for long response

**Comment by DaveDavenport** [comment]
Long shot, does the fix for #576 (on rofi master) help for this issue. I noticed my spotify issue is gone (but could also be spotify update).

**Comment by noahl98** [comment]
I just cloned from master and installed and it seems to be fixed for me as well!

**Comment by DaveDavenport** [comment]
Great!

**Comment by mzanibelli** [comment]
I can confirm this is fixed ! Thanks !

Additional info (using 1.3.1 release) :
- happens ~50% of the time when `compton --backend glx` is running
- happens ~5% of the time when `compton --backend xrender` is running
- couldn't really reproduce the bug without compton

I thought this could be useful somehow ;)

**Comment by SicariusNoctis** [comment]
Happens consistently on first window switch attempt. However, it works correctly on second window switch attempt.

Steps to reproduce:

 - Run `compton --backend glx`
 - Type the desired window name really fast and hit enter. You need to type at over 120 WPM.

**Comment by DaveDavenport** [comment]
@SicariusNoctis  what WM?

I am unsure what happens here, rofi sends the (right?) ewmh signals to the WM how this then handles it..

**Comment by SicariusNoctis** [comment]
@DaveDavenport I'm using i3 WM. My compton configuration is [here](https://gist.github.com/SicariusNoctis/19149584269ba59f6b8c57ce9417d944).

Oddly, this behavior is difficult to reproduce on my other laptop, but when it happens, it happens repeatedly until I restart compton.

**Comment by SicariusNoctis** [comment]
As a workaround for i3 users, I suggest using `i3-msg` to switch windows. Here is an example command:

```bindsym $mod+d exec "wmctrl -l |
                               rofi -dmenu -i -p 'window:' $rofi_style | cut -d ' ' -f1 | xargs -I {} i3-msg '[id=\\"{}\\"] focus'"```

**Comment by DaveDavenport** [comment]
@SicariusNoctis  see 2 comments ago.

It sends the EWHM signal: `xcb_ewmh_request_change_active_window`.
(I3 is on the quircks list, for other WMs it also sends the `xcb_ewmh_request_change_current_desktop`
but earlier bug reports indicated this causes some problems with i3).

**Comment by mgrechukh** [comment]
not fixed in rofi 1.3.1.2  on i3wm 4.15 (ubuntu 18.04)

**Comment by DaveDavenport** [comment]
@mgrechukh can you try with an update rofi? (1.3.1 is almost 1.5 years old)
For me it works fine with current rofi  on ubuntu 18.04.

**Comment by mgrechukh** [comment]
Yes, on 1.5.1 it works like a charm!

thank you very much

**Comment by DaveDavenport** [comment]
thx good to hear.
