### ISSUE TITLE
rofi -dmenu is always case sensitive

### ISSUE THREAD

**Issue by herrsimon** [DaveDavenport/rofi#559]
Hello,

I just noticed that 'rofi -dmenu' is always filtering in a case-sensitive manner. See below for details.

## Version
Version: 1.3.1-235-g1d6b149-dirty

## Configuration
no additional configuration (out of the box)

## Launch Command

echo "Bli\nbla" | rofi -dmenu
echo "Bli\nbla" | rofi -dmenu -case-sensitive

## Steps to reproduce

issue the above two commands and type 'b'

## What behaviour you see

Both times, the entry "Bli" is ruled out, i.e. behaviour is case-sensitive. 

## What behaviour you expect to see

Case-insensitivity when issuing first command.

**Comment by DaveDavenport** [comment]
In dmenu mode you need to use the dmenu compatible `-i` flag to switch sensitivity.

**Comment by herrsimon** [comment]
Sorry, didn't read the manpage properly. Thanks for the quick reply!

**Comment by DaveDavenport** [comment]
No problem.
