### ISSUE TITLE
Pango markup in run dialog prompt

### ISSUE THREAD

**Issue by He-Ro** [DaveDavenport/rofi#560]
## Version
Version: 1.3.1-245-g9bd4096-dirty (master)

## Configuration
https://gist.github.com/He-Ro/bd34c0d998d6d9dde64db85293308a13

## Launch Command

rofi -show run -display-run "\<b>test\</b>" -markup

## Steps to reproduce
Launch rofi

## What behaviour you see

* The prompt is set to the literal \<b>test\</b>.

## What behaviour you expect to see

* The prompt is formated in pango markup: <b>test</b>.

_Thank you for your work on rofi!_

**Comment by DaveDavenport** [comment]
`-markup` is only for `rofi -e` option.  The message in `-help` output is indeed misleading, will fix this.

I don't plan to make an individual markup option for everything.
(The new theme format allows you to make the text bold in the prompt box)

**Comment by He-Ro** [comment]
Thank you for the clarification.
