### ISSUE TITLE
Blezz Plugin

### ISSUE THREAD

**Issue by DaveDavenport** [DaveDavenport/rofi#561]
I thought it was an interesting concept, so I made a plugin for rofi that implements https://github.com/Blezzing/blezz/ .

Screencast here: https://filebin.pw/2T9/

Any interest in this? (@Blezzing what do you think?)

**Comment by Blezzing** [comment]
Woa, I'm honored! Nice to see that people other than me like that way of navigating! I've been a long time user of rofi as well and likes it extensibility, so a plugin that achieves that behaviour is a nice idea, i agree!

**Comment by DaveDavenport** [comment]
The plugin is mostly done (well first version). I should be compatible with your config file format.
Ill need to fix the build system in rofi (so rofi installing needed headers and a .pc file) and plugin to use it then I will put it online.

I think it is very useful for quick access scripts..  I have it set up now so I can quickly call my monitor-layout script, shutdown and stuff like that.

**Comment by DaveDavenport** [comment]
First test version here: https://gitcrate.org/DaveDavenport/rofi-blezz

You need rofi from git.

Run:
```
   rofi  -show blezz -modi blezz.so -auto-select -matching normal
```
To get blezz behaviour.
