### ISSUE TITLE
Question: Shift-Enter in custom mode?

### ISSUE THREAD

**Issue by AKuederle** [DaveDavenport/rofi#563]
Maybe I am missing something, but is there a way to use Shift-Enter or similar shortcuts in custom modes, like they are used in e.g. the run mode?

Tanks for the help!

**Comment by AKuederle** [comment]
Ok scrolling through the release notes I saw, that this feature was Impediment for dmenu using return codes. I think that will do for what I want to do.
I couldn't found any real documentation for that. Should I write something about this feature and if so, where?

**Comment by DaveDavenport** [comment]
The wiki would be a nice place.  Would be very usefull.
Thanks.
