### ISSUE TITLE
rofi doesn't parse /etc/rofi.conf

### ISSUE THREAD

**Issue by shibumi** [DaveDavenport/rofi#565]
## Version

Output of `rofi -v`
Version: 1.2.0-137-gd1d4a84-dirty (master)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://paste.archlinux.de/mxTI/
## Launch Command

The commandline used to launch **rofi**

rofi -show run 
## Steps to reproduce

Do this:
```
curl https://paste.archlinux.de/DJX/ -o /etc/rofi.conf
rofi -show run
rofi -show run -config /etc/rofi.conf
```

## What behaviour you see

rofi doesn't parse the global config

## What behaviour you expect to see

rofi should parse the global config

**Comment by DaveDavenport** [comment]
It reads `$(sysconfdir)/rofi.conf`, what  `${sysconfdir}`  is is determined by the whoever compiled it. (if unset it is ${prefix}/etc/). 

So if compiled yourself, pass `--sysconfdir=/etc/` to configure, if you use a package, file a bug with that.
