### ISSUE TITLE
rofi set line number to zero

### ISSUE THREAD

**Issue by shibumi** [DaveDavenport/rofi#566]
## Version

Output of `rofi -v`
Version: 1.2.0-137-gd1d4a84-dirty (master)

Hello,
is there a way to set the rofi line number to zero? I would like to have a more similar dmenu approach. so when i use `rofi -dmenu` i only want one line and the programms listed on the right of the input field.
is there such a way?

**Comment by DaveDavenport** [comment]
Duplicate of #252
