### ISSUE TITLE
ctrl-Enter (use entered text as command) does not work on run entries in a combi modi

### ISSUE THREAD

**Issue by justmytwospence** [DaveDavenport/rofi#567]
## Version

1.2.0

## Configuration

[gist](https://gist.github.com/justmytwospence/fca9159be15bf134b2aad9d07da56f95)

## Launch Command

`rofi -combi-modi drun,window,ssh,run -modi combi -show combi`

## Steps to reproduce

Run the above launch command.

## What behaviour you see

The ctrl-Enter keybinding (to use entered text as command) does not work in a `combi` modi. 

## What behaviour you expect to see

As far as a can tell from the README, it seems that this is technically intended behaviour because the keybinding is only supported in the `run` and `ssh` modi. Can this keybinding also be enabled for `run` and `ssh` entries in a `combi` modi which includes them?

**Comment by DaveDavenport** [comment]
Say you type in blaat in combi mode and it has no match. How would combi mode know with what mode  to execute it?

You can force it though by prepending it with !r (for run)

```
!r blaat
```

Will execute it with run mode.

**Comment by justmytwospence** [comment]
Forgive me but I'm not quite sure what you mean by "know with what mode to execute it." What is fundamentally preventing Rofi from just executing the unmatched command when I press Ctrl-Enter?

**Comment by DaveDavenport** [comment]
But if you type in `blaat` do you want to ssh to blaat (as ssh mode does) or execute it? How should the combi mode know?

**Comment by justmytwospence** [comment]
Oh I see the problem. I suppose the right thing could be determined for the case when the modi only includes one of those modes.  I would still find that better than nothing. And/or maybe a flag to resolve ambiguity?

**Comment by DaveDavenport** [comment]
As indicated above,  by prefixing your query with a bang you can tell it what todo:
```
!r blaat
```
Execute it using run dialog
```
!s blaat
```
Execute it using the ssh dialog.

I don't want to add 'smart' logic to resolve this, as it often results in confusing behaviour for the user.
