### ISSUE TITLE
[feature-request] more space between "run" and command in "run mode"

### ISSUE THREAD

**Issue by shibumi** [DaveDavenport/rofi#569]
Hello,
I am not sure if it's the fault of my font.. but when I run rofi in "dmenu" mode the gap between "run" and the "command" looks very small. So for example when I type "chromium" it looks like:"runchromium" that's a little bit irritating. I would ask if we could add more space or at least a seperator between both, or if we could add an option for a custom seperator.

**Comment by DaveDavenport** [comment]
This can be set in git in the new theme format.
