### ISSUE TITLE
[feature request] Support for Include directive in .ssh/config

### ISSUE THREAD

**Issue by Azenet** [DaveDavenport/rofi#570]
Hello,

Currently (45c70cbecf980769ec5cda10e1186bf3d7dcb580) the `Include` directive in `.ssh/config` is ignored. It would be useful if rofi read the `Include` directive recursively and included relevant files.

Thanks

**Comment by DaveDavenport** [comment]
In https://github.com/DaveDavenport/rofi/tree/issue570 I have implemented the Include.
It supports the following: `Include {path}`
Where `path` can be:  
- Relative
- Absolute
- `~`  and ~user/ are expand.

Glob style matching is implemented. You can do do `config.d/*` to read all files in ~/.ssh/config.d/.

Can you test?

**Comment by Azenet** [comment]
Relative and absolute works well, glob-style matching does as well, but `~` and `~user/` doesn't. No errors to be seen in logs:

```
## Include ~/.sshfiles/sshconfig
$ G_MESSAGES_DEBUG=Dialogs.Ssh ./rofi -show ssh
Adding mode: ssh
(process:13146): Dialogs.Ssh-DEBUG: Parsing ssh config file: /home/azenet/.ssh/config
(process:13146): Dialogs.Ssh-DEBUG: Found Include: ~/.sshfiles/sshconfig
```

```
## Include ~azenet/.sshfiles/sshconfig
$ G_MESSAGES_DEBUG=Dialogs.Ssh ./rofi -show ssh
Adding mode: ssh
(process:13146): Dialogs.Ssh-DEBUG: Parsing ssh config file: /home/azenet/.ssh/config
(process:13146): Dialogs.Ssh-DEBUG: Found Include: ~azenet/.sshfiles/sshconfig
```

**Comment by DaveDavenport** [comment]
oeps should be fixed. I expanded the path, but used the non expanded version......

**Comment by Azenet** [comment]
Yes, it works properly now. Thanks a lot!
