### ISSUE TITLE
ssh dialog doesn't support hosts with ssh on custom port.

### ISSUE THREAD

**Issue by sarg** [DaveDavenport/rofi#575]
## Version

Version: 1.3.1

## Configuration

debian default

## Launch Command

`rofi -show ssh`
## Steps to reproduce

* known_hosts should contain entries with port, like
`[storage.domain.my]:58319 ecdsa-...`
* select this entry in rofi

## What behaviour you see

* rofi silently closes and nothing happen

## What behaviour you expect to see

* I expect to see terminal window

**Comment by DaveDavenport** [comment]
it does actually start terminal with ssh, but probably ssh instantly fails.

I never use `known_hosts`  myself, I specify my hosts (And alternate ports) in my ssh config file.

Patch to fix this is welcome.

**Comment by gun1x** [comment]
I started using rofi this week and noticed that it gives me some nodes from `.ssh/known_hosts`, but not all. I have 500 nodes in known_hosts, and 10 patters for IPs and ports in `.ssh/config`, and rofi-ssh shows about 50 nodes, so I am really confused regarding how rofi gets the list of hosts.

Can somebody please point me in the right direction regarding how I should move forward to get rofi to display all nodes from known_hosts?

**Comment by DaveDavenport** [comment]
This is fixed now in git, needs testing.

**Comment by gun1x** [comment]
@DaveDavenport I tested this by installing rofi-git from AUR. It works wonders.

THANK YOU!!!
