### ISSUE TITLE
Local *.desktop files should have a higher priority than global ones

### ISSUE THREAD

**Issue by b52** [DaveDavenport/rofi#577]
For certain applications I want to override the default behaviour by placing a slightly modified version in my `~/.local/share/applications/` with the same name. However, it seems like `rofi` ignores this file if he already found a global one with the same name.

**Comment by DaveDavenport** [comment]
Please follow the guidelines for reporting an issue. Will re-open when missing information is added.

**Comment by b52** [comment]
Sorry for not following protocol, I just created a new issue #579 according to the guidelines.
