### ISSUE TITLE
Rofi does not close on escape key

### ISSUE THREAD

**Issue by BharatKalluri** [DaveDavenport/rofi#587]
## Version

Output of `rofi -v`
`Version: 1.3.1`

## Launch Command

The commandline used to launch **rofi**

 I am using a fresh fedora install, when I try to open rofi it opens up fine. for closing , escape does not work. I had to use ctrl-c to close rofi.
 How can I make rofi close when escape is pressed?

**Comment by DaveDavenport** [comment]
Can you fill in the missing information.

Can you also report what fedora version you are using and if you are using wayland?

**Comment by BharatKalluri** [comment]
@DaveDavenport Sorry for not being specific, I am using fedora 25 and yes, it is running on wayland.

Any more information needed? Had been using rofi in ubuntu before, love it!

**Comment by sardemff7** [comment]
It will work as soon as Fedora includes a recent enough Xwayland, with the not-yet-designed keyboard grab protocol. Nothing we can do on our side.

Also, it depends on your compositor. If you’re using GNOME, you’re stuck with Xwayland. With Weston (and other libweston-based compositors) you can try our shiny (WIP) Wayland native support (`wip/wayland` branch) thanks to the [wayland-wall](https://github.com/wayland-wall/wayland-wall/tree/master/unstable/launcher-menu) protocol and related [weston-wall](https://github.com/wayland-wall/weston-wall/blob/master/src/launcher-menu.c) plugin. Using a WLC-based compositor, you can use the [wlc-wall-injector](https://github.com/wayland-wall/orbment-wall/blob/master/src/wlc-injector.c).

See #446 for more information.
