### ISSUE TITLE
Cannot enter text when there are no background windows

### ISSUE THREAD

**Issue by adtac** [DaveDavenport/rofi#591]
## Version

Output of `rofi -v`

`Version: 1.3.1`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

https://gist.github.com/adtac/d618379a2e4e34f4c305a77f086ca0b1

## Launch Command

The commandline used to launch **rofi**

`rofi -show run`

## Steps to reproduce

* Step 1: Login to Wayland. Do not open any windows.

* Step 2: Have a keybinding mapped to run `rofi -show run`.

* Step 3: Press that keybinding.

* Step 4: rofi will correctly show up. But try typing stuff - it won't work.

* Step 5: Open any other window (you can't close rofi, let it stay up).

* Step 6: Now start typing: it'll work

And then it'll work perfectly if there's a window in the background.

## What behaviour you see

* Unable to type when there are no background windows.

## What behaviour you expect to see

* I should be able to type if there are no background windows

**Comment by DaveDavenport** [comment]
duplicate: #431

**Comment by adtac** [comment]
Couple of things:

 - I'm using GNOME, not sway.

 - I can't type even if there's a background window without any textbox. For example, a terminal will have a input area but an application like `evince` (a document viewer) will not. Pressing my keybinding and typing works when there's a terminal in the background. But pressing the keybinding and typing does not work when `evince` is in the background.

**Comment by adtac** [comment]
`-normal-window` works for me

**Comment by adtac** [comment]
Okay, I just read https://github.com/DaveDavenport/rofi/wiki/Wayland and it looks like native Wayland support will be impossible. Guess I'll go back to using `-normal-window`

**Comment by sardemff7** [comment]
@adtac Not impossible, at all. If you read the page, you should have seen that it exists already, and people even use it. Support in *GNOME*, otoh, is unlikely, but you can try to convince them it’s a feature you really need.
The current protocol is pretty much a draft and more than enough for non-DEs, but I bet GNOME will want something based on xdg_shell, which will need more work, but if they agree to support it, I will happily do the work.
