### ISSUE TITLE
Can't tab backwards with Shift+Tab (Thinkpad T410)

### ISSUE THREAD

**Issue by milopiccolo** [DaveDavenport/rofi#594]
## Version

Output of `rofi -v`

1.3.1

## Configuration

[Here.](https://gist.github.com/milopiccolo/a3647326e9420aaa2f6c2b8d4590d5d4)

## Launch Command

rofi -modi combi,window,run,ssh -combi-modi window,run -show combi

## Steps to reproduce

Step 1
Tab forward, works fine
Step 2
Try to Shift+Tab backward.

## What behaviour you see
Nothing happens on the Shift+Tab press.

## What behaviour you expect to see
It should go backward.

## My notes & fix
It works when I add "Shift_L+ISO_Left_Tab" to the rofi.kb-row-up entry.

I'm on a Thinkpad T410. This might be a device-specific issue, I'm not very knowledgeable about keycode stuff (any good links appreciated!). Reporting it anyway so that, at worst, people can find this on Google.

**Comment by DaveDavenport** [comment]
Can you try without the 'Shift_L', I don't think that does anything.

so:  rofi -kb-row-up 'ISO_Left_Tab' -show run

**Comment by milopiccolo** [comment]
Yes, I can confirm that this works.

**Comment by hobarrera** [comment]
Is the `kb-row-up` setting undocumented? The man page doesn't mention it, and there's not many references to it in the repo (basically, this issue is what made my find what I was looking for).

**Comment by DaveDavenport** [comment]
@hobarrera  please next time make new bug report, don't add to other reports.

Quote from manpage:
```
To get a full list of keybindings on the commandline, see `rofi -dump-xresources | grep kb-`.
Keybindings can be modified using the configuration systems.
To get searchable list of keybindings, run `rofi -show keys`.                                
```

**Comment by hobarrera** [comment]
Oh cool. Can we add `Tab` to the default keybindings listed on the README though?

**Comment by DaveDavenport** [comment]
@milopiccolo  thanks for the report. I  will add it to F.A.Q.
