### ISSUE TITLE
rofi fails to build after 46dee2671d: error: ./source/x11-helper.c: No such file or directory

### ISSUE THREAD

**Issue by Coacher** [DaveDavenport/rofi#602]
Hello.

rofi builds fine @ 4e3830a. When trying to build latest master build fails. Most likely the offending commit is 46dee2671d.

Complete build.log: https://paste.pound-python.org/show/DOHmarhGWxBMXbX0kLHi/

Please fix.

**Comment by sardemff7** [comment]
My bad, fixed in 96364c461f3c86a69497b53dbf68c23466f4942a.

“Please fix” is a bit rude btw.

**Comment by Coacher** [comment]
> “Please fix” is a bit rude btw.

Why?

**Comment by Coacher** [comment]
> My bad, fixed in 96364c4.

I can confirm 96364c4 fixes the problem. Thank you.
