### ISSUE TITLE
Meson does not generate pkgconfig

### ISSUE THREAD

**Issue by westernmagic** [DaveDavenport/rofi#610]
## Version

Version: 1.3.1 - 1.3.1-645-g252d89a1 (master)

## What behaviour you see

* meson.build does not generate rofi.pc pkgconfig file

## What behaviour you expect to see

* meson and autotools should result in the same build

**Comment by sardemff7** [comment]
Fixed in 2d96f948783344fdb776dff83972135080c362e6. Thanks for the report.
