### ISSUE TITLE
Rofi keybindings fail if the X modifiers mod3 or mod4 are in effect. Should these modifiers be ignored

### ISSUE THREAD

**Issue by talwrii** [DaveDavenport/rofi#612]
## Version

Output of `rofi -v`

    > rofi -v
    Version: 1.3.1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

https://gist.github.com/anonymous/78132190a6493a75b98e34e66520bbac

## Launch Command
    
    > echo -e 'one\ntwo\nthree' | rofi -dmenu -multi-select

## Steps to reproduce

I am using the mod3 modifier combined with another key to press return. This may not be a very common things to do. But I'm [not alone in in using this sort of thing](https://unix.stackexchange.com/questions/55076/what-is-the-mode-switch-modifier-for
).

Change your keyboard map so that some key is mapped to mod3, press this mod3 while pressing shift and return.

I tried to creating a repro using xdotool and similar but gave up because I could not find a software way to set modifier keys

This is an impressionistic idea for how you might reproduce this yourself 

    xmodmap -e 'clear control\nadd control = Control_L\nadd mod3 = Control_R'
    press left right controls and enter in rofi run as before

## What behaviour you see
 
This is treated as an enter command causing rofi to immediately exit rather than a shift-enter causing an item to be selected.

## What behaviour you expect to see

A dot to appear next to an item

## Possible fixes

It remains to be seen whether anyone is using mod3 and mod5 as modifiers rather than as a variant of the shift key. People might be using this for their window manager... but I believe window managers get offered to accept keybindings before apps? Also a guess people might like to use these modifiers for keybindings in rofi: unlikely but possible.

One approach is to just ignore these modifiers (but maybe not super!), another would be to provided the ability to bind them.

## Work around

This use case may be fairly rare. I am going to work around this by remapping a keybinding 

    > rofi -dump-xresources | grep kb-

**Comment by sardemff7** [comment]
`Mod4` is the same as `Super` (for us). `Mod5` is the same as `Alt` (and `Mod1`) for us. `Mod3` is already ignored. At least, if you use these exact names.
Using `Mod5` as an alias to `Alt` is probably what is troubling you. It is easily fixable by itself, but it should not be needed:
We do check for consumed modifiers, which means if your keymap has the proper info for `Mod5+otherkey` being `Return`, it will work. Or at least it should.
Can you give us the output of `setxkbmap -print'?

Hacks around X11-specific executables (`xmodmap`, `xkbcomp`) and old rarely used XKB features (like key redirects) will be less and less supported as we moved to libxkbcommon and more stuff is done client-side, which allows nicer Wayland support.

**Comment by talwrii** [comment]
@sardemff7 Interesting... I was hoping you wouldn't need to get people to use or understand my keymap!

`setxkbmap -print` doesn't look to be too helpful. Do I need some other flags?

    > setxkbmap -print
        xkb_keymap {
    	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
    	xkb_types     { include "complete"	};
    	xkb_compat    { include "complete"	};
    	xkb_symbols   { include "pc+gb+inet(evdev)"	};
    	xkb_geometry  { include "pc(pc105)"	};
    };

It looks like you've successfully goaded me into writing a repro. This suggests that `mod3` is somehow interfering with shift.

    set -x
    setxkbmap us
    xmodmap -e 'clear control'
    xmodmap -e 'clear shift'
    xmodmap -e 'keycode 37 = Mode_switch'
    xmodmap -e 'clear mod3'
    xmodmap -e 'add mod3 = Mode_switch  '
    xmodmap -e 'add shift = Shift_L Shift_R'
    xmodmap -e 'keycode 65 = space space Return Return space'

    echo 'left control is now mod3 and Mode_switch'
    echo 'press control+shift+space (on left hand side)'
    echo 'prove that it behaves as expected in xev'
    echo 'It should be similar to shift+enter'

    xev &
    proc=$!
    sleep 15
    kill $proc


    clear

    echo 'press shift+return. Observe that it does not quit'

    echo 'press control+shift+space (on left hand side)'
    echo 'this should select not quit. Note that it quits'

    echo  -e 'one\ntwo\nthree' | rofi -dmenu -multi-select  &
    proc=$!
    sleep 1

    #xdotool key 'Mode_switch+control+space'


    sleep 20
    kill -9 $proc

    sleep 1;

**Comment by talwrii** [comment]
For reference I'm using *i3wm* version 4.13-1

    > dpkg -l | grep i3 | grep window | head -n 1 
    ii  i3                                        4.13-1                                 amd64        metapackage (i3 window manager, screen locker, menu, statusbar)

I'm also using *Xorg*

    > dpkg -l | grep i3 | grep window | head -n 1 
    ii  i3                                        4.13-1                                 amd64        metapackage (i3 window manager, screen locker, menu, statusbar)

**Comment by sardemff7** [comment]
Some of your `xmodmap` commands are erroring out here. So I cannot test your exact setup.
However, your changes seem simple enough to not take hours of learning to make a proper xkb keymap out of them.
In the `/usr/share/X11/xkb/symbols/` directory, the `ctrl` and `altwin` files contain examples on how to change modifiers. Check files in there to add a modifier level if needed.
Just use `us` as a base (see the `include` in these files), and with a 8-lines file you should have the exact same setup.

**Comment by talwrii** [comment]
Thanks for the quick reply.

> Some of your xmodmap commands are erroring out here. So I cannot test your exact setup.

:/ Whoops, didn't spot that error! It was because I failed to clear `mod5` before using the `Mode_switch` key as a modifier. I think I didn't notice this because of all of `xev`'s output:  I should have used `set -o errexit`.  Anyway, I've fixed up the script in the above comment and added `set -o errexit`

> However, your changes seem simple enough to not take hours of learning to make a proper xkb keymap out of them .

`xmodmap` isn't deprecated yet! (Although it might be soon).
Alas my changes are quite a lot more complicated than this (I use `mod3` to add a new key to virtually every key on my keyboard). I can give you the `xmodmap` command I use if you like, but the above repro is a lot simpler to trigger the same behaviour.

I tried a while back to move my changes into `xkb` but gave up . I may try again at a later date.

Anyway, the workaround where I just remap the command in `rofi` seems quite acceptable to me. This was more an exercise in responsible bug reporting than an attempt to fix a problem for myself.

**Comment by sardemff7** [comment]
> `xmodmap` isn't deprecated yet! (Although it might be soon).
It is as soon as you try to support both X11 and Wayland with maximum shared code.
However, xmodmap should just alter the xkb keymap in the X server, so simple changes should not be an issue.

> Alas my changes are quite a lot more complicated than this
It’s not complicated to just add a modifier level. From your script:
```
xmodmap -e 'keycode 65 = space space Return Return space'
```
translates into:
```
key <SPCE> ( [ space space Return Return space ] );
```
not exactly hard to do :-)

However, I think you just lack a tiny xmodmap thing for all that to work directly.

Anyway, `Mod3` is already ignored, and `Mod5` seems to be the issue here. As it is used for the AltGr key, that people do expect to use as Alt too (at least I do), we cannot drop it from the list. But we check for consumed modifiers, so I’d call it a pure xmodmap incomplete hack issue. :-)

I’m closing this issue, but please share your full xmodmap script so that we can (maybe) help users with the same issue in the future.

**Comment by sardemff7** [comment]
Actually, thinking more about it, I will remove AltGr/`Mod5` from the list. In most cases, if it’s split from Alt, it means a whole new layer of keysyms are there and you’d have to bind them directly anyway.
