### ISSUE TITLE
rofi: error while loading shared libraries: libxcb-xrm.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by m147** [DaveDavenport/rofi#615]
After a lot of jackery I seemed to have successfully compiled and installed rofi (maybe).  Everything seemed to run without errors.  And I've learned a lot in the process :D :D :D.
But still one last (I hope) issue.

In terminal when I run "rofi" I get and error: 

`rofi: error while loading shared libraries: libxcb-xrm.so.0: cannot open shared object file: No such file or directory`

when I run "exec rofi" it kills that terminal window

also, I cannot get it to invoke in i3, here is the entry in my i3 config: 

`bindsym $mod+d exec rofi -show run`

**Comment by DaveDavenport** [comment]
Please do not abuse the **issue** tracker for (linux) support. I can help in the IRC channel, or on the forum [here](https://reddit.com/r/qtools/). 

Hint: After installing libxcb-xrm.so.0 you probably failed to run `ldconfig`.
