### ISSUE TITLE
Small bug in interpreting command line parameters of .desktop files

### ISSUE THREAD

**Issue by Dathem** [DaveDavenport/rofi#617]
## Version
`Version: 1.3.1`

## Configuration

https://gist.github.com/Dathem/1d6e315d4f714cdda24bc14f120088eb

## Launch Command

`rofi -show drun`

## Steps to reproduce

* Create a .desktop file that's supposed to run some command with something like an URL as parameter

**Example:**

```
[Desktop Entry]
Name=Start Counter Strike: Global Offensive through Steam
Exec=steam steam://rungameid/730
Type=Application
```

* Run it with rofi

## What behaviour you see

* The command `steam` being run with `steam:/rungameid/730` as parameter (One slash is missing after the colon)

## What behaviour you expect to see

* The command `steam` being run with `steam://rungameid/730` as parameter

**Comment by DaveDavenport** [comment]
problem seems to be `rofi_expand_path`

**Comment by DaveDavenport** [comment]
Removed the `rofi_expand_path` from drun. There is no point calling it.

Its on `next` branch.

**Comment by Dathem** [comment]
I can confirm it's working properly now.
