### ISSUE TITLE
Coredump when trying to run non-existing program

### ISSUE THREAD

**Issue by Coacher** [DaveDavenport/rofi#623]
## Version

Version: 727e3dc-dirty (git-r3/HEAD)

## Configuration

https://paste.pound-python.org/show/vee4D3XB1PR52yBaRP5l/

## Launch Command

rofi -modi run -show run

## Steps to reproduce

* Step 1. Type the name of non-existing program, e.g. 'lorumipsum'
* Step 2. Hit `<Enter>`

## What behaviour you see

* - rofi closes, core is dumped.

## What behaviour you expect to see

* - rofi closes (with an optional warning), core is not dumped.

**Comment by DaveDavenport** [comment]
yep, this was fixed yesterday evening. (on next branch). will merge soon (got 3rd party confirmation it worked).

**Comment by DaveDavenport** [comment]
Should be on master now. Can you confirm it fixes it.

**Comment by Coacher** [comment]
I confirm. Thank you very much.
