### ISSUE TITLE
Selected window is moved to active workspace

### ISSUE THREAD

**Issue by Honnou** [DaveDavenport/rofi#624]
## Version
Version: 1.3.1-677-git-46cff2d (master)

## Configuration
[rofi -help](https://gist.github.com/Honnou/dde020bbf7c0254acf997ab6074ca24a)
[theme config](https://gist.github.com/Honnou/db621ef63a71aa6eef4eac512183e391)

## Launch Command

Problem produced both when using this command
```rofi -show window```
or this script
```rofi \
    -show window  \
    -kb-cancel "Alt+Escape,Escape" \
    -kb-accept-entry "!Alt-Tab,Return"\
    -kb-row-down "Alt+Tab,Alt+Down" \
    -kb-row-up "Alt+Shift+Tab,Alt+Up"&
```

## Steps to reproduce

* Step 1: open 'window mode' 
* Step 2: select another window on a separate workspace

## What behaviour you see

* - when changing focus to another window, the window is moved to the currently active workspace, so if I have a terminal on WS3 while WS1 is active, I remain on WS1 while the window is moved to WS1.

## What behaviour you expect to see

* - when the focus is changed to another window, I want to see the active workspace to switch to that ws. In the previous example, where a terminal is active on WS3 and I am on WS1, I want to switch to WS3 when focusing on the terminal.

I hope I supplied everything correctly!

**Comment by DaveDavenport** [comment]
What window manager (and version) do you use. EWMH compatible should work out of the box, some others need work-arounds.

**Comment by Honnou** [comment]
I use the XFCE WM, I know should be EWMH compatible, as the EWMH polybar module works on my system. 

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DaveDavenport** [comment]
hmm haven't tried xfwm in a while.  I can add it to the list of WM's that need explicit ws change.
Normally I only do a 'request change active window', for awesome/openbox  I do a `change current desktop first`.

**Comment by DaveDavenport** [comment]
Can you run:
```bash
G_MESSAGES_DEBUG=X11Helper  ./rofi -show window
```
And tell me what it returns on this line (this is on i3):

```
X11Helper-DEBUG: Found window manager: i3
```

**Comment by Honnou** [comment]
(process:6594): X11Helper-DEBUG: Found window manager: Xfwm4
Is this what you mean?

**Comment by DaveDavenport** [comment]
Yes, thanks.

**Comment by DaveDavenport** [comment]
Ok, added a possible fix on the Xfwm4 branch  (PR #626).
Can you test?

**Comment by Honnou** [comment]
I'm afraid I can't test it anymore today, I'll let you know in about 12h

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Honnou** [comment]
Nevermind I could try it anyway, it works now!

**Comment by DaveDavenport** [comment]
Great! thanks.
