### ISSUE TITLE
Seperator-style ignored in Xresources

### ISSUE THREAD

**Issue by flatcap-monty** [DaveDavenport/rofi#627]
## Version
1.3.1.r668.gfcd9878a-1

## Configuration
Output of `rofi -help` (in a [gist](https://gist.github.com/))

## Steps to reproduce
* Add a rofi.seperator-style line in .Xresources and merge xrdb

## What behaviour you see

* Settings are ignored

## What behaviour you expect to see

* Settings to be followed

**Comment by DaveDavenport** [comment]
This should now be fixed in master.
