### ISSUE TITLE
-monitor -3 issue

### ISSUE THREAD

**Issue by vKnmnn** [DaveDavenport/rofi#630]
Version: 1.3.1 - 1.3.1-688-g0d6bff93 (master)

## Configuration
config at:
https://gist.github.com/vKnmnn/7fffce11b93bba70216d73c69adf9680

## Launch Command
checkupdates is a pacman tool which reports which packages are ready to be updated
checkupdates | rofi -dmenu -p "Updates" -no-fullscreen -lines $(checkupdates | wc -l) -width -30 -no-custom -monitor -3 -location 1 -theme-str '#window {anchor:southwest;}'
checkupdates | rofi -dmenu -p "Updates" -no-fullscreen -lines $(checkupdates | wc -l) -width -30 -no-custom -monitor -3 -location 1
checkupdates | rofi -dmenu -p "Updates" -no-fullscreen -lines $(checkupdates | wc -l) -width -30 -no-custom -monitor -3 

rofi is not being displayed, up and down arrows work and upon pressing enter, the invisible selected line appears in the terminal
all other monitor settings work (eg. 0, -1, -2, -5)

i found issue #358 which is a probable duplicate

i have a button in my i3blocks bar which displays the number of updates available. on leftmouseclick the script calls above command and should display the output of checkupdates but fails to do so.

**Comment by DaveDavenport** [comment]
aah I see, re-done the location to bitmask.. so the numbering scheme is off.
Will fix.
This should work: `-theme-str '#window {anchor:southwest; location: north west;}'`

**Comment by DaveDavenport** [comment]
should be fixed in git, I convert old location into new scheme.

**Comment by vKnmnn** [comment]
yes, it works again, thank you.

**Comment by DaveDavenport** [comment]
thx for testing.
