### ISSUE TITLE
Failed to execute 'command'. Error: 'Failed to execute child process'

### ISSUE THREAD

**Issue by eyalev** [DaveDavenport/rofi#631]
## Version
0.15.7

## Configuration

[gist](https://gist.github.com/eyalev/a644bb75fdc6f476c2b25d9284a94682)

## Launch Command

`rofi -show run`

## Steps to reproduce

* Run command: `VAR=value bash -c 'echo $VAR'`

## What behaviour you see

![selection_190](https://user-images.githubusercontent.com/117240/28081107-da04d792-6676-11e7-9ad9-27365173dda3.png)

## What behaviour you expect to see

Output in command line: `value`

**Comment by DaveDavenport** [comment]
your version is to old (2 years) and no longer supported.

The error messages is correct. `VAR=value` is most likely not a valid executable on your system.
You want `rofi` to execute your commands using a shell,  you can  configure this (atleast in current releases).

**Comment by sardemff7** [comment]
As a side not, this is what `env` is made for. Running `env VAR=value bash -c 'echo $VAR'` will work.

**Comment by eyalev** [comment]
@DaveDavenport I saw the -run-shell-command but I couldn't get it to work. Can you give an example how to run this as a command line option?

@sardemff7 thanks! this indeed works, but in my use case it will be much more comfortable for me to run it as I wrote it on the original post.
