### ISSUE TITLE
Add ability to embed rofi to windowid (as in dmenu -w)

### ISSUE THREAD

**Issue by mbfraga** [DaveDavenport/rofi#632]
Feature request to implement an option to embed rofi to a window via windowid. The idea here is to emulate the behavior in dmenu -w <windowid>.

## Version

Applies to all versions, but I am using 1.3.1.

## What behaviour you expect to see

Running rofi with this option should show rofi on the corresponding window. Perhaps it would be a good idea to force -normal-window in such a case. Otherwise I am not sure what will happen when you run it and the target window is not in an active workspace.

**Comment by DaveDavenport** [comment]
tried dmenu, with -w option:
```ls | dmenu -w 0x1c00007
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  138
  Current serial number in output stream:  139
```

It switches to the indicated window, and dmenu stops  fun.
(wanted to test if dmenu does the mouse/keyboard grab)

**Comment by DaveDavenport** [comment]
Added a test version to git.

**Comment by DaveDavenport** [comment]
fixed in git (master).
