### ISSUE TITLE
Underlining matches causes shift in rendering

### ISSUE THREAD

**Issue by mkoskar** [DaveDavenport/rofi#633]
## Version

``Version: 1.3.1``

## Configuration

``default``

## Launch Command

``printf '%-50s \U2185' 'ab' | rofi -config /dev/null -width 600 -dmenu``

## Steps to reproduce

* Step 1: launch with command above
* Step 2: type ``ab``

## What behaviour you see

* as ``ab`` will get underlined, alignment of row breaks down and the right side moves from right to the middle portion of the window 

## What behaviour you expect to see

* just underlining without shifting of characters

**Comment by DaveDavenport** [comment]
Weird pango bug.  It does not happen when I set color on highlight, but on bold,italic and underline if the whole word is marked, it does this.

**Comment by DaveDavenport** [comment]
I can reproduce this in **gedit** too. So it seems to be a bug in pango, not rofi specific (regrettable). 
Don't think I can fix this in rofi.

**Comment by mkoskar** [comment]
For me it happens regardless of colors, or do you refer to some code changes you did while testing this? I.e., is there any workaround that can be done with configuration?

So it's pango, I see, I thought it will be some font rendering library issue actually. I skimmed pango's bug-tracker searching if it's not a known or reported issue. No luck so far though.

**Comment by DaveDavenport** [comment]
In GIT you can specify the highlighting being used.

**Comment by DaveDavenport** [comment]
It seems that it uses whitespace from the `\U2185` character when the text up-to the whitespace is wrapped in a pango-attribute block.  The font used for \U2185 has a smaller space width.
For me it uses Font Awasome for this, using this font in rofi 'fixes'  the issue.

[this](https://bugzilla.gnome.org/show_bug.cgi?id=7577850) seems related.

**Comment by mkoskar** [comment]
Ah, interesting! Font Awesome doesn't cut it for me though. From what I've looked it doesn't have `\U2185` (it's just an random example anyway). On my system that one is provided by Symbola. Then having Symbola to render everything I can confirm the spaces are static, text moves a bit because of each underlined character stretches a tiny bit in width though.

Reading the linked bug report explains a lot, although towards the end see highlighted part.

> If font before and after space are both the same and they support space, then we should use that.  However, if the font used for before and after are different, **then currently we choose the one used for before**.  However, we should use the one between before/after that has a higher priority.  Fixing that will fix this case.

Based on that the space in our case here should be from the font before but that's not happening right?

**Comment by DaveDavenport** [comment]
I *think* because the highlighting does grouping (it renders each part with the same attributes separately , and therefor  it actually groups the space with the utf8 character. (adding a l infront of it fixes it again).
But this is mostly conjecture , but I can reproduce this behaviour in most gtk application

Anyway, regrettable, not something I can fix (sanely) on my side..

**Comment by mkoskar** [comment]
Right, I got lost in it. So in normal case it indeed works like mentioned in that quoted paragraph but then when pango markup is used for underlining it clumps remaining spaces together with the rightmost character and uses its font. Whereas I see some logic in it (in case I got it right), still it seem wrong to me. Anyway, I've made a note about this and will possibly report it to pango/cairo later and we'll see what comes out of it. Thanks for looking into it! ;)

**Comment by mkoskar** [comment]
I thought I post a way how to reproduce what we were talking about here for reference.

```
pango-view --font=monospace --markup -t '
followed by 10 spaces          ↅ
followed by 10 <u>spaces</u>          ↅ
followed by 10 <i>spaces</i>          ↅ
followed by 10 <b>spaces</b>          ↅ
'
```

Resulting in following rendered output (``--backend=cairo/xft/ft2`` doesn't make a difference):

![screenshot-2017-07-22 1500714504](https://user-images.githubusercontent.com/4387891/28489898-1bf06d38-6ece-11e7-9a44-68780a9ab2c3.png)

@DaveDavenport But look at the underline vs. italics / bold! This is very peculiar.

**Comment by DaveDavenport** [comment]
rofi does underline + bold. In git you can choose to only use underline.
