### ISSUE TITLE
how to add gksu before run ?

### ISSUE THREAD

**Issue by icf20** [DaveDavenport/rofi#636]
## Version

Output of `rofi -v`
1.3.1

if i type "printer" on rofi run mode i get system-config-printer, i dint find anyway to auto complete "system-config-printer" instead of "printer" into the run field to add gksu, the only way to do this is to type everything " gksu system-config-printer" and is annoying 

edit: i know i can select the system-config-printer with ctrl+space but then i need to press the left arrow key until the cursor goes in front of system-config-printer because "start/home" dont work

**Comment by carnager** [comment]
If you dont need the run-in-terminal option for anything else you could use this.
`rofi.run-shell-command: "gksu '{cmd}'"`
Then use Shift+Enter to run an application with gksu

**Comment by icf20** [comment]
and i fount it ... ctrl+a does what home i expected to do
