### ISSUE TITLE
"-drun"  renders rofi non functional

### ISSUE THREAD

**Issue by ivarsu** [DaveDavenport/rofi#638]
## Version

Output of `rofi -v`
Version: 0.15.11

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
"
https://gist.github.com/ivarsu/0132c202cd12decf2a20aa2db1bc7e4e
"
## Launch Command

The commandline used to launch **rofi**
-run (-drun is prefferable)
## Steps to reproduce

* Step 1
* Step 2

## What behaviour you see
when rofi is given "-drun", it does not launch. (this works fine on several other cmputers of mine)
* -

## What behaviour you expect to see
-drun working
* -

**Comment by sardemff7** [comment]
This is an ancient version, it is not supported any more. Please update to a newer version.
