### ISSUE TITLE
Feature request: Separate horizontal/vertical padding

### ISSUE THREAD

**Issue by zacps** [DaveDavenport/rofi#639]
When using rofi in fullscreen mode it would be nice to be able to specify a separate horizontal and vertical padding.
An example of my current configuration:
![2017-07-24-174250_1920x1080_scrot](https://user-images.githubusercontent.com/9827696/28509636-b09786b8-7097-11e7-85c3-7b58ef0596dd.png)

I'd like to be able to make the window narrower (horizontally) while keeping it centered.

**Comment by DaveDavenport** [comment]
This is supported in git, and will be part of the next release.

**Comment by binaryplease** [comment]
Has this been released yet? can't find the option in the docs

**Comment by sardemff7** [comment]
Yes, with the new theme format. See man `rofi-theme(5)`.
