### ISSUE TITLE
Custom keybindings fail to start rofi

### ISSUE THREAD

**Issue by fogine** [DaveDavenport/rofi#640]
## Version

Version: 1.3.1 - 1.3.1-700-g138ffc16 (master

## Configuration

https://gist.github.com/fogine/987e98b48ebf0df76a1a8f5f10d5fdb7

## Launch Command

```bash
rofi -show window -kb-row-down "Control+j"
```

Also fails with .Xresources option: `rofi.kb-row-down:Control+j,Down,Control+n`
This behavior applies for all user defined bindings.

## What behaviour you see

![rofi-2017-07-24-2030-00000](https://user-images.githubusercontent.com/7884288/28538848-f969d806-70af-11e7-913b-ec512e10c701.png)

Rofi fails to start with an error: "There is already a binding matching Control+j".. (hand written, not copy pasted).

## What behaviour you expect to see

Rofi launched with keybindings mapped.

**Comment by DaveDavenport** [comment]
The behavior is correct. you cannot bind two action to one key-combo.

**Comment by carnager** [comment]
To find out, which setting you need to unset use `rofi -dump-xresources | grep Control+j | awk '{ print $2 }'`
Then simply set it to nothing.

Example:
```
rofi -dump-xresources | grep Control+j | awk '{ print $2 }' | sed 's/.$//' 
rofi.kb-accept-entry

rofi -kb-accept-entry "" -kb-row-down "Control+j"
```

**Comment by fogine** [comment]
Thank you @carnager , I got confused as in previous versions of rofi I didn't need to unset the bindings. I guess some new default bindings were added since then. My bad.

**Comment by DaveDavenport** [comment]
In previous versions it indeed did not throw an error. It would bind the key twice, and the first one in the list would trigger.  So depending where your binding was in the list you would trigger one or the other.
This non-deterministic behaviour is even worse 🙁 .

**Comment by hxss** [comment]
@DaveDavenport Why command line options hasn't higher priority than configuration files?  I want to use rofi as interface of my script, but I can't be sure that my keybindings not already used in user config.

**Comment by DaveDavenport** [comment]
@hxss please follow the guidelines and open a new issue. Do not hijack issues.
