### ISSUE TITLE
ASAN is not disabled 

### ISSUE THREAD

**Issue by smarek** [DaveDavenport/rofi#642]
## Version
Version: 1.3.1-712-git-c4530f97-dirty (master)

## Steps to reproduce

Run rofi with any arguments (except for `-v`)

## What behaviour you see

.xsession-errors contains 

```
=================================================================
==8020==ERROR: LeakSanitizer: detected memory leaks
...
detected leaks
...
SUMMARY: AddressSanitizer: 170302 byte(s) leaked in 909 allocation(s).
```

## What behaviour you expect to see

No LeakSanitizer output after rofi command ends (no matter if it's CLI or GUI based)

Build was configured with `./configure --prefix=/usr/local --disable-asan` and configure summary did state that ASAN is disabled

From **`rofi -help`**
```
Detected modi:
        * +window
        * windowcd
        * +run
        * +ssh
        * drun
        * combi
        * keys

Compile time options:
	* window  enabled
	* drun    enabled
	* timings disabled
	* gcov    disabled
	* asan    disabled
```

**Comment by DaveDavenport** [comment]
hmm that autotools worked different then I thought.
Possible fix on next branch.

**Comment by smarek** [comment]
Well, you're goddamn genius. I can confirm that branch *next* compiles correctly without ASAN support and everything else seems to be working just right.

Thank you a lot for your great work and this great project!

**Comment by DaveDavenport** [comment]
this was more in the category of me being an idiot.. the autotools manual even warns for this mistake 😄

**Comment by smarek** [comment]
shhh, don't tell anyone :laughing: 

still awesome work on rofi, you deserve praise for that :trophy:
