### ISSUE TITLE
Update manpage for v1.4.0 release

### ISSUE THREAD

**Issue by DaveDavenport** [DaveDavenport/rofi#644]
On request of @fdmarcin .

For the upcoming v1.4.0 release it would be nice if the manpage (rofi and rofi-themes ) could be checked for grammar, clearness etc.
This Issue is to list what steps need to be taken.

Files: [rofi.1](https://github.com/DaveDavenport/rofi/blob/master/doc/rofi.1.markdown) [rofi-themes.5](https://github.com/DaveDavenport/rofi/blob/master/doc/rofi-theme.5.markdown).

**Comment by fdmarcin** [comment]
Thanks!
You've linked rofi.1.markdown twice. Did you mean rofi.1 and rofi-theme.5 instead?

**Comment by DaveDavenport** [comment]
fixed. c/p error.
