### ISSUE TITLE
Build fails when gnome-icon-theme-extras are installed

### ISSUE THREAD

**Issue by roosta** [DaveDavenport/rofi#653]
## Version

Rofi Version: 1.3.1 - 1.3.1-730-gb9ae0783 (master)
OS:  Arch Linux x86_64, Kernel Release: 4.12.4-1-ARCH
gnome-icon-theme-extras version: 3.12.0-3
adwaita-icon-theme version: 3.24.0-1

## Steps to reproduce
Try to build rofi with gnome-icon-theme-extras installed.
This issue started a while back, just now got around to figuring out what caused it. It happened after an update but those logs are long gone unfortunately.

## What behaviour you see
When installing rofi-git from Arch Linux AUR, if I had gnome-icon-theme-extras installed caused one of the build tests to fail:
```
ERROR:../subprojects/libnkutils/tests/xdg-theme.c:490:_nk_uuid_tests_func: assertion failed (file == data->result): ("/usr/share/icons/Adwaita/48x48/actions/zoom-in-symbolic.symbolic.png" == "/usr/share/icons/gnome/48x48/actions/zoom-in.png")
```
Full error log [here](https://gist.github.com/roosta/28c2293ad298b2b010f23e59b7550094)

Also tried manually building and running tests. They failed at the same spot.

## What behaviour you expect to see

Successful build and install

**Comment by sardemff7** [comment]
Does the file `/usr/share/icons/Adwaita/48x48/actions/zoom-in-symbolic.symbolic.png` exists? The test suite should check for it and skip the test if not. So I’d assume the file is there (otherwise we’ve found our bug) but something else is wrong.
Please also paste the output of `strace -e stat build/nk-xdg-theme.test 2>&1|grep /usr/share/icons/Adwaita/48x48/actions/zoom-in-symbolic.symbolic.png` (replace `build/nk-xdg-theme.test` with the test executable you built).

**Comment by roosta** [comment]
Ok, after I re-installed gnome-icon-theme-extras to reproduce this issue, and then I removed it but issue persisted so I checked its dependencies. Turns out it was gnome-icon-theme that was the culprit. Sorry about the mixup. gnome-icon-theme package version is: 3.12.0-4

**Comment by sardemff7** [comment]
Actually, nevermind my previous message. I am interested in the output of: `strace -e stat build/nk-xdg-theme.test -p /nkutils/xdg-theme/icon/gnome/symbolic/not-scalable`

**Comment by roosta** [comment]
The file ```/usr/share/icons/Adwaita/48x48/actions/zoom-in-symbolic.symbolic.png``` exists.
[here is the output of strace](https://gist.github.com/roosta/af11d54ff86ab56d855d50494d42f004)

**Comment by sardemff7** [comment]
This test should not check the Adwaita theme…
Is `$XDG_SESSION_DESKTOP` or `$DESKTOP_SESSION` set? To some value starting by "GNOME"? And is `gsettings get org.gnome.desktop.interface icon-theme` returning `'Adwaita'`?
If either answer is “no”, we have a big bug here. If all answers are “yes”, please test the `next` branch, I pushed a fix.

**Comment by roosta** [comment]
* `$XDG_SESSION_DESKTOP` is not set
* `$DESKTOP_SESSION` is set to `gnome`
* `gsettings get org.gnome.desktop.interface icon-theme` returns 'Adwaita'

Tried the `next` branch and it worked. Thanks :)
