### ISSUE TITLE
-mesg argument not displaying message

### ISSUE THREAD

**Issue by SpecialBlend** [DaveDavenport/rofi#654]
## Version

Output of `rofi -v`

Version: 0.15.11

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

[gist](https://gist.github.com/SpecialBlend/7ca115fd8c7aa99722b21c350bdce049)

## Launch Command

The commandline used to launch **rofi**

`rofi -show combi -mesg "test"`

## Steps to reproduce

run ``rofi -show combi -mesg "test"`` or ``rofi -mesg "test" -show combi``

## What behaviour you see

* - Normal rofi launcher without a message

## What behaviour you expect to see

* - Normal rofi launcher with message

**Comment by carnager** [comment]
`-mesg` is only available for `-dmenu` flag
