### ISSUE TITLE
Feature: Cancel with Super, Control, Alt

### ISSUE THREAD

**Issue by BonarBeavis** [DaveDavenport/rofi#655]
Hi,

I open rofi with 'Super' and would like to close it with 'Super'.
But closing rofi with a modifier key is only possible in combination with a letter.

An example for this behavior would be gnome dash.

Cheers

Gordian

**Comment by sardemff7** [comment]
Use the keysym name, like `Super_L`. Otherwise it cannot tell which key you want.
