### ISSUE TITLE
commandline to focus or start application

### ISSUE THREAD

**Issue by biocyberman** [DaveDavenport/rofi#658]
I come to ask rofi because it can seem to handle checking running application and jump to that application with window title. This is not possible to do from `i3wm` AFAIK.

## Version

Version: 1.3.1

## Configuration

Compile time options:
	* window  enabled
	* drun    enabled
	* timings disabled
	* gcov    disabled
	* asan    disabled

## Launch Command

not applicable

## Steps to reproduce

not applicable

## What behaviour you see

not applicable

## What behaviour you expect to see

* - Want to set in `i3` config a line like this: 

`bindsym $mod + a exec rofi mate-terminal -t MyTerm1 `
`bindsym $mod + b exec rofi mate-terminal -t MyTerm2 `

That would allow me to start a mate-terminal window with title "MyTerm1" if it is not running, and just focus to that window if it is running already. It should still allow me to start another terminal session with different name (MyTerm2) in the same way.

**Comment by DaveDavenport** [comment]
Don't think you need anything in rofi for this:
```bash
(i3-msg "[title=Testing] focus" 2>&1 | grep -q  false) && termite -t Testing &
```

This focus the window Testing, if i3-msg command returns false, start terminal.

**Comment by biocyberman** [comment]
`(i3-msg "[title=Testing] focus" 2>&1 | grep -q  false) && termite -t Testing &`
This works perfectly. I didn't know about this use of i3-msg. Thanks for showing me this.
