### ISSUE TITLE
Often rofi disappears after typing few words

### ISSUE THREAD

**Issue by rjdp** [DaveDavenport/rofi#660]
## Version

Version: 1.3.1-732-git-c5607bfb (master)

## Configuration

 [gist](https://gist.github.com/rjdp/bbc5e7012b748a82bf6604c9e919fea2)

## Launch Command

rofi -show run

## Steps to reproduce

* I have mpv  installed on my system
* when I open rofi and type 'mpv' rofi disappears even if I dont press enter

## What behaviour you see

* Rofi disappears

## What behaviour you expect to see

* Rofi Should not disappear

**Comment by DaveDavenport** [comment]
You have `-auto-select` enabled, if mpv is the only remaining match it will be automatically launched. 

Try turning it off:
```
-[no-]auto-select                       Enable auto select mode
True (File)
```

**Comment by rjdp** [comment]
Thanks
