### ISSUE TITLE
Rofi does not handle Ctrl-A correctly

### ISSUE THREAD

**Issue by ideaman924** [DaveDavenport/rofi#661]
## Version
Version: 1.3.1
Output of `rofi -v`

## Configuration
https://gist.github.com/ideaman924/55e5f8aca8058c8edd70d683908330a1
Output of `rofi -help` (in a [gist](https://gist.github.com/))

## Launch Command
rofi -show run -lines 3 -eh 2 -width 100 -padding 800 -font "NanumGothicCoding 18"
The commandline used to launch **rofi**

## Steps to reproduce

* Step 1 Launch rofi, type some text
* Step 2 Press Ctrl-A

## What behaviour you see

* - Rofi makes the cursor go to the start.

## What behaviour you expect to see

* - Highlight the text so I could delete it with the backspace or something.

**Comment by carnager** [comment]
and where in rofi manpage have you found that a) there is an option to select text?
How can this be wrong behavior if said feature never existed?

To delete the whole line from input field use ctrl+u like you do in any shell.

**Comment by ideaman924** [comment]
I stand corrected. Thank you for showing me the solution.

This issue can be closed.

2017. 8. 27. 오후 3:35에 "Rasmus Steinke" <notifications@github.com>님이 작성:
