### ISSUE TITLE
Tweaking the search functionality

### ISSUE THREAD

**Issue by victor-lund** [DaveDavenport/rofi#663]
I want to change how the search- and matching logic works. It's probably easiest if i explain what i want to achieve with a blunt example:

If i start typing "tor" when searching, i get suggestions in the following order:

phps**tor**m
**tor**-browser
etc...

I imagine this is because i launch phpstorm more often than tor-browser. However, i want the search / matching algorithm to "assume" that i dont search for a program by entering a string that's in the "middle" of the program's name. If i wanted to launch phpstorm, i would have typed "php". 

(in other words, when typing "tor", i want tor-browser to appear before phpstorm).

Is it possible to tweak the config in order to achieve this?

Many thanks

**Comment by carnager** [comment]
disable the history?

**Comment by victor-lund** [comment]
I could, but then i'd get suggestions that are irrelevant (programs that i never ever launch from rofi). So what i want is for the search algorithm to not look for matches in the "middle" of words but still take history into account. Does that make any sence?

**Comment by DaveDavenport** [comment]
Having no idea what version you run.... (why didn't you fill in the template? it is there for a reason). 

If you run git, i would suggest to use the fuzzy matching with the `fzf` sorting, this will sort matches at the word edges (so start) higher then when matched later.

**Comment by victor-lund** [comment]
Thanks for your suggestion Dave, I could not get it to work however. I now followed the template:


**Version**

Version: 1.3.1

**Configuration**

https://gist.github.com/victor-lund/2ae5398a5b5f7bb84489bdf20eb90d6c

**Launch Command**

rofi -show run -sort fzf -matching fuzzy

**Steps to reproduce**
Mod+d
type "tor"

phpstorm suggested before tor-browser

**What behaviour you expect to see**
tor-browser suggested befor phpstorm

**Comment by DaveDavenport** [comment]
You need `git` (see previous remark).
What is the `-sort fzf` option? if you use fuzzy search (in git) it will use this by default.

**Comment by victor-lund** [comment]
I must have misunderstood you in your last post. I replaced rofi in favor of rofi-git (Version: 1.3.1 - 1.3.1-740-gd7c432fe (master)) and just ran the command

rofi -show run -matching fuzzy

but phpstorm is still suggested before tor-browser when typing "tor".

**Comment by DaveDavenport** [comment]
did you enable sort?

```
rofi -show run -matching fuzzy  -sort
```

**Comment by victor-lund** [comment]
That seem to at least partially do the trick! However, does adding "-sort" disable all the history? Because  now i get suggestion of other programs that i never launch from rofi (torify, tor-resolve, tor-gencert etc)

**Comment by DaveDavenport** [comment]
no, but they won't be on top anymore, but 'sorted' into the list.

**Comment by victor-lund** [comment]
Ah I see - is there a way to move the matching results to the top of the suggestion list?

**Comment by DaveDavenport** [comment]
No, it either sorts the whole list or not.. It cannot sort 'parts' of the list.

**Comment by victor-lund** [comment]
Okok, well thanks for the help - much appreciated!
