### ISSUE TITLE
Regression between 1.3 and 1.4 theming.

### ISSUE THREAD

**Issue by bendem** [DaveDavenport/rofi#664]
## Version

```
Version: 1.3.0 (tags/1.3.0)
Version: 1.3.1-750-git-73827ce (next)
```

## Configuration

https://gist.github.com/bendem/ae38740885a3704042573ebbb6552f65

## Launch Command

```
rofi -show drun
```

## Steps to reproduce

N/a

## What behaviour you see

The input box looks like this
![rofi-2017-09-04-2225-00000](https://user-images.githubusercontent.com/2681677/30037974-701abcaa-91c0-11e7-91af-df1290bed3f3.png)

## What behaviour you expect to see
It used to look like that
![rofi-2017-09-04-2225](https://user-images.githubusercontent.com/2681677/30037979-79d92a92-91c0-11e7-90c3-ec3fdd56b7e8.png)

**Comment by DaveDavenport** [comment]
fixed in git.
