### ISSUE TITLE
Easy way to specify exclusions

### ISSUE THREAD

**Issue by majutsushi** [DaveDavenport/rofi#665]
It would be really useful if rofi had a way to specify not just what it _should_ match, but also what it _shouldn't_ match, i.e. a way to tell rofi that a specific string should not appear in a match. For example, when typing `foo bar !baz` it would match all strings that match `foo` and `bar`, but not `baz`. This syntax is what https://github.com/junegunn/fzf uses, but of course it could be done differently.

One particular use-case would be piping in the output of a `locate` call to rofi with the dmenu mode, and then excluding directories like `.git` or output dirs.

**Comment by DaveDavenport** [comment]
Added a branch issue665 that implements this. Please test.
The negate character is '-' as ! was already used in combi mode, and wanted to avoid collision.

**Comment by majutsushi** [comment]
Seems to be working well for me! There's only one small, unrelated thing I noticed while testing: the "loading" indicator on the right that's used when reading in more results from stdin appears on the first result line instead of on the query line, potentially obscuring part of the first result.

**Comment by balta2ar** [comment]
@majutsushi @DaveDavenport I can't get it working...

```
$ rofi -V
Version: 1.4.2
$ echo 'new line\nold line' | rofi -filter 'old' -dump -dmenu 
old line
$ echo 'new line\nold line' | rofi -filter '-new' -dump -dmenu
```
The second invocation prints nothing but I expect it to print "old line". I tried it with all `-matching` engines, still no luck. Is it broken or am I using it wrong?

Also, I couldn't find any mentions of this exclusion syntax in the manual. It could be nice to have it there.

**Comment by DaveDavenport** [comment]
Behavior seems to be correct, you are matching one line or not match it..   adding a `-e` to echo seems to reproduce the behavior you expect.

**Comment by balta2ar** [comment]
That's weird... I've built rofi from master branch and it indeed worked as expected. But on version 1.4.2 (which is latest in community repo, ArchLinux) it gives an empty output, even though related merge happened before the release.

Well, looking forward to the next release...

**Comment by DaveDavenport** [comment]
The above line will never work, as it is seen by rofi as one line, not two (atleast on bash).

**Comment by LaszloGombos** [comment]
Perhaps echo -e 'new line\nold line' ... instead of echo 'new line\nold line'
Anyways, works for me on 1.5 as expected
