### ISSUE TITLE
Take script modes from `-modi` for combi mode

### ISSUE THREAD

**Issue by somini** [DaveDavenport/rofi#668]
This is a feature request.

I have script modes defines in `.config/rofi/config` like
```
rofi.modi: combi,ssh,remmina:rofi-remmina
```

If I run `rofi -show combi -combi-modi ssh,remmina`, I expected combi to get the "remmina" definition from the modi settings.

My current workaround is repeating the definition on the command line: `rofi -show combi -combi-modi ssh,remmina:rofi-remmina`.

## Version

Output of `rofi -v`

Version: 1.3.1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

**Comment by DaveDavenport** [comment]
fixed in git in the next branch.
