### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by alexozer** [DaveDavenport/rofi#670]
## Version

Version: 1.3.1

## Configuration

https://gist.github.com/5c8761e70c2675b17606bc94747e223b

Also:

```
! ------------------------------------------------------------------------------
! ROFI Dracula Color theme
! User: milouse
! ------------------------------------------------------------------------------
! "Color scheme for normal row" Set from: File
rofi.color-normal:                   argb:00282a36, #f8f8f2, argb:00373844, #44475a, #e2e2dc
! "Color scheme for urgent row" Set from: File
rofi.color-urgent:                   argb:00282a36, #ff79c6, argb:00373844, #ff79c6, #282a36
! "Color scheme for active row" Set from: File
rofi.color-active:                   argb:00282a36, #50fa7b, argb:00373844, #50fa7b, #282a36
! "Color scheme window" Set from: File
! rofi.color-window:                   argb:ee282a36, #282a36, #f4f99d
rofi.color-window:                   argb:ee282a36, #282a36, #bd93f9
! "Separator style (none, dash, solid)" Set from: File
rofi.separator-style:                solid

rofi.matching: fuzzy
rofi.font: Ubuntu Mono derivative Powerline 16
```

## Launch Command

rofi -show drun

## Steps to reproduce

* Run rofi with these args and this config

## What behaviour you see

* rofi takes ~0.5 seconds to start. I sometimes type half my entry before the window shows up.

## What behaviour you expect to see

* rofi appears faster, faster than common thresholds of human-perceivable latency. Rofi used to be server, right? I wonder if that sort of functionality would decrease latency.

**Comment by DaveDavenport** [comment]
Please make a [timing trace](https://github.com/DaveDavenport/rofi/wiki/Debugging%20Rofi#timing-traces).

**Comment by alexozer** [comment]
@DaveDavenport Thanks for the reply.

Here's my timing trace after launching rofi from my window manager `make install`ed from git:

https://gist.github.com/5c43129e43da14f6fcbab418fea80e8f

So I'm using bspwm and launching from sxhkd. I also use compton.

Maybe unrelated, but I notice the version of rofi from the Arch repos only launches once I release my keybinding configured in sxhkd, but in the git version this doesn't appear to be so.

**Comment by alexozer** [comment]
@DaveDavenport Thanks for the additional issue references. I agree this could largely be disk i/o.

I'm coming from whiskermenu, a plugin for Xfce panel which also supports searching and launching desktop files with fuzzy matching. The menu seemed to have startlingly low latency (after triggering by keypress), but I'm really not sure if that's mostly due to the fact it was always in memory (I assume since it's triggered over dbus) or by some good caching scheme (I've heard the rofi server likely didn't do much to help performance). It also seems to update its collection of desktop files immediately after I install a new program that drops a new one, so I don't think it just polls for new ones.

**Comment by DaveDavenport** [comment]
Rofi seems to start in 120ms where the slowest part is getting the font metrics (55ms).

You can try to see how long the 'loading' of rofi takes by starting it on a terminal with time
time rofi -show run

then compare the total time from time with time in rofi-timings report.

rofi git indeed does not longer wait with starting until it can grab the keyboard, but immediately starts and tries to grab keyboard in background.

**Comment by DaveDavenport** [comment]
Can you do the experiment of comparing 'time' output with log. (to see if it is loading of the libs)

**Comment by alexozer** [comment]
Sorry for the delay! Here's `rofi -show drun` (I've been testing with drun this whole time):

```
rofi -show drun  0.14s user 0.02s system 26% cpu 0.594 total
```

That seems to correlate with the final time in the time trace before stopping:

```
0.131835 (0.000010): ../source/view.c:rofi_view_repaint:237 flush
```

**Comment by DaveDavenport** [comment]
hmm that looks pretty good.  
I wonder where the 'slow' feeling comes from then.

**Comment by DaveDavenport** [comment]
Any update on this one? Still want to know why it feels slow (as it seems to start in ~0.13 sec.)

**Comment by alexozer** [comment]
Hm I guess it's probably not really slower than on other systems, I'm probably just sensitive to it. It's not *slow* per se (if it was some IDE opening or something I wouldn't call it slow) but I guess I mentally expect the window to show up with a similar latency to typing characters on a screen (which avoids a mental pause I have to do to wait for it to pop up). It feels like 200-300 ms to me, I don't know.

**Comment by DaveDavenport** [comment]
Yeah, something that keeps running and therefor has fonts cached will be faster. (Fonts loading seems to be the general "slowness" in rofi.

I personally don't like things to be 'constantly' running, but could be re-added. (If somebody is willing to write a nice clean patch and maintain it).

**Comment by DaveDavenport** [comment]
Closing for now.

Thanks for the report.

**Comment by dansteen** [comment]
I know its closed, but I have found that adding additional modi also results in significant slowness on start.  It's not a big deal really - just make sure to only include the mode you are going to use for each particular call and things go much faster.
