### ISSUE TITLE
synaptic package manager not opening through dmenu or terminal, using debian 9

### ISSUE THREAD

**Issue by nadeem09wani** [DaveDavenport/rofi#674]
## Version

Output of `rofi -v` Version: 1.3.1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

## Launch Command

when dmenu of rofi is run then synaptic-pkexec is entered.

## Steps to reproduce

* Step 1  from terminal sudo synaptic-pkexec

## What behaviour you see

* -
No protocol specified
Unable to init server: Could not connect: Connection refused

(synaptic:7318): Gtk-WARNING **: cannot open display: :0

## What behaviour you expect to see

* -

**Comment by nadeem09wani** [comment]
nor from terminal

**Comment by DaveDavenport** [comment]
I have no idea what you are trying to reporte?
A bug in rofi?
A bug in dmenu?
A bug in synaptic?

If it does not launch from terminal, it does not sound like a rofi issue.

**Comment by nadeem09wani** [comment]
when i open synaptic mnager from dmenu its not opening, nor through terminal

**Comment by nadeem09wani** [comment]
i am using i3wm window managr

**Comment by DaveDavenport** [comment]
Sorry this seems very confused:
* dmenu is a dynamic menu. It cannot launch anything.
There are some wrapper scripts, like dmenu_launch and dmenu-run.
* Rofi is not dmenu
* If it does not launch when entering the command on a terminal emulator, fix that first!

**Comment by nadeem09wani** [comment]
from drun

**Comment by DaveDavenport** [comment]
Please be more clear. I don't understand, many things are mixed up and you are not very clear and precise in indicating what you are trying to do.

**Comment by nadeem09wani** [comment]
i am opening synaptic package manager from drun, its not opening .. nor am i able t

**Comment by squigglezworth** [comment]
If you've attempted to run it from a terminal and it's not running, it is not rofi's/dmenu's problem. Seek help from your distribution's support channels.

**Comment by nadeem09wani** [comment]
will look into that
