### ISSUE TITLE
create selction modi for rofi

### ISSUE THREAD

**Issue by zeltak** [DaveDavenport/rofi#68]
Hi as discussed in IRC :
would be cool to have different actions with different modifier keys, that is enter would be action 1 Shift-enter action 2 etc 
thx

Z

**Comment by DaveDavenport** [comment]
@carnager with the current highlighting I could change the dmenu mode a little bit to actually allow you to select/unselect and only on the final ' enter'  output all selected rows?

**Comment by carnager** [comment]
sounds great. 
When we have the possibility to unselect lines, rofi should discard the currently focused line, if its not selected.

**Comment by DaveDavenport** [comment]
This is now done!

**Comment by carnager** [comment]
:+1:

**Comment by jaksco** [comment]
what's the use case for this? how does it work? I saw this in the man page but it doesn't seem to do anything

Is there a way to perform file operations on selected files?

**Comment by DaveDavenport** [comment]
> Is there a way to perform file operations on selected files?

@jaksco please do not add random questions to issues.


If I remember correctly, this allows you (in dmenu mode) to bind actions to various keybindings. 
See rofi-theme-selector for an example of this.
