### ISSUE TITLE
[dmenu] Allow interpreting of input for formatted lists.

### ISSUE THREAD

**Issue by carnager** [DaveDavenport/rofi#681]
Right now dmenu acts as a pure input/output system with no additional interpretation done to the input. And that's exactly what it should do.

I have an idea however to make this even more powerful.
My idea is to feed dmenu mode with pairs of input, where one part is the actual raw input and the other one some custom string.

This could either be done in a very primitive way (one long line with a delimiter to split raw from visualization) or some proper format like json or similar.

When the user selects one of the lines in rofi, both visual and raw input should be written to stdout. Either as a delimited list of strings or as part of rofis already implemented "format" feature.

**Comment by DaveDavenport** [comment]
Aren't this issue and #680 not basically the same request? they both result in a way to pass data through rofi, without being visible in rofi? (either by having 2 columns where 2nd one is always hidden, or selectable columns.)

What I also miss what should happen to the hidden data?  if it is a transparent pass-through, there is little point in passinging it through rofi.

**Comment by DaveDavenport** [comment]
Closing, continue with this on #680.  (In agreement with @carnager )

**Comment by wstam88** [comment]
I use a <span lang="some_id_or_whatever">Hello world</span> to include hidden text.
Example: [rofi-fontawesome](https://github.com/wstam88/rofi-fontawesome)

**Comment by SicariusNoctis** [comment]
@wstam88 You can also just use a HTML comment:

```html
apple   <!-- id_1 -->
banana <!-- id_2 -->
```
