### ISSUE TITLE
Super keys stopped working in 1.4

### ISSUE THREAD

**Issue by infokiller** [DaveDavenport/rofi#684]
## Version

Version: 1.4.1

## Configuration

https://gist.github.com/infokiller/1852d7aabe5866fd2809786c615c61a6

## Launch Command

The commandline used to launch **rofi**

`rofi -show run`

## Steps to reproduce

* Start rofi with `rofi -show run`
* Use some keybinding with the super key, for example `Super+1`

## What behaviour you see

* The super key is ignored and rofi treats it as if only `1` was pressed

## What behaviour you expect to see

* Select row 1

## More details

I also tried with `Super_L` but that didn't change anything.
The output when I run `xev | grep key` from a terminal:
```
KeyPress event, serial 38, synthetic NO, window 0x5600001,
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
KeyRelease event, serial 38, synthetic NO, window 0x5600001,
    state 0x40, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
```

I tried running rofi with the `G_MESSAGES_DEBUG=all` variable in hope to see what's the keybinding the rofi intercepts, but I don't see it's being printed.

**Comment by DaveDavenport** [comment]
Can confirm.

**Comment by sardemff7** [comment]
Can you test `next` branch? 7f7da66c1a92a8f034fcb4c4533ce57bed45ce64 should fix this one.

**Comment by infokiller** [comment]
Works now, thanks!

**Comment by marcellmars** [comment]
i have ←, ↑, →, ↓, enter, backspace and delete binded to Mode_switch in combination with several other keys. it stopped working in rofi with the latest upgrade (1.4.2). that's how i got here. is it possible that this commit broke my keybindings in rofi?

**Comment by DaveDavenport** [comment]
that is not conclusive. anything between 1.3.1 and 1.4.2 could have broken it.
Can you attach your configuration so we can test? to me it is not clear how your bindings are setup.

**Comment by marcellmars** [comment]
i agree saying this commit broke it is not conclusive. sorry.

in my keyboard layout file in /usr/share/X11/xkb/symbols/my_keyboard i have things like:

`key <LCTL> {[ Mode_switch, Multi_Key]};
`

which would then let me do:

```
    key <AC06> { [ h, H], [Left,  any]};
    key <AC07> {[ u, U], [Down, any]};
    key <AC08> {[i, I], [Up, any]};
    key <AC09> {[o, O], [Right, any]};
    key <SPCE> {[space, space], [Return, any]};
    key <CAPS> {[Escape]};
    key <LWIN> {[Control_L]};
```

that config could be run by:

`setxkbmap my_keyboard -option
`

rofi runs as this:

`rofi -modi run,drun -show run -font "Terminus (TTF) 24"
`

the theme is configured (depending on the rofi version) in ~/.config/rofi/config as:

```
rofi.theme: /usr/share//rofi/themes//solarized_alternate.rasi
#include "/usr/share//rofi/themes//solarized_alternate.theme"
```

it worked fine before i upgraded to 1.4.2 and it works fine now after downgraded to 1.3.1
i didn't notice any particular application would have problems with my_keyboard.

my guess is that any keyboard which would have **Mode_switch** assigned to some key and then another one having **Down** set together with **Mode_switch** to do the **↓** should be minimal enough setup to test. these are the related lines from my keyboard configuration:

```
    key <LCTL> {[ Mode_switch, Multi_Key]};
    key <AC07> {[ u, U], [Down, any]};
```
