### ISSUE TITLE
Mode window is not found

### ISSUE THREAD

**Issue by NobbZ** [DaveDavenport/rofi#686]
## Version

Version: 1.4.1

## Configuration

```
Mode window is not found.
The following modi are known:
        * run
        * ssh
        * drun
        * combi
        * keys
```

## Launch Command

`rofi -show run` (or any other `-show`)

## Steps to reproduce

`rofi -show run`

## What behaviour you see

Output is the same as for `rofi -help`

## What behaviour you expect to see

Open up `rofi` with the requested menu.

**Comment by Gingerbreadz** [comment]
Looking at the code, it seems you now need to specify the modi you want enabled : e.g. `rofi -modi run -show run`

**Comment by sardemff7** [comment]
Yes, you need to, but `window` is in the default list. And here, rofi does not know about `window` at all.
The reason is that `window` is not built by default any more (with Autotools). Packages have to be updated, and users compiling their own need to pass `--enable-windowmode` to `./configure`.

**Comment by sardemff7** [comment]
Will still fix the default list to not have `window` when not built.

**Comment by DaveDavenport** [comment]
@sardemff7  Window mode is enabled by default.

**Comment by Gingerbreadz** [comment]
@DaveDavenport When rofi is built without windowmode ; perhaps window should not be in the default modi list.

**Comment by DaveDavenport** [comment]
@Gingerbreadz  @sardemff7  just fixed that.
