### ISSUE TITLE
Rofi input from terminal

### ISSUE THREAD

**Issue by Poetastrophe** [DaveDavenport/rofi#689]
I really like the combi modi functionality that allows me to either go to an app if it is open, or open it anew if it isn't: `rofi -combi-modi window,run -show combi -modi combi`
 But I was curious if this is also possible to do without opening a rofi window and instead doing it from the terminal and giving it input, like "emacs" and it goes to an emacs window if it is open.

**Comment by DaveDavenport** [comment]
No, I don't plan to support this.  I guess it could easily be done with a bash script.

If you want to go the rofi way, this is a dirty hack:
```
rofi -filter emacs -show combi & (sleep 0.3; xdotool key Return )
```
