### ISSUE TITLE
theme_parser_test i686 failure

### ISSUE THREAD

**Issue by Foxboron** [DaveDavenport/rofi#692]
Running the test suite on i686 fails, this works fine on x86_64. Using autoconf and make as meson 43.0 is currently broken.

```
==================================
   rofi 1.4.2: ./test-suite.log
==================================

# TOTAL: 15
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: theme_parser_test
=======================

Running suite(s): Theme
98%: Checks: 57, Failures: 1, Errors: 0
test/theme-parser-test.c:962:F:PropertiesColor:test_properties_color_names_alpha:0: Assertion 'p->value.color.alpha == (iter%101)/100.0' failed: p->value.color.alpha == 0.01, (iter%101)/100.0 == 0.01
FAIL theme_parser_test (exit status: 1)
```

**Comment by andreasbaumann** [comment]
In my opinion this should be fixed upstream, see https://github.com/libcheck/check/issues/133.

I would expect a library to write unit tests in to get the concept of floating point comparisions correctly.

**Comment by DaveDavenport** [comment]
I added a small delta tolerance. good enough for these tests.

**Comment by andreasbaumann** [comment]
Used patch on 1.4.2 release on i686, works fine, thanks.

**Comment by DaveDavenport** [comment]
thanks for testing.
