### ISSUE TITLE
Alpha colors are AGBR instead of ARGB

### ISSUE THREAD

**Issue by atomheartother** [DaveDavenport/rofi#693]
## Version
1.4.2

## Configuration
[Here!](https://gist.github.com/atomheartother/6bd809a2d03d605ea0629e2b208a35b3)

## Launch Command
(in i3 config file, bound to a key)
rofi -show run -display-run "🔍"

## Steps to reproduce
* - Update to 1.4.2
* - Launch rofi

## What behaviour you see
* - Colors on transparent colors are wrong because the parser interprets alpha colors as AAGGBBRR, and not AARRGGBB as the documentation states. Therefore #FFFF0000 is plain green, and #FF0000FF is plain red. I've only tested this on rofi.color-window

## What behaviour you expect to see
* - Colors should be interpreted correctly, #FFFF0000 should be plain red. That or this is a change I'm not aware of, and the doc should be updated.

## Additional info
Output of uname -a:
`Linux TomArch2 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux`

**Comment by warsawpact** [comment]
I believe the bug I'm having is also related to this issue.

Error I get is [this](https://u.teknik.io/Lb6GG.png).

When I comment out [lines 15-19 of my Xresources](https://gist.github.com/warsawpact/1293e1b5f39db6aa862abacd20e33f3e), everything works, albeit with different colors of course.

**Comment by AbrarSyed** [comment]
@warsawpact I got the same error. But the easy way to fix it is to add a 0 to the affected ARBG values. From what ive seen , it only throws that error when the ARGB color has 7 digits instead of the required 8.

`argb:0000000` -> `argb:00000000` will fix that error.

**Comment by DaveDavenport** [comment]
@warsawpact  unrelated, as @AbrarSyed said, your color specification is invalid.

Conversion to new theme is indeed going wrong, will fix. (odd that this was not caught as we used this code to convert all old themes.)

**Comment by DaveDavenport** [comment]
Fix will be in next release (will try to do soon).
