### ISSUE TITLE
Line margin no longer seems to apply above the first item in the list of matches

### ISSUE THREAD

**Issue by SeerUK** [DaveDavenport/rofi#694]
## Version

Version: 1.4.2

## Configuration

https://gist.github.com/SeerUK/a2b06ba58babc1b586db2b64638289f5

## Launch Command

Via i3:

```
$ rofi -modi drun -show drun
```

## Steps to reproduce

Use [my configuration](https://gist.github.com/SeerUK/c62f5cb6c5a260dbc479072c8a44c053), and notice that when you open rofi, the first item has no margin on the top on the list. In Rofi 1.3.1 (which seems to be the previous version that was in the Arch repositories) the margin was applied on top too.

## What behaviour you see

No margin / padding on top of the first item in the list of matches (doesn't matter which modi I'm using).

## What behaviour you expect to see

Equal spacing above and below all items in the list.

## Direct Comparison

https://imgur.com/a/vNSP2

## Other Comments

Honestly, I couldn't live without Rofi now, so thank you so much for making something this awesome. I also understand there has been a pretty huge set of changes between 1.3.* and 1.4.* so, maybe I'm just missing something here in the new theming support that lets me do this instead? If that's the case, then sorry about the issue!

**Comment by DaveDavenport** [comment]
*Technically* the current behavior is correct, old behavior is bug, as line-padding was *between* rows.

The new theme would allow you to tweak this any way you want. 

```
rofi -dump-theme  > mytheme.rasi
```

Then copy mytheme.rasi in `~/.config/rofi/` and set the theme option to `mytheme`.

There you can set any padding and spacing you want for each widget.

**Comment by SeerUK** [comment]
Aha, great stuff - I found the things I needed to tweak in the dumped theme, and now it looks like it did in 1.3.1 again. Thank you! :)

There were only a couple of things I changed. I updated the padding on `#message`, `#listview` and `#inputbar`; and I updated the `handle-color` property of the scroll bar to make it dark again.

**Comment by DaveDavenport** [comment]
Not a trivial fix  (given that separator is now a border). leaving it for now.
