### ISSUE TITLE
Arthur theme doesn't respect font option

### ISSUE THREAD

**Issue by mahmoudhossam** [DaveDavenport/rofi#695]
## Version

rofi 1.4.2

## Configuration

https://gist.github.com/mahmoudhossam/29f2c85a316fa26f2a7f2b0c02de3763

## Launch Command

`rofi -show drun`

## Steps to reproduce

* Use theme selector to select the `arthur by Qball` theme.
* Run rofi

## What behaviour you see

* The theme font doesn't change

## What behaviour you expect to see

* The theme should use the font specified in `.Xresources`

**Comment by carnager** [comment]
wrong. arthur theme uses it's own font you can change it in theme file.

**Comment by DaveDavenport** [comment]
The new format allows the font (per-widget) to be overridden. This is intended behavior.
