### ISSUE TITLE
Will not run due to spaces in config file between argb: and color values

### ISSUE THREAD

**Issue by jgjr** [DaveDavenport/rofi#697]
## Version

Version: 1.4.2

## Configuration

in .config/rofi/config

```
rofi.color-enabled: true
rofi.color-window: argb: CC000000, argb: CC000000, argb: CC000000
rofi.color-normal: argb: 00000000, #819396, argb: 00000000, #252525, #819396
rofi.color-active: #252525, #008ed4, #252525, #003642, #008ed4
rofi.color-urgent: #252525, #da4281, #252525, #003642, #da4281
```

(note the spaces between 'argb:' and the 'CC000000' values)

## Launch Command

> rofi -show run

## Steps to reproduce

> rofi -show run

## What behaviour you see

```
The following errors were detected when starting rofi:
Error while parsing theme: *{ background: argb: CC000000; }
Parser error: syntax error, unexpected invalid property value
Location: line 1 column 16 to line 1 column 28
```

## What behaviour you expect to see

Before updating to this version the config file worked without any errors, and now rofi will not run. 
It's not a huge issue, I obviously just had to remove a few spaces from my config file. I just thought it might be helpful for others who are having similar issues.

**Comment by DaveDavenport** [comment]
Yeah the new parser is more strict (it is a proper parser now).  I am not sure if this is worth the effort to fix. I am suprised it worked correctly in the old version. :smile: (apparently strtoull strips leading whitespace).
