### ISSUE TITLE
Can't set theme properties unless they're defined in the global section

### ISSUE THREAD

**Issue by RyanDwyer** [DaveDavenport/rofi#698]
## Version

Version: 1.4.2

## Configuration

Doubt this is relevant.

## Launch Command

`echo -e "foo\nbar" | rofi -dmenu -theme ~/test.rasi`

## Steps to reproduce

Create ~/test.rasi with this content:

    * {
        background: red;
        //background-color: blue;
    }
    
    #window {
        background-color: @background;
    }

## What behaviour you see

Rofi launches with a white background.

## What behaviour you expect to see

Rofi should launch with a red background.

If I uncomment the "background-color: blue;" line, the window section overrides it correctly and has a red background.

**Comment by DaveDavenport** [comment]
Interesting.  Will look into it.

**Comment by DaveDavenport** [comment]
Works fine for me.

**Comment by DaveDavenport** [comment]
I figured it out.. The behavior is correct. The default fallback background of widgets is white if you do not specify any theme.
So window is painted red, you just cannot see it.

To test, change blue to 'transparent'.
