### ISSUE TITLE
drun does not recognize custom $PATH programs

### ISSUE THREAD

**Issue by bootzin** [DaveDavenport/rofi#702]
I have a dir in my $HOME where I store any custom program that I have not installed with a package manager. From that dir, I symlinked all the program's executables to a ~/.bin folder which I've added to $PATH. Now, when I run rofi in run (`rofi -show run`) mode, I can run any of those custom programs, but when I run it in drun mode I can't. So, is there a way to make rofi recognize custom programs when run in drun (`rofi -show drun`) mode? And if not, could that be implemented?

P.s. Using rofi version 1.4.2-44-geff05976 with show_icons: true in .Xresources

**Comment by carnager** [comment]
drun mode reads your .desktop files, just like any startmenu for the big DEs do.
You would need to create .desktop files for every program that you want to run and place them in ~/.local/share/applications (which is the default directory according to XDG specifications)

**Comment by DaveDavenport** [comment]
You can also use combi mode to combine drun and run.

**Comment by bootzin** [comment]
Right, so, I'm having another problem now.. I wanted to use drun mostly because of the icons, so I set up a .desktop file in `~/.local/share/applications/firefox-nightly.desktop` like this:

    [Desktop Entry]
    Version=1.0
    Name=Nightly
    Comment=Browse the World Wide Web
    Icon=/home/konig/Software/firefox-nightly/browser/icons/mozicon128.png
    Exec=/home/konig/Software/firefox-nightly/firefox %u
    Terminal=false
    Type=Application
    Categories=Network;WebBrowser;
    Actions=Default;Mozilla;ProfileManager;

    [Desktop Action Default]
    Name=Default Profile
    Exec=/home/konig/Software/firefox-nightly/firefox --no-remote -P minefield-default

    [Desktop Action Mozilla]
    Name=Mozilla Profile
    Exec=/home/konig/Software/firefox-nightly/firefox --no-remote -P minefield-mozilla

    [Desktop Action ProfileManager]
    Name=Profile Manager
    Exec=/home/konig/Software/firefox-nightly/firefox --no-remote --profile-manager`

It was immediately recognized by rofi's drun menu, except it had no icon. It ran normally and opened without any problems, the only thing that wasn't being displayed was the icon, any changes to Name were also detected.

I tried changing the icon's location, using the full path to the icon, using only the icon's name, renaming the icon to the same name as the executable, moving the icon to ~/.icons, adding/removing the ".png" extension, adding/removing Desktop Actions,. I also tried using the 16, 32 and 48 px size icons, but none of them showed up. Any ideas on what's the reason behind this and how can I make it show the icon?

**Comment by DaveDavenport** [comment]
@bootzin  FOLLOW THE GUIDELINES!!!  New issue -> create a new ticket.. Do not hijack other issues.

Also CHECK previous issues: https://github.com/DaveDavenport/rofi/issues/701
