### ISSUE TITLE
[Feature Request] Configure location of history cache

### ISSUE THREAD

**Issue by brianclemens** [DaveDavenport/rofi#704]
It would be nice if the location of the rofi cache could be set in the configuration file or flag.  I currently use a tmpfs mounted as my ~/.cache directory and have to copy rofi's cache to and from disk at login / logout.

**Comment by DaveDavenport** [comment]
This is already possible, when launching rofi set the **XDG_CACHE_HOME** environment variable.

To move it to /tmp/:
```bash
 XDG_CACHE_HOME=/tmp/ rofi -show drun
```
