### ISSUE TITLE
Enhancement: Add back in the old -hmode option

### ISSUE THREAD

**Issue by slackhead** [DaveDavenport/rofi#705]
## Version
Version: 1.4.2-52-git-7973f586 (next)

It was useful to have a horizontal mode that didn't take up a lot of space. Can we have this back please?

**Comment by sardemff7** [comment]
Already possible, see the [dmenu theme](https://github.com/DaveDavenport/rofi/blob/master/themes/dmenu.rasi).

**Comment by DaveDavenport** [comment]
![image](https://camo.githubusercontent.com/eb08084784da7535efc177cf30baffb84cb9da1d/68747470733a2f2f35333238302e64652f726f66692f646d656e75312e706e67)
