### ISSUE TITLE
question: file browser switcher

### ISSUE THREAD

**Issue by carepack** [DaveDavenport/rofi#707]
hi hi,

is there a way to get all switchers activated? For example I'm ablte to show all switchers as tabs in rofi:
run,ssh,window,keys,combi ....
when I call rofi with the filemanager extension I'm only able to get combi and file as tabs in the rofi window. I would like to see the following tabs:
file,run,ssh,window,combi

Im failing all the time. Only file and combi are there. thx for helping me ount

**Comment by DaveDavenport** [comment]
All the modes listed in the modi setting will show up as tab, in that order.

**Comment by carepack** [comment]
Hi Dave,
thx for responding. Youre totally right, the modis are all there but can't get all modis + file tab. I only get combi + file tab in the rofi window.
I can post later my commandline. Or do you have a way to open all modi + file tab? What am I  missing?

**Comment by DaveDavenport** [comment]
I have *no* idea what you are doing, so I cannot tell you the solution. That is why there was a template when filing the issue that requested certain information.

Also please keep questions (not issues) to the reddit forum or IRC. (See [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)).
