### ISSUE TITLE
Rofi should not grab X11 input until its window is actually shown

### ISSUE THREAD

**Issue by michalrus** [DaveDavenport/rofi#709]
Having X11 input grabbed for a few seconds is especially awkward right after a cold boot, when `~/.xsession` is launching _a lot_ of programs and I want to launch another one w/ Rofi, while still using those already launched, waiting for Rofi to render itself.

---

## Version

`Version: 1.3.1`

## Configuration

https://pastebin.com/raw/MAkkDMG8

## Launch Command

`rofi -combi-modi window,drun,run -show combi -modi combi`

## Steps to reproduce

1. Generate very high load (to lengthen those normally incomprehensible times).
1. Launch Rofi.

## What behaviour you see

1. X11 input to other windows is blocked instantly after running the command, and **long before** Rofi’s window is even shown.

## What behaviour you expect to see

1. X11 input to other windows is blocked **only after** Rofi’s window is shown.

**Comment by DaveDavenport** [comment]
I do not agree, and there has been complaints in the past about rofi being to 'slow' to grab keyboard.
(#494 and there where others).

In normal usage you want to start rofi and directly start typing request, so the earlier it captures keystrokes the better.

TBH I don't see rofi launch that takes seconds as the target use-case. Normally it should launch in < 0.2seconds.

**Comment by michalrus** [comment]
Uh, right, that makes sense. You can’t possibly have both and I’d rather have current behavior w.r.t. #494. Thanks for clarifying!

**Comment by DaveDavenport** [comment]
np. thanks for understanding. (is refreshing)

**Comment by epitron** [comment]
Ok, I see the rationale behind capturing keyboard input immediately now.

Maybe rofi needs some way of closing or switching away from it, in case it hangs. It could only selectively capture keys -- eg: all unmodified keys and assigned shortcuts, but nothing more. That way, Alt-Tab and Alt-F4 would still function, and allow the user to escape.

**Comment by sardemff7** [comment]
We do not want to workaround X11 bugs and limitations in rofi by adding extra complexity that will make things much harder to maintain. A complete redesign (of X11) is a much better solution, and Wayland is exactly that.
