### ISSUE TITLE
Rofi Icon Theme with drun: add -drun-icon-theme to manpage.

### ISSUE THREAD

**Issue by Drakota** [DaveDavenport/rofi#712]
## Version
Version: 1.4.2

## Steps to reproduce

* Step 1 Enable Icons
* Step 2 Wrong Icon Theme

## What behaviour you see
The default icons are shown

## What behaviour you expect to see
The icons I have defined in LXAppearance

**Comment by DaveDavenport** [comment]
You can try setting:  `drun-icon-theme`  config option on rofi.

**Comment by sardemff7** [comment]
I would love to add LXAppearance support in libnkutils, could you tell me the values for these variables:
- `XDG_SESSION_DESKTOP`
- `XDG_CURRENT_DESKTOP`
- `DESKTOP_SESSION`
- any named with `LX` in it

And I need to know where it stores the setting.

**Comment by carnager** [comment]
lxappearance stores its settings in ~/.config/gtk-3.0/settings.ini

**Comment by sardemff7** [comment]
rofi is not a GTK+ application, so you cannot expect it to use GTK+ out of nowhere.
But, I prefer GTK+ over Qt, so I’m not completely against using the GTK+ setting as default fallback. However, I’ll let you deal with Qt users complaining about that.
Does that sound good to you? :-)

**Comment by carnager** [comment]
Qt users can always use the gtk+ theme :)

**Comment by Drakota** [comment]
Using `drun-icon-theme` worked, might want to update the man page, because there's no information about this.
