### ISSUE TITLE
rofi not starting parser error

### ISSUE THREAD

**Issue by Nabstar** [DaveDavenport/rofi#713]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

1.4.2

## Configuration

<a href="https://gist.github.com/Nabstar/ffe3b1dc8928ccfde37799ac2d16848c">here !</a>

## Launch Command

lunching from i3 config file via a key mapping
`bindsym $mod+d exec rofi -show run -lines 3 -eh 1 -width 70 -padding 500 -opacity "85" -font "Cantarell 18"`

## Steps to reproduce

* Update to 1.4.2
* Launch rofi

## What behaviour you see

* - `Error while parsing theme: *{ normal-background: argb:0383c4a;}
parser error: syntax error, unexpected invalid property value
location: line 1 column 23 to line 1 column 35`

* - `Error while parsing theme: *{ urgent-background: argb:02d303b;}
parser error: syntax error, unexpected invalid property value
location: line 1 column 23 to line 1 column 35`

## What behaviour you expect to see

* - I expect rofi to start.

**Comment by carnager** [comment]
please upload `/home/lukman/.config/rofi/config.rasi`

**Comment by DaveDavenport** [comment]
next version will have a better error message.

**Comment by Nabstar** [comment]
thank you :)
