### ISSUE TITLE
Rofi doesn't display icons with absolute paths

### ISSUE THREAD

**Issue by Drakota** [DaveDavenport/rofi#716]
## Version
Version: 1.4.2

## Configuration
https://gist.github.com/Drakota/dc4b8a139c89b2da80fe6307d1ecde52

## Launch Command
exec rofi -show drun

## Steps to reproduce

* Step 1: Create a custom .desktop application with an absolute icon path
* Step 2: Open Rofi and the icon doesn't show up

## What behaviour you see
* - The Icon is not displayed

## What behaviour you expect to see
* - The icon should be displayed

I created a custom .desktop applications, the actual entry runs the program fine, but the icon is not displayed (Postman).
![screenshot from 2017-11-04 14-18-02](https://user-images.githubusercontent.com/22665836/32408248-2de41f36-c16b-11e7-937b-8c850f87898c.png)

The icon works fine in other applications like Application Finder.
![screenshot from 2017-11-04 14-20-39](https://user-images.githubusercontent.com/22665836/32408260-6c35c47e-c16b-11e7-92bc-ba20f25bcb8a.png)
This may be a possible bug.
Thanks for helping.

**Comment by DaveDavenport** [comment]
#701

**Comment by patrick-motard** [comment]
@Drakota Did you ever figure this out?

**Comment by DaveDavenport** [comment]
@patrick-motard  it has been fixed, see linked bug..
