### ISSUE TITLE
[Feature request] rofi theme: height property for window widget

### ISSUE THREAD

**Issue by itspec-ru** [DaveDavenport/rofi#718]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Version: 1.4.2-80-git-74106921-dirty (git-r3/HEAD)

## Configuration

https://gist.github.com/itspec-ru/a1bac734e047c2a1319d0c078be77aee

Hello,
Sometimes I need to set the width and height of the window in percentages of the screen size. 
As a special case is the window width 25% and height 100% of the screen size.
In release 1.3.1 this case I used the option "-width 25 -lines 0", but starting with release 1.4 the option "-lines 0" has come to mean literally 0 lines. Maybe I missed something, but I have not found a way to get the desired result. In any case, the property "height" would be helpful.

**Comment by DaveDavenport** [comment]
Implemented in git, you can set height property on the window widget.
