### ISSUE TITLE
Is there a way to add custom bash scripts or aliases to rofi?

### ISSUE THREAD

**Issue by seongminnpark** [DaveDavenport/rofi#721]
## Version

    1.2.0

## Configuration

Default configuration

## Launch Command

    exec rofi -show run

Hello. I apologize if this was asked before. I could not find out how to add a bash alias to the rofi menu. If aliases are not supported, would there be a way to launch my .sh file from rofi? Thank you so much :)

**Comment by carnager** [comment]
add your .sh to PATH

**Comment by DaveDavenport** [comment]
aliases are mentioned in the [FAQ](https://github.com/DaveDavenport/rofi/wiki/Frequently-Asked-Questions) and long discussion in [issue](https://github.com/DaveDavenport/rofi/issues/97)
