### ISSUE TITLE
-drun-match-fields not work?

### ISSUE THREAD

**Issue by hxss** [DaveDavenport/rofi#723]
## Version

Version: 1.4.2

## Configuration

https://gist.github.com/hxss/454dbae7f1f66dd0578725d359caea1e

## Launch Command

rofi -show drun -drun-match-fields categories

## Steps to reproduce

* Run rofi with "-drun-match-fields categories" option.
* Write some text for matching.

## What behaviour you see

* rofi shows entries that matching not only by categories.

## What behaviour you expect to see

* Expected that rofi would show entries that matching only by categories
(According to [man](https://github.com/DaveDavenport/rofi/blob/next/doc/rofi.1.markdown#matching))

![screenshot from 2017-11-25 00-06-50](https://user-images.githubusercontent.com/17298149/33222950-28396c68-d17d-11e7-81f9-80651d6129df.png)

**Comment by DaveDavenport** [comment]
I don't think that option exists in 1.4.2.

**Comment by hxss** [comment]
@DaveDavenport I didnt find in what version you add this option. What I can do? I want to use matching by exec & name.

**Comment by DaveDavenport** [comment]
It will be in the next release.

**Comment by hxss** [comment]
ok. Thanks
