### ISSUE TITLE
Location property isn't documented

### ISSUE THREAD

**Issue by ollien** [DaveDavenport/rofi#726]
The `location` property is used in many themes, but isn't documented in `rofi-theme.5`. The closest that is documented is `anchor`. I would document it myself, but I don't want to give an inaccurate description.

**Comment by DaveDavenport** [comment]
Location (the old option) is documented in rofi manpage and on FAQ: https://github.com/DaveDavenport/rofi/wiki/WindowPosition.

Location in new theme format is the same option.

**Comment by hackedWifi** [comment]
So the rofi-theme.5 window should be changed to location. The POSITION does not work. It is documented as window position not LOCATION
