### ISSUE TITLE
-drun-icon-theme doesn't work with themes installed to ~/.icons

### ISSUE THREAD

**Issue by ollien** [DaveDavenport/rofi#727]
## Version
Version : 1.4.2
## Configuration

https://gist.github.com/ollien/de2ae31f89fe5e383fe83c080023164e

## Launch Command

`rofi -show drun`

## Steps to reproduce

* Step 1 Add an icon theme to `~/.icons`
* Step 2 Add it to rofi using `rofi.drun-icon-theme: theme-name`
* Step 3 Notice that the icon set doesn't change

## What behaviour you see

- The icon set in rofi is still the default

## What behaviour you expect to see

 - The icon set in rofi should reflect that of the icon set

**Comment by sardemff7** [comment]
I strongly believe `~/.icons` should be replaced by `~/.local/share/icons`, most implementations look in there too. :-)
A basic solution would be to have a symlink.

Anyway, added `~/.icons` lookup in `next` branch.
