### ISSUE TITLE
Exit rofi when input focus is taken away

### ISSUE THREAD

**Issue by Airblader** [DaveDavenport/rofi#728]
## Version

Version: 1.4.2

## Configuration

https://pastebin.com/2EhdYahn

## Launch Command

    rofi -show run

## Steps to reproduce

* Launch rofi
* Have i3lock activate while rofi is running

## What behaviour you see

* i3lock fails to lock the screen due to the active grabs

## What behaviour you expect to see

* rofi should exit
* i3lock should lock the screen

As a little background: we recently merged a change in i3lock (see https://github.com/i3/i3lock/pull/155) that mirrors the behavior of xscreensaver: if the keyboard / mouse cannot be grabbed, we manually set the input focus to some other window, hoping that the client holding the grab exits as a result of that; then we try again.

This happens, for example, also with context menus. However, rofi is also such a case as @saligrama reported here: https://github.com/i3/i3lock/issues/162

Thus I'd like to propose that rofi also reacts to losing input focus with exiting, based on the premise that rofi cannot do anything useful once it loses input focus (?)

**Comment by carnager** [comment]
Actually it does. Try clicking somewhere outside of rofi window.

**Comment by DaveDavenport** [comment]
No. It does not.

**Comment by Airblader** [comment]
@carnager  You can reproduce the fact that it doesn't exit by running

    sleep 3; xdotool windowfocus $(xwininfo -root | grep "Window id" | awk -F' ' '{print $4}')

and opening rofi. I'm assuming the exit-on-click is solved differently, not with loss of input focus.

**Comment by Airblader** [comment]
So since we all agree now, can we reopen it? :-)

**Comment by DaveDavenport** [comment]
Re-open what?  the issue never got closed.

**Comment by Airblader** [comment]
I guess I'm seeing things now. Sorry.

**Comment by DaveDavenport** [comment]
I don't see rofi receive a focus out event. But this should close it if it does (and not in normal window mode.)
```patch
diff --git a/include/view.h b/include/view.h
index 96e478a8..f10093b3 100644
--- a/include/view.h
+++ b/include/view.h
@@ -302,5 +302,6 @@ void rofi_view_get_current_monitor ( int *width, int *height );
  * Takes a screenshot.
  */
 void rofi_capture_screenshot ( void );
+void rofi_view_cancel_out_of_window ( RofiViewState *state );
 /**@}*/
 #endif
diff --git a/source/view.c b/source/view.c
index 5881a459..e25acf51 100644
--- a/source/view.c
+++ b/source/view.c
@@ -1438,13 +1438,19 @@ void rofi_view_temp_configure_notify ( RofiViewState *state, xcb_configure_notif
     }
 }
 
-void rofi_view_temp_click_to_exit ( RofiViewState *state, xcb_window_t target )
+void rofi_view_cancel_out_of_window ( RofiViewState *state )
 {
+    // Called on focus out or click outside window.
     if ( ( CacheState.flags & MENU_NORMAL_WINDOW ) == 0 ) {
-        if ( target != CacheState.main_window ) {
-            state->quit = TRUE;
-            state->retv = MENU_CANCEL;
-        }
+        state->quit = TRUE;
+        state->retv = MENU_CANCEL;
+    }
+}
+
+void rofi_view_temp_click_to_exit ( RofiViewState *state, xcb_window_t target )
+{
+    if ( target != CacheState.main_window ) {
+        rofi_view_cancel_out_of_window ( state );
     }
 }
 
diff --git a/source/xcb.c b/source/xcb.c
index cb136470..64b6bf74 100644
--- a/source/xcb.c
+++ b/source/xcb.c
@@ -758,6 +758,12 @@ static void main_loop_x11_event_handler_view ( xcb_generic_event_t *event )
         nk_bindings_seat_handle_key ( xcb->bindings_seat, NULL, xkre->detail, NK_BINDINGS_KEY_STATE_RELEASE );
         break;
     }
+    case XCB_FOCUS_OUT:
+    {
+        printf("Focus out\n");
+        rofi_view_cancel_out_of_window ( state );
+        break;
+    }
     default:
         break;
     }
```

**Comment by Airblader** [comment]
I'm assuming that rofi isn't selecting focus events (`XCB_EVENT_MASK_FOCUS_CHANGE`)

**Comment by Airblader** [comment]
Actually quickly scanning the code it looks like it does.

**Comment by DaveDavenport** [comment]
Yes, it receives it fine in 'normal window' mode.
Seems to be caused by the XCB_CW_OVERRIDE_REDIRECT attribute.

**Comment by Airblader** [comment]
It looks like rofi never even takes input focus (at least it doesn't call `xcb_set_input_focus`).

**Comment by Airblader** [comment]
Yeah, I guess rofi doesn't set input focus (in the unmanaged case) and just works with the grab alone. I don't think I'd recommend setting input focus »just because« (in fact, in other i3 tools we explicitly removed setting input focus if the grab suffices).

Oh well, the »set input focus to get the client to exit« method was a wooden hammer anyway (and one that I was against). I guess there's nothing rofi can do afterall.

**Comment by DaveDavenport** [comment]
anything else I can do?

**Comment by Airblader** [comment]
I don't think so. There's unfortunately also no event for when another client tries to grab the keyboard / pointer, so rofi just isn't aware of i3lock trying to lock the screen. X11 sucks. :-)

Sorry for the noise!

**Comment by DaveDavenport** [comment]
There is no way i3lock can see what application (rofi) has *grabbed* the keyboard and send it a signal?

**Comment by Airblader** [comment]
No, X11 doesn't allow checking which client is holding the grab either, unfortunately. What we'd need is a proper protocol, but that ship has sailed for X11 some ten, twenty years ago. :-)
