### ISSUE TITLE
Instructions to build rofi are no longer up to date

### ISSUE THREAD

**Issue by alarsyo** [DaveDavenport/rofi#729]
## Steps to reproduce

* Step 1: follow instructions in INSTALL.md
* Step 2: `./configure`

## What behaviour you see

* - the `configure` file doesn't exist anymore. `configure.ac` isn't executable

## What behaviour you expect to see

* - New instructions on how to build rofi ?

**Comment by sardemff7** [comment]
There are two sets of instructions in `INSTALL.md`, one for releases, and one for git checkouts. If there is no `configure`, you are most likely using a git checkout, and the wrong set of instructions.
Or do you mean the release tarballs are lacking the `configure` scripts and were really terrible at explaining that?
Please follow the guidelines when reporting a bug. Of course you cannot run `rofi -v` or `rofi -help` here, but I’m sure you can give us the version of the release tarball or a `git describe --tags`.

**Comment by alarsyo** [comment]
Oh, my bad :( didn't see there were two sets of instruction. Sorry!
