### ISSUE TITLE
-padding conflict with -e and -mesg

### ISSUE THREAD

**Issue by hxss** [DaveDavenport/rofi#730]
## Version

Version: 1.4.2

## Configuration

```
width: 1920;
padding: 800;
```
[gist](https://gist.github.com/hxss/454dbae7f1f66dd0578725d359caea1e)

## Launch Command

rofi -dmenu -p "run: " -sep " " -mesg "asd" <<< "sad zxc qwe"

## Steps to reproduce

I use padding option for force rofi to be opened in fullscreen mode AND for centering content. Rofi shows messages incorrect with my big value of padding. Rofi add padding after -mesg text depending on the number of characters and add window offset(50% of screen) when I use -e messages.

## What behaviour you see

* no -mesg:
![image](https://user-images.githubusercontent.com/17298149/33317409-d69444c6-d458-11e7-940d-6670985d17a3.png)
* with -mesg text:
![image](https://user-images.githubusercontent.com/17298149/33317442-f873c738-d458-11e7-8f32-1f4772d53053.png)
* more -mesg:
![image](https://user-images.githubusercontent.com/17298149/33317496-2adeb836-d459-11e7-9261-0005249f4974.png)
* if I press any key then extra-padding disappear
![image](https://user-images.githubusercontent.com/17298149/33317596-69212a34-d459-11e7-9668-3f61b45adb10.png)

* with -e:
![image](https://user-images.githubusercontent.com/17298149/33317631-86950afe-d459-11e7-8283-a914c14545f7.png)
* -e -padding 50
![image](https://user-images.githubusercontent.com/17298149/33317668-9cc204a8-d459-11e7-9051-4b3c613074b0.png)

Is there any other way to get centered content in fullscreen mode?

**Comment by DaveDavenport** [comment]
You are trying to do a padding that is bigger then the height of the monitor?

(800 top + 800 bottom = 1600 px.  > 1080.

This will go wrong I guess.

**Comment by DaveDavenport** [comment]
You can (in new theme format), set padding as a percentage..  (like 20%.)
Or add dummy widgets on top/bottom,left/right that expand.

**Comment by hxss** [comment]
> 800 top + 800 bottom = 1600 px
I think this is 800 + [content height] + 800
> bigger then the height of the monitor...This will go wrong I guess.
Anyway bug is exist. You cn test -mesg with -padding 50:
![image](https://user-images.githubusercontent.com/17298149/33324338-2f593e50-d471-11e7-8852-c36d87122b4e.png)
And after I press anykey:
![image](https://user-images.githubusercontent.com/17298149/33324380-45ea3b6a-d471-11e7-90e2-3fa42ac04f2f.png)

> dummy widgets on top/bottom,left/right
Where I can read about this widgets? Is this work in 1.4.2? Didnt find this on [man page](https://github.com/DaveDavenport/rofi/blob/next/doc/rofi.1.markdown).

**Comment by DaveDavenport** [comment]
In the [man page](https://github.com/DaveDavenport/rofi/blob/master/doc/rofi-theme.5.markdown)

**Comment by DaveDavenport** [comment]
Ill look at the re-sizing issue, because that should not happen.

It is an issue with it calculating desired height when it does not know its correct  width.

**Comment by hxss** [comment]
So, how I can change height of #top and #bottom widgets? Why they not expanded by y? Why #mainbox display only #inputbar and first line of #listview, while I specify lines: 5?
[gist](https://gist.github.com/hxss/454dbae7f1f66dd0578725d359caea1e)

**Comment by DaveDavenport** [comment]
expand is a boolean,  so must be either true of false.

**Comment by hxss** [comment]
>try to set width: 30em; on the entry element

like this?
![image](https://user-images.githubusercontent.com/17298149/33361531-5fc56d28-d4fa-11e7-88d8-d1dfe652a350.png)

And when I try to use expand - why #mainbox still eat all horizontal space?
![image](https://user-images.githubusercontent.com/17298149/33361738-3979f75a-d4fb-11e7-9b6f-d9343e29ed2c.png)

(look at sublime on background of the screenshot)

**Comment by DaveDavenport** [comment]
Width can now be set on box widgets.
