### ISSUE TITLE
cannot parse config file

### ISSUE THREAD

**Issue by dummys** [DaveDavenport/rofi#731]
## Version

`1.4.2`

## Configuration
```
For more information see: man rofi
                 Version: 1.4.2
              Bugreports: https://github.com/DaveDavenport/rofi/
                 Support: https://reddit.com/r/qtools/
                          #rofi @ freenode.net
      Configuration file: /home/dummys/.config/rofi/config.rasi
```
I'm trying to change the font. Using the .Xresources it's working but not with config.rasi

config.rasi:
```
rofi.font: Source Code Pro Light 40
```
## rofi error

error: parse error config
I tried removing the ":", rofi-font, etc

**Comment by DaveDavenport** [comment]
rename `config.rasi` to `config`

**Comment by dummys** [comment]
nop it's not this, with this configuration and .rasi it's working.

```
configuration {
font: "Source Code Pro Light 40";
}
```

**Comment by DaveDavenport** [comment]
Yes, that format to store configuration is not yet 'stable' and considered alpha.

**Comment by dummys** [comment]
Ok, so why the binary tell it to me ?

**Comment by DaveDavenport** [comment]
Because that is gonna be fixed in next release :smile: .  If no config present, it takes the last one tested.

**Comment by dummys** [comment]
So can I keep the alpha or it's better to switch ?

**Comment by DaveDavenport** [comment]
Should be fine.

**Comment by dummys** [comment]
ok thanks for help !

**Comment by sardemff7** [comment]
Please stop discussing unrelated matters in a bug report. Even the questions about the config file would have been better on IRC directly.
