### ISSUE TITLE
How to get rofi to parse .desktop files

### ISSUE THREAD

**Issue by jarun** [DaveDavenport/rofi#733]
It seems the XFCE4 whisker menu understands the program *Comment* section is `.desktop` files. For example, here's the `/usr/share/applications/eboard.desktop` file content (on Ubunru 16.04):

```
[Desktop Entry]                                                                                                                             
Version=1.0                                                                                                                                 
Type=Application                                                                                                                            
Name=eboard                                                                                                                                 
Comment=A graphical chessboard program                                                                                                                                                              
Comment[de]=Ein Schachprogramm                                                                                                              
TryExec=/usr/games/eboard                                                                                                                   
Exec=/usr/games/eboard                                                                                                                      
Categories=GTK;Game;BoardGame;                                                                                                              
Icon=eboard
```

If I type `chess` in the whisker menu it shows me eboard. I tried strings like `a`, `gra` and it still works. A contextual search like this helps to find programs you need once in a while but may not even be aware are installed in your system.

How can I achieve this in rofi?

**Comment by sardemff7** [comment]
rofi drun modi doesn’t use the `Comment` field, so it is a feature request.

**Comment by DaveDavenport** [comment]
I am unsure about this bug report.
1.) Requested information is ignored and not given.
2.) The title is confusing. Rofi parses desktop files just fine.
3.) Most programs uses GenericName instead of Comment for a generic description of the program. Rofi uses this field for matching.
This is what comment is used for according to spec:

Tooltip for the entry, for example "View sites on the   Internet". I am not sure adding this to the matching is desirable, as it will generate more falls hits (and people been complaining about this before in current setup).

**Comment by jarun** [comment]
@DaveDavenport I think you understood the problem. The spec says - "The value should not be redundant with the values of Name and GenericName." Which does indicate the field has something unique. In my example I cited eboard because typing `chess` when someone wants to play chess makes sense.

> and people been complaining about this before in current setup

Why not provide an option to ignore it by default and enable only if someone wants extended Comment section parsing?

**Comment by DaveDavenport** [comment]
>  In my example I cited eboard because typing chess when someone wants to play chess makes sense.

I still think that you should file a bug against the eboard, as Chess should be in the generic name.
We already discussed and will see about adding comments to the select-able options.

**Comment by jarun** [comment]
Thanks for considering the request.
