### ISSUE TITLE
Rofi performance problems after updating. (Also theme problem.)

### ISSUE THREAD

**Issue by AndreaHasani** [DaveDavenport/rofi#734]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Output of `rofi -v`
Version: 1.4.2-104-gae4ea622 (makepkg)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/AndreaHasani/4bf21b7246ab2d90f39c2b9f61d3833a

## Launch Command

The commandline used to launch **rofi**
rofi -show drun  -display-drun 'App: ' -window-format '{n}' -lines 10 -fake-transparency -theme ~/Documents/Scripts/Rofi-Scripts/Rofi.rasi

## Rofi.rasi theme
https://gist.github.com/AndreaHasani/f4c052571402818e08f0fe51de48cc10

## Steps to reproduce

* Step 1
Run Rofi command with my theme
* Step 2

## What behaviour you see

* - Rofi lags alot in in drun mode (after upgrading from a older version). It noticable when I press the keys.
* - drun rofi doesn't get the lines and column setting.

## What behaviour you expect to see

* - Smooth performance like the older version I was using. 
* - Lines should work in drun mode like they do on run mode.

First of all thanks for this amazing app.I use it everyday.
I just reinstalled my config on another pc and saw that my theme was not working there. Found out that rofi updated so I did go through with that and my settings broke and I was getting performance problems in rofi. I though it was strange since my laptop rofi was working fine. Just to test it I went through with the update there too and things broke there too. Had to spent 2-3h to fix the theme and still can't get the lines and columns working.

**Comment by DaveDavenport** [comment]
This seems to be a meta bug:
1. lines does not work?
2. columns does not work?
3. it lags.

1.  Not sure about this one.  With the current theme lines does not do anything as it is in fullscreen mode. This behavior is unchanged from 1.3.1.

2. Columns  Works for me. What is wrong here? Not clear to me?

3. I notice no lag.. Can you compile rofi with --enable-timings and get a trace.

**Comment by AndreaHasani** [comment]
I it possible to compile it with  --enable-timings from AUR? I've been looking in PKGBUILD but can't find the place where to put that (Sorry I don't have alot of experience with compilng apps).
Or do I need to do it after clonning the git?

**Comment by AndreaHasani** [comment]
### Old Theme
https://gist.github.com/anonymous/d9ecddb63b66efbeb9e4c4b67feec1c9

**Comment by DaveDavenport** [comment]
That old theme is in a never released format. That explain why it did not convert.
Sorry, but if you want to avoid these issues, please try to stick to release versions, we try to make the migration as good as possible between those versions.

I am unsure if you can specify that in aur, for install instructions check the INSTALL file.

**Comment by AndreaHasani** [comment]
It seems its compton problem.

**Comment by DaveDavenport** [comment]
The slowness? I think we had that before, some drivers + compton flags caused lagging.

**Comment by AndreaHasani** [comment]
Yeah the performance problem. The only thing different from my laptop and Desktop is the GPU driver. Going to try to install nouveu driver and see if nvidia driver is the problem.
Anyways we can close this issue since its not related to rofi.
Thanks

**Comment by DaveDavenport** [comment]
If you have more information, please report back. It might be useful for other users.
I think there are some more issues in the issue-tracker where people had performance issues with certain compton flags and rofi.
