### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by notaduck** [DaveDavenport/rofi#735]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Version: 1.4.2

## Configuration

https://gist.github.com/notaduck/8bc2a10cbe912d8ecb1384b034752b08
## Launch Command

rofi -modi run,drun,ssh -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font "Noto Sans 8"

## What behaviour you see

Normally while creating a ssh connection with a remote server where I have copied my ssh public key I don't have to insert a password, however while using rofi I'm **always** prompted for a password in order to obtain a connection through ssh.

**Comment by DaveDavenport** [comment]
Rofi just calls SSH.  SSH check environment for the pato the SSH_AUTH_SOCK.
Make sure that when you call rofi, that environment is set.
