### ISSUE TITLE
[Documentation missing] -kb-cancel not documented

### ISSUE THREAD

**Issue by Hritik14** [DaveDavenport/rofi#736]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version
Version: 1.4.2-39-
I came across the option -kb-cancel which binds a key to close rofi window but I couldn't find it anywhere on man page. Could you please add it ?

**Comment by DaveDavenport** [comment]
as mention in manpage:
```
To get a full list of key bindings on the commandline, see `rofi -dump-xresources | grep kb-`.
Key bindings can be modified using the configuration systems.                                 
To get a searchable list of key bindings, run `rofi -show keys`.
```

**Comment by DaveDavenport** [comment]
Changed manpage to point to rofi -h, as the output is better readable.
