### ISSUE TITLE
Instant Exit 1

### ISSUE THREAD

**Issue by postcert** [DaveDavenport/rofi#737]
## Version
1.4.2 - Current Arch version
Have removed and installed multiple times.

## Configuration

Default, application actually won't even run `rofi -help`

## Launch Command

`rofi`, `rofi -dmenu`, basically anything that is not `rofi -v` (only working command)

## Steps to reproduce

* Run `rofi`

## What behaviour you see

```(process:6232): Rofi-WARNING **: Failed to set locale.```
Leading to an instant (Exit 1)

## What behaviour you expect to see

* Normal rofi prompt/window

## GDB Output

```(gdb) run
Starting program: /home/postcert/rofi/build/rofi 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

(process:13750): Rofi-WARNING **: Failed to set locale.
[Inferior 1 (process 13750) exited with code 01]```

**Comment by sardemff7** [comment]
Can you paste the output of `locale` please? There is obviously something wrong with your locale settings, and rofi just doesn’t want that to happen. :-)

**Comment by postcert** [comment]
Was assuming being tagged as a `WARNING` it might not have been the issue (perl and such complained too.) You were right though! Did a little more poking around with the locales past setting the env variables locally and I've rebooted into a working setup.

Thanks!
