### ISSUE TITLE
names of dependencies for ubuntu?

### ISSUE THREAD

**Issue by Troyciv** [DaveDavenport/rofi#738]
I have unmet dependencies on ubuntu 16.04 when trying to ``./configure``

    configure: error: Package requirements (glib-2.0 >= 2.36 xcb xcb-aux xcb-xkb xkbcommon 
    xkbcommon-x11 xcb-ewmh xcb-icccm xcb-xrm xcb-randr xcb-xinerama) were not met:

    No package 'xkbcommon-x11' found
    No package 'xcb-xrm' found
    No package 'xcb-xinerama' found

Does anybody know the names of the packages for ubuntu?

 

## Version

1.4.2

**Comment by sardemff7** [comment]
This is not the place to ask that. Please go to the IRC channel of your distribution or whatever.

**Comment by DaveDavenport** [comment]
Also check out the [install](https://github.com/DaveDavenport/rofi/blob/next/INSTALL.md) file.
