### ISSUE TITLE
Some commands don't work

### ISSUE THREAD

**Issue by alem0lars** [DaveDavenport/rofi#740]
## Version

Version: 1.4.2

## Configuration

https://paste.pound-python.org/show/oKaxBiF0y6ncMRu59KDD

## Launch Command

```
rofi -show
```

## Steps to reproduce

* Start rofi
* Type `scrot -s`

## What behaviour you see

Scrot isn't started (or instantly killed)

## What behaviour you expect to see

Program should run, allowing user to select a region and take a screenshot

**Comment by DaveDavenport** [comment]
This works fine for me:

* rofi -show run
* scrot -s <Enter>
* select region -> enjoy screenshot

**Comment by alem0lars** [comment]
Using my configuration?

**Comment by alem0lars** [comment]
I think the problem is when using `rofi.matching = fuzzy` with parameters (**because different program will match**)

**Comment by DaveDavenport** [comment]
Aaah new information, For me with your config it had no match.
if there are still matches, it will execute the match unless you do ctrl-return (accept custom).

**Comment by alem0lars** [comment]
With `ctrl+<enter>` it works! Thanks

**Comment by DaveDavenport** [comment]
It should now also show up as match next time you run rofi -show run.

**Comment by alem0lars** [comment]
However when it shows again, when there is a exact match of `scrot -s` it still matches `spicy-screenshot` entry instead of `scrot -s`. I think that fuzzy matching should give more priority to exact matches

**Comment by DaveDavenport** [comment]
Please follow the guidelines and do not tag on other issues. Please make a new issue.
