### ISSUE TITLE
Rofi -show run spawned from awesome wm crashes Xorg process

### ISSUE THREAD

**Issue by sandric** [DaveDavenport/rofi#741]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

1.4.2

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/sandric/771c10f39438d3fa57cf4b284895f2c8))

## Launch Command

In awesome `rc.lua`
```lua
  awful.key({ "Mod4", "Shift" }, "q",
    function ()
      awful.util.spawn("rofi -show run")
  end),

```

## Steps to reproduce

Execute `awful.util.spawn("rofi -show run")` from within awesome process.  
See how Xorg crashes immidiately.

## What behaviour you see

* Crash of X server process

## What behaviour you expect to see

* No crash, visible rofi window.

The thing is that it appears only for `run` option, with `window` show option works just fine. Also appears only inside `awesome` session, if you run `rofi -show run` from console, everything works just fine also. So I'm not sure if thats smth related to rofi itself, or awesome.

**Comment by DaveDavenport** [comment]
Do you have more information? Does awesome WM crash and then X shutting down? or really X crashing.
If so what drivers?
Do you have a backtrace?

**Comment by sandric** [comment]
Please, newermind, I'm completely idiot, I bound command to already existing shortcut before to close awesome session. Sorry for that.
