### ISSUE TITLE
Possible to only list scratchpad on rofi window mode.

### ISSUE THREAD

**Issue by AndreaHasani** [DaveDavenport/rofi#748]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Output of `rofi -v`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

## Launch Command

The commandline used to launch **rofi**

## Steps to reproduce

* Step 1
rofi window -show window
* Step 2

## What behaviour you see

* - Rofi showing all opend window

## What behaviour you expect to see

* - I would like to have it filter only scratchpad windows or if possible to have a scratchpad tag so I know the windows are located in scratchpad.

**Comment by DaveDavenport** [comment]
This sounds very specific to the WM used (not mentioned) not sure this belongs in rofi or if it is information we can obtain via EWMH commands.
You can write a custom modi script/c-plugin that displays scratchpad windows that implements this.

**Comment by sardemff7** [comment]
Still, scratchpad is not an EWMH, AFAICT, so it has to be WM-specific to workx
