### ISSUE TITLE
vertical-align/horizontal-align of textbox set to 1 does not align text to bottom/right

### ISSUE THREAD

**Issue by Roliga** [DaveDavenport/rofi#752]
## Version

Version: 1.4.2-126-git-ad9c4c0f-dirty (makepkg)

## Configuration

[Output of rofi -help](https://gist.github.com/Roliga/7bcc853bf437f573182a5bc5f4b7d101)

config.rasi:
```
#window {
	children: [ textbox1, textbox2 ];
}

#textbox1 {
	str: "This aligns to the bottom";
	vertical-align: 0.999;
}

#textbox2 {
	str: "This does not align to the bottom";
	vertical-align: 1;
}
```

## Launch Command

`rofi -show run`

## What behaviour you see

A textbox with vertical-align or horizontal-align set to 1 keeps the text in the top/left corner as if no alignment was applied. Anything less than 1 (e.g. 0.999) works as expected though.

## What behaviour you expect to see

Vertical-align and horizontal-align set to 1 aligns text to the bottom/right.

**Comment by DaveDavenport** [comment]
I suspect that it parses it as integer not double.  `1.0`  will probably work.

Will fix.

**Comment by DaveDavenport** [comment]
sorry did not want to close.

**Comment by Roliga** [comment]
Makes sense, thanks!

**Comment by DaveDavenport** [comment]
Should be fixed, integer numbers are also accepted now for double properties.
