### ISSUE TITLE
Is there a guide anywhere as to how to use the rasi themes? 

### ISSUE THREAD

**Issue by KevOBrien** [DaveDavenport/rofi#753]
I am completely lost since rasi themes were introduced. Am I still supposed to have a config file with all the options of `rofi -dump-Xresources` set? And then I also set `rofi.theme: <path/to/theme.rasi>` and in this `.rasi` file I set all the theme colours, etc.? 

Is there anywhere explaining in detail the syntax of the rasi files, as well as what is supposed to go in them (and what still goes in the original config file that now points to the rasi theme)? I have looked at the [example .rasi themes](https://github.com/DaveDavenport/rofi-themes/tree/master/Official%20Themes), but am still lost with customising my own.

**Comment by carnager** [comment]
You were *never* supposed to have a dump of the config. In fact that can lead to breakage on updates (and did with 1.4.0). 

You set whatever defaults you changed in your config (or config.rasi - still alpha). Nothing changed here.

Yes, you can override config options in themes themselves, but obviously you don't always want to do this. It makes sense though for special themes which are e.g. dependent on small font sizes.
