### ISSUE TITLE
Sudden odd transparency and color behavior with rofi and compton

### ISSUE THREAD

**Issue by skinamarink** [DaveDavenport/rofi#757]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

1.4.2-131-git-5c5665ef (next)
(same result with release versions 1.4.2 and 1.4.0)

## Configuration

https://gist.github.com/skinamarink/c87744a5a803a3f8dda976d08dcd672c

## Launch Command

rofi -show run

## Steps to reproduce

* start compton with transparency enabled
* select any of the default rasi themes
* launch rofi

## What behaviour you see

* Rofi is launched with incorrect colors and transparency, and slowly becomes more unreadable with every keypress. This behavior spontaneously showed up about a week ago, without any changes to my install of either rofi or compton.

Gif: https://giphy.com/gifs/l0HU37AzS0QotFw88

In the above gif I am using the unmodified sidebar rasi theme, but the same thing happens with any of the other themes.

## What behaviour you expect to see

* Normal colors with normal transparency. Here is a gif of the same menu after killing compton: 

https://media.giphy.com/media/3o751V4AX6eltzNiuI/giphy.gif

(I realize this is most likely a compton problem, but I figured I would start here)

**Comment by DaveDavenport** [comment]
I have no idea.   if you take a screenshot internally in rofi , is it correct?  (Alt+s)

**Comment by skinamarink** [comment]
The resulting screenshot is a transparent background with very faint text. The screenshot is the same regardless of whether compton is running or not.

![sidebar theme](https://user-images.githubusercontent.com/17435367/35128263-9ba17930-fc83-11e7-9a94-f13e7bd782e4.png)

![solarized theme](https://user-images.githubusercontent.com/17435367/35128285-c01d1a1c-fc83-11e7-89f3-9afb3addce64.png)

**Comment by Coffei** [comment]
This looks like the issue I am experiencing and have reported to Compton - https://github.com/chjj/compton/issues/475. I only experience this on `GLX` backend, `xrender` seems to work fine. You can check it's the same problem and add your info on the compton issue, hopefully we'll get some answer there soon.

**Comment by skinamarink** [comment]
Yup, that looks exactly to be it. I'll follow it over on the compton tracker. Thanks!
