### ISSUE TITLE
rofi does not pickup default configuration (new format)

### ISSUE THREAD

**Issue by snwiem** [DaveDavenport/rofi#758]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Output of `rofi -v`
Version: 1.4.2-131-git-5c5665e (next)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/snwiem/b6ae526b8147281f56d55865c6fb5e2d

## Launch Command

The commandline used to launch **rofi**
```
rofi -show run -config ~/.config/rofi/config
```

## Steps to reproduce

* Create dump of configuration
```rofi -dump-config > ~/.config/rofi/config```

* Adjust configuration, eg uncomment and change width to 100
```
configuration {
/*	modi: "window,run,ssh";*/
	width: 100;
	lines: 15;
/*	columns: 1;*/
/*	font: "mono 12";*/
```

* Run rofi

Test with default config picked up as described in the man page
```
rofi -show run
```

Test with explicitly giving the configuration file
```
rofi -show run -config $HOME/.config/rofi/config
```

## What behaviour you see

* Configuration is not picked up. For example, the rofi window is still 50% (which is the default i guess)

## What behaviour you expect to see

* The window should be configured to be 100% of screenwidth.

**Comment by sardemff7** [comment]
`~/.config/rofi/config` is for Xresources-format config, the rasi one is `~/.config/rofi/config.rasi` (and is still considered alpha).
