### ISSUE TITLE
source/xcb.c:674:72: error: unknown type name ‘NkBindingsMouseButton’

### ISSUE THREAD

**Issue by thugcee** [DaveDavenport/rofi#759]
Strange thing: I can't compile 1.5.0 on Ubuntu 16.04. There is no such type as `NkBindingsMouseButton` and I can't google anything about it.

## Version

1.5.0

## Configuration

configured by `./configure --disable-check`

## Launch Command

`make`

## Steps to reproduce

```
git checkout 1.5.0
rm -fr build
./configure --disable-check
make
```
## What behaviour you see

```
source/xcb.c:674:72: error: unknown type name ‘NkBindingsMouseButton’
 static gboolean x11_button_to_nk_bindings_button ( guint32 x11_button, NkBindingsMouseButton *button )
                                                                        ^
source/xcb.c:704:72: error: unknown type name ‘NkBindingsScrollAxis’
 static gboolean x11_button_to_nk_bindings_scroll ( guint32 x11_button, NkBindingsScrollAxis *axis, gint32 *steps )
                                                                        ^
source/xcb.c: In function ‘main_loop_x11_event_handler_view’:
source/xcb.c:760:9: error: unknown type name ‘NkBindingsMouseButton’
         NkBindingsMouseButton button;
         ^
```

`./configure` doesn't report any problems. Any ideas what can be wrong with my setup?

**Comment by sardemff7** [comment]
You need to run `git submodule update` after a `git checkout`.

**Comment by DaveDavenport** [comment]
See https://github.com/DaveDavenport/rofi/blob/next/INSTALL.md#install-a-checkout-from-git
