### ISSUE TITLE
Can't delete recent items from ssh menu

### ISSUE THREAD

**Issue by theKlanc** [DaveDavenport/rofi#765]
## Version

Version: 1.5.0-dirty (tags/1.5.0)

## Configuration

https://gist.github.com/theKlanc/3d286c7991495f56f981f440627d3994

## Launch Command

rofi -show ssh

## Steps to reproduce

* Run "rofi -show ssh"
* Attempt to delete an entry by using shift+Del

## What behaviour you see

All entries appear to be deleted, but when reopening rofi they appear again

## What behaviour you expect to see

Highlighted entry disappears, and doesn't reappear when reopening rofi

**Comment by DaveDavenport** [comment]
For me I can delete history items, however the list does not correctly update after deleting.
Will look at it.

**Comment by DaveDavenport** [comment]
Fixed that the view did not get reloaded correctly.  Deleting works correctly here. Not sure what is wrong.

**Comment by theKlanc** [comment]
That must've been it. I tried deleting an entry and it didn't disappear(but I guess it did after I reopened rofi), and I tried another one that was already at .ssh/known_hosts, so that one did reappear when opening rofi again and thought it was a bug for both cases. Thanks!
