### ISSUE TITLE
Resetting "urgent" from script

### ISSUE THREAD

**Issue by oliversturm** [DaveDavenport/rofi#767]
## Version 

Output of `rofi -v`

Version: 1.5.0

I'm using a custom script to browse a menu hierarchy. I use "urgent" marks to indicate folders. So for instance, on first run my script produces this output (`\x` style hieroglyphs replaced with `X`):

```
prompt:XLaunch:

urgentX0,1

Browser
Tools
Skype
VMWare
```

This works, and the lines "Browser" and "Tools" are highlighted as urgent. Now let's say the user select "Tools", so my script is called with that parameter. Because there are no folder items in my Tools folder, I render something like this from the script:

```
prompt:XLaunch:

urgentX

Tool1
Tool2
Tool3
```

However, here's the snag: the "urgent" marks from the first run are not reset at this point, and I still end up with the first two lines marked as urgent.

Is there a hidden way of resetting the marks? I tried passing `-1`, just for fun, but it didn't work. Other than that I haven't been able to come up with an idea for a syntax that would say "please forget about anything you marked urgent before, and don't mark anything urgent this time round".

Thanks
Oli

**Comment by DaveDavenport** [comment]
Can you test if the last commit fixes it?

**Comment by oliversturm** [comment]
Yes, it does. Thanks for the quick fix!
