### ISSUE TITLE
There are no way to specify concrete monitor for rofi window in dmenu mode

### ISSUE THREAD

**Issue by shadowxnex** [DaveDavenport/rofi#771]
## Version
`Version: 1.4.2 (tags/1.4.2)`

## Configuration
https://gist.github.com/shadowxnex/f470f7a8b246e22ddea1158920e7923f

## Launch Command
`ps | rofi -dmenu -monitor 0 -normal-window -no-click-to-exit -lines 50 -width 1280 -multi-select -matching regex -i -sort -async-pre-read 1`

## Problem
I want output rofi window will be placed on the specific monitor, "-monitor 0" argument pair in my case how I think must do it. But that option has no effect: had I typed '-monitor 1' or '-monitor 2' - there are no difference, the window appears on that monitor where mouse is. The declaration in the '~/.Xresource' file as `rofi.monitor: 1` doesn't make effect too. This feature greatly works in modes other that -dmenu.

I suspect that such behaviour is a little bug. Correct me if I wrong!

**Comment by DaveDavenport** [comment]
I don't think it works with normal-window mode, as the window-manager takes control of placing the window.
It would work correctly withouth `-normal-window`.

**Comment by DaveDavenport** [comment]
![rofi-2018-03-28-0028-00000](https://user-images.githubusercontent.com/406245/37998472-01249e88-321f-11e8-80d0-cfd37cfcdcce.png)

**Comment by DaveDavenport** [comment]
Tested, worked correctly in normal operation mode.
