### ISSUE TITLE
Message option suggestions

### ISSUE THREAD

**Issue by p3lim** [DaveDavenport/rofi#772]
With `rofi -e` we can display a message, with optional pango markup, and that's about it.
I would like to see two options for it:

1. Allow it to be shown without grabbing the keyboard
2. Give it a timeout option, so it hides itself after X seconds (preferably support for milliseconds)

The message box is a perfect candidate for very customizable popup notifications, if only those two options were available (especially the first, the second _can_ be handled externally).

**Comment by sardemff7** [comment]
Except notifications is something else entirely, with dedicated software, more features (like queuing), integration into DEs and other softwares, CLI tools.

**Comment by p3lim** [comment]
I'm not expecting that of rofi, fully fledged desktop notifications (e.g. libnotify) is a whole different ballgame.
The request is merely to improve the message box, not to add functionality to replace software like dunst.

**Comment by sardemff7** [comment]
And yet, what you ask for is that. You can do exactly that with dunst or eventd already, no need for rofi here.

**Comment by p3lim** [comment]
Dunst takes orders from libnotify exclusively, which means I can't do something like uniquely style and position individual notifications, or bypass the queue system. The only options available are the ones libnotify exposes, which is the message and the urgency, and I'm looking for the ability to have an independant system for notifications (or rather popups since you're so adament on relating the word "notifications" with what libnotify provides).

What I'm ultimately after is the ability to show custom non-queued notifications (or popups) with custom styling and positioning as I wish. [Someone posted on /r/unixporn a while ago](https://www.reddit.com/r/unixporn/comments/4tklii/bspwm_workflowgif) an environment without a bar (e.g. i3bar/polybar), but rather using popups for showing system information, which is not possible with a notification system like the one dunst provides. The two additions I've requested would make that possible without having to resort to extremely modified bar solutions.

**Comment by carnager** [comment]
One word: dzen2

**Comment by sardemff7** [comment]
Well, dunst cannot, but eventd can, with a very high level of customisation. Both using libnotify or its own protocol, with any kind of crazy filtering you can think about.

**Comment by p3lim** [comment]
Had a quick look at the docs for eventd, it looks very promising for what I'm after, just need to test it.

**Comment by sardemff7** [comment]
Make sure to come on IRC if you have any question (and I bet you will) because the doc is still not perfectly clear on some use cases (and yours is one that could use work).

**Comment by p3lim** [comment]
Ended up using eventd, but these would still (IMO) be nice additions.
