### ISSUE TITLE
Use ctrl+enter key binding in combi 

### ISSUE THREAD

**Issue by AUTplayed** [DaveDavenport/rofi#774]
## Version

Version: 1.5.0-dirty (tags/1.5.0)

## Launch Command

`rofi -combi-modi window,drun,run -show combi -modi combi -theme-str '#prompt {enabled:false;}'`

## What behaviour you see

If I try to input a command and press ctrl+enter to use the entered text as a command it works great with 

`rofi -show run` 

but doesn't with a combi command as shown above.

## What behaviour you expect to see

I would love to be able to use the keybinding in the combi if the combi includes `run`.

**Comment by DaveDavenport** [comment]
There is a good reason that it does not work? How would rofi know what mode to use to launch it?

If you tell combi mode what mode to use f.e. like `!r gedit /etc/passwd` it should work.

**Comment by AUTplayed** [comment]
oh, I didn't know that was a thing. Sorry and thanks
