### ISSUE TITLE
Need more spaces in the list of window switcher

### ISSUE THREAD

**Issue by dikiaap** [DaveDavenport/rofi#775]
## Version

Version: 1.5.0-17-git-d9d37246 (next)

## Configuration
```
! Rofi config file
rofi.lines: 12
rofi.font: Fira Sans 11
rofi.show-icons: true
rofi.theme: ~/.config/rofi/oxide.rasi
```

and

```
! Rofi config file
rofi.lines: 12
rofi.font: Fira Code 11
rofi.show-icons: true
rofi.theme: ~/.config/rofi/oxide.rasi
```

## Launch Command

`rofi -show window`

## Steps to reproduce

* If I use a monospaced font, the spaces between apps and description looks pretty good.
* If I use a sans-serif font, the spaces between apps and description become random.

## What behaviour you see

![screenshot from 2018-02-25 23-46-26](https://user-images.githubusercontent.com/8542502/36644156-a744303e-1a88-11e8-90f0-f36d85ddd210.png)

## What behaviour you expect to see

* If I use sans-serif font, I hope to get a nice list like in monospaced font:

![screenshot from 2018-02-25 23-46-44](https://user-images.githubusercontent.com/8542502/36644161-bd788d6e-1a88-11e8-98bb-4e2312226aef.png)

**Comment by DaveDavenport** [comment]
Yes, that is what happens when using a non-monospaced font.
Very little we can do about it without adding support for columns and that is not on the list.

**Comment by facocalj** [comment]
Couldn't that be fixed by _len_ being the field width and not the maximum field width? 

Wouldn't it just be a matter of padding the field string with spaces or tabs to reach _len_ characters?
