### ISSUE TITLE
Anyway to disable antialiasing on bitmap fonts?

### ISSUE THREAD

**Issue by vypr** [DaveDavenport/rofi#776]
I can't find any documentation for theming, so I have no clue if there already is an option. I apologize if this is unnecessary, but I'd like to use dweep on rofi.

Thank you! :)

**Comment by sardemff7** [comment]
This sounds like a [fontconfig](https://wiki.archlinux.org/index.php/Font_configuration) job. Read the documentation, find the pieces which are of interest for you (hint: you need [font matching options](https://wiki.archlinux.org/index.php/Font_configuration#Disable_scaling_of_bitmap_fonts)) and adapt them to your needs.

FTR, rofi theming documentation is in `man rofi-theme`.
