### ISSUE TITLE
How to limit menu entries?

### ISSUE THREAD

**Issue by mese79** [DaveDavenport/rofi#778]
Hi
Is it possible to limit rofi run menu to show only a selection of desktop files?  or even to create menu entries by an running a script file?
I have a favorites folder with files(usually pdfs) i frequently read them. now i want rofi to show only these files titles in a menu and launch them. i'm thinking of a script(bash/python) to providing proper menu entries for rofi, but i'm not sure if rofi can be limited to show only the provided entries.

**Comment by DaveDavenport** [comment]
>  or even to create menu entries by an running a script file?
Yes, script modi or dmenu mode

I don't get the rest of the question..  If you write a script to show files in a folder, you can easily limit this in the script. 
What do files in a favorites folder have to do with desktop files?
