### ISSUE TITLE
Prompt not shown on smaller monitor

### ISSUE THREAD

**Issue by vbrandl** [DaveDavenport/rofi#779]
## Version

```
$ rofi -v
Version: 1.5.0
```

## Configuration

https://gist.github.com/e992d695730e4af8261e5542400bf6c4

## Launch Command

```
$ rofi -show run
```

## Steps to reproduce

* Start rofi on the smaller one of two monitors

## What behaviour you see

* Blurred overlay but no prompt (Entering a query and then hitting enter will still execute a program)

![screenshot0](https://i.imgur.com/jiKNjEn.png)

## What behaviour you expect to see

* Regular rofi prompt as on the larger monitor

![screenshot1](https://i.imgur.com/YsxjyOL.png)

**Comment by DaveDavenport** [comment]
can you post theme?

**Comment by vbrandl** [comment]
I had `rofi.padding` set to high (400). Setting it to 200 fixed the issue.

**Comment by DaveDavenport** [comment]
You can also set percentage if you want. 
Validation of 'sane' numbers is still on the todo.

**Comment by vbrandl** [comment]
Thanks for the tip. I'll try using a percentage when I'm at home.
