### ISSUE TITLE
Focusing a different program on other monitor changes tags on both monitors.

### ISSUE THREAD

**Issue by plitter** [DaveDavenport/rofi#780]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version
Version: 1.5.0-dirty (tags/1.5.0)

## Configuration

https://gist.github.com/plitter/156c8a62be60d23b1b493eff135c29b2

## Launch Command

 "rofi -show window"

## Steps to reproduce

1. Use DWM.
2. Create 1 program.
3. Move focus to other monitor and change tag.
4. rofi -show window
5. Type name of window that you created in step 2 and enter.

## What behaviour you see

Focus is moved to correct monitor, but both monitors are changed to the tag of the program. When having 3 monitors it changes the tag of the correct monitor and the monitor the program was called from and does nothing to the third.

## What behaviour you expect to see

Focus moved to correct monitor and tag and the monitor that you called it from stays at the tag it was called in.

**Comment by DaveDavenport** [comment]
Rofi uses EWMH to switch focus. Not sure how that relates to DWM.

**Comment by DaveDavenport** [comment]
I do not use DWM, if anybody can pin-point what goes wrong and how to work around it, please comment.

**Comment by plitter** [comment]
For the record I found the problem here. The patch pertag added some code that I needed to take away from DWM. So no issues with rofi here.
