### ISSUE TITLE
"make check" fails in 1.5.0

### ISSUE THREAD

**Issue by mbakke** [DaveDavenport/rofi#782]
## Version

1.5.0

## Configuration

N/A

## Launch Command

N/A

## Steps to reproduce

* Download the 1.5.0 release tarball.
* `./configure ; make ; make check`

## What behaviour you see

```
./test-driver: line 107:  2915 Segmentation fault      "$@" > $log_file 2>&1
FAIL: subprojects/libnkutils/tests/gtk-settings.test
```

## What behaviour you expect to see

`PASS: subprojects/libnkutils/tests/gtk-settings.test`

## Additional information

The problem is already solved in https://github.com/sardemff7/libnkutils/commit/3b5de1a4d59dba544dedcf9724ed547b30b826cb, but I could not find existing reports about it, and it took me a while to diagnose, so I'm creating this to aid anyone facing the same issue.

The solution is to simply create the gtk settings.ini files, or wait until the above commit makes its way into a Rofi release tarball.

**Comment by mbakke** [comment]
This is still an issue in 1.5.1.

**Comment by DaveDavenport** [comment]
Yep, sorry my bad.  I forgot to update module when rolling the release.. I have re-uploaded the tarballs, should be fixed now.
