### ISSUE TITLE
Single click suggestion from earlier doesn't work.

### ISSUE THREAD

**Issue by Kommynct** [DaveDavenport/rofi#787]
So, the suggestion [here](https://github.com/DaveDavenport/rofi/issues/441) doesn't work anymore, presumably due to updated configuration, and I can't find anything else in the documentation that would allow me to do this.
## Version
Version: 1.5.1-dirty (tags/1.5.1)

## Configuration
I don't have a config file, i just use command line options.

## Launch Command
rofi -show -run -theme ~/.config/rofi/themes/config.rasi -click-to-exit -separator-style none -font "Noto Sans 24" -disable-history -hide-scrollbar -width 155 -location 0 -threads 4 -me-select-entry '' -me-accept-entry 'Mouse1' -display-run ''
my config file is as follows:
```
* {
 background-color: #000;
 text-color: #bbb;
}
#element.selected.normal {
 background-color: #ff5050;
 text-color: #fff;
}
textbox-prompt-colon {
 str: "";
}
entry {
    text-color: #fff;
}

```
## Steps to reproduce

* Step 1 
set -me-select-entry '' -me-accept-entry 'Mouse1'  in the command line

## What behaviour you see

* -it'll tell you it doesn't know what mouse1 is. And it will fail to set binding, and not launch.

## What behaviour you expect to see

* -Being able to click on things and have it accept.

My configuration is odd because i'm using it as a menu, if you're wondering why my config is weird.

**Comment by sardemff7** [comment]
`config.rasi` **is** a config file, in rasi format, and considered alpha feature for now. You should rename it something else than `config`, just to be safe.

Concerning your issue, as of 101c4dcc267fd112fa24e154ac97035540e1e018, `Mouse1` was replaced with `MousePrimary`.

**Comment by Kommynct** [comment]
Sorry, I didn't look there, I promise I tried! 

and i'm only using rofi for menus, so, I wasn't too worried about the config.rasi thing.

Thanks though!
