### ISSUE TITLE
Decrease cursor width?

### ISSUE THREAD

**Issue by navdeepio** [DaveDavenport/rofi#788]
Is it possible?

**Comment by DaveDavenport** [comment]
No.

Please follow the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md) when creating an issue.

**Comment by navdeepio** [comment]
@DaveDavenport Please consider this issue as a feature request

**Comment by DaveDavenport** [comment]
@navdeepio Please read my comment from 31st of March.
