### ISSUE TITLE
Get Desktop apps (system dirs) taking a very long time

### ISSUE THREAD

**Issue by h1nk** [DaveDavenport/rofi#789]
## Version

Output of `rofi -v`: `Version: 1.5.1`

## Configuration

Output of [`rofi -help`](https://gist.github.com/h1nk/d4d4e9c012272762905ac8a414a37c8e#file-rofi-help-log).

## Launch Command

The commandline used to launch **rofi**: `rofi -combi-modi "window,drun,ssh" -show combi -modi combi -lines 25 -display-combi '> '`

## Steps to reproduce

* Step 1: Launch rofi with above launch command after the following sequence of commands to generate additional system debug information:
```lua
awful.spawn.with_shell("truncate -s 0 $HOME/*rofi-timing.log")
awful.spawn.with_shell("uname -aorpi >> $HOME/pre-rofi-timing.log")
awful.spawn.with_shell("free -m >> $HOME/pre-rofi-timing.log")
awful.spawn.with_shell("find /usr/share/applications/ -name '*.desktop' | wc -l >> $HOME/pre-rofi-timing.log")
awful.spawn.with_shell("sh -c \"TERM=vt100 top -b -n 1 >> ~/pre-rofi-timing.log\"")
awful.spawn.with_shell("rofi -combi-modi \"window,drun,ssh\" -show combi -modi combi -lines 25 -display-combi '> '")
```
My system has a modern i5, 8 giabytes of RAM and is sitting idle. The information piped into the [`pre-rofi-timing.log`](https://gist.github.com/h1nk/d4d4e9c012272762905ac8a414a37c8e#file-pre-rofi-timings-log) file should prove that the system is not overloaded with I/O.

## What behaviour you see

* - [A 10-30 second delay before launching](https://gist.github.com/h1nk/d4d4e9c012272762905ac8a414a37c8e#file-rofi-timings-log)

## What behaviour you expect to see

* - Instantaneous responsiveness of the rofi window frame spawning and appearing without much of a delay.

**Comment by DaveDavenport** [comment]
I am unsure how to tackle this one,   I am on a lot slower machine, more desktop files and it takes 20ms for me.

I use glib's build in parser, the overhead of rofi's code is very small.
I wonder what is slow (can you run a debug build through perf? )

```
 perf record -g --call-graph dwarf  rofi -show drun
```
then `perf report -g > log.txt`

**Comment by DaveDavenport** [comment]
For me if I look at the time spend in drun, the most time is spend in `g_key_file_get_locale_string`.

**Comment by h1nk** [comment]
```shell
$ # To emulate the lag I get when launching I'm first performing a test run directly after clearing the disk cache:
$ echo 3 | sudo tee /proc/sys/vm/drop_caches
3
$ perf record -g --call-graph dwarf rofi -combi-modi "window,drun,ssh" -show combi -modi combi -lines 25 -display-combi '> '
[ perf record: Woken up 37 times to write data ]
[nvidia] with build id 59c6a71bfcd9f7f05ba3ad70708ef150e2c1edd7 not found, continuing without symbols
[ perf record: Captured and wrote 9.338 MB perf.data (1160 samples) ]
$ # Run a subsequent test when the disk cache is fresh:
$ perf record -g --call-graph dwarf rofi -combi-modi "window,drun,ssh" -show combi -modi combi -lines 25 -display-combi '> '
[ perf record: Woken up 11 times to write data ]
[ perf record: Captured and wrote 3.225 MB perf.data (403 samples) ]
```
### Cached Cleared:
- [`rofi-timings.log`](https://gist.github.com/h1nk/b067f81148d612f32199648e58375f59#file-normal_clear_cache_rofi-timings-log)
- [`perf.log`](https://gist.github.com/h1nk/b067f81148d612f32199648e58375f59#file-normal_clear_cache_perf-log)
### Cache NOT cleared:
- [`rofi-timings.log`](https://gist.github.com/h1nk/b067f81148d612f32199648e58375f59#file-normal_no_clear_cache_rofi-timings-log)
- [`perf.log`](https://gist.github.com/h1nk/b067f81148d612f32199648e58375f59#file-normal_no_clear_cache_perf-log)

**Comment by DaveDavenport** [comment]
I am correct saying that it is only slow when cache is cleared?

**Comment by h1nk** [comment]
Yes, this is correct. I first thought it may be the health of my mechanical hard disk, but I am somewhat doubtful of this as most other programs I use on the system that are performing similar disk read access operations have little to no problems.

**Comment by DaveDavenport** [comment]
From what I can see from the perf logs (shamefully they do not include waiting time), it is actual disk-io causing the slowdown.

Both opening the fonts (1.2 seconds) and reading the desktop files.

I am not sure how to solve this one, as it is not slowness in rofi, but still the access of (many) small files.
I could have rofi write out a cache file, but that will bring a load of problems on it own (when to refresh the cache, how to handle invalid items, etc.).

**Comment by h1nk** [comment]
Well I suppose I'll have to get an SSD and see how it handles the many small files in terms of speed. Thank you for your help, I'll reopen this if I can get any better information.

**Comment by DaveDavenport** [comment]
A bigger change (might be nice for future, to not have to wait X time)  is to do all the loading async.
(I never did this before, because it often is less fast then quickly load everything, then show gui at once).

**Comment by eater** [comment]
How does [Kupfer](https://github.com/kupferlauncher/kupfer) handle this? It seems almost instantaneous compared to Rofi.

**Comment by DaveDavenport** [comment]
It loads it once at startup (probably slow-ish), and keeps running in the background.
This is something I prefer not to do.

**Comment by DaveDavenport** [comment]
Don't ask me, I did not write it.

**Comment by DaveDavenport** [comment]
I have some ideas of how to (possibly) speed it up. But alas no time to implement them at the moment.

**Comment by DaveDavenport** [comment]
As a test, I wrote a small plugin that implements drun using GLibs build in application info functions (not fully complete).
https://gitcrate.org/qtools/rofi-grun

For me this is slower then the current drun implementation, ymmv.
