### ISSUE TITLE
Passing commandline options in custom modes

### ISSUE THREAD

**Issue by InspectorMustache** [DaveDavenport/rofi#791]
Hi there,
from looking at test_script_mode.sh it appears, it's possible to pass options to rofi via the script's return output:
```
    echo -en "\x00prompt\x1ftesting\n"
    echo -en "\0urgent\x1f0,2\n"
    echo -en "\0active\x1f1\n"
    echo -en "\0markup-rows\x1ftrue\n"
    echo -en "\0message\x1fSpecial <b>bold</b>message\n"
```
Is this documented somewhere? The syntax seems to be `NULL option SEP arguments NEWLINE` but apparently only specific options are supported as `\0fullscreen\n` does nothing. So which options can actually be used?

Thanks!

**Comment by DaveDavenport** [comment]
[Release notes](https://github.com/DaveDavenport/rofi/releases/tag/1.5.0)
