### ISSUE TITLE
Jupyter notebook doesn't open when rofi is launched via i3 shortcut

### ISSUE THREAD

**Issue by ilsenatorov** [DaveDavenport/rofi#793]
## Version

Version: 1.5.1-4-git-aa03eb7f-dirty (makepkg)

## Configuration

[gist](https://gist.github.com/ilsenatorov/6ce091925c37c3aae0ae0c3ca5823dc3)

## Launch Command

The commandline used to launch **rofi**
Launched from i3 using `bindsym $mod+d exec --no-startup-id jupyter-notebook`

## What behaviour you see
* when rofi is called from command line using `rofi -show run` and `jupyter-notebook` is called, both server and browser open (as they should)
* when rofi is launched via i3 keybind, jupyter server is launched, however the browser doesn't open

**Comment by DaveDavenport** [comment]
Does jupyter-notebook need a terminal to work?

**Comment by DaveDavenport** [comment]
I checked.  You cannot launch jupyter-notebook without an underlying terminal.
You can launch it from rofi in a terminal by doing 'shift-enter'
