### ISSUE TITLE
Rofi closes when changing modi in sidebar mode

### ISSUE THREAD

**Issue by facocalj** [DaveDavenport/rofi#798]
## Version
1.5.1

## Configuration
Default in Solus

## Launch Command
rofi -show drun -sidebar-mode -no-fixed-num-lines

## Steps to reproduce
* - Launch rofi using sidebar mode and without a fixed number of lines
* - Clicking on a modi that has fewer lines than the previous, e.g., from drun, click on the ssh button

## What behaviour you see
* - Rofi quickly changes to the new modi and closes before I take any action
* - However, it works if perfectly if iterating between modi, e.g., using Ctrl+Tab

## What behaviour you expect to see
* - Rofi should change to the new modi and stay there, open and visible

**Comment by DaveDavenport** [comment]
Can you add the missing information? (I have *no* idea what solus default config is)

Does rofi crash? as I cannot reproduce this.

**Comment by DaveDavenport** [comment]
closing. re-open when information is added.
