### ISSUE TITLE
Caps Lock inhibits Esc keybindings

### ISSUE THREAD

**Issue by sehe** [DaveDavenport/rofi#799]
## Version

Version: 0.15.11

## Configuration

Output of `rofi -help` in this [gist](https://gist.github.com/sehe/44ff41c24ce42f823f5a00606f2e59a5)

## Launch Command

    rofi -show window

Configured in i3wm config:

    bindsym Mod1+Tab exec --no-startup-id rofi -show window

## Steps to reproduce

 * have Caps Lock on
 * summon window menu
 * try to dismiss (the only way I know possible: Pressing <kbd>Esc</kbd>)

## What behaviour you see

* window menu stays

## What behaviour you expect to see

* window menu closes

**Comment by sardemff7** [comment]
0.15.11 is ancient, the keyboard code was completely rewritten since, twice. Please update to the latest release.
