### ISSUE TITLE
writing to xclip causes rofi to freeze

### ISSUE THREAD

**Issue by benjumanji** [DaveDavenport/rofi#802]
## Version
Version: 1.5.1-dirty (tags/1.5.1)

## Configuration

https://gist.github.com/benjumanji/55e4f6fa28a2d0335b49c74c330cfc00

## Launch Command

`rofi -modi pw:$PWD/pw -show pw`

## Steps to reproduce

run the launch command and make a selection

## What behaviour you see

Rofi is unresponsive, keyboard and mouse grabbed, have to kill rofi from other tty

## What behaviour you expect to see

Rofi to exit, and for foo to in the clipboard.

**Comment by DaveDavenport** [comment]
If the script is not exiting? show should rofi know what todo? maybe there is some output coming in the future to display.

**Comment by benjumanji** [comment]
Ok, but in any other context `cat foo | xclip -sel clip` _does_ just exit. And if I get rid of the call to xclip, the above script works just fine, therefor I surmise that somehow it is the combination of the two. If you were investigating this, what would you try?

**Comment by benjumanji** [comment]
Ok, your comment has made me think a bit harder, and reading the xclip man pages has made me realise that I didn't _know_ xclip actually works process wise, and I can see that _xclip_ isn't exiting. Sorry for the spurious report. Thanks for your time!

**Comment by DaveDavenport** [comment]
no problem.
