### ISSUE TITLE
drun can't open Caja (file manager - MATE)

### ISSUE THREAD

**Issue by pqanc** [DaveDavenport/rofi#803]
## Version

rofi 1.3.1 / Debian 9.4 / Mate 1.16.2

## Configuration

[gist](https://gist.github.com/perqbn/7139bfb8d51ec96eb7e29adef6a2bad2/)

## Launch Command

`rofi -show drun`

## What behavior you see

* When i launch rofi with keyboard combination and type `caja` nothing happens.
* But when i lauch rofi (rofi -show drun) on terminal and type `caja` the app opens.

**Comment by DaveDavenport** [comment]
Works for me. Not sure how to debug this.

**Comment by DaveDavenport** [comment]
https://www.reddit.com/r/qtools/comments/76rn3p/rofi_wont_open_caja/

**Comment by mrm** [comment]
Old issue but in case anybody runs into this, edit `/usr/share/applications/caja-browser.desktop` and change `Exec=caja --no-desktop --browser %U` into `Exec=caja --no-desktop --browser .`.
