### ISSUE TITLE
Icons aren't showing if it's from /usr/share/pixmaps

### ISSUE THREAD

**Issue by Daenarii** [DaveDavenport/rofi#805]
## Version

Version: 1.5.1-dirty (tags/1.5.1)

## Configuration

https://gist.github.com/Daenarii/beb58bbfe28be09bf88810d88d43e8d7

## Launch Command

``rofi -show drun -lines 10 -show-icons -location 6``

## Steps to reproduce

* Create a `.desktop` file
* Add `Icon=appname.png` which has its icon available in /usr/share/pixmaps

## What behaviour you see

* The icon wouldn't appear
    - Other .desktop entries have icons
    - Anything else that has its icon in /usr/share/pixmaps are affected
    - Defining `Icon=/usr/share/pixmaps/appname.png` works, so it means the directory isn't just recognized by rofi as an icon path
    - PCManFM seems to detect the icon (on both `Icon=appname.png` and `Icon=/usr/share/pixmaps/appname.png`), so it's not a system-wide problem and therefore a rofi-specific bug

**Comment by sardemff7** [comment]
As per the [Desktop Entry specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) the `Icon=` key must be either a full path or an *icon name*, not a *file name*.
Just put `Icon=appname` and it’ll work.

**Comment by DaveDavenport** [comment]
I have done that in the past, and it became a mess of 'requested'  exceptions.
For now I prefer to follow the specifications as good as possible and avoid exceptions.
