### ISSUE TITLE
Bring back '-lines 0' behaviour.

### ISSUE THREAD

**Issue by afraidofmusic** [DaveDavenport/rofi#806]
- Version:
In Debian: 1.3.1 (No Configuration)
In Arch Linux:  1.5.1-dirty
[Arch Linux Configuration](https://gist.github.com/afraidofmusic/82428a3ea7ef0cb7acd0feba5639d323)

- Steps to reproduce:

run rofi with '-lines 0'

Expected behaviour:
![2018-05-15-070005_1366x768_scrot](https://user-images.githubusercontent.com/25895258/40036165-6ca39280-580e-11e8-8731-2a8be93ccbbe.png)
Current behaviour:
![2018-05-15-070059_1366x768_scrot](https://user-images.githubusercontent.com/25895258/40036166-6fd66e32-580e-11e8-95b2-2bc7eb605169.png)

**Comment by DaveDavenport** [comment]
The theming has completely changed, this is one of the things that did not convert 100% correctly.
Changing your theme, or passing the following command-line will get the same .

```
rofi -show run -theme-str 'window { height: 100%;}'
```
