### ISSUE TITLE
Allow user to turn off italicising of markup in drun browser. [Question]

### ISSUE THREAD

**Issue by The-Soulless** [DaveDavenport/rofi#812]
## Version

Version: 1.5.1

## Configuration

https://gist.github.com/The-Soulless/a24d1fbf184ef61b09050d2dee18b240

## Launch Command

bindsym $mod+d exec rofi -show combi
bindsym $mod+Shift+d exec rofi -show run

## Steps to reproduce

* Step 1 Set the font as terminus
* Step 2 Run rofi

## What behaviour you see

* - https://a.uguu.se/iRpinuWMHJ74.png

## What behaviour you expect to see

* - A way in the options to turn off italication

**Comment by DaveDavenport** [comment]
This is possible using the new theme format.

**Comment by The-Soulless** [comment]
Mind saying how?

**Comment by DaveDavenport** [comment]
By setting the highlight property on the element field:

```css
element {
highlight: bold underline;
}
```

to test:

rofi -theme-str 'element {  highlight: bold underline; }' -show drun

**Comment by The-Soulless** [comment]
That doesn't change the description in the parentheses
https://a.uguu.se/q0iZhB2WLDOq.png

**Comment by DaveDavenport** [comment]
That is currently not yet possible.  It will be added once we have the string formatting functionality from @sardemff7 .

**Comment by The-Soulless** [comment]
Is it possible to turn off markup completely? Or even just colour it the same as the background?

**Comment by DaveDavenport** [comment]
See previous comment.

**Comment by DaveDavenport** [comment]
added feature 'drun-display-format' should allow you to fix this.
