### ISSUE TITLE
bw and padding aren't scaled with respect to dpi

### ISSUE THREAD

**Issue by frebib** [DaveDavenport/rofi#815]
## Version

`1.5.1-dirty (tags/1.5.1)`

## Configuration

https://gist.github.com/frebib/dd799069cdb150e133d4177757f395fe/raw

## Launch Command

`rofi -show run -sidebar-mode -terminal i3-sensible-terminal -normal-window`

## What behaviour you see

Most things in rofi seem to scale appropriately with `rofi.dpi: 0` such as font etc. When using high DPI values such as >200 it is obvious that some elements are disproportionate to the rest of the window. This seems to happen for either inherited Xft dpi and a hard-coded value.

## What behaviour you expect to see

Every value scaled relative to the DPI value.

**Comment by DaveDavenport** [comment]
This depends on how the theme specified the width of the border and the margin.
If it is hardcoded in pixels it won't scale, if it is specified in `em` or `ch` it should scale with the font size (that scales with dpi).

**Comment by frebib** [comment]
That did the trick, thanks!

**Comment by DaveDavenport** [comment]
ncie to hear that worked.

**Comment by frebib** [comment]
Actually, scratch that, I was being deceived.. 

This is the result at dpis of 96 and 300:
![](https://i.imgur.com/GAvfuMh.png)

To reproduce: 

```
rofi -show run -no-config -normal-window -decorate -dpi 96 -pid $(mktemp) -font 'sans 14' -bw 6em -lines 6 -width 30 
rofi -show run -no-config -normal-window -decorate -dpi 300 -pid $(mktemp) -font 'sans 14' -bw 6em -lines 6 -width 30
```

**Comment by sardemff7** [comment]
It could be because you’re using the old config/theme style, which does not support these units. Or maybe it does and it is a bug, but anyway, please test with the new theme syntax, the old stuff will be removed and we won’t use time to fix it.

**Comment by DaveDavenport** [comment]
You can try:
```bash
rofi -show combi -no-config -theme-str '#window { border: 2ch; }'  -dpi 10
```

v.s.

```bash
rofi -show combi -no-config -theme-str '#window { border: 2ch; }'  -dpi 100
```

**Comment by frebib** [comment]
I wasn't aware that there was a new theme syntax. I've been using Rofi for years and have only ever changed the config when there were breaking changes!

How would I go about globally setting a default theme similar to the old(/existing) `.config/rofi/config` xresources-style configuration?

**Comment by DaveDavenport** [comment]
From the top of my head:

```
rofi -dump-theme
```

copy it in `~/.config/rofi/default.rasi`

Set in your config rofi.theme: default


there are many example themes now  shipped with rofi.

**Comment by frebib** [comment]
Just spent some time with the rasi theming and it's so much more flexible. I can confirm perfect scaling with the `em` and `ch` units so I'm going to mark this as solved!

**Comment by DaveDavenport** [comment]
Good to hear!.

The new theme format is very flexible, but also a bit more difficult to use.
