### ISSUE TITLE
Only one hostname in SSH known_hosts causing line to be ignored

### ISSUE THREAD

**Issue by kepi** [DaveDavenport/rofi#820]
According to [sshd documentation](http://manpages.ubuntu.com/manpages/bionic/en/man8/sshd.8.html#contenttoc7) in **hostname** part of **known_hosts** file is comma-separated list of hostnames. Rofi parse this well but doesn't work in case there is only one hostname like:

```
server.somedomain.com ssh-rsa .....
```

I "workarounded" it by putting coma at the end of hostname, but it should work even without it as SSH is working fine like that and all other tools too.

I guess that "the problem" is on [this line](https://github.com/DaveDavenport/rofi/blob/ac29c537dd15677e42b4c4bb76fc4678b18f35f7/source/dialogs/ssh.c#L151)

**Comment by kepi** [comment]
Hmm... I'm fighting with this for couple weeks but just now I found out that at least [TRAMP](https://www.gnu.org/software/tramp/) has same "problem".

I'm not sure if I understand documentation correctly, maybe I'm wrong in my original statement.

**Comment by DaveDavenport** [comment]
Improved the parser a bit. Please test.

**Comment by kepi** [comment]
Finnaly found time to test it, works like a charm - at least for my known host. Thanks!

btw. I had problem with unavailable check 0.11.0 on Debian, but it is working with 0.10.0 too. If 0.11 is not needed, maybe better to depend on 0.10 so it will be easier for maintainers to include. Anyway I'm totally unaware what it is doing :)

**Comment by DaveDavenport** [comment]
0.10 does not work.

Thanks for testing.
