### ISSUE TITLE
Packaging fails in PCLinuxOS

### ISSUE THREAD

**Issue by alebersol** [DaveDavenport/rofi#821]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Output of `rofi -v`

Trying to package version 1.5.1

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

## Launch Command

The commandline used to launch **rofi**

## Steps to reproduce

* Step 1
* Step 2

## What behaviour you see

* - Trying to package Rofi for PCLinuxOS, it aborts the compiling process with errors.
Make file does not find libnkutils, but that library is never mentioned as a build dependency.

## What behaviour you expect to see

* -
I would expect it to compile and create the package.

I'm attaching the building messages that it displays when I try to build the package and the spec file.
[rofi_building_errors.txt](https://github.com/DaveDavenport/rofi/files/2133333/rofi_building_errors.txt)
[pclos-rofi.spec.txt](https://github.com/DaveDavenport/rofi/files/2133337/pclos-rofi.spec.txt)

**Comment by DaveDavenport** [comment]
libnkutils is included in the release, or a submodule in the git repository.
(I cannot read the exact error message.)

**Comment by sardemff7** [comment]
rofi doesn’t use libtool, and it is confusing the whole thing. I don’t know what is the proper way to avoid libtoolize in PCLinuxOS build system.
I can see in [a Fedora spec](https://ignatenkobrain.fedorapeople.org/for-review/rofi.spec) that they use `autosetup` instead of `setup -q`, but it might not help here.
(Please do not have `Provides:       bundled(libgwater)` in your spec, these are static libs, not installed, and designed for direct embedding only.)

**Comment by alebersol** [comment]
Ok Gentlemen, I did change the spec, and added the line %define __libtoolize    /bin/true, disabling libtool.

Now, it did compile and the whole process went smooth.

Just in the %files section (after compiling, in the package assembly phase) I'm getting two errors:

Error while creating the RPM:
error: The file should begin with "/": MIT
error: The file should begin with "/": COPYING
And then, it doesn't create the package. But, I'm closer now than I was before. 

Just out of curiosity, does it create a Devel package too ?

I got a spec from Suse and another from Fedora, just to help me create the PCLOS spec, and, it does create a devel package with the Suse spec, but not with the Fedora one.

What do you tell me ?

Well, thanks again for your tips and directions, the work evolved.

Best regards,

**Comment by sardemff7** [comment]
It should have a `-devel` package, there is one in the spec I linked.

**Comment by alebersol** [comment]
Ok,

I changed the Copying file to the %doc line and it did build the two packages: The program package and the devel package, so, everything is fine.

Thanks for the help, much appreciated.

Best regards,

**Comment by alebersol** [comment]
Might close this one as Solved. Ok ?
