### ISSUE TITLE
Without fixed-num-lines rofi is not correctly centered

### ISSUE THREAD

**Issue by memeplex** [DaveDavenport/rofi#823]
Version: 1.5.1-dirty (tags/1.5.1)

Using fixed-num-lines=false rofi is no longer centered on the screen but positioned below the center, even if location = 0.

**Comment by DaveDavenport** [comment]
This is indeed correct. With fixed-num-lines it centers on the top of the window.

This was to avoid that the window would keep moving as you type and 'shrink' the list.

**Comment by memeplex** [comment]
I think, at least heuristically, placing the window a bit above the center
(say on fourth or third of max lines) could work better, because currently
rofi will be below the center for sure.

**Comment by DaveDavenport** [comment]
It used to do that in older versions, but with the new theme format, the list can be anywhere.
This heuristic won't work anymore.

**Comment by memeplex** [comment]
I was going to suggest about adding an optional percentage offset to the location option, but I see that's exactly what the theme configuration can do. I was happy with my old style color specification otherwise, but I guess I will have to move to a full fledged theme.

**Comment by carnager** [comment]
You can use `rofi -dump-theme > $HOME/.local/share/rofi/themes/my_theme.rasi` to store current theme in new format. This will also appear in **rofi-theme-selector**

**Comment by memeplex** [comment]
Well, I now see there is the -theme-str option, that could be enough, I'll give it a try.

Besides, there are a couple of options not documented in the man page: xoffset, yoffset (although there is an example using yoffset in the man). Are they still supported?

**Comment by DaveDavenport** [comment]
That is a bug in the manpage then. They are still supported.

**Comment by memeplex** [comment]
Great, then we can close this, I suppose. Do you want me to open another
issue for the man page?

**Comment by DaveDavenport** [comment]
I see 'x-offset'  and 'y-offset'  are in theme manual. closing.
