### ISSUE TITLE
[Feature Request] Support for `rofi -dmenu` in modi and combi

### ISSUE THREAD

**Issue by aksh1618** [DaveDavenport/rofi#824]
This is somewhat related to #356. It'd be really helpful if `rofi -dmenu` could be used as a modi and thus in combi. This would allow utilities that use `rofi -dmenu` but aren't simple scripts, such as [dmenu-extended](https://github.com/MarkHedleyJones/dmenu-extended), to be used easily within a single instance.

**Comment by DaveDavenport** [comment]
As indicated before this won't work.
The difference is that in dmenu mode, the script calls rofi. When used as modi rofi calls the script.

The script mode exists to make a mode from a script.
