### ISSUE TITLE
Rofi not keeping config

### ISSUE THREAD

**Issue by BitstyRoss** [DaveDavenport/rofi#826]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version
1.5.1

## Configuration

Configuration file is located here: /home/ywft/.config/rofi/config

    rofi.show-icons:            false
    rofi.modi:                  drun,run,window,ssh
    rofi.lines:                 7
    rofi.line-padding:          10
    rofi.matching:              fuzzy
    rofi.bw:                    0
    rofi.padding:               0
    rofi.separator-style:       none
    rofi.hide-scrollbar:        true
    rofi.line-margin:           0
    rofi.columns:               4
    rofi.font:                  sans-serif 10

    rofi.theme: /usr/share/rofi/themes/nord.rasi

## Launch Command

It loads the proper config if I use the right click menu in Openbox >  preferences > rofi theme selector or if it's loaded from the command line. If i load it using the super key it ignores my formatting for the most part, but does pick up the correct theme. I can change some things, like # of lines but it ignores option to leave out icons and adjust columns.

I have noting under .Xresources and no other config I can find, but it's pulling it from somewhere.

## Steps to reproduce

na

## What behaviour you see

Loads with my theme with incorrect formatting if loaded using super key in Manjaro Openbox

## What behaviour you expect to see
Expect it to load the same config when done via command line

* -

**Comment by carnager** [comment]
First of all you haven't defined a proper font. There are 2 problems with your choice:

1) sans-serif is not a font at all. It's an alias which can point to different fonts, depending on your environment. 

2) It's most likely not a monospace font, which is needed for rofi to display things properly

**Comment by YWFT** [comment]
That alone will ignore columns and lines yet load fine when loading it via cmd line or with theme selector?? If i dump it and load default config, same deal though.

**Comment by DaveDavenport** [comment]
Please pastebin the output of `rofi -h`.

**Comment by carnager** [comment]
Also you mentioned .Xresources. Also check for .Xdefaults. And make sure you don't have a config.rasi file.

**Comment by BitstyRoss** [comment]
Output from terminal - https://gist.github.com/BitstyRoss/89bd09f1c80a60ca15fb3d4d28aa3b02#file-rofi

**Comment by BitstyRoss** [comment]
@carnager no file, Found a `.local/share/rofi/themes/manjaro-openbox.rasi` but it's just another theme.

**Comment by JayKopinski** [comment]
Can close, turns out the keybinding was tied to alt + F1 and it was calling `/usr/bin/rofr.sh` and this is where the config was that was trumping mine. I guess i could copy and move it to ~/bin but instead i just updated the keybinding to run rofi like it does from terminal as `rofi -show run drun window`

**Comment by BitstyRoss** [comment]
I saw a reply, but that was it for me too, it was being set by the rofr.sh  file being called by the super key, just changed my superkey to call rofi the same way I do from terminal :)
