### ISSUE TITLE
Rofi is not using inline colors

### ISSUE THREAD

**Issue by leewdch** [DaveDavenport/rofi#828]
## Version

Version: 1.5.1-dirty (tags/1.5.1)

## Configuration

https://pastebin.com/M1PFxGtk

## Launch Command

```
$ echo $ROFI_COL                           
-color-window "#0b0407,#874e6b,#5d3449"           -color-normal "#0b0407,#e9d5de,#24111b,#eedfe5,#874e6b"           -color-active "#0b0407,#e9d5de,#24111b,#eedfe5,#874e6b"           -color-urgent "#0b0407,#e9d5de,#24111b,#eedfe5,#874e6b"
$ rofi -disable-history -show run $ROFI_COL
```

## What behaviour you see

* rofi uses default colors

## What behaviour you expect to see

* rofi using colors specified in $ROFI_COL

**Comment by DaveDavenport** [comment]
can you pastebin
```
rofi -h $ROFI_COL
```

**Comment by leewdch** [comment]
Tried exporting a new variable on a single line but same result. I'll try breaking it till it work
`export ROFI_COL="-color-window \"$background,$color4,$color3\""`

**Comment by DaveDavenport** [comment]
I *personally* think placing these options in the config file is the best way to go. Commandline handling of large options often give problems (esp when called from f.e. i3)

If you switch to the new theme format it is easier, you can make multiple themes and use -theme 'name'  to select the right one.

**Comment by DaveDavenport** [comment]
closing, as it is not an rofi issue.

**Comment by leewdch** [comment]
I don't think I can use env variables in rofi templates, that's why I'm using the command line for the job

**Comment by DaveDavenport** [comment]
true. (will add that).

**Comment by DaveDavenport** [comment]
Added.
