### ISSUE TITLE
Theme generator not worked

### ISSUE THREAD

**Issue by ol3gart** [DaveDavenport/rofi#829]
Hello!
When i try to open theme generator http://davedavenport.github.io/rofi/p11-Generator.html i see that Rofi website is not maintened.
Where i can found themes generator now?

**Comment by sardemff7** [comment]
As stated, it is unmaintained. You can recover the old code from the repository, but the generated theme will stop working in a few releases (if not the next one) so it will be useless, unless you want to update and maintain it for the new theme format.
The new theme format has a CSS syntax, many properties (but not 1:1 to CSS properties) and thus can do much more than just changing colours. So if you want to update the generator, it may be limiting (and frustrating) to others not to support it all.

**Comment by ol3gart** [comment]
Pls tell me where i can get the old code for rofi theme generator site?
and did u have a docs for new format?
wanna make new generator in web.
can we contact in Telegram ?

**Comment by DaveDavenport** [comment]
There is an IRC channel.

The code can be found in git in the gh-pages branch.
I think it would need a ground up re-engineer, documentation are in the rofi-themes manpage.
