### ISSUE TITLE
Unknown glyphs in ROFI

### ISSUE THREAD

**Issue by ol3gart** [DaveDavenport/rofi#830]
:arrow_right: First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)! :arrow_left:

## Version

Version: 1.5.1-dirty (tags/1.5.1)

## Configuration

https://gist.github.com/ol3gart/bed01ea3d827b1ca504557291a77459e

## Launch Command

rofi -combi-modi window,drun,ssh -font 'hack 10' -show combi

## Steps to reproduce

run Rofi in Manjaro I3 edition

## What behaviour you see

In all themes i've got a strange unknown symbols.
Try to use a different fonts - useless.

## What behaviour you expect to see

I thins this unknown glyph is ugly, and earlier when i use ROFI i didnot see it (btw i ve got a clean install, before i had a Arch system).
Sorry for bad image quality
https://cdn1.savepice.ru/uploads/2018/7/11/d5ca2fe1f2cea0f51659252c4c8c1d40-full.jpg

**Comment by DaveDavenport** [comment]
You can make a screenshot in rofi using it build in screenshot function. `Alt+s`

It looks like a font issue, you could look at:
```
-window-format [string]                 Window Format. w (desktop name), t (title), n (name), r (role), c (class)
```

Option, as it seems to go wrong for window with desktop name.
So try passing ``` -window-format '{i}{c} {t}'```

**Comment by ol3gart** [comment]
yes, it works!
thx!

**Comment by gigavinyl** [comment]
I tried this solution but still had unknown glyphs. I'm on NetBSD and this only happens when I use the scientifica font, not the default.
