### ISSUE TITLE
Custom combi mode prefix

### ISSUE THREAD

**Issue by binaryplease** [DaveDavenport/rofi#834]
Hi,

is it possible to specify a custom prefix for the list items in combi mode in the rasi themes?
I mean the "run" and "window" strings marked here with arrows.

![2018-07-13-005942_1366x768_scrot](https://user-images.githubusercontent.com/1719781/42663968-887a36fa-8638-11e8-874f-8b98c50af080.png)

**Comment by DaveDavenport** [comment]
Yes. You can set the display string for each combi. Option starting with `-display-`, like `-display-run` or `-display-window`.

**Comment by bohrshaw** [comment]
@DaveDavenport How to I use `-display-` with the `Script` `modi`?
