### ISSUE TITLE
Support alternative .desktop actions

### ISSUE THREAD

**Issue by ExoticMatter** [DaveDavenport/rofi#836]
Some applications have alternative actions in their .desktop files, each of which may have their own Exec and/or TryExec entries.  For example, Firefox has the actions ```new-window``` and ```new-private-window```.

It would be nice to be able to use these with ```-show drun```.

**Comment by DaveDavenport** [comment]
Patch that implements this: https://filebin.pw/mbKs95/

**Comment by ExoticMatter** [comment]
The patch is great, thanks!

As a final touch, could the alternative actions be "collapsed" into the application's main entry until needed, or at least a toggle be added that hides/unhides all alternative actions?  Some applications (e.g. Steam) litter the menu with actions.

**Comment by DaveDavenport** [comment]
I could make it an config/cli option for the drun browser to show actions or not.

**Comment by mustaqimM** [comment]
@DaveDavenport I added the option but still can't seem to load the alternate actions

**Comment by DaveDavenport** [comment]
are you on a recent enough git checkout?
