### ISSUE TITLE
Configurable "show" option causes wrong font to be used for spacing

### ISSUE THREAD

**Issue by Mange** [DaveDavenport/rofi#837]
## Version

```
› rofi -v       
Version: 1.5.1-dirty (tags/1.5.1)
```

## Configuration

This happens when using a blank configuration file (`-config /dev/null`).

## Launch Command

```
rofi -config /dev/null \
  -modi combi -show combi \
  -show-icons -display-window ' '
```

(`show-icons` not required, but is being used in the screenshot)

## Steps to reproduce

* Run command above.
* This works for any modi, but `window` has the worst problem due to spaces being used to "indent" windows.

## What behaviour you see

![spaces](https://user-images.githubusercontent.com/1599/42876794-18135942-8a88-11e8-815d-cfbaacf5ccba.png)

* Space characters are rendering only in the font used by the `display-` option.
* When `display-` option uses normal ASCII characters the problem goes away.

## What behaviour you expect to see

* Spaces to use the normal font and render like other text.

I don't know how it knows to pick the font that has the glyph, or why it don't revert to the configured font. Is this pango doing this?

**Comment by DaveDavenport** [comment]
Duplicate of? https://github.com/DaveDavenport/rofi/issues/830

**Comment by Mange** [comment]
> `-no-config`

Thanks. I tried that and the problem still persists, just to be completely honest.

> It seems to work correct for me.

See if we can narrow it down, then.

```
› rofi -no-config -modi combi -show combi -display-window ' ' -font "sans 16"
# Has the same problem
› fc-match -s "sans" | head -n6
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Nerd Font Complete.ttf: "Symbols Nerd Font" "2048-em"
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"
```

The glyph used in the `display-` option comes from *Symbols Nerd Font* AFAIK. Do you have that font?

I tried changing the symbol to a Camel emoji (🐪), which is rendered using the *Noto Color Emoji* font. Then all is well.

Manually switching to rendering everything with the symbols font (using `-font "Symbols Nerd Font 16"`) renders like when I used `sans`; text renders in my normal font, symbol still renders, and spaces have the "missing glyph" rendering.

**Comment by DaveDavenport** [comment]
Rofi uses pango to render the string..  It uses the same font for rendering the whole entry.

Not sure what is causing this.

**Comment by Mange** [comment]
I made another experiment. Seems like the font selection goes back after using normal letters again. This also confirms that it has nothing to do with the `display-` option.

```bash
echo 'Hello Spacy   World full of spaces!' | rofi -no-config -dmenu
```

![rofi](https://user-images.githubusercontent.com/1599/42886196-3c25c1e2-8aa3-11e8-9ab3-f60adaa9a969.png)

Spaces before the icon are fine. Spaces after the icon are broken. Spaces after the first word after the space are also fine.

Maybe this is about control characters...?

```bash
echo 'Symbol, non-breaking space, tab, escape:          ^]' | rofi -no-config -dmenu
```

(`^]` is a literal escape, using <kbd>Ctrl</kbd>+<kbd>v</kbd> <kbd>Ctrl</kbd>+<kbd>]</kbd>, non-breaking space and tab are also included in a similar fashion.)

![rofi](https://user-images.githubusercontent.com/1599/42886493-f82b0b40-8aa3-11e8-9866-72cafc62af3f.png)

**Comment by DaveDavenport** [comment]
Then it is pango screwing up, as I pass that data one-on-one to pango for rendering.
Does it work in f.e. gedit?

**Comment by Mange** [comment]
Other people having the same problem over here: https://github.com/stark/siji/issues/3

I tried their override with adding U+202d after the symbol. That worked!

```bash
echo 'Example fix: <202d>        lots of space' | rofi -no-config -dmenu
```

(`<202d> is a literal U+202D character, inputed using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd> <kbd>2</kbd> <kbd>0</kbd> <kbd>2</kbd> <kbd>d</kbd> <kbd>Return</kbd>)

![rofi](https://user-images.githubusercontent.com/1599/42886958-251e47d8-8aa5-11e8-8132-7352efb9038e.png)

**Comment by DaveDavenport** [comment]
fun.

**Comment by Mange** [comment]
> Does it work in f.e. gedit?

I don't have that installed, but it has the same problem in `pango-view`. That confirms it. Sorry to bother you! This was the first time I saw this problem. :sweat_smile: 

```bash
DISPLAY=:0 pango-view --font=monospace -t ' '
```

![screenshot from 2018-07-18 16-13-24](https://user-images.githubusercontent.com/1599/42887147-8d94fbc2-8aa5-11e8-8451-c96d883d3416.png)

**Comment by DaveDavenport** [comment]
no problem, thanks for getting to the bottom of it.

**Comment by Mange** [comment]
For any future readers:

---

Upstream bugs to Pango have been reported here:
- https://bugzilla.gnome.org/show_bug.cgi?id=775202
- https://bugzilla.gnome.org/show_bug.cgi?id=780068

Choice quote:

> Right.  Pango assumes all fonts support space...  We should fix this.

Essentially: Pango has a heuristic that don't even check if the font contains the glyph or not when outputting control characters, etc.

```c
if (G_UNLIKELY (type == G_UNICODE_CONTROL ||
                      type == G_UNICODE_FORMAT ||
                      type == G_UNICODE_SURROGATE ||
                      (type == G_UNICODE_SPACE_SEPARATOR && wc != 0x1680u /* OGHAM SPACE MARK */))
```

I also made sure to talk about this problem at the upstream for the font:
https://github.com/ryanoasis/nerd-fonts/issues/275#issuecomment-405952380

My current workaround is to not use the symbol. :grimacing:
