### ISSUE TITLE
Opens on incorrect monitor output

### ISSUE THREAD

**Issue by rafi** [DaveDavenport/rofi#84]
I've recently disabled all mouse handling in i3:
```
focus_follows_mouse no
mouse_warping none
```
Everything works great except in one scenario:
1) Prepare a global hot-key to open Rofi
2) Close all windows in monitor B's workspace
3) Focus on a window in monitor A
4) With a keyboard-shortcut, jump to the empty workspace on monitor B
5) Run Rofi with the predefined hot-key
Rofi opens on monitor A instead of B.

**Comment by fmos** [comment]
It seems this can be resolved only via i3 IPC messaging (i.e. another i3 "hack"), in particular by calling GET_OUTPUTS and parsing the JSON response to determine the coordinates of the active output. (https://i3wm.org/docs/ipc.html#_outputs_reply).

Alternatively the above could be implemented by a wrapper script if rofi supports an option to force the screen (see #220).

**Comment by DaveDavenport** [comment]
thx for the information. I prefer not having to add a json parser to rofi, so a wrapper script could be a nice workaround.

**Comment by fmos** [comment]
Here is my wrapper script for future releases:
```sh
#!/bin/sh
# wrapper script to open rofi on the focused i3 workspace
rofi -m $(i3-msg -t get_outputs | jq '.[] | select(.active) | .name' | awk "/`i3-msg -t get_workspaces | jq '.[] | select(.focused) | .output'`/ { print FNR-1 }") $@
```
This needs [jq](https://stedolan.github.io/jq/) for JSON parsing.

**Comment by DaveDavenport** [comment]
Should be fixed in git, please check!
