### ISSUE TITLE
Icons in dmenu/custom mode script

### ISSUE THREAD

**Issue by tadly** [DaveDavenport/rofi#840]
Couldn't find anything in the man page/existing issues so I'm curious whether this is already possible, and if not if it would be possible to add.

My idea was to have [dunst](https://github.com/dunst-project/dunst/) additionally save its notifications in a file somewhere (which is rather easy to achieve) and than display those in rofi to get a *notification history thingy.*

**Comment by tadly** [comment]
Not sure what about this question is "incomplete" so if something is unclear, let me know and I'll try my best to clarify it :)

**Comment by DaveDavenport** [comment]
The information requested in the template that was there when filling in the issue (and the linked guidelines).

**Comment by tadly** [comment]
None of these are relevant but if you insist...

## Version
Version: 1.5.1-dirty (tags/1.5.1)

## Configuration
https://pastebin.com/HhMJURrm

## Launch Command
echo "" | rofi -dmenu

## Steps to reproduce
Nothing to be done

## What behaviour you see
No icons

## What behaviour you expect to see
I'd like to be able to display icons/images with rofi executed in dmenu mode

**Comment by DaveDavenport** [comment]
You again did not read the guidelines, and the version is *very* relevant if people later look back through the history..

**Comment by tadly** [comment]
I did read the guidelines and I don't know what I'm missing...

**Comment by DaveDavenport** [comment]
a.) It is currently not possible to show icons in dmenu.
b.) We can add it, but the question is how to relate what icon to show with what column.

**Comment by tadly** [comment]
Well yes, I was pretty much aware this is not possible hence this feature-request to further discuss:
 1. if this is something that could be added
 2. **how** this could be added.

If I understand correctly, you don't want feature request on github than? The guidelines do not mention that...

**Comment by DaveDavenport** [comment]
You are absolutely right, it is not explicitly stated. mea culpa. I will clarify this.

I want to keep the bug/issue tracker as clean as possible, so it is easy(er) for people to search back.
IMHO having questions/long discussions pollute this.

Your initial report does not read at all like a feature request, it are two yes/no questions.

**Comment by tadly** [comment]
Alright. We are finally getting somewhere.

You're right in saying that OP does not really read as a feature-request so sorry for that.
The title was basically all there was to say for the feature request itself and I used the description to flesh it out a little bit (ensuring I'm not missing anything obvious hence the two questions in there).

Anyways, where do we go from here? Where **should** I post a feature request than?

**Comment by DaveDavenport** [comment]
Here is fine,  I will see if I can put up some guidelines for a feature request. 
(I think we have most information by now.)

**Comment by DaveDavenport** [comment]
Any proposition of how to relay what icon should be displayed for what entry ? (without breaking existing dmenu scripts)

**Comment by tadly** [comment]
Oh, so you wanted to use this very issue. I thought we'd create a new one or something but that's fine.

From the brainstorming I did myself (without knowing anything in regards to the source) I couldn't come up with a 100% clean idea.

If possible, extending the pango markup parser to support something like...
```xml
<image>absolute-image-path</image>
```
...wouldn't break existing scripts and is the best I could come up with for now.

**Comment by DaveDavenport** [comment]
I myself was thinking to use the same system as used for passing extra information in the script command. (that will work when not using pango markup, as parsing 'xml' is not the cheapest to do).

```My entry \x00icon\x1ffile-browser\n```
We use the 0 character to separate extra info, then \x1f as separator

**Comment by tadly** [comment]
I didn't even know that was a thing and the point about xml parsing is a good one (especially when it comes to what I'd try to do).

To be honest, I don't mind how it's implemented as long as it's clean and documented :)

Can I read up on the whole _extra information_-thing somewhere?
I though I read all the documentation there is when trying to figure out if the whole image thing is possible already...

**Comment by DaveDavenport** [comment]
It is in the [release](https://github.com/DaveDavenport/rofi/releases/tag/1.5.0) notes.
I don't have a lot of time to work on rofi, esp. documentation suffers because of this.

**Comment by tadly** [comment]
I never checked the release page, good to know there's information to be gathered :)

Having read those examples, I do agree that your idea makes a lot of sense and would be as clean as it gets IMO

**Comment by tadly** [comment]
one more thing I just though about.

would it be possible to support both, absolute paths and icon-theme icons?
rofi already does the heavy lifting when it comes to "figuring out the correct image from an active icon theme".
Scripts would have to do a lot of work to get that right.

So your example (I now finally understand it I thinkg) `My entry \x00icon\x1ffile-browser\n`
Would display the `file-browser` icon.

Additionally `My entry \x00image\x1f/absolute/path/img.png\n` be nice

**Comment by DaveDavenport** [comment]
That is already supported by the icon system. (needs the file:// prefix I think).

**Comment by DaveDavenport** [comment]
Added the above scheme to the script parser. needs testing.

**Comment by DaveDavenport** [comment]
Implemented.
