### ISSUE TITLE
Fallback Fonts in ThemeName.rasi?

### ISSUE THREAD

**Issue by SomethingSomethingArchLinux** [DaveDavenport/rofi#843]
I spent about an hour looking for a solution and the closest I got was setting system wide fall backs using fontconfig but I'd rather set a font fallback in a .rasi theme.

All I want to do is basically set a default font, DejaVu and use Font Awesome just for workspace icon glyphs. 

## Version

Output of `rofi -v` = `Version: 1.5.0`

## Configuration

`*{
font: "DejaVu Sans Bold 11, Font Awesome 12";
}`

Technically not the whole config but only relevant part. 

## Launch Command

'rofi -show window -theme mytheme.rasi'

## What behaviour you see

* - Rofi uses the latter font, workspace icons show up correctly but the regular text is not the correct font. If I remove Font Awesome 12 and just have the DejaVu, font shows up correctly but workspace glyph icons do not.

## What behaviour you expect to see

* - Expecting to see DejaVu Bold 11 with workspace glyph icons falling back to Font Awesome 12

**Comment by DaveDavenport** [comment]
Rofi uses pango to render fonts.  How fallback fonts are handled depends on pango and the backend that pango uses.
There is currently (that I am aware of) no way for rofi to specify to pango what fallback font to use.
I pass the user entered font directly to pango.
