### ISSUE TITLE
Slow startup time when run-command and run-list-command are used

### ISSUE THREAD

**Issue by andornaut** [DaveDavenport/rofi#844]
## Version

Version: 1.0.0

## Configuration

https://gist.github.com/andornaut/6ba7063317fb2cc512654d2744eab7e5

```bash
$ cat ~/.config/rofi/aliases
alias | awk -F'[ =]' '{print $2}'
```
```bash
$ cat ~/.config/rofi/config
rofi.run-command: /bin/bash -i -c '{cmd}'
rofi.run-list-command: source ~/.config/rofi/aliases
```

## Launch Command

```bash
rofi -show run
```

## Steps to reproduce

* Use config as noted above.
* Run `rofi -show run`

## What behaviour you see

Noticeable delay before the rofi window is rendered and keypresses are accepted.

## What behaviour you expect to see

Close to instant startup (on Ryzen 1700, Samsung 960pro NVME SSD). 

When i comment out `rofi.run-command`and/or `rofi.run-list-command`, the time-to-window-rendered improves noticeably.

Ultimately, my request is that rofi support bash (or other) aliases while maintaining good performance.

**Comment by DaveDavenport** [comment]
I don't see how `run-command` has any influence on startup time (it is only used when you activate an entry),  `run-list-command` obviously does as it is executed during startup.

Can you make a timing trace, so we can pinpoint where it is slow:  [instructions](https://github.com/DaveDavenport/rofi/wiki/Debugging-Rofi#timing-traces)

**Comment by DaveDavenport** [comment]
Your version is also hopelessly outdated (2+ years), please update.

**Comment by andornaut** [comment]
I've upgraded to 1.5.0, which is indeed much faster, though there is still a noticeable delay when using `run-list-command` as described above.

> run-list-command is indeed ran on startup [...], so if this is slow, rofi will be slow to startup

The aliases script is not slow, though:
```
$ time source ~/.config/rofi/aliases > /dev/null
real	0m0.004s
user	0m0.001s
sys	0m0.005s
```

> Can you make a timing trace

Will do.

**Comment by andornaut** [comment]
> keep in mind it also needs to load bash.

Ah, that was it. My `~/.bashrc` invoked a script that was slowing down bash startup.

I wrote a script - [cache-command](https://github.com/andornaut/cache-command) - which has helped.

```
source <(cache-command --expiration 86400 -- kubectl completion bash)
```

Thanks for pointing me in the right direction!
