### ISSUE TITLE
Make it possible to color single entries

### ISSUE THREAD

**Issue by Wiadomy** [DaveDavenport/rofi#847]
Just as in topic, the ability to color entries based on, for example, entry's value.

**Example:**
`rofi --color firefox #ffffff --color discord blue -show window`
The same thing with custom icons, optionally.
Of course I don't know if it is possible, but would be great. Especially for projects based on rofi, such as menugen

Version: 1.5.1-53-git-859a9c79-dirty

**Comment by DaveDavenport** [comment]
You can do this via pango markup on the rows.
