### ISSUE TITLE
Run new command instead of match from history but keep history

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [DaveDavenport/rofi#852]
Current behavior: When I type "Some in" and I have "Some input" in history. Expected behavior: The first string to be run instead of the longer string from the history. Sometimes I have a partial match from history when wanting to run a new command and then the entry from the history runs. I hope this makes sense.

**Comment by sardemff7** [comment]
rofi is a filter, so the behaviour is just as expected from a filter. If you want to run what you typed exactly, you have the `accept-custom` binding (defaults to `Ctrl+Return`).
