### ISSUE TITLE
Press Tab to complete instead of launch

### ISSUE THREAD

**Issue by giangm9** [DaveDavenport/rofi#854]
I use rofi as a bin launcher. Sometimes, I need no lauch with parameters ( ex: gnome-screenshot -a ), but when I press tab, rofi starts the binary instead of complete the search
I looked at the hotkey table, but I didn't see the hot key for that
## Version

Output of `rofi -v`

1.5.0

## Launch Command

rofi -show run

## Steps to reproduce

* Step 1
  open rofi

* Step 2
   gnome-scree *tab*

## What behaviour you see

* - screenshot

## What behaviour you expect to see

* - gnome-screenshot

**Comment by sardemff7** [comment]
The binding is `row-tab`. You want to set the `row-tab` binding to `""` and the `row-select` binding to `Tab`.
