### ISSUE TITLE
Transparency issue with alpha channel in hexcode

### ISSUE THREAD

**Issue by th3voic3** [DaveDavenport/rofi#856]
## Version

Version: 1.5.1-dirty (tags/1.5.1)

## Configuration
https://gist.github.com/th3voic3/891935a502edb23612cbab4795cedde0

## Launch Command

rofi -show run -m -1 -lines 10

## Steps to reproduce

* Step 1
Assign Alpha channel to rofi background hexcode
* Step 2
Launch rofi

## What behaviour you see
"Seethrough rofi" so completely transparent no matter which value I assign to the alpha channel

* -

## What behaviour you expect to see
The transparency should scale with the assigned alpha channel

* -
![rofi-screenshot](https://user-images.githubusercontent.com/6437665/45538713-1bc5d800-b808-11e8-8618-c8a4564263be.png)

**Comment by balta2ar** [comment]
@th3voic3 Do you think this could have the same root cause as [this](https://github.com/DaveDavenport/rofi/issues/845) issue?

**Comment by th3voic3** [comment]
Well for me it's only happening when I set transparency with alpha channel.
If I don't set transparency at all rofi acts normal.

So I'm not sure if it's related.

**Comment by DaveDavenport** [comment]
Not sure what is going wrong, bu the pasted theme is extremely transparent: `background: #B3010102;`
like 99%.

The last entry in the hex is the alpha channel, that is seens as an opacity. So 0x00 is fully transparent.

For me it works fine:
![rofi-2018-09-14-1136-00000](https://user-images.githubusercontent.com/406245/45542558-87ad3e00-b812-11e8-9dd1-ad93859f44f0.png)
this is with background set to 0x62.

**Comment by th3voic3** [comment]
In that case I had the order wrong.
I changed it and it works now, but the weird thing to me is that only the padding gets the transparency.
I want the entire background to be transparent. Any idea how to achieve that?

![rofi-screenshot2](https://user-images.githubusercontent.com/6437665/45542915-83355500-b813-11e8-9bb1-db846f7237f6.png)

**Comment by DaveDavenport** [comment]
It is stacked.  so make background of the other widgets fully transparent.
