### ISSUE TITLE
rofi stays open when a command has a & after it.

### ISSUE THREAD

**Issue by humCopper** [DaveDavenport/rofi#857]
## Version  
Version: 1.5.1-dirty (tags/1.5.1)

## Configuration
[gist](https://gist.github.com/humCopper/78f5290615ad1f2386a917c4ce8b7777)

## Launch Command
rofi -modi Search:./rofi-surfraw.sh -show Search 

## Steps to reproduce

* Step 1  
download [rofi-surfraw.sh](https://gitlab.com/humCopper/rofi-scripts/tree/master)

* Step 2  
run rofi with no browser open because

## What behaviour you see

* Rofi stays open while the command in the background is still running.
The command does not matter. I tested it with sleep 5& and Rofi still stays open for 5 seconds.Rofi still stays open when you call a command with a & after it. The command seems to not go to the background.

## What behaviour you expect to see

* Rofi closes after the script calls the command&.

**Comment by DaveDavenport** [comment]
Use the [coproc](https://github.com/DaveDavenport/rofi/blob/next/Examples/rofi-file-browser.sh#L56) trick as used in the examples.

**Comment by humCopper** [comment]
Thank you. I did not know about coproc.
