### ISSUE TITLE
broken wiki link

### ISSUE THREAD

**Issue by Fandekasp** [DaveDavenport/rofi#861]
## Steps to reproduce

* Go to the [wiki](https://github.com/DaveDavenport/rofi/wiki)
* Click on "Using rofi in scripts"

## What behaviour you see
Page is missing

## What behaviour you expect to see
Page should be present with documentation on how to use rofi in scripts.

I am looking for an application-agnostic text expander, and after finding [snippy](https://bbs.archlinux.org/viewtopic.php?id=71938&p=2) which work for dmenu, I'd like to adapt it for rofi.
I wasn't clear on the process after reading rofi's manpage, which is why I went looking for more infos in the wiki.

**Comment by Fandekasp** [comment]
@carnager thanks for the reply.

I went with something very simple to start

textexpand
```bash
#!/usr/bin/env bash

CONFIG=${HOME}/.textexpandrc
ALL_KEYS=$(sed 's/\].*/]/' ${CONFIG} | tr -d '[]')
KEY=$(echo $ALL_KEYS | rofi -sep ' ' -dmenu -p "autocomplete")

grep "\[${KEY}\]" $CONFIG | sed "s/\[${KEY}\] //" | xsel -ib
xdotool key ctrl+shift+v
```

i3config
```
bindsym $mod+c exec --no-startup-id textexpand
```

.textexpandrc
```
[yoro] よろしくお願いします。
[otsu] お疲れさまでします。
[ohayo] おはようございます。
```

**Comment by DaveDavenport** [comment]
Not gonna fix this one (no time), help/contributions welcome.
