### ISSUE TITLE
Build/install instructions reference `configure` executable that is not present

### ISSUE THREAD

**Issue by pbx** [DaveDavenport/rofi#863]
## Version

1.5.1 (11afb8e6)

## Configuration

N/A (can't build)

## Launch Command

N/A 

## Steps to reproduce

1. Clone rofi repo
2. Follow [installation guide](https://github.com/DaveDavenport/rofi/blob/next/INSTALL.md)
3. At "Check dependencies and configure build system" step, discover there is no `configure` in the top level directory (or anywhere in the project working dir).

## What behaviour you see

* no `configure` in the top level directory

## What behaviour you expect to see

* `configure` in the top level directory

**Comment by DaveDavenport** [comment]
It is clearly mentioned [here](https://github.com/DaveDavenport/rofi/blob/next/INSTALL.md#install-a-checkout-from-git)
