### ISSUE TITLE
Rofi freezes in script mode

### ISSUE THREAD

**Issue by haolian9** [DaveDavenport/rofi#864]
## Version

Output of `rofi -v`

```
Version: 1.5.1-dirty (tags/1.5.1)
```

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

```
...

Monitor layout:
              ID: 0 (primary)
            name: eDP1
        position: 0,0
            size: 1920,1080
            size: 340mm,190mm  dpi: 143,144


Detected modi:
        * +window
        * windowcd
        * +run
        * ssh
        * drun
        * combi
        * keys

Compile time options:
	* window  enabled
	* drun    enabled
	* timings disabled
	* gcov    disabled
	* asan    disabled

For more information see: man rofi
                 Version: 1.5.1-dirty (tags/1.5.1)
              Bugreports: https://github.com/DaveDavenport/rofi/
                 Support: https://reddit.com/r/qtools/
                          #rofi @ freenode.net
      Configuration file: /home/haoliang/.config/rofi/config
```

## Launch Command

The commandline used to launch **rofi**

`rofi -show x -modi x:~/.config/rofi/plugins/freeze.sh`

## Steps to reproduce

create the freeze.sh script and launch it via rofi.

content of freeze.sh

```
#!/usr/bin/env bash

main() {
    case $# in
        0)
            echo "alacritty"
            ;;
        *)
            alacritty
            ;;
    esac
}

main "$@"
```

## What behaviour you see

after launched rofi window, select the "alacritty" option, then the whole world freezed: keyboard, click have no effect; rofi window still remains.

**Comment by DaveDavenport** [comment]
This is expected behaviour, as rofi stays listening on output of alacritty.
See: https://github.com/DaveDavenport/rofi/issues/857.

Try launching the tool you want to run in a coproc.

**Comment by haolian9** [comment]
oh, thank you.I tried search, but did not see the issue you mentioned above.

I think add some guides in script mode section of readme would be very helpful.

**Comment by DaveDavenport** [comment]
Still looking for help on documentation.
