### ISSUE TITLE
Running through rofi results in different behavior towards running in terminal

### ISSUE THREAD

**Issue by RedTailBullet** [DaveDavenport/rofi#866]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v` 
1.5.1-dirty (tags/1.5.1)

OS version:
4.18.12-arch1-1-ARCH

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/)) https://gist.github.com/RedTailBullet/327e2c9496656a8124aaee12968ef643

## Launch Command

The commandline used to launch **rofi**
rofi -show drun

## Steps to reproduce

* Step 1 Install vscode and nvm from AUR.
* Step 2 `npm install typescript` to install typescript in the local workspace, `nvm install --lts` to install lts version node. Set vscode to use workspace version typescript.
* Step 3 Config vscode with a launch configuration with a task of "tsc build".
* Step 4 Use F5 to run the debug.

**PS** Only nvm version of node should be installed! If you have another node in your system this error disappeared.

## What behaviour you see

* - Task "tsc" is failed with an error `/usr/bin/env: ‘node’: No such file or directory`.

## What behaviour you expect to see

* - Task "tsc" should be successful and vscode enter debug mode.

## Why this is interesting

When running through rofi, no matter if I run with `drun` or `run`, there are an error. However, if I run `code` in terminal, the error disappeared. I checked the code-oss.desktop file and removed any extra parameters but that still cuase this error. I am wondering whether rofi is passing any extra parameters to run the software which leads to this issue. Or rofi is using a different user to run it.

**Comment by sardemff7** [comment]
This is most likely an env issue. rofi does not “use a different user” (it doesn’t run as root, so it cannot) or add any parameter. The “no system node install” also rings the env bell to me.
How do you run rofi itself? Do you run it from the same terminal `code` works in? Or from a DE/WM keybinding?

**Comment by RedTailBullet** [comment]
I am running it using i3wm's shortcut.

**Comment by RedTailBullet** [comment]
I do think that this might be an issue with env. However, with vscode's integrated terminal, everything works fine.

**Comment by sardemff7** [comment]
Could you try running rofi from the terminal? If that works, just checks whatever shell files (probably `~/.bashrc`) that `nvm` might be tweaking to update your `PATH`.

**Comment by RedTailBullet** [comment]
While running from terminal, everything works fine. NVM do have something in .bashrc to update the path. So how does that happen?

**Comment by sardemff7** [comment]
It’s just how these tools usually work, and they always expect `.bashrc` to work. In your setup, you’ll have to source it from your `~/.xinitrc` file before running i3. I would even advice to use `~/.profile` (or `~/.bash_profile`) if NVM can be made to use it. That way, you always need a reboot to really change the env, but you’re almost sure it’ll always work. Actually, some distributions do use a login shell for X sessions so it would source `~/.profile` but not `~/.bashrc`. (Though most also source `~/.bashrc` from `~/.profile` because tools only touch `~/.bashrc`.)

**Comment by RedTailBullet** [comment]
Thanks for the advice! I will check whether that works.

**Comment by RedTailBullet** [comment]
Unfortunately adding the init script to ~/.bash_profile doesn't seem to work. VSCode is still throwing the same error while started with rofi.

**Comment by sardemff7** [comment]
I cannot give the magical solution for your exact setup, but anyway, this is not a rofi bug and you’ll surely find all the documentation you need on Arch’s wiki. :-)

**Comment by RedTailBullet** [comment]
Thanks for your help!
