### ISSUE TITLE
rofi invisible when called recursively

### ISSUE THREAD

**Issue by jeffguorg** [DaveDavenport/rofi#868]
## Problem

Call rofi in a script called by rofi will make later rofi invisible

## Version

Output of `rofi -v`
```bash 
> rofi -v
Version: 1.5.0
```

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
```
...(common stuff)
Monitor layout:
              ID: 0
            name: eDP-1-1
        position: 0,0
            size: 1920,1080
            size: 344mm,193mm  dpi: 142,142

              ID: 1 (primary)
            name: HDMI-1-1
        position: 1920,0
            size: 1920,1080
            size: 477mm,268mm  dpi: 102,102


Detected modi:
        * +window
        * windowcd
        * +run
        * +ssh
        * +drun
        * +combi
        * keys

Compile time options:
	* window  enabled
	* drun    enabled
	* timings disabled
	* gcov    disabled
	* asan    disabled

For more information see: man rofi
                 Version: 1.5.0
              Bugreports: https://github.com/DaveDavenport/rofi/
                 Support: https://reddit.com/r/qtools/
                          #rofi @ freenode.net
      Configuration file: /home/guochao/.config/rofi/confi
```
## Launch Command

there is two rofi process related:
  - i call rofi with i3 key binding: i3 config:```bindsym $mod+Return exec rofi -show combi -combi-modi 'window#drun#ssh#tools:rofi-tools#run:rofi-run' -show-icons``` 
    and rofi should be ```rofi -show combi -combi-modi 'window#drun#ssh#tools:rofi-tools#run:rofi-run'```
  - second is from tools:rofi-tools, it calls a script which directly call rofi(again)

## Steps to reproduce

as i said above. call rofi in the script which is called by rofi

## What behaviour you see

rofi is invisible but still response to user interaction. 

## What behaviour you expect to see

rofi shows itself as usual

## Workaround

I'm not sure if it's a feature or bug. so i just file a issue here. and the workaround is to fork and wait for parent rofi to die in the script. 

i'm lazy so i just fork and wait for a second and then call rofi

**Comment by DaveDavenport** [comment]
To start:
* Calling rofi recursive is not supported.
* Calling rofi (recursive) from script-mode is not supported.

Not because it is impossible, it is easy to do wrong.

Having said that, with the blezz plugin (that i use daily) I call rofi (dmenu script) from rofi without issues.

Is it possible to get the debug output of the 2nd rofi. (See wiki on how to enable it).

**Comment by DaveDavenport** [comment]
Closing, because no further information.
