### ISSUE TITLE
Missing i3_empty_workspace.sh script in Examples/ directory

### ISSUE THREAD

**Issue by T-J-Teru** [DaveDavenport/rofi#869]
## Version
```
> rofi -v
Version: 1.5.1
```

## Launch Command

The `rofi` manual suggests this as a demo for an i3 workspace switcher:
```
rofi -modi "window,run,ssh,Workspaces:i3_switch_workspaces.sh" -show Workspaces
```
And the `i3_switch_workspaces.sh` script is installed in `rofi-1.5.1/Examples/i3_switch_workspaces.sh`, however, that script makes use of `i3_empty_workspace.sh` which isn't in the `Examples/` directory, and I don't have installed 

I don't have that script installed as part of i3, nor does it seem to be included with rofi, and the `i3_switch_workspace.sh` script doen't have any hints for where I could find it.

## Steps to reproduce

* Run `i3` desktop
* Run `rofi -modi "window,run,ssh,Workspaces:i3_switch_workspaces.sh" -show Workspaces`
* Select `empty` from the list of available workspaces
* See an error about `i3_empty_workspace.sh` script not being found.

## What behaviour you see

* Error due to missing script.

## What behaviour you expect to see

I think either:

* Include the `i3_empty_workspace.sh` script in the examples directory, or
* Remove the empty workspace functionality from `i3_switch_workspace.sh`, or
* Include a comment in `i3_switch_workspace.sh` pointing folks at the location of the missing script

**Comment by DaveDavenport** [comment]
Thanks.
