### ISSUE TITLE
-drun-match-fields and -no-show-match not working

### ISSUE THREAD

**Issue by catzybluphish** [DaveDavenport/rofi#871]
## Version

1.5.1-dirty

## Configuration
	-modi [string]                          Enabled modi
	run,drun (File)
	-width [number]                         Window width
	370 (File)
	-lines [number]                         Number of lines
	20 (File)
	-columns [number]                       Number of columns
	1 (Default)
	-font [string]                          Font to use
	SF Pro Display 13 (File)
	-bw [number]                            Border width
	0 (File)
	-location [number]                      Location on screen
	0 (Default)
	-padding [number]                       Padding
	50 (File)
	-yoffset [number]                       Y-offset relative to location
	0 (Default)
	-xoffset [number]                       X-offset relative to location
	0 (Default)
	-[no-]fixed-num-lines                   Always show number of lines
	True (Default)
	-[no-]show-icons                        Whether to load and show icons
	True (File)
	-terminal [string]                      Terminal to use
	rofi-sensible-terminal (Default)
	-ssh-client [string]                    Ssh client to use
	ssh (Default)
	-ssh-command [string]                   Ssh command to execute
	{terminal} -e {ssh-client} {host} (Default)
	-run-command [string]                   Run command to execute
	{cmd} (Default)
	-run-list-command [string]              Command to get extra run targets
	 (Default)
	-run-shell-command [string]             Run command to execute that runs in shell
	{terminal} -e {cmd} (Default)
	-window-command [string]                Command executed on accep-entry-custom for window modus
	xkill -id {window} (Default)
	-window-match-fields [string]           Window fields to match in window mode
	all (Default)
	-drun-icon-theme [string]               Theme to use to look for icons
	(unset) (Default)
	-drun-match-fields [string]             Desktop entry fields to match in drun
	name (File)
	-[no-]disable-history                   Disable history in run/ssh
	False (Default)
	-[no-]sort                              Use sorting
	False (Default)
	-[no-]levenshtein-sort                  Use levenshtein sorting also for fuzzy matching
	False (Default)
	-[no-]case-sensitive                    Set case-sensitivity
	False (Default)
	-[no-]cycle                             Cycle through the results list
	True (Default)
	-[no-]sidebar-mode                      Enable sidebar-mode
	False (Default)
	-eh [number]                            Row height (in chars)
	1 (Default)
	-[no-]auto-select                       Enable auto select mode
	False (Default)
	-[no-]parse-hosts                       Parse hosts file for ssh mode
	False (Default)
	-[no-]parse-known-hosts                 Parse known_hosts file for ssh mode
	True (Default)
	-combi-modi [string]                    Set the modi to combine in combi mode
	window,run (Default)
	-matching [string]                      Set the matching algorithm. (normal, regex, glob, fuzzy)
	normal (Default)
	-[no-]tokenize                          Tokenize input string
	True (Default)
	-m [string]                             Monitor id to show on
	-5 (Default)
	-line-margin [number]                   Margin between rows *DEPRECATED*
	5 (File)
	-line-padding [number]                  Padding within rows *DEPRECATED*
	1 (Default)
	-filter [string]                        Pre-set filter
	(unset) (Default)
	-separator-style [string]               Separator style (none, dash, solid) *DEPRECATED*
	none (File)
	-[no-]hide-scrollbar                    Hide scroll-bar *DEPRECATED*
	True (File)
	-[no-]fullscreen                        Fullscreen
	False (Default)
	-[no-]fake-transparency                 Fake transparency *DEPRECATED*
	False (Default)
	-dpi [number]                           DPI
	-1 (Default)
	-threads [number]                       Threads to use for string matching
	0 (Default)
	-scrollbar-width [number]               Scrollbar width *DEPRECATED*
	8 (Default)
	-scroll-method [number]                 Scrolling method. (0: Page, 1: Centered)
	0 (Default)
	-fake-background [string]               Background to use for fake transparency. (background or screenshot)
	screenshot (Default)
	-window-format [string]                 Window Format. w (desktop name), t (title), n (name), r (role), c (class) *DEPRECATED*
	{w}    {i}{c}   {t} (Default)
	-[no-]click-to-exit                     Click outside the window to exit
	True (Default)
	-[no-]show-match                        Indicate how it match by underlining it.
	True (Default)
	-theme [string]                         New style theme file
	(unset) (Default)
	-color-normal [string]                  Color scheme for normal row
	argb:00000000, #696969, argb:00000000, argb:00000000, #ffffff (File)
	-color-urgent [string]                  Color scheme for urgent row
	(unset) (Default)
	-color-active [string]                  Color scheme for active row
	(unset) (Default)
	-color-window [string]                  Color scheme window
	argb:ff00000c (File)
	-max-history-size [number]              Max history size (WARNING: can cause slowdowns when set to high).
	25 (Default)
	-[no-]combi-hide-mode-prefix            Hide the prefix mode prefix on the combi view.
	False (Default)
	-pid [string]                           Pidfile location
	/run/user/1000/rofi.pid (Default)
	-display-window [string]                The display name of this browser
	(unset) (Default)
	-display-windowcd [string]              The display name of this browser
	(unset) (Default)
	-display-run [string]                   The display name of this browser
	(unset) (Default)
	-display-ssh [string]                   The display name of this browser
	(unset) (Default)
	-display-drun [string]                  The display name of this browser
	(unset) (Default)
	-display-combi [string]                 The display name of this browser
	(unset) (Default)
	-display-keys [string]                  The display name of this browser
	(unset) (Default)
	-kb-primary-paste [string]              Paste primary selection
	Control+V,Shift+Insert (Default)
	-kb-secondary-paste [string]            Paste clipboard
	Control+v,Insert (Default)
	-kb-clear-line [string]                 Clear input line
	Control+w (Default)
	-kb-move-front [string]                 Beginning of line
	Control+a (Default)
	-kb-move-end [string]                   End of line
	Control+e (Default)
	-kb-move-word-back [string]             Move back one word
	Alt+b (Default)
	-kb-move-word-forward [string]          Move forward one word
	Alt+f (Default)
	-kb-move-char-back [string]             Move back one char
	Left,Control+b (Default)
	-kb-move-char-forward [string]          Move forward one char
	Right,Control+f (Default)
	-kb-remove-word-back [string]           Delete previous word
	Control+Alt+h,Control+BackSpace (Default)
	-kb-remove-word-forward [string]        Delete next word
	Control+Alt+d (Default)
	-kb-remove-char-forward [string]        Delete next char
	Delete,Control+d (Default)
	-kb-remove-char-back [string]           Delete previous char
	BackSpace,Control+h (Default)
	-kb-remove-to-eol [string]              Delete till the end of line
	Control+k (Default)
	-kb-remove-to-sol [string]              Delete till the start of line
	Control+u (Default)
	-kb-accept-entry [string]               Accept entry
	Control+j,Control+m,Return,KP_Enter (Default)
	-kb-accept-custom [string]              Use entered text as command (in ssh/run modi)
	Control+Return (Default)
	-kb-accept-alt [string]                 Use alternate accept command.
	Shift+Return (Default)
	-kb-delete-entry [string]               Delete entry from history
	Shift+Delete (Default)
	-kb-mode-next [string]                  Switch to the next mode.
	Shift+Right,Control+Tab (Default)
	-kb-mode-previous [string]              Switch to the previous mode.
	Shift+Left,Control+ISO_Left_Tab (Default)
	-kb-row-left [string]                   Go to the previous column
	Control+Page_Up (Default)
	-kb-row-right [string]                  Go to the next column
	Control+Page_Down (Default)
	-kb-row-up [string]                     Select previous entry
	Up,Control+p,ISO_Left_Tab (Default)
	-kb-row-down [string]                   Select next entry
	Down,Control+n (Default)
	-kb-row-tab [string]                    Go to next row, if one left, accept it, if no left next mode.
	Tab (Default)
	-kb-page-prev [string]                  Go to the previous page
	Page_Up (Default)
	-kb-page-next [string]                  Go to the next page
	Page_Down (Default)
	-kb-row-first [string]                  Go to the first entry
	Home,KP_Home (Default)
	-kb-row-last [string]                   Go to the last entry
	End,KP_End (Default)
	-kb-row-select [string]                 Set selected item as input text
	Control+space (Default)
	-kb-screenshot [string]                 Take a screenshot of the rofi window
	Alt+S (Default)
	-kb-toggle-case-sensitivity [string]    Toggle case sensitivity
	grave,dead_grave (Default)
	-kb-toggle-sort [string]                Toggle sort
	Alt+grave (Default)
	-kb-cancel [string]                     Quit rofi
	Escape,Control+g,Control+bracketleft (Default)
	-kb-custom-1 [string]                   Custom keybinding 1
	Alt+1 (Default)
	-kb-custom-2 [string]                   Custom keybinding 2
	Alt+2 (Default)
	-kb-custom-3 [string]                   Custom keybinding 3
	Alt+3 (Default)
	-kb-custom-4 [string]                   Custom keybinding 4
	Alt+4 (Default)
	-kb-custom-5 [string]                   Custom Keybinding 5
	Alt+5 (Default)
	-kb-custom-6 [string]                   Custom keybinding 6
	Alt+6 (Default)
	-kb-custom-7 [string]                   Custom Keybinding 7
	Alt+7 (Default)
	-kb-custom-8 [string]                   Custom keybinding 8
	Alt+8 (Default)
	-kb-custom-9 [string]                   Custom keybinding 9
	Alt+9 (Default)
	-kb-custom-10 [string]                  Custom keybinding 10
	Alt+0 (Default)
	-kb-custom-11 [string]                  Custom keybinding 11
	Alt+exclam (Default)
	-kb-custom-12 [string]                  Custom keybinding 12
	Alt+at (Default)
	-kb-custom-13 [string]                  Csutom keybinding 13
	Alt+numbersign (Default)
	-kb-custom-14 [string]                  Custom keybinding 14
	Alt+dollar (Default)
	-kb-custom-15 [string]                  Custom keybinding 15
	Alt+percent (Default)
	-kb-custom-16 [string]                  Custom keybinding 16
	Alt+dead_circumflex (Default)
	-kb-custom-17 [string]                  Custom keybinding 17
	Alt+ampersand (Default)
	-kb-custom-18 [string]                  Custom keybinding 18
	Alt+asterisk (Default)
	-kb-custom-19 [string]                  Custom Keybinding 19
	Alt+parenleft (Default)
	-kb-select-1 [string]                   Select row 1
	Super+1 (Default)
	-kb-select-2 [string]                   Select row 2
	Super+2 (Default)
	-kb-select-3 [string]                   Select row 3
	Super+3 (Default)
	-kb-select-4 [string]                   Select row 4
	Super+4 (Default)
	-kb-select-5 [string]                   Select row 5
	Super+5 (Default)
	-kb-select-6 [string]                   Select row 6
	Super+6 (Default)
	-kb-select-7 [string]                   Select row 7
	Super+7 (Default)
	-kb-select-8 [string]                   Select row 8
	Super+8 (Default)
	-kb-select-9 [string]                   Select row 9
	Super+9 (Default)
	-kb-select-10 [string]                  Select row 10
	Super+0 (Default)
	-ml-row-left [string]                   Go to the previous column
	ScrollLeft (Default)
	-ml-row-right [string]                  Go to the next column
	ScrollRight (Default)
	-ml-row-up [string]                     Select previous entry
	ScrollUp (Default)
	-ml-row-down [string]                   Select next entry
	ScrollDown (Default)
	-me-select-entry [string]               Select hovered row
	MousePrimary (Default)
	-me-accept-entry [string]               Accept hovered row
	MouseDPrimary (Default)
	-me-accept-custom [string]              Accept hovered row with custom action
	Control+MouseDPrimary (Default)

Monitor layout:
              ID: 0 (primary)
            name: DVI-D-0
        position: 0,0
            size: 1920,1080
            size: 480mm,270mm  dpi: 102,102

Detected modi:
        * window
        * windowcd
        * +run
        * ssh
        * +drun
        * combi
        * keys

Compile time options:
	* window  enabled
	* drun    enabled
	* timings disabled
	* gcov    disabled
	* asan    disabled

For more information see: man rofi
                 Version: 1.5.1-dirty (tags/1.5.1)
              Bugreports: https://github.com/DaveDavenport/rofi/
                 Support: https://reddit.com/r/qtools/
                          #rofi @ freenode.net
      Configuration file: /home/catsik/.config/rofi/config
## Launch Command

rofi -show drun

## Just a little help with customizing rofi
I'm trying drun rofi without showing what kind of app it is next to the names of them and to disable showing the underlining of letters when typing matching letters. I've read the manpage that they're "-drun-match-fields name" and "-no-show-match" but when I put them in my rofi config:
![2018-11-04-212243_768x1060_scrot](https://user-images.githubusercontent.com/40843060/47963411-cd9abb80-e077-11e8-9e2c-ca1d9c98e850.png)
they don't do anything. I'm following the syntax that has worked for the settings other than the last two. How can I fix this?
Cheers.

**Comment by DaveDavenport** [comment]
For the highlight can you try:
```
rofi -show drun -theme-str 'element {highlight: none;}'
```

**Comment by catzybluphish** [comment]
> The syntax is:
> 
> ```
> rofi.show-match: false
> ```
> 
> This should be fixed in manpage.

Thanks. Is there a way to not show the type of application next to their names in drun? E.g. Next to Spotify it would say "(Music Player)"

**Comment by DaveDavenport** [comment]
See #858

**Comment by catzybluphish** [comment]
> See #858

I've seen them but still don't exactly understand what I'm meant to do so please bear with me. I've put `rofi.drun-display-format: true/false` and `rofi-display-format: name` to no avail.

**Comment by DaveDavenport** [comment]
See manpage: 'https://github.com/DaveDavenport/rofi/blob/next/doc/rofi.1.markdown' and you need latest git checkout.

**Comment by DaveDavenport** [comment]
(sorry clicked wrong button)
