### ISSUE TITLE
dmenu theme - unexpected end of file

### ISSUE THREAD

**Issue by RaitaroH** [DaveDavenport/rofi#873]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`
```
▶ rofi -v
Version: 1.5.1-66-git-1915de73-dirty (next)
```

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

rofi --help
https://gist.github.com/RaitaroH/4a455023f318095521fc017972533619
rofi config
https://gist.github.com/RaitaroH/d9d88fa51ca1ce2c39ce32160b11b14f
dmenu.rasi
https://gist.github.com/RaitaroH/0f804a11dda1ddfd9ed9cd76588f97a0

## Launch Command
```
▶ echo -e "foo\nbar\n" | rofi -dmenu -multi-select -theme dmenu
** (process:21589): WARNING **: 21:27:37.950: /home/raitaro/.config/rofi/config.rasi:25:18: Option: levenshtein-sort is not found.
````

## Steps to reproduce

* Step 1
Use the dmenu.rasi file.
* Step 2
Use the command above.

## What behaviour you see

I get an error with the file. I suppose something with rofi changed since version 1.5.1 in ubuntu 18.04 repos?
![image](https://user-images.githubusercontent.com/19552720/47968885-91b42600-e078-11e8-8367-e9ff8c4ef42e.png)

## What behaviour you expect to see

The theme to work.

**Comment by carnager** [comment]
remove that empty (and wrong) configuration block

**Comment by RaitaroH** [comment]
Interesting. If I delete the dmenu.rasi in my config it works.

After a
`cp /usr/share/rofi/themes/dmenu.rasi ~/.config/rofi`
it doesn't.

**Comment by carnager** [comment]
Well, the dmenu.rasi file you provided above is NOT the one shipped with rofi.

**Comment by RaitaroH** [comment]
> Well, the dmenu.rasi file you provided above is NOT the one shipped with rofi.

May not be, but I just `cp` the one that is which works if it is in /usr but not in `.config`

**Comment by carnager** [comment]
possible... i am not sure right now how rofi handles themes, that are duplicated and not called with absolute path.

**Comment by RaitaroH** [comment]
Ok...
So rofi IS NOT using `/usr/share/rofi/themes/dmenu.rasi` as the dmenu file. I just removed it and rofi still works

**Comment by RaitaroH** [comment]
Aha. `/usr/local/share/rofi/themes/dmenu.rasi` is this instead.

**Comment by RaitaroH** [comment]
Welp, I think the configuration block being empty in the new rofi is not good huh? Well I didn't add it but it seems it got removed since I got it and modified it. Though it took me 15 minutes to find out how rofi is dealing with themes. Why have theme in 2 places though? So strange.

Though.... `cp /usr/share/rofi/themes/dmenu.rasi ~/.config/rofi` didn't work what? :thinking:

**Comment by RaitaroH** [comment]
Welp, works for me. I mean, now rofi is less forgiving on the rasi files it seems. ¯\_(ツ)_/¯

**Comment by carnager** [comment]
if you installed rofi to a different prefix, the prefix for themes will naturally change. self compiled software usually installs to /usr/local
