### ISSUE TITLE
Follow CSS syntax to declare a variable

### ISSUE THREAD

**Issue by dannycolin** [DaveDavenport/rofi#876]
## Version

1.5.1

## Configuration

https://gist.github.com/dannycolin/fe02588d5bf65bbade2573a3a439ab31

## Launch Command

rofi -show drun

## What behaviour you see

At the present moment, variables **are set** like so in the new rasi theme format:

```
my-variable: variable-value;
property: property-value
property: property-value
```

As you can see, when there's a lot of variables and properties it can be hard to quickly see which one is the variable and each is the property. 

Further, when we use them elsewhere they are prepend by a `@`. That could cause other issues in the future if we want to implement other functionalities based on the CSS syntax like `@media{max-width: ...}`.

## What behaviour you expect to see

I would except rasi variables to follow a bit more CSS variables' format. In CSS, variable **are set** by adding `--` in front of them.

```
--my-variable: variable-value
property: property-value
```

When you call them, you use the same name `--my-variable` wrapped in `var()`. It is cleaner and more consistent.

And other advantage of that syntax is that It let us set a fallback value in case the variable is undefined.

```
background-color: var(--my-variable, #000000);
```

### Notes

This modification could (will) probably break the backword compatibility of certain config files. A solution could be to add a property that let the user set the symbol that prepend the variable. By default, it could be `variable-symbol: "@"`. But someone could easily set it to `variable-symbol: ""` to be able to use the CSS variables' format.

Thanks!

**Comment by DaveDavenport** [comment]
Implemented, but needs testing.

The -- is not mandatory, it will work without.

**Comment by dannycolin** [comment]
@DaveDavenport thanks. It works on my side.
