### ISSUE TITLE
issue with double dash augments as rofi input

### ISSUE THREAD

**Issue by demure** [DaveDavenport/rofi#877]
## Version

Output of `rofi -v`
Version: 1.5.1
(this is "1.5.1-1" from debian sid's repo)

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

https://gist.github.com/demure/b918bec2199122224b3cfe8749beb72f

## Launch Command

The commandline used to launch **rofi**
```
rofi -sidebar-mode -show run -font 'Pragmata Pro 10' -fg \#505050 -bg \#000000 -bgalt \#101010 -hlfg \#008080 -hlbg \#454A4F -bc \#008080 -bw 1 -location 2 -width 100 -padding 0 -lines 10 -no-disable-history -no-levenshtein-sort
```

(also recreated with `rofi -show run`)

## Steps to reproduce

* Step 1 lunch rofi
* Step 2 input `firefox --private`

## What behaviour you see

* - Firefox opens a non-private window. The top right privacy indicator is missing, the purple blank page is missing.

## What behaviour you expect to see

* - When running the same command from the command line (`firefox --private`), a normal private window opens.

As pointed out by Rasi on the irc channel, I can input `firefox \-\-private` into rofi as a work around.
Submitting bug on Rasi's request :)

**Comment by demure** [comment]
Further advice from SardemFF7 is that ctrl+enter is the way to get around this issue.
Perhaps some form of visual indicator (color change, pop out warning, etc) could be employed so that users have some way of realizing that the dash is being used for a different purpose?

**Comment by DaveDavenport** [comment]
Yeah, the negate seems to work confusing.  Wonder what other prefix we can use for it. (given that `!` is already in use for combi mode)

**Comment by DaveDavenport** [comment]
Not to happy with adding another option, but being able to disable this one might be nice.

Hopefully we can find a better solutino in the future.

**Comment by demure** [comment]
Thank you for working on the issue :+1:
