### ISSUE TITLE
Not opening from i3-gaps on fresh arch install

### ISSUE THREAD

**Issue by slole** [DaveDavenport/rofi#881]
When launching rofi with a terminal emulator wit the command: `rofi -show run` it works, however when launching with `i3 "exec rofi -show run"` i3 only returns: 
`12/08/18 10:46:05 - Additional arguments passed. Sending them as a command to i3.
[{"success":true}]`

## Version
1.5.1-dirty

## Configuration
https://gist.github.com/slole/6c3451461aae148161e42a12aaf75b59

## Launch Command
`rofi -show run`

## Steps to reproduce
* Fresh install of arch linux
* Install lightdm
* Install i3-gaps
* Install rofi
* Try to launch rofi from i3

## What behaviour you see
* rofi not opening

## What behaviour you expect to see
* rofi opens up

**Comment by carnager** [comment]
i3 is not the same as i3-msg

**Comment by slole** [comment]
Same output with i3-msg.

**Comment by carnager** [comment]
well, i cannot reproduce and this really seems more like a i3-related question.

**Comment by slole** [comment]
Ok, I'll open this issue in i3-gaps.

**Comment by slole** [comment]
Ok, I found a solution: my locales were wierd. Fix: https://wiki.archlinux.org/index.php/locale

**Comment by robsaunders** [comment]
Had this same issue - this really needs to be documented or a better error message should be returned. The locale issue is presented as a warning and should be an error.
