### ISSUE TITLE
Window switching on different workspaces does not work with xfwm4

### ISSUE THREAD

**Issue by fikovnik** [DaveDavenport/rofi#882]
## Version

Version: 1.5.1-dirty (tags/1.5.1)

## Configuration

All default

## Launch Command

```
rofi -show window \
     -show-icons \
     -p "> " \
     -kb-accept-entry '!Super-Tab,!Super-ISO_Left_Tab,!Super-Up,!Super-Down,Return' \
     -kb-row-down 'Super+Tab,Super+Down,Down' \
     -kb-row-up 'Super+ISO_Left_Tab,Super+Up,Up'
```

## Steps to reproduce

workspace 1:
- firefox

workspace 2:
- firefox
- emacs
- terminal

From workspace 1 with firefox in focus, launch rofi (using a keybinding set in xfce) to switch to emacs, it will jump to workspace 2, but it selects firefox instead.
Go back to workspace 1, select firefox and try again to switch to emacs. It will jump to workspace 2, but selects terminal instead (usually a different window than in the first try).
Go back to workspace 1, select firefox and try again to switch to emacs. It will jump to workspace 2 and selects emacs. Basically, it is a bit random which window is put to focus when switching to windows on different desktops.

I don't know if it is xfwm4, the way I run rofi or a bug.

**Comment by DaveDavenport** [comment]
Is follow mouse focus enabled?

Currently rofi calls ewmh switch desktop then change active window.  So it should switch to the right window.

**Comment by fikovnik** [comment]
No, it is not.

**Comment by DaveDavenport** [comment]
@fikovnik does @notbntly suggestion fix it for you?

**Comment by fikovnik** [comment]
Unfortunately, it does not. Still the same behavior.

**Comment by DaveDavenport** [comment]
I tried out xfwm4, worked fine for me. Not sure what is going wrong.

**Comment by fikovnik** [comment]
Interesting ... Anyway, I have moved away from xfwm4 so I will close it.
