### ISSUE TITLE
Fuzzy matching should favor 

### ISSUE THREAD

**Issue by gsaga** [DaveDavenport/rofi#883]
## Version

    Version: 1.5.1-67-git-2624cb9c (next)

## Configuration

Output of `rofi -help`:

https://gist.github.com/gsaga/9db19522a84c4177548bd5cd4a460659

## Launch Command

    rofi -modi drun,run -show drun

## Steps to reproduce

* Step 1
Intall `Intellij IDEA community edition`and `qt V4L2 video capture utility` ( or just put `.desktop` files with these names at correct place.
* Step 2
start rofi as mentioned above and type `idea`

## What behaviour you see
![rofi](https://user-images.githubusercontent.com/21998969/50014213-4da63080-ffe9-11e8-8593-a080bb823e09.png)

## What behaviour you expect to see

Intellij above v4l2, since "`idea`", the complete sequence of characters typed is contained completely in it's entry.

Maybe fuzzy matching should be a backup (or of low priority), for when normal matching fails. Is there any use case for which the suggested behavior will be insufficient?

**Comment by DaveDavenport** [comment]
Matching and sorting are considered different things in rofi. The maching in the above screenshot seems to be right. The sorting is less logic.

If you set the sorting method to fzf, it should do be closer to what  you want.
```-sorting-method fzf```
 
![rofi-2018-12-15-0010-00000](https://user-images.githubusercontent.com/406245/50034605-05453d80-fffe-11e8-9816-4f7de721c7be.png)

**Comment by gsaga** [comment]
@DaveDavenport How do I specify that in `config.rasi`?

**Comment by gsaga** [comment]
I wanted to know exactly what to put in `config.rasi`, found it in man page, thanks anyways.

**Comment by woshichuanqilz** [comment]
> -sorting-method fzf

Hi the fzf option still worked? 
Here is my situation, seems fzf match not worked. How to solve it?

![2020-08-27_15-02](https://user-images.githubusercontent.com/11295355/91408431-71b9ac00-e876-11ea-8005-dead74c13392.png)

**Comment by DaveDavenport** [comment]
As mentioned above, matching != sorting. 
> Matching and sorting are considered different things in rofi.

**Comment by woshichuanqilz** [comment]
> As mentioned above, matching != sorting.
> 
> > Matching and sorting are considered different things in rofi.

Sorry I misunderstand the meaning. Is there a way to fzf match the result?

**Comment by DaveDavenport** [comment]
Please do not hijack old issues (see rules).  For matching methods, see documentation.
