### ISSUE TITLE
Ability for plugins to execute a function after the window has been closed

### ISSUE THREAD

**Issue by Mange** [DaveDavenport/rofi#890]
I'm writing a C plugin for selecting emojis (https://github.com/Mange/rofi-emoji). Currently it only copies the emoji to the clipboard on selection, but I'd love to have it automatically insert it into the previous window.

I've seen some existing solutions that do this by executing `xdotool type …` after Rofi exits, but this is only possible when Rofi is wrapped in a script.

I think that if there was a plugin lifecycle function pointer that can be executed *after* the window has closed and the keyboard released, then I could use that to send the keys to the previous window. This is just a guess on my part.

Am I approaching this the wrong way? I'm not very experienced in either C or X11-programming.
I tried doing it in the `_result` call, but as I expected, it doesn't work since Rofi is still the focused window at that point.

**Comment by DaveDavenport** [comment]
There is a call `rofi_view_hide ();` you can do inside the  result callback. This should hide rofi window.

See the window switcher as example.

**Comment by Mange** [comment]
It does not look like `rofi_view_hide` is exposed in the headers I have installed.

```
../src/plugin.c:14:10: fatal error: 'rofi/view.h' file not found
#include <rofi/view.h>
         ^~~~~~~~~~~~~
1 error generated.
```

```
> rg "view_hide" /usr/include/rofi
>
```

**Comment by DaveDavenport** [comment]
you can get around it by  just declaring the function in your plugin.

```c
void rofi_view_hide ();
```

It should resolve fine on loading the plugin.

**Comment by Mange** [comment]
That worked! Thank you.

Now I just have to figure out how to get `xdotool` to emit unicode. :thinking:
