### ISSUE TITLE
drun-display-format doesn't display comment

### ISSUE THREAD

**Issue by SolitudeSF** [DaveDavenport/rofi#892]
## Version
Version: 1.5.2

## Configuration
```
-drun-display-format [string]           DRUN format string. (Supports: generic,name,comment,exec,categories)
{name} [({comment})] (Rasi File)
```
## Launch Command
`rofi -show drun`

## What behaviour you see
Comment field is not displayed

## What behaviour you expect to see
Comment field displayed

**Comment by DaveDavenport** [comment]
(for performance) comments are only loaded when enabled in `-drun-match-fields`, can you check if adding it there fixes it?

**Comment by SolitudeSF** [comment]
yep, that fixes it. maybe fields use in `display-format` should be implicitly added to `match-fields`?

**Comment by DaveDavenport** [comment]
Yes, the manpage should be updated to indicate this.
