### ISSUE TITLE
can't add customize mode to the list of modi.

### ISSUE THREAD

**Issue by archmj** [DaveDavenport/rofi#894]
## Version
Version: 1.5.2
## Configuration
 [https://gist.github.com/archmj/8c85a36cfb690a86769e86b8ac90b041](https://gist.github.com/archmj/8c85a36cfb690a86769e86b8ac90b041)

## Launch Command
```
Rofi is unsure what to show.
Please specify the mode you want to show.

    rofi -show {mode}

The following modi are enabled:
 * window
 * run
 * ssh

The following can be enabled:
 * windowcd
 * drun
 * combi
 * keys

To activate a mode, add it to the list of modi in the modi setting.

```
## Steps to reproduce

* Step 1
```bash
rofi -modi "window,run,ssh,teiler:/home/maojun/Documents/GitHub/teiler/teiler"  -show teiler
```
* Step 2
I want to activate a mode and  add it to the list of modi. I use the shortcut key `win+d` to start rofi. But it can't load my custom modi.I can only use it once after adding it on the command line. I don't want to run this command every time. I tried to add this command to i3wm's `win+d` shortcut to start it, but this doesn't work.I added this command to the rofi configuration file and it still doesn't work.
```bash
 maojun@maojun-pc  ~  rofi -modi "window,run,ssh,teiler:/home/maojun/Documents/GitHub/teiler/teiler" 
Rofi is unsure what to show.
Please specify the mode you want to show.

    rofi -show {mode}

The following modi are enabled:
 * window
 * run
 * ssh
 * teiler

The following can be enabled:
 * windowcd
 * drun
 * combi
 * keys
```

## What behaviour you see
-  Rofi no content output
can run teiler in rofi, but there is no text prompt. But I can run the teiler directly in the terminal, it can run normally and it will display the function normally in rofi. For example: exit, 1 [scrrenfetch], 2 [screencasts], 3 [History]...4
```bash
 maojun@maojun-pc  ~  rofi -modi "window,run,ssh,teiler:/home/maojun/Documents/GitHub/teiler/teiler"  -show teiler

(process:23790): Helper-WARNING **: 14:59:16.668: Failed to set lock on pidfile: Rofi already running?

(process:23790): Helper-WARNING **: 14:59:16.668: Got error: -1 Socket operation on non-socket

```

## What behaviour you expect to see

*  Use rofi -show custom mode
I want the custom mode to be used like the built-in mode, which works every time.
Just like can use this customize mode  `rofi -show teiler` directly.

**Comment by DaveDavenport** [comment]
Unsure about your story, if teiler is this one (https://github.com/carnager/teiler) then teiler is a 'dmenu' script, not a mode.

You should not be able to use this a mode, and it will try to create a nested instances of rofi. This will fail. (last posted error message).

**Comment by archmj** [comment]
This is my debug log information `G_MESSAGES_DEBUG=all rofi -modi "window,run,ssh,teiler:/home/maojun/Documents/GitHub/teiler/teiler" -show teiler > rofi_debug.log`
：[https://gist.github.com/archmj/aaf00f61390eb43c7f61e3cfc8976812](https://gist.github.com/archmj/aaf00f61390eb43c7f61e3cfc8976812)

**Comment by DaveDavenport** [comment]
Teiler is a dmenu script, not a mode. **It will not work as a mode!**

This is not the intended use of teiler. 

You should run teiler, by executing teiler directly.. Teiler will then call rofi.
