### ISSUE TITLE
drun-display-format doesn't provide a way to italicize the generic part of the name

### ISSUE THREAD

**Issue by nukeop** [DaveDavenport/rofi#896]
## Version
1.5.2

## Configuration
https://gist.github.com/nukeop/b5ce121240956b90656a92b6159eb49b

## Launch Command
rofi -show

## Steps to reproduce
If you don't specify a custom `drun-display-format`, the default format is the name of the program followed by italicized generic name in parentheses.
If you use what is listed as the 'default' format the generic part is printed using the regular font face. This is the setting I'm using for reference:
`rofi.drun-display-format: {name} [({generic})]`

## What behaviour you see

* - The generic part of the string is not italicized

## What behaviour you expect to see

* - There should be a way to italicize a part of the formatted string

**Comment by DaveDavenport** [comment]
It seems the manpage generation remove the markup, it is correct in the source file:
`
 Default: *{name} [<span weight='light' size='small'><i>({generic})</i></span>]*
`
