### ISSUE TITLE
Show line numbers in list?

### ISSUE THREAD

**Issue by solars** [DaveDavenport/rofi#900]
Not an issue but since rofi allows to select lines by using super+number (line number) it would be convenient to show line numbers so you don't have to count (at least 1-9)

**Comment by lnikkila** [comment]
I wish this was something that could be controlled through the theme, a separate element à la `case-indicator` that could be packed into each element.

Off-topic: I couldn’t be happier with rofi, switched a month ago or so and it’s been a joy to configure and use!

**Comment by DaveDavenport** [comment]
incomplete report. closing.

**Comment by solars** [comment]
well I thought the feature description is (very) obvious :)

**Comment by sardemff7** [comment]
In a bug report, nothing is ever obvious. You **must** follow the guidelines for a clean understanding of the situation. It will help in all future references to this feature.
