### ISSUE TITLE
Feature request: Window selector mode brings to current workspace

### ISSUE THREAD

**Issue by technicalguy** [DaveDavenport/rofi#902]
I often use rofi in combi mode with window first and then .desktop entries after that. This way I don't end up launching multiple instances of the same application.

If I am on workspace 1 and I want to launch, say Firefox, but it is already running on workspace 3, then the window will show in the top of the rofi list and if I press enter then I will be switched to workspace 3 and Firefox will be focused. I would like a configuration option that Firefox could be brought to the current workspace (e.g. workspace 1), and then focused, rather than switching my entire view to the other workspace. (Or perhaps an alternative binding like Ctrl+Enter.)

(Conversely, if Firefox is not running then I know that it will launch on the current workspace. My desired behaviour is that I always remain on the current workspace, whether or not I'm launching a new instance or focusing an instance that may be on another workspace.)

This is equivalent to the [`-R` option of `wmctrl`](https://linux.die.net/man/1/wmctrl).

(See also [mkropat/jumpapp/pull/38](https://github.com/mkropat/jumpapp/pull/38).)

rofi Version: 1.5.0

**Comment by DaveDavenport** [comment]
You can bind `wmctrl -R` it to the custom key in rofi (it is now calling xkill).

**Comment by technicalguy** [comment]
It works perfectly with

```
rofi.window-command: wmctrl -i -R {window}
```

thanks for your help! :)

**Comment by DaveDavenport** [comment]
great to hear it works, might be a nicer default then xkill (as shift-delete sends a close already).

I am gonna change this!

**Comment by technicalguy** [comment]
I was pleased to note that shift-enter works even if the application is not already running, so I can freely type the application name and press shift-enter on autopilot without having to actually check if it is currently running to know whether to press just enter or shift-enter.

**Comment by DaveDavenport** [comment]
combi-mode allows you to combine run with window. that is even nicer (imho).

**Comment by technicalguy** [comment]
That's what I'm using! My observation is that shift-enter works regardless of if it is run-mode or window-mode.
