### ISSUE TITLE
[MUSL] Please add support for musl

### ISSUE THREAD

**Issue by Li-Gru** [DaveDavenport/rofi#906]

**Comment by sardemff7** [comment]
Please follow the guidelines, and in this specific case, please provide all the build logs concerning musl-related errors you get.
To actually provide musl support, we need someone to *test* on musl, which may be tricky on a glibc system, so if you cannot help us getting there, it won’t happen.

**Comment by DaveDavenport** [comment]
Empty bug report. Closing.
