### ISSUE TITLE
Is there a Way to Exclude Entries on SSH config?

### ISSUE THREAD

**Issue by codeitlikemiley** [DaveDavenport/rofi#907]
Hope someone can help me Thanks

## Version

Version: 1.5.2

## Configuration

```
! Rofi config file
rofi.lines: 12
rofi.font: DejaVu Sans Mono 14
rofi.show-icons: true
rofi.theme: ~/.config/rofi/oxide.rasi
rofi.display-window: Window
rofi.display-drun: Search
rofi.display-ssh: SSH
rofi.parse-known-hosts: false
```

## Launch Command

The commandline used to launch **rofi**
`rofi -show ssh`

## Steps to reproduce

I followed some guidelines to disabled parsing known_host
by adding  rofi.parse-known-hosts: false

with that the number of host listed decreased, but still i only expect one 
which is the one i use to connect remotely on a server.

The other ssh config is used by github and bitbucket for pushing commits
I dont wanna see that also...

## What behaviour you see

* - I still see SSH Entries Such as Github and Bitbucket and their corresponding IP address

## What behaviour you expect to see

* - I Just wanna see one SSH name listed when i run `rofi -show ssh`

**Comment by DaveDavenport** [comment]
No. This is not possible. If you just want a limited list of actions, I guess making a small script that just displays what you want is more suitable.
