### ISSUE TITLE
Start up slow caused by get_apps?

### ISSUE THREAD

**Issue by Sh3Rm4n** [DaveDavenport/rofi#908]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`

`Version: 1.5.2`

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))

[output](https://gist.github.com/Sh3Rm4n/8375ee59916e1807736ee5bccad9e237)

## Launch Command

The commandline used to launch **rofi**

Binary build with `./configure --enable-timings --disable-checks`

Run via `./rofi -show drun`

## What behaviour you see

Rofi consistently takes about a second to start up without consideration of the draw time it takes about 0.5 seconds to recognize keystrokes. The time-trace can be looked up [here](https://gist.github.com/Sh3Rm4n/8375ee59916e1807736ee5bccad9e237#file-timings)

 ` ` `
0.164602 (0.047062): ../source/dialogs/run.c:get_apps:216 start
0.474250 (0.309648): ../source/dialogs/run.c:get_apps:336 stop
0.474324 (0.000074): ../source/dialogs/drun.c:get_apps:586 Get Desktop apps (start)
0.474405 (0.000081): ../source/dialogs/drun.c:get_apps:593 Get Desktop apps (user dir)
0.481487 (0.007082): ../source/dialogs/drun.c:get_apps:611 Get Desktop apps (system dirs)
0.481491 (0.000004): ../source/dialogs/drun.c:get_apps_history:553 Start drun history
0.481521 (0.000030): ../source/dialogs/drun.c:get_apps_history:573 Stop drun history
 ` ` `
## What behaviour you expect to see

I noticed that get_apps takes up most of the time and i wonder if this is expected behavior or if it possible to get faster start up times.

**Comment by DaveDavenport** [comment]
duplicate #898 ?

get apps does *very* little, it  mostly does a file listing on all directories in $PATH.
Normally this is completely limited by disk-io.

**Comment by Sh3Rm4n** [comment]
Sorry if I bothered you with that simple question. Thank you for taking your time to answer anyway and thanks for the hint. :slightly_smiling_face:

**Comment by Sh3Rm4n** [comment]
Okay, after some investigation, I found the cause of my slow start up times. `get_apps` does indeed take very little time to execute, at least the part, where the $PATH dirs are searched through. However this function also calls the external `get_apps_external`, which calls an external program via `run-list-commands`, if I understand correctly. This call took more than 200 ms.

I've not touched the `run-list-command` and left it out commented in the `config.rasi` file. I use some external scripts / plugins listed by the User Scripts entry in the wiki. Maybe this value was set by some of these scripts? This function can slow up start up times (as seen in #844). 

Explicitly settings `run-list-command` like this:

```
	run-list-command: "";
```

fixed the issue.

**Comment by DaveDavenport** [comment]
`run-list-command` should be empty.

You can use `rofi -h`  to see where the property was set.

**Comment by Sh3Rm4n** [comment]
Oh, ok thank you. To wrap this up, this comes down to be totally my fault. I use the fish-shell and set-up `~/.Xresources` as stated in the wiki and I seem to have read over the bold part, which says that this could cause delay.  ([Using Rofi with Fish Shell](https://github.com/DaveDavenport/rofi/wiki/Using-Rofi-with-Fish-Shell))

Thank you again for taking your time and pushing me in the right direction.
