### ISSUE TITLE
Usefull on Ubuntu 18.04 running GNOME?

### ISSUE THREAD

**Issue by guettli** [DaveDavenport/rofi#915]
I asked for a simple window-switching-tool and your project was the answer.

See: https://askubuntu.com/questions/1116691/list-of-window-names-on-alt-tab

The author of the answer writes:

> I'm not sure it's advisable to attempt to change the window manager in Ubuntu 18.04. The window manager is integrated into GNOME Shell. 

What do you say: is it advisable?

**Comment by carnager** [comment]
a) the quoted question talks about switching window managers... I can't see any relation to rofi here.
b) try it and see for yourself?
c) this is a bug tracker, for general questions join our IRC channel #rofi on freenode.
