### ISSUE TITLE
Rofi completely invisible with i3/compton, works in GNOME

### ISSUE THREAD

**Issue by gibsjose** [DaveDavenport/rofi#916]
## Version

Output of `rofi -v`
```
Version: 1.5.0
```

## Configuration

https://gist.github.com/gibsjose/ce57b4fefed6aa460eebc1c3b4620a66

`~/.config/rofi/config` contains:

```
! Rofi Configuration
rofi.combi-modi:    window,drun,ssh
! rofi.theme:         gruvbox-dark-hard
! rofi.font:          Hack 10
rofi.modi:          combi
rofi.run-command: fish -c '{cmd}'
rofi.run-list-command: 'fish -c functions'
```

I have also tried without the config file, using all defaults, and did not notice any change in behaviour.

Other things to note:

* Running relatively fresh install of Ubuntu 18.04 with `i3-gaps`, compton, fish shell, konsole terminal emulator
* Running from inside VirtualBox, hosted on macOS

## Launch Command

Does not work when launched from `i3-gaps` via: `bindsym $mod+d exec --no-startup-id "rofi -show combi"`, and also does not work when launched directly from terminal (`konsole`) via `rofi -show run`.

## Steps to reproduce

* Open terminal
* Type `rofi -show run`
* No rofi window shows up whatsoever. Nothing is displayed to the screen
* Same behaviour when invoking from i3 keybindings

## What behaviour you see

* I see no window appear whatsoever. Focus is removed from my current window, so there's something trying to be displayed, but nothing is displayed to the screen
* If I simply log out and log back in using GNOME instead of `i3`, running `rofi -show run` works and I see the rofi window displayed
* I have another VM running Ubuntu 16.04 with i3/bash, and it seems to work fine on that machine even when using i3
* I have tried with the baseline `i3` rather than i3-gaps, and the behaviour was the same. Nothing displayed.
* I have tried launching compton from within my i3 config with `exec compton --config ~/.config/compton-conf --focus-exclude '_NET_WM_NAME@:s = "rofi"'`, and that also did not seem to work.

## What behaviour you expect to see

* The normal rofi window displayed

**Comment by gibsjose** [comment]
Also, please note that when I run: `rofi -show run`, even though there is nothing displayed to the screen, I can still use rofi. For example, if I launch `rofi -show run`, and then type `konsole` followed by `<enter>`, it will indeed launch a new konsole window. So rofi is working... it's just not displayed to the screen.

**Comment by gibsjose** [comment]
Investigating a bit further, it looks like a compatibility issue with compton... Enabling compton on the 16.04 box that was working allowed me to replicate the same behaviour (no output).

My compton config file is linked below. Could you take a look at it and see if anything jumps out at you?

https://gist.github.com/gibsjose/d4adcd06ceaa21f6347fa0e95c288f3a

**Comment by gibsjose** [comment]
Comparing my `compton-conf` to the [sample one in the compton repo](https://github.com/chjj/compton/blob/master/compton.sample.conf), it looks like the only real difference is that I have `backend = "glx";`, instead of `xrender`. Is there a known incompatibility with compton and the GLX backend?

**Comment by gibsjose** [comment]
Okay, so switching to `backend = "xr_glx_hybrid";` seems to allow rofi to display properly.

Not sure if this is going to break something else, but it at least solves this issue. I'd still like to understand why it's breaking with regular GLX.

**Comment by DaveDavenport** [comment]
good you figured it out,  we had more issues in the past with compton.
