### ISSUE TITLE
Going into submenu / Receiving a prompt to enter a "query" after making a selection from combi mode

### ISSUE THREAD

**Issue by sakishrist** [DaveDavenport/rofi#919]
Hello Dave, all!

Thank you for creating Rofi! Really great tool!

On to the issue:
I would like to be able to chose a "search engine" from the `combi-modi` mode and then once the search engine is selected, to be prompted to enter some free text in (maybe/I think) dmenu mode.

From old issues, it seems I should be able to go into submenus of an entry, but it does not seem clear how I can make use of that from the issue. (#18)
## Version

Version: 1.5.0

## Configuration

https://gist.github.com/sakishrist/98126042a9d55d3a3858165ed033b413

## Launch Command

rofi -show combi

## Custom script 
Used as custom modi. See `-combi-modi [string]` option in above gist.

https://gist.github.com/sakishrist/a1798501e0a6cb001a5ae60731471883

## Steps to reproduce

1. Launch Rofi
2. Go to `de` entry
3. Press `Enter` key
4. _(The custom script goes correctly into the `INTERACTIVE` section)_
5. _(Rofi cannot launch due to the error below)_
6. _(Browser window launches)_

## What behaviour you see
```
(process:5206): Helper-WARNING **: 16:17:02.855: Failed to set lock on pidfile: Rofi already running?

(process:5206): Helper-WARNING **: 16:17:02.855: Got error: -1 Inappropriate ioctl for device
```

## What behaviour you expect to see
I would like to do the following:
- Launch rofi in combi mode
- Select a search provider from the ones the custom script provides
- Be prompted to enter some free text without getting all the other modes' results

**Comment by DaveDavenport** [comment]
Nested rofi's is not possible and will not be possible soon.

What needs to happen, is wait till rofi closes, then launch the dmenu. This is possible (from the script), but not easy.

**Comment by sakishrist** [comment]
OK, that hint helped a lot actually. Thanks.

Yep. It does seem kind of hard to wait for the pid to exit, especially in bash. There is the poll option of checking every so often until it does, but I don't like it much.

Anyway, thanks a lot! :) Closing for now

**Comment by dannycolin** [comment]
You could do some string manipulation in your script. Something like : 

1. Enter `!my_engine my search terms` in the prompt
2. split string on first space character in your shell script

**Comment by sakishrist** [comment]
> You could do some string manipulation in your script. Something like :
> 
>     1. Enter `!my_engine my search terms` in the prompt
> 
>     2. split string on first space character in your shell script

Yep. Already did that, but it was a bit counter intuitive since it requires a few more keypresses: 

`Super` de `Tab` `Space` search terms `Enter`

`Super` key is mapped to rofi in combi mode
de is the search engine
`Tab` is for autofill
`Space` is needed to separate it from the last word after the autofill, which is "de".

So I figured out why not make it a bit more efficient and intuitive like so:

`Super` de `Enter` search terms `Enter`

**Comment by sakishrist** [comment]
Writing this update so that there is complete info in the issue for anyone else.

The way I solved the "waiting" issue is by fork and then waiting for a lock on the pidfile.

From the parent script, this is the way I forked:
```sh
# Completely detach from the parent script
# If in/outputs are not redirected, rofi will wait for the forked process as well.
waitAndGetQuery </dev/null >/dev/null 2>/dev/null &
```
And the child process executes this function which makes sure rofi has exited before proceeding:
```sh
waitAndGetQuery () {
    # wait for a lock on the rofi pidfile
    flock $XDG_RUNTIME_DIR/rofi.pid true
    query=$( rofi  -dmenu -matching fuzzy -location 0 -p "Query" )
    search
}
```

Thanks for the hints!
