### ISSUE TITLE
New format config in ~/.config/rofi/config doesn't get loaded

### ISSUE THREAD

**Issue by tleydxdy** [DaveDavenport/rofi#926]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Version: 1.5.2

## Configuration
all default

## Launch Command
rofi -show drun

## Steps to reproduce

* create config to ~/.config/rofi/config with rofi -dump-config
* uncomment and change something, i.e. font and dpi

## What behaviour you see

* the new config does not get loaded 

## What behaviour you expect to see

* load new config

**Comment by DaveDavenport** [comment]
The new format should be in `~/.config/rofi/config.rasi`.

This should be better documented in the manpage.

**Comment by matt-snider** [comment]
Ran into the same issue.Thanks :+1:
