### ISSUE TITLE
Valid icon theme has no effect

### ISSUE THREAD

**Issue by electric-ladyland** [DaveDavenport/rofi#931]
## Version

Version 1.5.2

## Configuration

https://gist.github.com/electric-ladyland/eb2779f715c8c33883cc8747f31ee959

## Launch Command

`rofi -show drun`

## Steps to reproduce

- Install [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme to ~/.local/share/icons
- Verify icon themes are installed correctly (Xfce uses them fine)
- Set rofi icon settings:
```
rofi.show-icons: true
rofi.drun-icon-theme: Papirus
```
- Launch rofi as shown above
- See that none of the icons are Papirus

## What behaviour you see

Uses default system icons.

## What behaviour you expect to see

Papirus icons show up.

**Comment by DaveDavenport** [comment]
hmm I think it should be: `rofi.icon-theme: Papirus`

**Comment by electric-ladyland** [comment]
You're 100% right.
Thanks for quick response and awesome tool.
