### ISSUE TITLE
full-screen rofi window with vim editor

### ISSUE THREAD

**Issue by Fandekasp** [DaveDavenport/rofi#933]
:exclamation:
First read the [guidelines](https://github.com/DaveDavenport/rofi/blob/next/.github/CONTRIBUTING.md)!
This is not optional for any report/question. People must be able to understand the full context of the report when reading it, at any time.
If you feel like you “just have a simple question”, please consider you’re wrong and still fill the full report.
Any report missing these informations will be labeled as “Incomplete Report - Please follow the guidelines” and may not be answered in a timely fashion.
:exclamation:

## Version

Output of `rofi -v`      
Version: 1.5.2

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/))
https://gist.github.com/Fandekasp/58dd1b7f8adfec0faa34c524ecb269a8

## What behaviour you expect to see

I would like to launch `jrnl` (and therefore the vim editor) from a full-screen rofi window that I'd trigger everyday at the same time, forcing me to write a journal entry before I can do anything else.
I couldn't find the full-screen option, and was wondering generally whether it's a good idea or not to use rofi here.
What do you think ?
Thank you for your advices

**Comment by carnager** [comment]
that `trigger everyday at the same time` is the part that triggers me here... This sounds much more like a use case for cron or similar tools?

**Comment by Fandekasp** [comment]
@carnager well yes. I had in mind to trigger rofi from a systemctl timer. I'm just thinking about a way to force full-screen of a window in my wm (i3-wm), and rofi seemed like an idea

**Comment by carnager** [comment]
You might have missed the edit to my answer... `-fullscreen` exists.

**Comment by Fandekasp** [comment]
@carnager indeed I had missed the edit, thanks for pinging me back. And sorry I missed this option in the help text :/

But I think I got it wrong regarding rofi, and I cannot use vim within a rofi fullscreen window ? Or I would have to write a plugin for it ?

**Comment by Fandekasp** [comment]
Assuming that my rofi usage plan is incorrect, I'll investigate how to do with just systemctl, i3 and termite. Thanks again for the quick replies!

**Comment by carnager** [comment]
Just to mention it: You can't actually use ANY application while rofi is open, because rofi steals your keyboard input :)
