### ISSUE TITLE
Higher priority for command line options

### ISSUE THREAD

**Issue by hxss** [DaveDavenport/rofi#935]
## Version

Version: 1.5.2

## Configuration

Output of `rofi -help` (in a [gist](https://gist.github.com/hxss/2b429fc3d73fcf5d4547e6da5c452da1))

## Launch Command

`rofi -dmenu -no-custom -p file: -kb-custom-1 Control+h `

## What behaviour you see

* Error message: `There is already a binding matching Control+h`

## What behaviour you expect to see

* I expect that command line option(keybind in this case) will override config settings. In default setup we have 4 keybindings for `-kb-remove-char-back` action including `Control+h`. I expect that `Control+h` will be removed from `-kb-remove-char-back` and used for my custom action. Other 3 keybindings from `-kb-remove-char-back` list will remain intact.

**Comment by DaveDavenport** [comment]
Setting an option from the command line option has priority over the other configuration systems. I think the title of the issue does not match the question asked.

I think the requested feature (automatic clear colliding keybindings) is wrong.  If there is a collision it should be mentioned, having stuff happen 'magically' in the background to hide problems  (and resulting in unexpected problems) is something I hate in programs and won't add to rofi.

**Comment by hxss** [comment]
Ok, if you say so
