### ISSUE TITLE
Variables return a syntax error

### ISSUE THREAD

**Issue by dannycolin** [DaveDavenport/rofi#936]
## Version

Version: 1.5.2-37-git-b1336e98 (next)

## Configuration

https://gist.github.com/dannycolin/fa9035cf4aac35369c3f62192d2a61cf

## Launch Command

rofi -show drun 

## Steps to reproduce

* Create a variable (e.g. --my-var) with an rgba value
* Call the variable for a rule value (e.g. background-color: --my-var; OR with var() syntax)

It also happens with : 

`border-radius: --myvar 0 0 0;` (here --myvar is set to a pixel value).

## What behaviour you see

* Parser return an error syntax

## What behaviour you expect to see

* Parser should be able to read a variable with rgba value and in a rule that accepts multiple values.

**EDIT**

Going to try this patch tomorrow : https://gist.github.com/DaveDavenport/f42ee4814e0f08596d5d7f3834a104cf

**Comment by DaveDavenport** [comment]
(as mentioned on irc).
This `border-radius: --myvar 0 0 0;` I can cannot easily implement without a rewrite. 
(given `0 0 0 0` is internally one token at the same level as the variable link.).
