### ISSUE TITLE
Issues installing in Debian stretch

### ISSUE THREAD

**Issue by lifeBalance** [DaveDavenport/rofi#939]
Since the **rofi** package for **Debian** is Version **1.3.1**, I'm trying to install the latest release following [the instructions](https://github.com/DaveDavenport/rofi/blob/master/INSTALL.md#install-a-checkout-from-git).
I installed all the dependencies:
* libpango1.0-dev
* libcairo-5c0
* libcairo2-dev
* libglib2.0-0
* librsvg2-dev
* librsvg2-bin
* libstartup-notification0 
* libxkbcommon-dev
* libxkbcommon-x11-0
* libxkbcommon-x11-dev
* libstartup-notification0
* libstartup-notification0-dev
* libxcb1:
    * libxcb-xrm-dev
    * libxcb-xkb1
    * libxcb-xkb-dev
    * libxcb-randr0
    * libxcb-randr0-dev
    * libxcb-xinerama0
    * libxcb-xinerama0-dbg
    * libxcb-xinerama0-dev
* libxcb-util0
* xcb-util-wm:
    * libxcb-ewmh2
    * libxcb-ewmh-dev 
    * libxcb-icccm4
    * ibxcb-icccm4-dev

There are probably some that are not needed, since I wasn't sure what package was required, the ``-dev`` version or the plain one. 
When I run ``../configure`` I'm still missing a package that I can't find:
```
Package requirements (check >= 0.11.0) were not met:
Requested 'check >= 0.11.0' but version of Check is 0.10.0
```
What can I do about it?

I found [check 0.12.0-0.1](https://packages.debian.org/sid/check). It was in the **sid/unstable** branch so I added it to my ``/etc/apt/sources.list`` and installed version 0.12.
I could finish the **rofi** installation. SOLVED.

**Comment by DaveDavenport** [comment]
It looks like you have not installed the dependencies.
```
apt build-dep rofi
```
should get you started.

**Comment by sardemff7** [comment]
You’re missing `libglib2.0-dev`, as the name of the macro is hinting.

**Comment by sardemff7** [comment]
Please do not edit your post when adding information, it is highly annoying for anyone trying to follow the issue, either in real time or for future reference.

Now, people have to dig into your edition history to see the original question, which may be the very reason a search engine brought them here for.
IOW, people will search “rofi AM_PATH_GLIB_2_0 macro missing”, find your issue, and wonder how the hell that could help them.

**Comment by DaveDavenport** [comment]
Closing. solved.. 
(p.s. check is not needed as mentioned in instruction.)

**Comment by dannycolin** [comment]
> I found check 0.12.0-0.1. It was in the sid/unstable branch so I added it to my /etc/apt/sources.list and installed version 0.12.

https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

**Comment by lifeBalance** [comment]
Danny, my man, it's in a Virtual Machine, not a production server. Haven't you heard 

> In order to learn we need to fail
Or this other one:
> The best to learn is breaking things

There  you go, a link for you too:
https://lifehacker.com/the-science-behind-how-we-learn-new-skills-908488422

Plus, don't tell me what I have to do ;-)
