### ISSUE TITLE
Support for custom aliases and functions

### ISSUE THREAD

**Issue by orschiro** [DaveDavenport/rofi#97]
Hi there,

I was almost able to replace dmenu with rofi except for one missing functionality.

In dmenu I can source and run custom aliases and functions. Basically, I created a file `~/.zsh_aliases` which contains all my custom aliases and functions. I am using it together with a small [script](https://github.com/orschiro/dmenu-scripts-collection/tree/master/dmenu-recent-aliases) that sources these aliases and functions and allows me to call them from dmenu. The advantage here is that I can also source the exactly same file in my shell rc file. 

What do you think about including support for custom aliases and functions into rofi and what would be the best approach to do that?

Thanks for your advice!

Robert

**Comment by DaveDavenport** [comment]
I have added a command 'run-list-command'. This can call a list that can return a list of 'extra' commands to include in the run-dialog.

**Comment by orschiro** [comment]
@DaveDavenport 

Thanks! How can I call it? Tried:

```
rofi run-list-command
```

Returns no error, neither any window.

**Comment by DaveDavenport** [comment]
rofi -run-list-command "<path to magic script returning aliases>" -rnow

You might also want adjust the -run-command to execute the result using zsh.

**Comment by orschiro** [comment]
I begin to understand. So, given that my aliases are stored in `~/.zsh_aliases`, something like the following should almost do the trick:

```
 rofi -run-list-command "cat ~/.zsh_aliases" -rnow 
```

`~/.zsh_aliases`:

```
~ ❯ cat .zsh_aliases
#
# .zsh_aliases
#

[ -e "${HOME}/.zshenv" ] && source "${HOME}/.zshenv"

# Package management aliases
alias pkg-install='pacaur -Sy --noedit'
alias pkg-install-ruby='pacgem'
pkg-remove() {
    sudo pacman -Rsn "$@"
}

```
~ ❯ rofi -run-list-command "cat ~/.zsh_aliases" -rnow
cat: ~/.zsh_aliases: No such file or directory
```

**Comment by DaveDavenport** [comment]
No.

I have a script alias.sh that lists all possible commands:

```
alias | awk -F'[ =]' '{print $2}'
```
This only lists aliases, but you can add a list of 'functions' too.

Then I execute rofi like this:

```
rofi -run-list-command ". ~/Scripts/alias.sh" -run-command "/bin/bash -i -c '{cmd}'" -rnow
```

You need to do the run-command, otherwise rofi will try to execute the command, but in case of an alias this is not possible, the 'shell' should execute it. By using the run command it will call bash, and use bash to execute it.

How the exact line is for zsh I do not know.

**Comment by DaveDavenport** [comment]
Note to self: With history possible duplicate entries are possible.

**Comment by orschiro** [comment]
> I have a script alias.sh that lists all possible commands:

Strangely this command does not find all my aliases...

Example of such an alias:

```
~ ❯ cat .zsh_aliases | grep crashplan
alias crashplan-stop='gksudo systemctl stop crashplan'
alias crashplan-restart='gksudo systemctl restart crashplan'
alias crashplan='CrashPlanDesktop'
    gksudo "systemctl stop crashplan.service insync@orschiro.service dropbox@orschiro.service"
    gksudo "systemctl restart crashplan.service insync@orschiro.service dropbox@orschiro.service"
```

Output of the awk command returns nothing:

```
~ ❯ alias | awk -F'[ =]' '{print $2}' | grep crashplan
~ ❯ 
```

The shell, however, is able to find the alias:

![screenshot](https://cloud.githubusercontent.com/assets/170947/5642810/305a77fe-9650-11e4-8e64-ce7f1bb7c80d.png)

**Comment by DaveDavenport** [comment]
I have no idea about zsh. You do not _have_ to use the awk line I provided. that was just an example.

**Comment by orschiro** [comment]
Many thanks for your dedicated help! Finally found a zsh-compatible solution.

`zsh_aliases_functions.sh`:

```
# fetch all zsh aliases 
alias | awk -F'[ =]' '{print $1}'

# fetch all zsh functions
# http://superuser.com/questions/681575/any-way-to-get-list-of-functions-defined-in-zsh-like-alias-command-for-aliases
print -l ${(ok)functions}
```

Function to call the menu in Openbox' `rc.xml`:

```
    <keybind key="A-F2">
      <action name="execute">
        <execute>rofi -run-list-command ". ~/Bin/zsh_aliases_functions.sh" -run-command "/bin/zsh -i -c '{cmd}'" -rnow</execute>
      </action>
    </keybind>
```

With this extra feature, rofi is close to perfect. :+1:

**Comment by DaveDavenport** [comment]
happy you got it working!

**Comment by DaveDavenport** [comment]
Need to fix the duplicates with history still :D

**Comment by orschiro** [comment]
Can you outline what you mean by possible duplicates? Haven't noticed any.

**Comment by DaveDavenport** [comment]
duplicate entries.  It might not be there.. but I am not 100% sure, so want to double check .

**Comment by orschiro** [comment]
Alright.

Please let me know if I can do any testing.

Robert

On 07.01.2015 10:12, Dave Davenport wrote:
>
> duplicate entries. It might not be there.. but I am not 100% sure, so 
> want to double check .
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DaveDavenport/rofi/issues/97#issuecomment-68995751>.
>

-- 
Sharing my passion & inspiration for

#sustasty lifestyles #transitions
#OpenSource #Sufficiency
#ResourceEfficiency

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by orschiro** [comment]
@DaveDavenport 

I renamed my alias `wifi-restart` to `wifiRestart` but it still shows up. Is this a result of the `remove duplicates` issue?

Screenshot:

![image](https://cloud.githubusercontent.com/assets/170947/5709220/3e69e98c-9a98-11e4-8e3e-774150363a44.png)

**Comment by DaveDavenport** [comment]
It is history... do shift-del to remove the old entry.

**Comment by orschiro** [comment]
> It is history... do shift-del to remove the old entry.

You are great. Thank you!

**Comment by tylerjdurden** [comment]
I'm attempting to do this on bash. I've written a script:

    tyler:~/scripts > cat print_alias.sh
    alias | awk -F'[ =]' '{print $2}'
    
    tyler:~/scripts > . ./print_alias.sh
    ls
    spot
    vim

I'm running rofi in i3wm. My command to open rofi, without the `-run-list-command` argument, has worked in the past. Now I've changed my command to be:

`bindsym $mod+d exec rofi -run-list-command ". ~/scripts/print_alias.sh" -run-commmand "/bin/bash -i -c '{cmd}'" -rnow -font "terminus 24" -show run`

When I press mod+d, rofi opens for a split second then crashes.

First, **are there any log files I can look at to find the problem or give you more information?** 

Secondly, let me know if you know the solution offhand.

**Comment by DaveDavenport** [comment]
please do not resurrect an very old bug report.
Please make a new ubg report with the requested information.
